### ISSUE TITLE
worker[] exit with status 9

### ISSUE THREAD

**Issue by impuulse** [walkor/Workerman#100]
Hello, what is mean? I' am using Timer.

**Comment by walkor** [comment]
if Timer runs a very time consuming task, when the process of receiving the restart signal, because it can not quickly stop so being killed by the main process, then the log will be recorded. 
It's not a serious problem.

**Comment by impuulse** [comment]
exit with code - it's mean that timer stoped? In "PROCESS STATUS" no one timer left, and i manualy restart them.

**Comment by walkor** [comment]
Timer not stoped, but busy.
In "PROCESS STATUS" no one timer left, because your processes are busy , no time to respond to the status command.

**Comment by impuulse** [comment]
Should i do manual restart when in "PROCESS STATUS" no one timer left?

**Comment by walkor** [comment]
No need to restart.
May be your php code called exit or die, witch cause processes eixted  with status 256.
