### ISSUE TITLE
Kill worker in linux

### ISSUE THREAD

**Issue by xenion54** [walkor/workerman#1005]
In linux, this code not killing worker

```php
<?php

use Workerman\Connection\TcpConnection;
use Workerman\Timer;

require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'Libs' . DIRECTORY_SEPARATOR . 'init.php';

global $argv;

$argv[1] = 'start';
$argv[2] = '-d';


$sw = new \Workerman\Worker('websocket://0.0.0.0:7856' );
$sw->count = 1;

$sw->onWorkerStart = function (\Workerman\Worker $worker) {

    Timer::add(5, function () {
        \Workerman\Worker::stopAll();
    });

};


\Workerman\Worker::runAll();
```

How to kill him from inside?

**Comment by xenion54** [comment]
as workaround, now using 
```php
$master_pid = file_get_contents(\Workerman\Worker::$pidFile);
            unlink(\Workerman\Worker::$pidFile);
            posix_kill($master_pid, SIGKILL);
```

**Comment by walkor** [comment]
The meaning of \Workerman\Worker::stopAll() is to stop all worker instances of the current process. If it runs in a child process, this means stopping the current child process. If you want to stop all processes, you can use `posix_kill(posix_getppid(), SIGINT);`.

**Comment by xenion54** [comment]
> The meaning of \Workerman\Worker::stopAll() is to stop all worker instances of the current process. If it runs in a child process, this means stopping the current child process. If you want to stop all processes, you can use `posix_kill(posix_getppid(), SIGINT);`.

Thx for answer. It looks better, than my workaround. Maby add Workerman::stopParent() method with this realization?

**Comment by walkor** [comment]
In order to be compatible with older versions, I am unable to adjust the behavior of Worker::stopAll(). Perhaps in the future, we may consider adding an interface similar to stopParent().
