### ISSUE TITLE
Implementation of the onError() handler

### ISSUE THREAD

**Issue by programarivm** [walkor/workerman#1009]
Hello, I just noticed that the `$ws_worker->onError()` handler is missing in the [WebSocket server](https://github.com/walkor/workerman?tab=readme-ov-file#a-websocket-server) example and was wondering if the following one would be okay.

```php
// ...

        $this->worker->onError = function ($conn, $code, $msg) {
            $conn->close();

            echo "error $code $msg\n";
        };

// ...
```

Questions:

1. Why is the WebSocket example ignoring this one handler?

2. Is it necessary to close the connection when an error occurs? 

3. Or should it perhaps be as per the [onError documentation](https://www.workerman.net/doc/workerman/worker/on-error.html)?

```php
// ...

        $this->worker->onError = function ($conn, $code, $msg) {
            echo "error $code $msg\n";
        };

// ...
```

Thanks for the help,

**Comment by walkor** [comment]
Workerman has many callback methods, and it's not possible to list all callbacks in every example. More detailed usage should be referred to the manual. https://manual.workerman.net/doc/en/worker/on-error.html
The manual has listed all the situations where errors occur, and whether to close the connection depends on the business logic.
