### ISSUE TITLE
workman项目必须在项目的目录下拷贝一份吗？我composer安装的无法运行。。。

### ISSUE THREAD

**Issue by xjdata** [walkor/Workerman#101]
workman项目必须在项目的目录下拷贝一份吗？我composer安装的无法运行。。。

按readme来。 `composer require workerman/workerman -vvv --prefer-dist`
test.php

```
<?php
use Workerman\Worker;
require_once './Workerman/Autoloader.php';
//....
```

`php /data/wwwroot/test.php start`  报错 `PHP Fatal error:  require_once(): Failed opening required './workerman/Autoloader.php'`  当然这不奇怪，因为我test.php同级目录下确实没有`/workerman/Autoloader.php`

但是我composer安装成功的啊。
composer.json 

```
    "workerman/workerman": "^3.3", //确定有装

//同时 composer目录下的autoload_static.php 也存在workerman的配置
        'Workerman\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/workerman',
        ),
```

如果说 我项目目录下必须包含一份 Workerman 的整体代码   为什么又给出了composer安装方式呢？
直接指明下载代码包是不是 更让人容易明白一点呢？

当然我水平很菜，可能这种composer安装的方式有什么好处，我不了解，所以在这里乱说了。
不对的地方请指正，并包涵。谢谢。

**Comment by walkor** [comment]
```require_once './Workerman/Autoloader.php';```主要是给非composer用户使用的。
composer用户直接使用 ```require_once './vendor/autoload.php';```就可以了，熟悉composer的用户都知道这个，你第一次用不理解也正常。

多个项目可以复用同一个workerman代码库，只要引入```Workerman/Autoloader.php```或者```vendor/autoload.php```即可
