### ISSUE TITLE
Param sameSite in the $response->cookie() should be a string

### ISSUE THREAD

**Issue by Qclanton** [walkor/workerman#1010]
According to documentation, param "SameSite" for cookie can take values "None", "Strict", or "Lax" ([documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value)) but `\Workerman\Protocols\Http\Response::cookie()` expects boolean value for this param

**Comment by walkor** [comment]
Fixed
