### ISSUE TITLE
Run Workerman in daemon mode with Windows

### ISSUE THREAD

**Issue by joanhey** [walkor/workerman#1017]
Running the Testman functional tests in GH actions with Win OS, stop indefinitely after run it.
Like if it was without daemon mode, and awaiting to finish.

If we use Symfony/Proccess work without problems.

Is it Workerman working in daemon mode in Windows?
Or we do anything bad ?

### Windows
https://github.com/joanhey/TestMan/actions/runs/8039629986/job/21956826330#step:6:12
![image](https://github.com/walkor/workerman/assets/249085/dffedb61-4642-4cd9-8257-9343bb986724)

### Ubuntu
https://github.com/joanhey/TestMan/actions/runs/8039629986/job/21956826073#step:6:12
![image](https://github.com/walkor/workerman/assets/249085/ba47c915-3225-4019-bfac-86c3bf059d74)

Also work OK with Mac OS.
Workflow: https://github.com/joanhey/TestMan/actions/runs/8039629986/workflow

~Another curios fact, is that in **windows install Workerman v4.0.0 and not v4.1.15** !!!
Edit: It seems that is for the constrains in the composer.json. We'll need to think a solution for win.~
![image](https://github.com/walkor/workerman/assets/249085/1dfb11bd-9644-40b6-8d89-9f7ed1d0dd23)
Edit: It seems than in windows is not working correctly the Caret Version Range (^), but work OK with Tilde Version Range (~). But still fail the daemon mode with windows, with workerman v4.1.15.

PD: It'll be good to show at start in the info panel, in which OS is running.
Now we show Workerman version, PHP version and event lib using.

**Comment by walkor** [comment]
Workerman does not support daemon mode on Windows. Due to the lack of support for the posix pcntl module in PHP on Windows, many features cannot be implemented. I suggest temporarily not running unit tests on Windows, and only running them on Linux and Mac OS.

**Comment by joanhey** [comment]
I'll use a php process.
Thank you!
