### ISSUE TITLE
PHP8.4弃用了隐式可空类型

### ISSUE THREAD

**Issue by pinerge** [walkor/workerman#1046]
![图片](https://github.com/user-attachments/assets/ba94259b-731c-4efc-8c7f-4d6fab1507f0)

https://github.com/walkor/workerman/blob/14e66a8c7353395b23e1fb3103d7dc778b4c27e2/src/Timer.php#L81

https://github.com/walkor/workerman/blob/14e66a8c7353395b23e1fb3103d7dc778b4c27e2/src/Protocols/Http.php#L76

只是会报 Deprecated，影响不大。

**Comment by joanhey** [comment]
It's only deprecated, we have time to change it !!
