### ISSUE TITLE
RFC3875 compliance for Workerman version

### ISSUE THREAD

**Issue by joanhey** [walkor/workerman#1066]
Now:

```
------------------------------------------------ WORKERMAN -------------------------------------------------
Workerman version:5.0.0-rc.2    PHP version:8.1.30 (Jit off)
------------------------------------------------- WORKERS --------------------------------------------------
```
We can change that for RFC3875 compliance
https://php.watch/versions/8.3/cli-server-server-software-changes

```
------------------------------------------------ WORKERMAN -------------------------------------------------
Workerman/5.0.0-rc.2    PHP/8.1.30 (Jit off)
------------------------------------------------- WORKERS --------------------------------------------------
```
So we have more space to add extra information.

Actually Adapterman use it too.
`Adapterman/0.6.1 (Workerman/4.2.0) OK`

PD: Adapterman it's using also `$_SERVER['SERVER_SOFTWARE']` that I think will be good for Workerman
https://github.com/joanhey/AdapterMan/blob/master/src/Http.php#L354

So any framework using this SERVER variable can show which server or runtime is using.
Example in php-src SAPIs:
https://github.com/search?q=repo%3Aphp%2Fphp-src%20server_software&type=code

**Comment by walkor** [comment]
Thank you for your suggestion.
Done.
