### ISSUE TITLE
多进程问题

### ISSUE THREAD

**Issue by 772807886** [walkor/Workerman#107]
我在开发项目时，需要用到异步执行本地命令行的情况。我在代码中使用`pcntl_fork();`分裂出一个新的进程去执行本地的命令行，不阻塞原来的进程的执行，父进程需要继续与客户端通信。
在子进程的分支中，我调用了`exit(0);`来结束子进程（父进程通过信号来回收僵尸进程）。
但是每次子进程结束时，在wokerman的log日志中都会出现一条日志：
```
pid:**** WORKER EXIT UNEXPECTED
```
由于子进程会频繁出现，所以日志中很大一部分都是这一条。
我想问一下，能不能取消这一个log的输出，或是有其他更好的方法来结束子进程？

**Comment by walkor** [comment]
直接```exit(0);```会被workerman判断异常退出，所以会有个日志。
用```Worker::stopAll();```来代替```exit(0);```就好了。

**Comment by 772807886** [comment]
谢谢。

**Comment by 772807886** [comment]
@walkor 顺便问一下，在手动执行php xxx.php stop结束的时候，log里会出现多条
```
worker[none:****] exit with status 9
```
一堆状态码为9的退出信息。这个一般是由什么引起的？有影响么？

**Comment by walkor** [comment]
**常见的exit_status及其含义如下：**

0：表示正常退出，运行reload平滑重启后会出现值为0的退出码，是正常现象。注意在程序中调用exit或die也会导致退出码为0，并产生一条WORKER EXIT UNEXPECTED错误信息，workerman中不允许业务代码调用exit或者die语句。
9：表示进程被SIGKILL信号杀死了。这个退出码主要发生在reload平滑重启时，导致这个退出码的原因是由于子进程没有在规定时间内响应主进程reload信号(例如mysql、curl等长时间阻塞等待或者业务死循环等)，被主进程强制使用SIGKILL信号杀死。注意，当在linux命令行中使用kill命令发送SIGKILL信号给子进程也会导致这个退出码。
65280：导致这个退出码的原因是业务代码有致命错误，例如调用了不存在的函数、语法错误等，具体错误信息会记录到Worker::logFile指定的文件中，也可以在php.ini中error_log指定的文件中(如果有指定的话)找到。
64000：导致这个退出码的原因是业务代码抛出了异常，但业务没有捕获这个异常，导致进程退出。如果workerman以debug方式运行时异常调用栈会打印到终端，daemon方式运行时异常调用栈会记录到Worker::stdoutFile指定的文件中。

```exit with status 9``` 一般是进程在处理业务，没办法及时响应stop/reload命令，2秒内没有执行退出，被主进程杀死。

摘自手册 http://doc3.workerman.net/advanced/status.html
