### ISSUE TITLE
Error: Undefined constant "Workerman\TCP_KEEPIDLE" 

### ISSUE THREAD

**Issue by joanhey** [walkor/workerman#1071]
Using Testman, the last tests fail with macos and PHP >= 8.2
Before was working OK.

![image](https://github.com/user-attachments/assets/82a237ee-abe1-4e20-91a0-15401289c4b9)

https://github.com/joanhey/TestMan/actions/runs/11817605546/job/32924093740
![image](https://github.com/user-attachments/assets/faff7fc1-7b51-4383-a09b-bcb142f426a8)

Using debug mode, show the error:
https://github.com/joanhey/TestMan/actions/runs/11869928695/job/33080782820
![image](https://github.com/user-attachments/assets/dc09ba4b-b07d-48d6-8cf7-0d87ecd71951)

Seems that TCP_KEEPIDLE don't work with all OSs.
So it'll be better to change the validation in:
https://github.com/walkor/workerman/blob/master/src/Worker.php#L2354

From 
`if (PHP_VERSION_ID >= 80200) {`
to
`if (defined('TCP_KEEPIDLE')) {`

**Comment by joanhey** [comment]
@walkor 
The daemon mode work with Windows?
Or we need to do it in another way.

**Comment by walkor** [comment]
PHP does not support the pcntl and posix extensions on the Windows platform, it cannot implement daemon mode.

**Comment by joanhey** [comment]
![image](https://github.com/user-attachments/assets/64574491-9bdd-4238-9439-6ded523655fa)
