### ISSUE TITLE
Add info about event loop used

### ISSUE THREAD

**Issue by joanhey** [walkor/workerman#1073]
Workerman v4
![image](https://github.com/user-attachments/assets/1d06c952-ad18-4c36-95e9-4abf571b1338)

Workerman v5
![image](https://github.com/user-attachments/assets/6a1a6712-3dff-4b1d-ab23-b6ba6103d18b)

It's more important to know which event-loop is using, than the php OS build (we can get it form php-cli).

**Comment by walkor** [comment]
![image](https://github.com/user-attachments/assets/a3a6a608-ed01-4259-b26e-1a026def2437)
In Workerman v5, the event-loop is placed here because Workerman allows setting its own event-loop for specific processes.
