### ISSUE TITLE
多进程问题

### ISSUE THREAD

**Issue by 772807886** [walkor/Workerman#108]
我觉得我发现了一个比较严重的问题：
如#107 ，我将自己代码中子进程中的`exit(0);`改成了`Worker::stopAll();`，这样子进程确实正常结束了，并且log里也没有异常退出的日志了。
但是这会产生一个比较严重问题：就是当用户连接后，服务器创建了一个子进程完成操作后，在子进程中`Worker::stopAll();`了。这时调用`php xxx.php status`就会发现进程列表里少了一个进程，并且用户无法再次连接到这个进程，但是使用Linux的`top`命令发现进程还在：
> 1. 执行`php xxx.php start`启动服务，创建了2个worker进程（含主进程一共3个）。
> 2. 执行`php xxx.php status`查看状态，下面的列表中显示有2个进程worker（A）和worker（B）。
> 3. 执行`top`，看到里面有3个php的进程。
> 4. 用户连接，自动分配了一个worker（A）给用户。
> 5. 在worker（A）的业务代码中`pcntl_fork();`分裂出一个子进程（C）。
> 6. 子进程（C）运行结束，调用了`Worker::stopAll();`。
> 7. 执行`php xxx.php status`查看状态，下面的列表中少了一个进程，只有1个worker（B）了。
> 8. 执行`top`，列表中还是有3个php的进程。
> 9. 用户如果继续向服务器发送数据，是可以正常发送的。
> 10. 用户断开连接。
> 11. 用户重新连接，此时会将第7步中剩下的那个worker（B）分配给用户。
> 12. 在worker（B）的业务代码中`pcntl_fork();`分裂出一个子进程（D）。
> 13. 子进程（D）运行结束，调用了`Worker::stopAll();`。
> 14. 执行`php xxx.php status`查看状态，下面的列表中就没有进程了。
> 15. 执行`top`，列表中依旧有3个php的进程。
> 16. 用户断开连接。
> 17. 用户重新连接，此时浏览器会一直处于pending状态，无法进行连接。
> 18. 执行`php xxx.php stop`，此时就会在log中产生两条`exit with status 9`的日志。（如果上面用户只连接了一次，则只会产生一条）

如果是使用原先我写的`exit(0);`的话，`php xxx.php status`列表中的进程项目也还是会消失，但是如果用户重新连接的话，剩下的进程的“connections”不会增加，应该是用户还是被分配给原来的那个worker。
如果浏览器快速进行两次连接，那么第二次连接会被分配给剩下的进程中的某一个，此时如果在进程中分裂子进程，并`exit(0);`，也会少一个进程，但是用户还是可以正常连接。
在`php xxx.php stop`时也不会出错。

**Comment by walkor** [comment]
strace -p pid
pid为那个status里面消失的进程pid，看看进程在干什么

**Comment by 772807886** [comment]
![qq 20161115224151](https://cloud.githubusercontent.com/assets/10294977/20309939/f11bb386-ab84-11e6-85b7-4dca31fec5b9.png)

**Comment by walkor** [comment]
把event扩展去掉应该就好了。
由于子进程A使用了event扩展，子进程再次fork后，子进程的子进程B会继承这个event实例。
我怀疑B退出后影响了A的event实例。
这个在开发workerman时有遇到过，开发时尝试主进程和子进程都是用event/libevent，
也是会出现子进程退出后，影响到了主进程的event/libevent行为，
所以目前workerman主进程都是select，没有用epoll，所以没这个问题。
你可以尝试下把event扩展去掉

**Comment by xpader** [comment]
理论上不应该在 worker 进程中自己进行 fork() 操作吧，自己在流程中 fork 的进程没能走 Workerman 内置的流程，但很多资源指向相同，退出时 Workerman 中得不到该资源，但 fork 前的进程还在，理论上就是应该会出现这个问题。那就是 status 命令看不到，但还能接受请求进行处理，因为 socket 资源还把持在那fork 前的进程中呢。

**Comment by walkor** [comment]
@xpader 说的对，不建议在workerman里fork进程，容易因为共享资源导致不可预知的问题。

**Comment by 772807886** [comment]
嗯，目前去掉event扩展，子进程里使用`Worker::stopAll();`，就都正常了，子进程退出后也不影响status里的显示，日志里也没有异常退出的信息。
不过的确可能出现无法预测的问题，后期再想其他解决方案。
不过我还是希望能给个比较好的异步执行命令的方案。。。

**Comment by walkor** [comment]
http://doc3.workerman.net/faq/async-task.html
手册这里有异步执行任务的示例，看下是不是想要的

**Comment by 772807886** [comment]
嗯，这个的意思就是写两个workerman，一个用于处理用户的连接服务，然后把需要执行的任务交给另一个workerman去处理。
这样做也可以，但就是处理任务的workerman的进程数不太好把握，设置少了在高峰期可能会导致部分任务不能及时分配到，设置多了会长时间占用内存资源。

**Comment by walkor** [comment]
用fork的方法高峰期估计内存占用更高，而且感觉不可控。另外实时fork很耗费资源，性能会比较差。

上面异步任务会好很多，异步任务不仅可以扔给本机去做，还可以丢给服务器集群去做，内存占用可控，并且没有fork开销。集群前挡一层dns或者lvs，可以随时加减服务器多到动态扩容或者缩容而不影响服务。

**Comment by 772807886** [comment]
听起来不错，可以试试。
