### ISSUE TITLE
心跳计时器问题

### ISSUE THREAD

**Issue by nashjob** [walkor/Workerman#109]
文档中写的是
$pingNotResponseLimit * $pingInterval 时间内，客户端未发送任何数据，断开客户端连接

但是程序里面相对应的判断是个定值  *2

// 上次发送的心跳还没有回复次数大于限定值就断开
```
if($this->pingNotResponseLimit > 0 && $connection->pingNotResponseCount >= $this->pingNotResponseLimit * 2) {
	$connection->destroy();
	continue;
}
```

是设计就这样呢？还是个bug？

**Comment by walkor** [comment]
这个是GatewayWorker中的设置，和Workerman没关系。

不是bug，就是这么设计的。这个定时器是每二分之一$pingInterval 时间执行一次，所以乘以2
