### ISSUE TITLE
Multiple custom workers.

### ISSUE THREAD

**Issue by JABirchall** [walkor/Workerman#110]
So me and few guys are looking to update one of the teamspeak 3 frameworks to allow for multiple connections to a server each handling different tasks on different protocols.

from reading the readme.md I think it's not possible (I can't seem to find any actual documentation).

But we are looking to create something like (As would be design for Workerman)
```php

use TeamSpeak3\TeamSpeak3;
use TeamSpeak3\Helper\Signal;
use Worker\Worker;

$ts3WelcomeBot = TeamSpeak3::factory("serverquery://serveradmin:password@127.0.01:10011/?nickname=WelcomeBot&server_port=9987&blocking=0");
$ts3WelcomeBot->notifyRegister("server");
Signal::getInstance()->subscribe("notifyCliententerview", "onCliententerview");

$ts3AuditBot = TeamSpeak3::factory("serverquery://serveradmin:password@127.0.01:10011/?nickname=AuditBot&server_port=9987&blocking=0");
$ts3AuditBot->notifyRegister("server");
Signal::getInstance()->subscribe("notifyServeredited", "onServeredited");

$ts3ChatBot = TeamSpeak3::factory("serverquery://serveradmin:password@127.0.01:10011/?nickname=ChatBot&server_port=9987&blocking=0");
$ts3ChatBot->notifyRegister("server");
Signal::getInstance()->subscribe("notifyTextmessage", "onTextmessage");

$worker = new Worker();
$worker->manage($ts3WelcomeBot);
$worker->manage($ts3AuditBot);
$worker->manage($ts3ChatBot);
$worker->runAll();
```
Discussion: https://github.com/planetteamspeak/ts3phpframework/issues/13
Is this possible or could this be functionality be added?

**Comment by ronindesign** [comment]
Managing multiple instances is definitely in the scope of _workerman_.

However, you may be missing a stage of async looping, as you never call the `wait()` method.
For example:
```php
while(1) $ts3WelcomeBot->getAdapter()->wait();
```

Most likely you will need to implement non-blocking loop that integrates the `$worker->manage()` at the right level.

For example, we see in the source for `wait()`:
```php
do {
  $evt = $this->getTransport()->readLine();
} while($evt instanceof TeamSpeak3_Helper_String && !$evt->section(TeamSpeak3::SEPARATOR_CELL)->startsWith(TeamSpeak3::EVENT));

return new TeamSpeak3_Adapter_ServerQuery_Event($evt, $this->getHost());
```

Some options:
1) If you include built-in `wait()`, then internally `waitForReadyRead()` will continually block on stream until _waitTimeout_ value before it loops.
2) Use `$worker->manage()` to handle the read mechanism looping. You'll still need to implement the read logic, but the worker should have no problem handling the stream management.
3) Implement your own read mechanism that doesn't block, similar to lots of native stream select switching implementations, you can find examples online.

**Comment by JABirchall** [comment]
Yes, we are aware the framework in its current state would block workman, the framework is currently being rewritten to v2 and researching possible options. As the last major update was sometime in 2012 to add support for the multiple protocols in TeamSpeak (ServerQuery, FileTransport, TSDNS etc). But to use all of them, you need to create separate scripts or disconnect from on and reconnect to the other visa verse.

v2 will plan to have, multiple instance support, PSR-4 autoloading, better event handling etc.

**Comment by walkor** [comment]
I think the codes with workerman most like this for your application.
```php
use Worker\Worker;
// serverquery protcol
$worker = new Worker('serverquery://0.0.0.0:1001');
$worker->onMessage = function($connection, $message){
    // $message->cmd = 'notifyCliententerview/notifyServeredited/notifyTextmessage/..etc'
    $callback = $message->cmd;
    if (is_callable($callback)) {
        $callback($message);
    }
};
Worker::runAll();
```
In workerman you do not need to handle sockets and read data manually, just deal with your business in onMessage callback.

**Comment by ronindesign** [comment]
@walkor this makes sense for the _action_ stage of the logic.

However, since the _TeamSpeak3_ class is used in managing (and emitting) during the _listen_ stage, the logic or scenario is more complex.

The issue currently is that the _TeamSpeak3_ class blocks internally while _listening_ to sockets, so this seems to complicate using workerman to manage each connection.

**Comment by taozywu** [comment]
@ronindesign 
hi, you can follow this. also refer @walkor 's codes.

foreach($workerConfigs as $wc) {
     // this you can write custom protcol
     // serverquery://0.0.0.0:10011  serverquery://0.0.0.0:10012  serverquery://0.0.0.0:10013
     $worker = new Worker($wc['protcol']);
     $worker->count = 1;
     $worker->onMessage = function($connection, $message){
         // $message->cmd = 'notifyCliententerview/notifyServeredited/notifyTextmessage/..etc'
         $callback = $message->cmd;
         if (is_callable($callback)) {
              $callback($message);
         }
      };
}
Worker::runAll();
---
As above,  this reach Multiple custom workers. at last  good luck!
