### ISSUE TITLE
实例化后的Worker在onMessage里能找到实例化的Worker但是在onConnect里面无法找到

### ISSUE THREAD

**Issue by BoundlessHaung** [walkor/Workerman#111]
`// 创建一个Worker监听2346端口，使用websocket协议通讯
$mc_server = new Worker("websocket://0.0.0.0:2346");

// 启动1个进程对外提供服务
$mc_server->count = 1;

// 为服务器增加一个属性用来存储在线玩家（映射 username=>$connection）
$mc_server->playerlist = array();

// 客户端连接服务器
$mc_server->onConnect = function($connection)
{
............................................................................................................
    // 这里的$mc_server会爆出Undefined错误
    $mc_server->playerlist[$connection->username]
............................................................................................................
};

// 当收到客户端发来的数据时
$mc_server->onMessage = function($connection, $data)
{
............................................................................................................
    // 这里的$mc_server不会出问题并且运行正常
    $connection->username = $clientMsg['username'];
    $mc_server->playerlist[$clientMsg['username']] = $connection;
............................................................................................................
};`

**Comment by walkor** [comment]
正常，PHP里函数内部访问不到函数外部定义的变量，这个是PHP基本的运行机制。
你可以在函数内部声明 global $mc_server; ，通过全局变量的方式去访问。或者use闭包的方式访问。

**Comment by BoundlessHaung** [comment]
尴尬的地方主要是onMessage里能访问··onConnect 却不行·

**Comment by walkor** [comment]
onMessage里肯定也不行，你自己搞错了

**Comment by BoundlessHaung** [comment]
不好意思●﹏●，刚才仔细看了一下，确实搞错了···有点想当然了。
