### ISSUE TITLE
Custome protocol

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#113]
Hi
How can I use my custom protocol?
According to https://github.com/walkor/Workerman/blob/master/Worker.php#L1412
I cannot put my class in my namespace , I must put it in ```\Workerman\Protocols``` but when I install workerman using compeser , I must not change vendor folder

According to https://github.com/walkor/Workerman/blob/master/Worker.php#L1406
Can I use ```myNameSpace\myProtocol://0.0.0.0:1234``` ?

**Comment by walkor** [comment]
Workerman will check ```Protocols/myProtocol ``` first and then ```Workerman/Protocols/myProtocol```, so there is no need to put your protocol  in ```\Workerman\Protocols```.

Yes you can also use ```myNameSpace\myProtocol://0.0.0.0:1234```.
