### ISSUE TITLE
Suppoer LibEv

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#114]
Please add LibEvLoop for react

**Comment by sm2017** [comment]
How long it take to support this feature ?

**Comment by walkor** [comment]
Im not sure ,maybe a week or longer.

**Comment by sm2017** [comment]
OK , I want waiting and hope you implement this feature 
Thanks you

**Comment by sm2017** [comment]
Any update?

**Comment by forkeer** [comment]
Dec 11, 2016  from now has not changed?

**Comment by walkor** [comment]
I have no time to do that.
This is an open source project, you can send PR if you need.

**Comment by forkeer** [comment]
tnx

**Comment by forkeer** [comment]
walkor 
please do it i need this feature

**Comment by sm2017** [comment]
Any updates?

**Comment by walkor** [comment]
I tried to add LibEvLoop for react but unfortunately there is coredump for [libev extension](https://github.com/m4rw3r/php-libev) and which I  can not solve.
So I decide not to support LibEvLoop until [libev](https://github.com/m4rw3r/php-libev) is stable enough.
