### ISSUE TITLE
Timer Problem

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#115]
I update my workerman from '3.3.3' to '3.3.6' , but it is not compatible wit my project (the timer don't works in react loop)
I have problem with timer
```php
Timer::add(1, 'MyClass::MyStaticMethod', [[$this, 'method']], false);
```
As you can see I have MyClass::MyStaticMethod and I pass a callback as first argument , but when timer is runned ```Object(React\EventLoop\Timer\Timer)``` will be passes as first argument

I know I can do following instead
```php
Timer::add(1,[$this, 'method'], [],false);
```
But there is a good reason for me to use 'MyClass::MyStaticMethod' 

Why ```Object(React\EventLoop\Timer\Timer)``` will be passed as first argument?

**Comment by sm2017** [comment]
I found the bug , /react/event-loop/src/Timer/Timers.php(90) use ```call_user_func``` and pass ```$timer``` as first parameter and ignore all other args :-(

**Comment by walkor** [comment]
:-(

**Comment by sm2017** [comment]
I think , the solution is the following , instead of pass callback to react do the following
```php
public static function add($time_interval, $func, $args = array(), $persistent = true)
{
$reactCallback = function() use ($func,$args) {
    call_user_func_array($func,$args);
}
//Other codes
}

```

**Comment by walkor** [comment]
Fixed.
I added similar codes in Workerman\Events\React.php.

**Comment by sm2017** [comment]
Thanks

**Comment by sm2017** [comment]
You forgot to add
```php
unset($func,$args);
```

It is very important part , As you know anonymous functions is ```Closure``` object , Also until you have a reference to object it remain to memory
So if you pass a variable in ```$args``` that refer to  ```Closure``` It remain in memory , It is safe to use ```unset```
