### ISSUE TITLE
Load balancer

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#116]
How we can have a load balancer for gateway worker (Websocket server) , Do you have native load balancer in workerman or have plan to implement it?
If yes let me know more details otherwise , Can you tell me which load balancing solution is good for huge web socket connection? (About 10,000,000 concurrent connection and 100 server)

**Comment by walkor** [comment]
No plan to implement load balancer in workerman.

I think
```Client<-->DNS<-->Server```  
or
```Client<-->DNS<-->LVS<-->Server```
is good for your situation.

**Comment by sm2017** [comment]
What about ngnix , h2o and other load balancing system , what you think?
What about http://emqtt.io/ , I am planning to replace workerman Gateways with this , What do you think about performance?

**Comment by walkor** [comment]
LVS works in the 4 layer network and has better performance than other balancing system(nignx, haproxy etc...) witch work in the network of 7 layers.

I don't have a deep understanding of emqtt.io so I can't make any comments.
