### ISSUE TITLE
HTTPS and WSS

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#117]
How can I run a server using workerman that support WSS and HTTPS in native? without load balancer or proxy?

**Comment by walkor** [comment]
You should add a ssl proxy with nginx/stunnel etc.
Here is the link for nginx ssl proxy setting [nginx-tcp-ssl-termination/](https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-termination/).

**Comment by sm2017** [comment]
Is there any solution ? without any proxy?

**Comment by walkor** [comment]
Make socket ssl with [contex functions](http://php.net/manual/en/context.ssl.php) maybe work but I'm not sure.
See https://github.com/walkor/phpsocket.io/issues/35 .
