### ISSUE TITLE
Timer Problem

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#118]
Yesterday I open #115
>You forgot to add
>```
>unset($func,$args);
>```
>It is very important part , As you know anonymous functions is Closure object , Also until you have a reference to object it remain to memory
So if you pass a variable in $args that refer to Closure It remain in memory , It is safe to use unset

**Comment by walkor** [comment]
I have tested that and conclusion is there is not need add ```unset``` codes. Here the codes.

```php
<?php
$c = str_pad('', 10240000, 1);
$a = function()use($c){
    $a = $c."\n";
    //unset($c);
};
$a();
echo memory_get_usage(true)."\n";
```

**Comment by sm2017** [comment]
Run this code 
```php
class A{
	public $a;
	
	function __destruct(){
		echo "This object(A) removed from memory<br/>\n";
	}
}

class B{
	public $B;
	
	function __destruct(){
		echo "This object(B) removed from memory<br/>\n";
	}
}


$a = new A;
$a->a = function()use($a){

};


$b = new B;
$b->b = $a;

unset($a,$b);
echo "You think both \$a and \$b are freed from memory But \$a is in memory<br/>\n";
````

So it is safe to use ```unset``` inside anonymous function

As you see object of class A is in memory and destructed in shutdown

**Comment by walkor** [comment]
I tried the codes below and $a still in memory. unset is no need in function context.
Since  version 5.3  PHP has its own GC and unset is not required in function context.
Here is the link for [PHP GC](http://php.net/manual/en/features.gc.collecting-cycles.php).
You can call gc_collect_cycles() after code ```unset($a,$b);``` then $a will destruct.
```php
<?php
class A{
        public $a;

        function __destruct(){
                echo "This object(A) removed from memory<br/>\n";
        }
}

class B{
        public $B;

        function __destruct(){
                echo "This object(B) removed from memory<br/>\n";
        }
}

$a = new A;
$a->a = function()use($a){
    unset($a);
};

$b = new B;
$b->b = $a;

call_user_func($a->a);

unset($a,$b);
echo "You think both \$a and \$b are freed from memory But \$a is in memory<br/>\n";
```
