### ISSUE TITLE
Event loop

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#119]
How can I force workerman use EV event loop?
```php
Worker::$globalEvent = new Ev();
```
is Works , but in ```php index.php status``` , it shown React as event loop

Also we have this error in this way
>SendBufferToWorker fail. The connections between Gateway and BusinessWorker are not ready.

**Comment by walkor** [comment]
This feature is not implemented yet.

**Comment by sm2017** [comment]
Do you have plan to implement it?

**Comment by walkor** [comment]
Yes ,after a few weeks.

**Comment by sm2017** [comment]
Any update?

**Comment by forkeer** [comment]
walkor from 29 days ago
any update ?

**Comment by walkor** [comment]
I have no time to do that.
This is an open source project, you can send PR if you need.

**Comment by forkeer** [comment]
tnx

**Comment by forkeer** [comment]
hi walkor 
any update ????

**Comment by sm2017** [comment]
Any update?

**Comment by walkor** [comment]
Now you can force workerman use EV like this.
```
use Workerman\Worker;
// Set eventLoopClass for workerman.
Worker::$eventLoopClass = '\Workerman\Events\Ev';
$worker = new Worker('http://0.0.0.0:1234');
$worker->on....
```
