### ISSUE TITLE
workerman run in hhvm file not found

### ISSUE THREAD

**Issue by donglei** [walkor/workerman#12]
debian 7 安装了hhvm 运行 workerman 的时候，报出大量的文件找不到。如下：

Fatal error: Class undefined: Lib\StoreDriver\File in /mnt/hgfs/d/php/workerman/applications/Demo/Lib/Store.php on line 60
Worker[BusinessWorker:57934]:WORKER EXIT UNEXPECTED   File not found: /mnt/hgfs/d/php/workerman/applications/Demo/Config/Store.php in  on line -1

Fatal error: Class undefined: Lib\StoreDriver\File in /mnt/hgfs/d/php/workerman/applications/Demo/Lib/Store.php on line 60

Fatal error: Class undefined: Lib\StoreDriver\File in /mnt/hgfs/d/php/workerman/applications/Demo/Lib/Store.php on line 60

Fatal error: Class undefined: Lib\StoreDriver\File in /mnt/hgfs/d/php/workerman/applications/Demo/Lib/Store.php on line 60
Worker[BusinessWorker:57953]:WORKER EXIT UNEXPECTED   Class undefined: Lib\StoreDriver\File in  on line -1
Worker[BusinessWorker:57938]:WORKER EXIT UNEXPECTED   Class undefined: Config\Store in  on line -1
Worker[BusinessWorker:57957]:WORKER EXIT UNEXPECTED   Class undefined: Config\Store in  on line -1
Worker[BusinessWorker:57962]:WORKER EXIT UNEXPECTED   Class undefined: Lib\Store in  on line -1
Worker[BusinessWorker:57954]:WORKER EXIT UNEXPECTED   Class undefined: Config\Store in  on line -1
Worker[BusinessWorker:57959]:WORKER EXIT UNEXPECTED   Class undefined: Config\Store in  on line -1
Worker[BusinessWorker:57966]:WORKER EXIT UNEXPECTED   Class undefined: Lib\StoreDriver\File in  on line -1
Worker[BusinessWorker:57964]:WORKER EXIT UNEXPECTED   Class undefined: Lib\StoreDriver\File in  on line -1
Worker[BusinessWorker:57951]:WORKER EXIT UNEXPECTED   Class undefined: Config\Store in  on line -1
Worker[BusinessWorker:57939]:WORKER EXIT UNEXPECTED   Class undefined: Config\Store in  on line -1
Worker[BusinessWorker:57971]:WORKER EXIT UNEXPECTED   Class undefined: Lib\StoreDriver\File in  on line -1
Worker[BusinessWorker:57980]:WORKER EXIT UNEXPECTED   Class undefined: Lib\StoreDriver\File in  on line -1
^C

**Comment by donglei** [comment]
hhvm --version

HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829

**Comment by walkor** [comment]
请使用3.x版本吧，3.x版本对hhvm支持的更好些
