### ISSUE TITLE
Implement a mechanism to get real ip when user come from a reverse proxy.

### ISSUE THREAD

**Issue by HillLiu** [walkor/Workerman#121]
Do a quick survey, workerman extract userip with stream_socket_accept.

So want to know if it possible overwrite the user ip with header when user come from a reverse proxy.

https://github.com/walkor/Workerman/blob/master/Worker.php#L1567-L1574

**Comment by walkor** [comment]
Yes.
Set up an HTTP proxy that inserts the userip header on every request then you can get it in ```$_SERVER['HTTP_USERIP']```.

**Comment by RubyTheRose** [comment]
Coming back to this a year later, this issue seems to be closed abruptly without any real solution created.
