### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#122]
Hello
I have a timer with 0.00001 sec interval , after a while I have this warning , why?

>Warning: stream_socket_client(): unable to connect to tcp://127.0.0.1:2300 (Cannot assign requested address) in vendor/workerman/gateway-worker/src/Lib/Gateway.php on line 363

**Comment by walkor** [comment]
Open /etc/sysctl.conf and add 
```
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
```
Run ```sysctl -p```

**Comment by sm2017** [comment]
Can you explain what is it? line by line

**Comment by walkor** [comment]
Explain it in english is too hard for me.  : )
I found a similar link hope that will help you.
https://redmine.lighttpd.net/projects/weighttp/wiki

**Comment by hadrizi** [comment]
Hi
I still get the same error, although I added lines listed above(except `net.ipv4.tcp_tw_recycle = 1`, because it is not available anymore) 
![CRLrjcn4B9](https://user-images.githubusercontent.com/28650696/81503084-6011c000-92ea-11ea-9cbb-fe54f9383344.PNG)
