### ISSUE TITLE
HTTP Server

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#123]
When a client is connected to http server and don't send any payload , onConnected will be called but never onMessage in called , this is right but there is an issue
As we process the request in onMessage , we will send result or error in this callback and will close the connection , so when client don't send any payload , the connection is open forever , it is better have a timer for conenction

**Comment by walkor** [comment]
Thank you for your advice.
But some times we need long connection for realtime communication on http and do not want to close it. 
I tend to use workerman as a generic service without any business like when or how to close connection.
If a timer for connection is required I suggest to extend workerman but not do it in workerman.
