### ISSUE TITLE
stop fail

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#126]
Can you tell me why sometimes workerman cannot stop itself?

```
php index.php stop
```

>Workerman[index.php] stop 
Workerman[index.php] is stoping ...
Workerman[index.php] stop fail

Now I have an issue with workerman , I have ```ChatBusinessWorker``` , ```ChatGateway``` , ```Register``` And ```HttpServerWorker``` in my server when I start service all of them started , if I check status immediatly using
```
php index.php status
```
There is no problem sometimes but sometimes there is not ```HttpServerWorker``` , Why? I am sure there is no fatal error in this worker , but I know workerman reopen worker if it happens

In this case , when there is no ```HttpServerWorker``` in status table ```php index.php stop``` always failed , after this when I check ```php index.php status``` , the result is 

>3 workers       4 processes

but no ```pid``` is listed

**Comment by walkor** [comment]
Try to use command ```ps aux``` to find the pid of ```HttpServerWorker``` which disappeared in status,
And then use command ```strace -ttp pid``` to see what happened in the process.

**Comment by sm2017** [comment]
Where is problem? I am not familiar with ```strace```


## Result of ``` ps aux```

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      3945  0.0  0.1 370180 18236 pts/0    T    12:17   0:00 WorkerMan: master process  start_file=/home/index.php
root      3946  0.0  0.0 370180 10384 pts/0    T    12:17   0:00 WorkerMan: worker process  HTTP-Worker components\protocols\Http://0.0.0.0:80
root      3947  0.0  0.0 370180 10384 pts/0    T    12:17   0:00 WorkerMan: worker process  HTTP-Worker components\protocols\Http://0.0.0.0:80
root      3948  0.0  0.0 370180 10384 pts/0    T    12:17   0:00 WorkerMan: worker process  HTTP-Worker components\protocols\Http://0.0.0.0:80
root      3949  0.0  0.0 370180 10384 pts/0    T    12:17   0:00 WorkerMan: worker process  HTTP-Worker components\protocols\Http://0.0.0.0:80
root      3950  0.0  0.0 370468 10852 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatBusinessWorker none
root      3951  0.0  0.0 370468 10852 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatBusinessWorker none
root      3952  0.0  0.0 370180 10672 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatBusinessWorker none
root      3953  0.0  0.0 370468 10868 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatBusinessWorker none
root      3954  0.0  0.0 370244 11704 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatGateway components\protocols\SecureWebsocket://0.0.0.0:1122
root      3955  0.0  0.0 370244 11716 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatGateway components\protocols\SecureWebsocket://0.0.0.0:1122
root      3956  0.0  0.0 370244 11692 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatGateway components\protocols\SecureWebsocket://0.0.0.0:1122
root      3957  0.0  0.0 370244 11700 pts/0    T    12:17   0:00 WorkerMan: worker process  ChatGateway components\protocols\SecureWebsocket://0.0.0.0:1122
root      3958  0.0  0.0 370180 10432 pts/0    T    12:17   0:00 WorkerMan: worker process  Register text://0.0.0.0:1236
root      3990  0.0  0.0 149144  1756 pts/0    R+   12:19   0:00 ps aux
```


## result of strace -ttp 3946
```
strace -ttp 3946
Process 3946 attached
12:23:55.104831 --- stopped by SIGTSTP ---
```

## result of strace -ttp 3951
```
strace -ttp 3951
Process 3951 attached
12:24:44.656523 --- stopped by SIGTSTP ---
```

All other pids has same result for ```strace -ttp pid```

**Comment by walkor** [comment]
```stopped by SIGTSTP``` means that the process was killed by signal SIGTSTP.
But I don't know who sended the signal.

**Comment by sm2017** [comment]
I use the following command
```
php index.php stop
```

After that . all websocket connection of clients lost and disconnected.but database connection from business works is connected

**Comment by sm2017** [comment]
Why websock connection is lost and no body can connect but the result of ps aux told gateway worker is alive??

**Comment by forkeer** [comment]
Try running it with strace -f -v

**Comment by walkor** [comment]
I noticed that the value of ```STAT``` in your result of ```ps aux``` was ```T```, That means your process was halted by signal ```SIGTSTP ```.

Pressing Ctrl+Z will sends the TSTP signal to your process.  Do you pressed ```CTRL+Z```?

**Comment by sm2017** [comment]
> Did you pressed CTRL+Z?

No , How can I do this when I start php in daemon mod using ```php index.php start -d``` ?

I only do the following
*  ```php index.php start -d```
* after 2-3 days ```php index.php stop```

**Comment by sm2017** [comment]
Again occurred 

# ps aux

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      4863  0.0  0.0 370180 10616 ?        S    08:38   0:00 WorkerMan: master process  start_file=/home/index.php
root      4868  2.1  1.2 505584 146200 ?       S    08:38   0:10 WorkerMan: worker process  ChatBusinessWorker none
root      4869  2.6  1.2 511728 152344 ?       S    08:38   0:12 WorkerMan: worker process  ChatBusinessWorker none
root      4870  2.6  1.6 560884 201496 ?       S    08:38   0:12 WorkerMan: worker process  ChatBusinessWorker none
root      4871  2.3  1.2 515824 156440 ?       S    08:38   0:11 WorkerMan: worker process  ChatBusinessWorker none

```


after minutes , no workerman listed in ```ps aux```

**Comment by walkor** [comment]
This is something I've never met before, and I can't tell you what's wrong.

**Comment by sm2017** [comment]
# result of strace -ttp  pid
```
11:39:59.446451 write(1, "pg_connect(): Unable to connect "..., 206) = 206
11:39:59.446548 rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
11:39:59.446685 rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
11:39:59.446811 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
11:39:59.446937 nanosleep({1, 0}, 0x7ffe15bd2430) = 0
11:40:00.447524 socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 84
11:40:00.447875 setsockopt(84, SOL_TCP, TCP_NODELAY, [1], 4) = 0
11:40:00.448158 fcntl(84, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
11:40:00.448383 fcntl(84, F_SETFD, FD_CLOEXEC) = 0
11:40:00.448498 setsockopt(84, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
11:40:00.448643 connect(84, {sa_family=AF_INET, sin_port=htons(30001), sin_addr=inet_addr("10.10.10.11")}, 16) = -1 EINPROGRESS (Operation now in progress)
11:40:00.448809 poll([{fd=84, events=POLLOUT|POLLERR}], 1, 4294967295) = 1 ([{fd=84, revents=POLLOUT}])
11:40:00.448950 getsockopt(84, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
11:40:00.449073 getsockname(84, {sa_family=AF_INET, sin_port=htons(42266), sin_addr=inet_addr("10.10.10.15")}, [16]) = 0
11:40:00.449217 poll([{fd=84, events=POLLOUT|POLLERR}], 1, 4294967295) = 1 ([{fd=84, revents=POLLOUT}])
11:40:00.449365 sendto(84, "\0\0\0\10\4\322\26/", 8, MSG_NOSIGNAL, NULL, 0) = 8
11:40:00.449585 poll([{fd=84, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=84, revents=POLLIN}])
11:40:00.449748 recvfrom(84, "N", 16384, 0, NULL, NULL) = 1
11:40:00.449875 poll([{fd=84, events=POLLOUT|POLLERR}], 1, 4294967295) = 1 ([{fd=84, revents=POLLOUT}])
11:40:00.450014 sendto(84, "\0\0\0i\0\3\0\0user\0postgres\0database\0p"..., 105, MSG_NOSIGNAL, NULL, 0) = 105
11:40:00.450148 poll([{fd=84, events=POLLIN|POLLERR}], 1, 4294967295) = 1 ([{fd=84, revents=POLLIN}])
11:40:00.453400 recvfrom(84, "E\0\0\0\223SFATAL\0CXX000\0MCould not ob"..., 16384, 0, NULL, NULL) = 148
11:40:00.453498 close(84)               = 0
```


I use ```pg_connect()``` in my code , how can I tell my application don't connect to pg when stopeed

**Comment by walkor** [comment]
Do not use sleep in workerman.
And do not use infinite loop in workerman.
All of these will cause process statistics to disappear for ```php index.php status``` command, because event-loop can not be executed for temporary or permanent and can not responds the status command.

**Comment by sm2017** [comment]
>Do not use sleep in workerman.

I never use but may be third party library use usleep for less than 1ms sleep


>And do not use infinite loop in workerman.

I never use

I only have heavy duty , 1M-10M events per second

**Comment by walkor** [comment]
Yes heavy duty  may also cause the problem because process can not deal with status command in time.
