### ISSUE TITLE
One socket disconnect other socket

### ISSUE THREAD

**Issue by joanebrown** [walkor/Workerman#127]
Hi! Im using `workerman` with `phpsocket.io` and I have a problem when two sockets (I only test with two) are connected. When I restart the browser of one of this sockets two or three times the other users is disconnected and I see the next error:

`Argument 1 passed to React\EventLoop\StreamSelectLoop::cancelTimer() must implement interface React\EventLoop\Timer\TimerInterface, null given, called in /var/www/myapp/vendor/workerman/workerman/Events/React.php on line 90 and defined' in /var/www/myapp/vendor/react/event-loop/src/StreamSelectLoop.php:122`

Would you be so kind as to tell me that it might be happening?

**Comment by walkor** [comment]
Try to update phpsocket.io. The problem had been fixed .

**Comment by joanebrown** [comment]
As I see in my composer I have the latest version `workerman/phpsocket.io 1.1` and the `"workerman/workerman": "^3.3",`. How can I check if this is real? How can I update with composer?

Thank you very much for your amazing work

**Comment by joanebrown** [comment]
Well, I see the code of `phpsocket.io` and[ I have the fixex by @Buri](https://github.com/walkor/phpsocket.io/pull/53/commits/95d8eb01487519fcba520cf8ae9edc528d67cbe2) but still fails, as I described you...

It's a know bug?

**Comment by joanebrown** [comment]
@walkor Have you tried my fix?

**Comment by walkor** [comment]
You can send a pull request.

**Comment by joanebrown** [comment]
Of Course :-) Thank you.

**Comment by tolew1** [comment]
@joanebrown  thank you for that patch. I can confirm I was having this problem and that fixed the fatal error above. This does need to be in the update so that composer won't overwrite when updated.
