### ISSUE TITLE
服务器怎么主动推消息？

### ISSUE THREAD

**Issue by yanpeipan** [walkor/workerman#13]
向某个房间推送消息？

**Comment by walkor** [comment]
要先获得某个房间的所有client_id，这个在workerman-chat中是存储在memcache中的，
key为 $key = "ROOM_CLIENT_LIST-$room_id";

然后参照下面链接调用接口发送，根据你的需求情况参考下面的链接

非workerman项目向用户推送数据
http://wenda.workerman.net/?/question/130

worekrman定时任务，定时推送数据
http://wenda.workerman.net/?/question/72

**Comment by yanpeipan** [comment]
tks
