### ISSUE TITLE
Socket connection id resetting

### ISSUE THREAD

**Issue by flashape** [walkor/Workerman#132]
I'm currently running into an issue where the socket connection id is being reset.  The following logs shows a demonstration of the issue, notice after connection 2 the next connection id is 1:

```
New connection : 2
received message : queue-popped
onQueuePopped : array (
  'eventName' => 'queue-popped',
  'data' =>
  array (
    'queue' => 'wait-queue/gmg/us-west-2',
  ),
)
PHP Notice:  Undefined index: queue in /var/www/websocket/WebsocketController.php on line 1075

Notice: Undefined index: queue in /var/www/websocket/WebsocketController.php on line 1075
New connection : 1
```

Much of my app is built around the socket id, is there a fix or workaround?

**Comment by walkor** [comment]
I don't really understand what you mean. Can you show me your code?
