### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#133]
1- What is the ```memory```  showing in the ```php index.php status``` , current using memory? Peak memory?

2- How Gateway (G) , Business worker (B) and Register (R) is connected together?
If we have 1 R , 10 G and 20 B , how are connected? and how many connection have R , B and G?

3- If I have a GatewayClient in my BusinessWorker and I use ```sendToClient``` OR ```sendToUid``` , What happens exactly? If I have 10 Gateway , I think for both command each 10 gateway receive a message

**Comment by walkor** [comment]
Thank you for your issue but it is not workerman's issue but gatewayWorker.
Please move this to [GatewayWorker](https://github.com/walkor/gatewayworker)

**Comment by sm2017** [comment]
Moved to https://github.com/walkor/GatewayWorker/issues/19
