### ISSUE TITLE
websocket lunch on remote host

### ISSUE THREAD

**Issue by mkeyno** [walkor/Workerman#144]
hi, I'm sorry to open ticket for my question , but actually I'm not pro in php and with your instruction not figure out how to install it in my remote directory host , and really appreciate for couple of hints , in fact I've tried to hook url on my host to the Telegram webhoock call back bot, so at first step new update data inserted to MySQL database then websoket server give the update data to designated live client .
the problem is I bought the domain & host which is has Cpanel and I don't know how to configure my php server to lunch websocket service 
can you tell me which files should be copy in designated host URL and what files should be modified?
Thanks
My Cpanel images
[image](https://cloud.githubusercontent.com/assets/6232001/23093326/57fb941c-f5f5-11e6-82cc-33b0f8bb0195.jpg)

[image](https://cloud.githubusercontent.com/assets/6232001/23093360/e1f67326-f5f5-11e6-8ef8-290754664d77.jpg
)

**Comment by walkor** [comment]
You must have SSH permissions for your linux server.
All of control must be done in ssh terminal.
I don't think your Cpanel has the ability to run workerman.
Here is a screenshot show how to install and run workerman in ssh terminal. 
![image](https://cloud.githubusercontent.com/assets/6073368/23093566/38bf6416-f622-11e6-938b-a45da730fe16.png)

**Comment by mkeyno** [comment]
@walkor  thanks for reply , I have ssh private/public key but I don't know how to configure putty  to connect my host server
