### ISSUE TITLE
status 11

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#152]
What is status 11 ?
``` worker[ChatGateway:10239] exit with status 11 ```

**Comment by walkor** [comment]
```status 11``` means core dump occurred.
Using unstable extensions or PHP bug  will cause the problem.

**Comment by sm2017** [comment]
See https://github.com/expressif/pecl-event-libevent/issues/11#issuecomment-286056747
Can you help me ? can you understand why?

I try to do same as workerman do in a test script but test script works well

**Comment by walkor** [comment]
I really want to help you, but I can do nothing because C is not my forte.

**Comment by sm2017** [comment]
The problem is 
https://github.com/walkor/Workerman/blob/master/Events/Libevent.php#L113

This event added to https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L171 , but out of workerman project I cannot reproduce error , I think before https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L171 we have another file descriptor that added to libevent , if right , can you tell me where I can find file descriptors that added to  Libevent before https://github.com/walkor/Workerman/blob/master/Connection/AsyncTcpConnection.php#L171
