### ISSUE TITLE
Timer status

### ISSUE THREAD

**Issue by Hypoaristerolactotherapist** [walkor/Workerman#164]
Hi @walkor,

I am trying to enhance the status function to include the status of the timers created. I mean I want to prepare a pull request for you. I use a lot timers and I don't fully understand how the information is gathered and displayed. Would you care explain this a bit so I can get into this?

Thanks

**Comment by walkor** [comment]
Good idea.

You can get the count of timer by code ```count($this-> _eventTimer)``` inside ```Events/Event.php``` ```Events/Libevent.php``` ``` Events/Ev.php ``` ```Events/Select.php```.
And use ```count($this->_timerIdMap)``` in ```Events/React/ExtEventLoop.php``` ```Events/React/LibEventLoop.php``` ```Events/React/StreamSelectLoop.php```.

I think you can add a method ```getCount``` for ```Lib/Timer.php``` which get the real timer
 count by above codes and display it in writeStatisticsToStatusFile method of Worker.php.

**Comment by Hypoaristerolactotherapist** [comment]
I can't grab the list of currently open timed tasks in `Timer`. `self::$_tasks` is always empty when I have a timer running

**Comment by walkor** [comment]
Not ```self::$_tasks``` but ```$this->_tasks```.

**Comment by Hypoaristerolactotherapist** [comment]
none work, I will get try directly from `globalEvent`

**Comment by Hypoaristerolactotherapist** [comment]
@walkor I have something decent but am having issues with changing the event loop to something else than `select`, I have to install all others before I can update these. I have an intense two weeks so I'll get back to it later.
My small test is done with
```php
<?php
require_once("Autoloader.php");
use Workerman\Worker;
use Workerman\Lib\Timer;

$task = new Worker();
$task->name = "Stats Test";
$task->count = 8;
//Worker::$eventLoopClass = '\Workerman\Events\Libevent';
//Worker::$eventLoopClass = '\Workerman\Events\Event';
//Worker::$eventLoopClass = '\Workerman\Events\Ev';
//Worker::$eventLoopClass = '\Workerman\Events\React\ExtEventLoop'
//Worker::$eventLoopClass = '\Workerman\Events\React\LibEventLoop'
//Worker::$eventLoopClass = '\Workerman\Events\React\StreamSelectLoop'

class foo
{
    public function bar()
    {
        echo "|";
    }
}

$task->onWorkerStart = function($task)
{
    $foo = new foo();
    for($i = 1; $i <= 4;$i++)
    {
        Timer::add($i,[$foo,"bar"]);
        Timer::add($i*1.5,function()
        {
            echo "-";
        });
    }
};

// run all workers
Worker::runAll();
```

**Comment by walkor** [comment]
Timer status has been implement in version 3.4.7.
