### ISSUE TITLE
Using blocking operations ( such  sleep ) inside the worker

### ISSUE THREAD

**Issue by abshammeri** [walkor/Workerman#165]
How can we use the blocking operations inside the worker without blocking.

Example:

```
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;

// #### http worker ####
$http_worker = new Worker("http://0.0.0.0:8888");

// 4 processes
$http_worker->count = 100;

// Emitted when data received
$http_worker->onMessage = function($connection, $data)
{

	sleep(1);
	$connection->send('test');
};

// run all workers
Worker::runAll();

```

What I'm trying to do is to make it as fast as nginx/php-fpm.

**Comment by xpader** [comment]
Make the long time job or blocking job to queue, or another worker process.

**Comment by Hypoaristerolactotherapist** [comment]
Hi @abshammeri I built a backend server on Workerman for these long running jobs. What it does is this

- Custom protocol to accept a job
- Put the job in a queue and return a job ID
- Timers run the job offline and put the result in a specific place under the given job ID
- The client can come later to check the result at this specific place and check - non blocking - if the result is available

It also allows me to have a custom cron server I can run to the second using timers.

Hope it helps
