### ISSUE TITLE
Unable to get request size of HEAD and OPTIONS.

### ISSUE THREAD

**Issue by CismonX** [walkor/Workerman#166]
HEAD and OPTIONS don't have a message body, thus no Content-Length shall be sent.
But Workerman HTTP implementation only treat GET method like that. (in getRequestSize method)
Therefore, request will always fail to parse HEAD and OPTIONS request unless a Content-Length: 0 header is sent.
Http::getRequestSize method should be changed to below:
```
//...
if($method == 'GET' || $method == 'OPTIONS' || $method == 'HEAD') {
    return strlen($header) + 4;
}
//...
```

**Comment by walkor** [comment]
Fixed.
