### ISSUE TITLE
processes count

### ISSUE THREAD

**Issue by 88gumak88** [walkor/Workerman#168]
i run websocket in 4 processes

how to make a connection to a specific process (example 3)

**Comment by walkor** [comment]
You can  create 4 processes and each process has its own port, like 
```php
$worker1 = new Worker('websocket://0.0.0.0:8081');
$worker1->count = 1;
$worker2 = new Worker('websocket://0.0.0.0:8082');
$worker2->count = 1;
$worker3= new Worker('websocket://0.0.0.0:8083');
$worker3->count = 1;
$worker4 = new Worker('websocket://0.0.0.0:8084');
$worker4->count = 1;
```
Client can chose any one you want to connect with specific port.

But you can not make a connection to a specific process when these processes are listening the same port, like
```php
$worker = new Worker('websocket://0.0.0.0:8080');
$worker->count = 4;
```

**Comment by dandanlee** [comment]
这两者有什么区别呢？

**Comment by walkor** [comment]
Four processes are listening different ports.
Four processes are listening the same port.
This is the main difference.

**Comment by 88gumak88** [comment]
This is the main difference. because i use port 443

**Comment by taozywu** [comment]
@88gumak88  you can look http://doc.workerman.net/315298 , i hope to help u.

good luck!
