### ISSUE TITLE
Websocket: How to send message from php ?

### ISSUE THREAD

**Issue by Wakirin** [walkor/Workerman#169]
How to send message from another php file to exists websocket server (local) ?

**Comment by chenyangguang** [comment]
@Wakirin [这里有例子](http://doc.workerman.net/315156)

**Comment by Wakirin** [comment]
Sorry, I don't understand Chinese. I think, it that what I need.

```
// 建立socket连接到内部推送端口
$client = stream_socket_client('tcp://127.0.0.1:5678', $errno, $errmsg, 1);
// 推送的数据，包含uid字段，表示是给这个uid推送
$data = array('uid'=>'uid1', 'percent'=>'88%');
// 发送数据，注意5678端口是Text协议的端口，Text协议需要在数据末尾加上换行符
fwrite($client, json_encode($data)."\n");
// 读取推送结果
echo fread($client, 8192);
```

**Comment by Wakirin** [comment]
It's not working, sorry for long response. 
Last time I leaved current project and now return.

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/issues/184#issuecomment-308069727
See this.

**Comment by Wakirin** [comment]
It's helped. 
Thanks.
