### ISSUE TITLE
process_timeout

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#172]
What is process_timeout? and why occurred?

    2017-05-13 21:13:26 pid:23206 process_timeout:
    #1 /home/app/vendor/workerman/workerman/Events/React/StreamSelectLoop.php(149): pcntl_signal_dispatch()
    #2 /home/app/vendor/react/event-loop/src/StreamSelectLoop.php(225): Workerman\Events\React\StreamSelectLoop->streamSelect(Array, Array, 10000)
    #3 /home/app/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(10000)
    #4 /home/app/vendor/workerman/workerman/Events/React/StreamSelectLoop.php(104): React\EventLoop\StreamSelectLoop->run()
    #5 /home/app/vendor/workerman/workerman/Worker.php(1561): Workerman\Events\React\StreamSelectLoop->loop()
    #6 /home/app/vendor/workerman/gateway-worker/src/BusinessWorker.php(183): Workerman\Worker->run()
    #7 /home/app/vendor/workerman/workerman/Worker.php(959): GatewayWorker\BusinessWorker->run()
    #8 /home/app/vendor/workerman/workerman/Worker.php(922): Workerman\Worker::forkOneWorker(Object(GatewayWorker\BusinessWorker))
    #9 /home/app/vendor/workerman/workerman/Worker.php(430): Workerman\Worker::forkWorkers()
    #10 /home/index.php(45): Workerman\Worker::runAll()
    #11 {main}

**Comment by walkor** [comment]
It is not workerman's issue but gatewayworker's. Please move it to [GatewayWorker](https://github.com/walkor/gatewayworker).

**Comment by sm2017** [comment]
Moved to https://github.com/walkor/GatewayWorker/issues/27
