### ISSUE TITLE
The server to receive data after a number of database connections will become more, eventually leading to error.

### ISSUE THREAD

**Issue by cnsms** [walkor/Workerman#187]
6 clients send data once per minute. About twenty and twenty minutes after the server is being given.

![1](https://user-images.githubusercontent.com/14196675/27846957-3cacd3ea-616d-11e7-83f5-dd0ea50d3249.jpg)
![2](https://user-images.githubusercontent.com/14196675/27846960-3cdc4bac-616d-11e7-96b5-872bd2384220.png)
![3](https://user-images.githubusercontent.com/14196675/27846961-3ce8eff6-616d-11e7-96a3-2eda68346563.jpg)

**Comment by walkor** [comment]
Creating mysql connections without closing them can cause this error.
So the simple way is just close all mysql connection at the end of onMessage.
The best way is to create a global mysql connection and all requests reuse this connection. It looks like this.
```php
$worker = new Worker(...);
// Global db connection.
$db_connection = null;
$worker->onWorkerStart = function($worker) {
    global $db_connection;
    $db_connection = new your\db\Connection(....);
};
$worker->onMessage = function($client_connection, $data) {
    // Reuse global db connection.
    global $db_connection;
    $db->connection->query(....);
};
```

**Comment by cnsms** [comment]
ok,i'll try it.

**Comment by cnsms** [comment]
是不是不能用tp5的数据库呢？
你这样写的就是单独再连接数据库咯。

**Comment by cnsms** [comment]
Is not the database can not use tp5?
You write this is a separate re-connected to the database slightly.

**Comment by taozywu** [comment]
@cnsms  

$worker = new Worker(...);
// Global db connection.
$db_connection = null;
$db_configs = [
     "host" => "localhost",
     "user" => "root",
     "dbtable" => "test",
     "password" => "123456!@#",
     "charset" => "",
];
$worker->onWorkerStart = function($worker) {
    // Create global db connection.
    global $db_connection, $db_configs;
    require_once your_path . "/think/db/connector/mysql.php";
    // $db_connection = new \think\db\connector\MySQL($db_configs);
    $db_connection = Db::connect($db_configs);
};

$worker->onMessage = function($client_connection, $data) {
    // Reuse global db connection.
    global $db_connection ;
    $result = $db_connection ->table('')->select();
    file_put_contents("/tmp/tmp.log", var_export($result, true)."\n", FILE_APPEND));
};

--
like this!

**Comment by cnsms** [comment]
@taozywu ok,i'll try it.
