### ISSUE TITLE
Send command to business worker

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#188]
Hi
I asked before here https://github.com/walkor/GatewayWorker/issues/28 but no reply
According to the following codes
https://github.com/walkor/GatewayWorker/blob/master/src/Gateway.php#L409-L414

each client is indirectly connected to specific business worker

From another business worker I want to send a command to the specific business worker using `clientId`

In other words , If I have business worker A (BWA) and B (BWB) and `clientId` = X is connected to BWA , Some times I need from BWB send a command to BWA that do something

How is possible ?

**Comment by walkor** [comment]
Moved to https://github.com/walkor/GatewayWorker/issues/28 .
