### ISSUE TITLE
 Hello, do you support Android IOS?

### ISSUE THREAD

**Issue by 18667366881** [walkor/Workerman#189]
Hello, do you support Android IOS?

**Comment by 18667366881** [comment]
android   socket  and  ios socket   Support?  thinkyou

**Comment by walkor** [comment]
Yes. Support android socket and ios socket.

**Comment by 18667366881** [comment]
Hello, can I have an demo please? Thank you very much

**Comment by 18667366881** [comment]
我在手册里面并没有找到 安卓 和ios d的 demo   帮忙分享一个吧  QQ674483879

**Comment by walkor** [comment]
No demo.

**Comment by 18667366881** [comment]
那 能不能说一下   安卓需要用哪个库  才能连接到 workerman

**Comment by walkor** [comment]
Please use english, that can help all people to understand each other. Thanks.

**Comment by 18667366881** [comment]
Hello, can you tell me what code framework Android needs to use the workerman framework?

**Comment by walkor** [comment]
https://github.com/koush/AndroidAsync
https://github.com/daltoniam/Starscream
https://github.com/facebook/SocketRocket

**Comment by 18667366881** [comment]
Thank you very much!
