### ISSUE TITLE
English docs

### ISSUE THREAD

**Issue by IngwiePhoenix** [walkor/workerman#19]
I really, really like workerman. After a few tests I did with it, I want to put it into my project under production. In order to really do so, I need to know more of the API. Like how to associate worker names, which `on{...}` methods exist and which variables can be set.

Further, I would like to be able to give my server some arguments of its own. It will be started by a parent process and receive its arguments via command line. Can I still get the arguments for my script even after workerman took them?

Kind regards, Ingwie.

**Comment by walkor** [comment]
http://doc3.workerman.net/
Here is the docs,but only chinese.
Yes, you can get the arguments for your script.

**Comment by IngwiePhoenix** [comment]
When will english docs be available?

I worked out the API, sort of, with a lot of `print_r()`'s... but having the actual docs would be helpful.

**Comment by walkor** [comment]
English document may be available after 2 months.

**Comment by IngwiePhoenix** [comment]
Okay, sounds good! But maybe you can answer me a little question.

Which callback is used upon client initialization? Like, there is `onConnect` and such. But is there a function that is called each time the worker is made, on the worker's end? I saw `onWorkerCreate`...but I am not sure if this is called from the main process or the worker process.

**Comment by walkor** [comment]
Yes， ```onConnect ``` will be  triggered when new client come.
```onWorkerStart``` will be triggered when worker is made.
```onWorkerStop``` will be triggered when worker is down.
And ```on{...}``` is allways called from worker process.

**Comment by IngwiePhoenix** [comment]
Awesome. What are the arguments given to the various callbacks? Only the worker object or more?

**Comment by walkor** [comment]
```$connection``` is the instance of ```TcpConnection```  and ```$worker``` is the instance of  ```Worker```.

Worker's callback and arguments  

``` php
onWorkerStart($worker)    
onWorkerStop($worker)
onConnect($connection) 
onMessage($connection, $data)  
onClose($connection)   
onBufferFull($connection)  //Emitted when $connection‘s write buffer becomes full.  
onBufferDrain($connection)  //Emitted when $connection‘s write buffer becomes empty.  
onError($connection, $error_code, $error_msg)  
```

TcpConnection's Api and arguments

```php
send($data)  // Send data.
getRemoteIp()
getRemotePort()
close()  //Close connection.
pauseRecv()  //Pauses the reading of data.   
resumeRecv()   //Resumes reading.  
```

**Comment by IngwiePhoenix** [comment]
Very nice! This helps me a lot!

One last thing though. I want to intentionally restart a worker. Currently, I am doing this by sending `SIGUSR1` to the process itself: http://git.ingwie.me/ingwie/bird3/blob/master/php-lib/YiiApp.php#L250

Is there an actual "right" way to relaunch a worker?

Does `onClose()` reffer to when the client closes the connection to the worker?

**Comment by walkor** [comment]
If you  start workerman by command ```php start.php start```, you can restart all workers by command ```php start.php restart``` or ```php start.php reload``` for gracefull restart.

You can also send ```SIGINT``` or ```SIGUSR1``` signal to the main process, then all worker processes will be restart or reload. If you send ```SIGINT``` or ```SIGUSR1``` signal to one worker process, then the worker process will be restart or reload.

Any end  closed connection will emitted ```onClose```.

**Comment by IngwiePhoenix** [comment]
Is there a way to reload a worker, but keeping its statistics? Reloading a worker also means that the stats for connections and such are reset to 0.

**Comment by walkor** [comment]
It difficult to do that. 
Workerman's reload is restart worker processe(s).When a process exit everything will be destroyed.
Maybe [Classkit](http://php.net/manual/zh/book.classkit.php) is useful for what you want, but need a lot of codes to achieve it.

**Comment by IngwiePhoenix** [comment]
Actually it is not that hard.

Each time a worker is created, use the uniqid() function and save that as a variable. Then offer this very worker a restart function. This restart function should mention to the parent process that it wants to restart and give it it’s unique ID. The master sends a signal to finally stop the worker. Then, the process re-fork()s itself and assigns the previous ID again.

You then can assign this very ID to the entries in the worker table - that way the workers can keep their state.

This is just an diea of mine though!

Kind regards, Ingwie.

**Comment by walkor** [comment]
For example.
You can't reassign the original connnections to the new worker process, because the connections are closed when original  worker process stoped.
Main process dose not hold connnections. Every worker processes hold connections for themselves.

**Comment by walkor** [comment]
English docs are available. [English docs](https://github.com/walkor/workerman-manual/blob/master/english/src/SUMMARY.md)

**Comment by IngwiePhoenix** [comment]
Awesome work! I just looked through them, they are very nice. :)
