### ISSUE TITLE
How to send message to all connections (sessions) of the user?

### ISSUE THREAD

**Issue by Drabiv** [walkor/Workerman#190]

**Comment by walkor** [comment]
```php
foreach ($connections_of_some_user as $connection) {
    $connection->send('.....');
}
```

**Comment by Drabiv** [comment]
How to get $connections_of_some_user? 

For example, I have chat application. One user for some reason opened chat in 4 different browsers. Now I send him message and expect to see this message appearing in all 4 browsers simultaneously.

I have tried to use the below code, but managed to send message only to the one client (the one to which user connected latest).

`$users = [];

       $app_work = new AppWorker("websocket://0.0.0.0:8000");
        switch ($status) {
            case 'start':

       }

       $app_work->onWorkerStart = function () use (&$users) {
            // create local tcp-server
            $inner_tcp_worker = new Worker("tcp://127.0.0.1:1234");




            $inner_tcp_worker->onMessage = function ($connection, $data) use (&$users) {
                $data = json_decode($data);

                if (isset($users[$data->user])) {
                    $webconnection = $users[$data->user];
                    $webconnection->send($data->message);

               }
            };
            $inner_tcp_worker->listen();
        };
        $app_work->onConnect = function ($connection) use (&$users) {
            $connection->onWebSocketConnect = function ($connection) use (&$users) {
                // when connecting new user store get-parameter, that we received from client
                $users[$_GET['user']] = $connection;

            };
        };
        $app_work->onClose = function ($connection) use (&$users) {
            $user = array_search($connection, $users);
            unset($users[$user]);
        };


       $app_work->args($status, true, 'server');
        $app_work->runAll(); `

**Comment by walkor** [comment]
```php
       $users = [];

       $app_work = new AppWorker("websocket://0.0.0.0:8000");
        switch ($status) {
            case 'start':

       }

       $app_work->onWorkerStart = function () use (&$users) {
            // create local tcp-server
            $inner_tcp_worker = new Worker("tcp://127.0.0.1:1234");

            $inner_tcp_worker->onMessage = function ($connection, $data) use (&$users) {
                $data = json_decode($data);
                if (isset($users[$data->user])) {
                    $webconnections = $users[$data->user];
                    // ==== Key point =====
                    foreach($webconnections as $con) {
                          $con->send($data->message);
                    }
               }
            };
            $inner_tcp_worker->listen();
        };
        $app_work->onConnect = function ($connection) use (&$users) {
            $connection->onWebSocketConnect = function ($connection) use (&$users) {
                // ===== Key point =====
                $users[$_GET['user']][$connection->id] = $connection;
                $connection->user = $_GET['user'];
            };
        };
        $app_work->onClose = function ($connection) use (&$users) {
            // ===== Key point =====
            if (!isset($connection->user))  return;
            unset($users[$connection->user][$connection->id]);
        };

       $app_work->args($status, true, 'server');
       $app_work->runAll(); `
```

**Comment by Drabiv** [comment]
Thanks a lot Walkor. It works!
