### ISSUE TITLE
socket.io Failed to load resources

### ISSUE THREAD

**Issue by DeeCann** [walkor/Workerman#197]
I've got an issue with Failed to load resources on http://mydomain.com:2206/socket.io/ . It seems like server doesn't work but Server.php status is ok. I was thinking that something is wrong with my configuration but then I checked demo on http://www.workerman.net/demos/phpsocketio-chat/ and the same problem is there.

![zrzut ekranu 2017-08-07 o 13 24 21](https://user-images.githubusercontent.com/9107948/29024744-a2bdb062-7b73-11e7-8629-66807864b3ea.png)

**Comment by walkor** [comment]
I closed this issue because this is not workerman's issue but phpsocket.io‘s.
Please go to https://github.com/walkor/phpsocket.io/issues and create a new issue.
