### ISSUE TITLE
How to run it with Supervisor ?

### ISSUE THREAD

**Issue by Wakirin** [walkor/Workerman#199]
I have these config
```
[program:worker-dev]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/html/worker.php start
autostart=true
autorestart=true
user=test
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/logs/worker-dev.log
```
It's works, but if I do `supervisorctl reload`, it's not start again because got error `stream_socker_server(): unable to connect to tcp://0.0.0.0:4654 (Address already in use)`

I use worker with with Channel, from this https://github.com/walkor/Workerman/issues/184#issuecomment-308069727

**Comment by Wakirin** [comment]
At now, I use this command for kill all process:
`kill -9 $(ps aux|grep WorkerMan|grep test|awk '{print $2}')`

Maybe somebody will advise better solution.

**Comment by farwish** [comment]
@Wakirin Set the \Workerman\Worker object's attribute reusePort to true, it may be resolved.

**Comment by denfm** [comment]
Workerman has a bug from posix-signal processing, the TERM signal in particular (used in supervisor by default). 
Solution: use _stopsignal=INT_ to resolve this problem.

**Comment by walkor** [comment]
@denfm 
Thank you for your replay.
Can you describe what specific bug is?

**Comment by Wakirin** [comment]
@denfm it's working, thanks!

**Comment by denfm** [comment]
@walkor I think that fork processes loop when obtaining the TERM signal, i.e. this process is terminated, but it is immediately restored by the script. That is why the possible quick solution is static::$_gracefulStop set as true, or not to restore the process when obtaining such signal.

**Comment by walkor** [comment]
Thank you so much @denfm .
I get it.
Workerman not obtaining TERM signal before this [commit](https://github.com/walkor/Workerman/commit/78869fec16391b727dcfb848d1ed66f70b0de3ef#diff-15ba8437bf709108ffa75bc6f519e844) at 13 Oct. So when master process of workerman got a term signal it will exits leaving the child process which still listening. 
But now workerman added an graceful stop with Term signal so it will works fine now.

**Comment by Wakirin** [comment]
@walkor 
do I need remove `stopsignal=INT` from config, if `workerman` will be update ?

**Comment by walkor** [comment]
No, you don't have to  remove it.
