### ISSUE TITLE
Composer: master is not in sync with packagist

### ISSUE THREAD

**Issue by IngwiePhoenix** [walkor/workerman#20]
Could you please fix that? Installing Workerman via composer resulted in an obviously outdated version...

**Comment by walkor** [comment]
fixed

**Comment by IngwiePhoenix** [comment]
Awesome! I’ll verify. :)

**Comment by IngwiePhoenix** [comment]
https://packagist.org/packages/wujingke/workerman

It still reads 2014...

**Comment by walkor** [comment]
Here is the link.
https://packagist.org/packages/walkor/workerman

**Comment by IngwiePhoenix** [comment]
Oh my bad! Thanks for the link :)

**Comment by IngwiePhoenix** [comment]
Strange. I installed Workerman 3.1 via composer now and commented out my manual require_once - expecting Workerman to load automaticaly. But when I load a file that extends Workerman with a protocol, i get an error that Workerman\Protocols\ProtocolInterface is not defined...

That is my code, a snippet from it:

    namespace Workerman\Protocols {
    use \Workerman\Connection\ConnectionInterface;
    class Hdp implements ProtocolInterface {

For now, I am just require_once()’ing the Autoloader file from vendor/walkor/workerman/Workerman/Autoloader.php. But it would be nice if you could find a way to avoid needing to do this. I also will do a research and see what I can find.
