### ISSUE TITLE
run php start.php status issue

### ISSUE THREAD

**Issue by keppelcao** [walkor/Workerman#201]
Sometimes the status output miss header of the process status table.
_有时候状态信息输出缺失头部的两行。_
The wrong output:
_错误的输出：_
Workerman version:3.4.8          PHP version:7.0.22-0ubuntu0.16.04.1
start time:2017-08-17 17:04:53   run 0 days 16 hours   
load average: 0, 0, 0            event-loop:\Workerman\Events\Event
13 workers       23 processes
worker_name                  exit_status      exit_count
_HttpWorker                           0                0
_Register                                0                0
12834	4M      http://0.0.0.0:2345      _HttpWorker       0           269           0         0        [idle] 
12835	4M      http://0.0.0.0:2345      _HttpWorker       1           797           0         0        [idle] 
12836	2M      text://127.0.0.1:2341     _Register         6           6             0         0        [idle] 
12839	2M      websocket://0.0.0.0:8100 Gateway_External 6           3709          0         1        [idle] 

The right output:
_正确的输出：_
Workerman version:3.4.8          PHP version:7.0.22-0ubuntu0.16.04.1
start time:2017-08-17 17:04:53   run 0 days 16 hours   
load average: 0, 0, 0            event-loop:\Workerman\Events\Event
13 workers       23 processes
worker_name                  exit_status      exit_count
_HttpWorker                           0                0
_Register                                0                0
---------------------------------------PROCESS STATUS-------------------------------------------
pid	memory  listening            worker_name             connections total_request send_fail timers   status
_（上面两行没有输出）_
12834	4M      http://0.0.0.0:2345      _HttpWorker       0           269           0         0        [idle] 
12835	4M      http://0.0.0.0:2345      _HttpWorker       1           797           0         0        [idle] 
12836	2M      text://127.0.0.1:2341     _Register         6           6             0         0        [idle] 
12839	2M      websocket://0.0.0.0:8100 Gateway_External 6           3709          0         1        [idle]

**Comment by keppelcao** [comment]
I found the issue occurs in GW project, but the WM project is fine.

Sorry for my poor English.

**Comment by lvshuang** [comment]
@keppelcao  大部门是国人在用，可以用汉语提问

**Comment by walkor** [comment]
Fixed and thank you for your issue.
