### ISSUE TITLE
ev support

### ISSUE THREAD

**Issue by morozovsk** [walkor/Workerman#202]
Thank you for you good library.

Why do you recommend to enable support Ev with code 
`'Worker::$eventLoopClass = '\Workerman\Events\Ev';'` ?

Is it not stable yet for adding in 
`Worker::$_availableEventLoops` ?

With Ev your library is faster two times then swoole.

Thank you for you good library again.

**Comment by walkor** [comment]
Yes , I found extension ev is not stable enough .
Extension event is also a high performance extension similar to ev.

**Comment by morozovsk** [comment]
Thank you. I have tested event. It is litle faster then ev. So I will use event.
