### ISSUE TITLE
How to create nested worker inside onMessage

### ISSUE THREAD

**Issue by abshammeri** [walkor/Workerman#203]
I have a blocking operation `sleep(20)` just for the sake of testing and `$tcp_worker->count = 1`. I need to make the current connection process the request without blocking the tcp server from accepting new data.

I'm trying to create another Worker inside onMessage but not sure how? 
```php
<?php
require_once './vendor/autoload.php';
use Workerman\Worker;
$tcp_worker = new Worker("tcp://0.0.0.0:1111");
$tcp_worker->count = 1;
$tcp_worker->onConnect = function($connection)
{
	echo "New connection\n";
};

$tcp_worker->onMessage = function($connection, $data)
{
   // How to make this non blocking , what's the syntax of creating another worker here?
	sleep(20);
    $connection->send('done');
};

$tcp_worker->onClose = function($connection)
{
};

Worker::runAll();
```

**Comment by walkor** [comment]
Workerman prohibits recreating processes because they can make programs unstable(out of memory and zombie processes) when developers don't have enough experience.
It is recommended that you create enough task processes to handle time-consuming tasks.
These are the example.

task_worker.php
```php
use Workerman\Worker;
require_once __DIR__ . '/Workerman/Autoloader.php';
// task protocol
$task_worker = new Worker('Text://0.0.0.0:12345');
$task_worker->count = 100;
$task_worker->name = 'TaskWorker';
$task_worker->onMessage = function($connection, $task_data)
{
     $task_data = json_decode($task_data, true);
     $task_result = ......
     $connection->send(json_encode($task_result));
};
Worker::runAll();
```

```php
use Workerman\Worker;
use \Workerman\Connection\AsyncTcpConnection;
require_once __DIR__ . '/Workerman/Autoloader.php';

// websocket
$worker = new Worker('websocket://0.0.0.0:8080');

$worker->onMessage = function($ws_connection, $message)
{
    // connect to task worker.
    $task_connection = new AsyncTcpConnection('Text://127.0.0.1:12345');
    // task.
    $task_data = array(
        'function' => 'send_mail',
        'args'       => array('from'=>'xxx', 'to'=>'xxx', 'contents'=>'xxx'),
    );
    // send task to task worker.
    $task_connection->send(json_encode($task_data));
    // get the result from task worker.
    $task_connection->onMessage = function($task_connection, $task_result)use($ws_connection)
    {
         var_dump($task_result);
         // remember close the task connection.
         $task_connection->close();
         $ws_connection->send('task complete');
    };
    $task_connection->connect();
}

Worker::runAll();
```

Also see #165.

**Comment by abshammeri** [comment]
Thanks @walkor. I'm still learning and exploring the project internal structure. We are planning to use it as TCP server into production soon.  But just a side question, why are you creating all the process at once on the server start instead of forking child process on each connection? The child process can communicate with the parent process by sending signal each X seconds. if no signal received.. the parent process can kill the child. The child/parent can use shared memory if needed.

What do you think? does that make sense? I'm not expert by the way.

Thanks for the project.. appreciated.

**Comment by walkor** [comment]
Forking child process on each connection is Inefficient, and the service will becomes unstable (memory exhaustion, zombie process etc).
There are many workerman users whose applications have more than 10 thousand client connections, so this solution is not applicable.

**Comment by abshammeri** [comment]
Thanks for your time.
