### ISSUE TITLE
How to specify a timeout for TCP connection?

### ISSUE THREAD

**Issue by abshammeri** [walkor/Workerman#204]
I want to specify a timeout for a simple tcp server. So if the client wait X seconds while he's Idle ( no request) , I want to disconnect the connection. I search in the source code and docs, but nothing there.

```php
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;

$tcp_worker = new Worker("tcp://0.0.0.0:1234");


$tcp_worker->onConnect = function($connection)
{
    echo "New Connection\n";
};

$tcp_worker->onMessage = function($connection, $data)
{
    $connection->send("hello $data \n");
};

$tcp_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

Worker::runAll();
```

**Comment by walkor** [comment]
Here is an example.
```php
<?php
require_once __DIR__ . '/../Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Lib\Timer;
// Max idle time
define('MAX_IDLE_TIME', 30);
$worker = new Worker('tcp://0.0.0.0:1234');
$worker->onWorkerStart = function($worker){
    // Global timer that check if any connection timedout
    Timer::add(1, function()use($worker){
        $time_now = time();
        foreach($worker->connections as $connection) {
           if ($time_now - $connection->lastMsgTime > MAX_IDLE_TIME) {
              $connection->close();
           }
        }
    });
};
$worker->onConnect = function($connection){
    $connection->lastMsgTime = time();
};
$worker->onMessage = function($connection, $data)
{
    $connection->lastMsgTime = time();
    $connection->send("hello $data \n");
};
Worker::runAll();
```

**Comment by abshammeri** [comment]
Thanks @walkor

**Comment by gashik1979** [comment]
Hello walkor! This doesn't work for me. After the request, it waits for 15 seconds and then I get the response 'Ok'

```
define('MAX_IDLE_TIME', 5);

$worker->onMessage = function($connection, $data)
{
    $connection->lastMsgTime = time();
    
    for($i=1; $i<15; $i++) {
            sleep(1);
        }

    $connection->send("Ok");
    $connection->close();
};
```

**Comment by walkor** [comment]
You have blocked the entire process by using sleep, preventing Workerman from gaining execution rights. In Workerman, you should not use long-blocking functions or methods.

**Comment by gashik1979** [comment]
Thank you for your response!

Could you tell me if it's possible to pause a single worker from accepting connections? I'm trying to use a persistent connection to the database, but the database has a connection timeout, so I need to periodically refresh the connection to the database. How can I ensure that all connections to the database are paused during this refresh?

`
public function initWorker()
{
	$worker = new Worker("http://0.0.0.0:2345");
	$worker->count = 8;

	$worker->onWorkerStart = function ($worker) {
		$db = Db::setupDatabaseConnection();
		$worker->db = $db;
		$worker->connectTime = time();

	};

	$worker->onWorkerStop = function (Worker $worker) {
		Db::disconnect($worker);
	};

	$worker->onMessage = function ($connection, $request) use ($worker) {

		$time = time() - 600;
		if ($worker->connect_time < $time) {
			//Here, I need to somehow block new connections and execute the code when the clients that were already connected earlier receive a response from the server.

			Db::disconnect($worker);
			$db = Db::setupDatabaseConnection();
			$worker->db = $db;
			$worker->connectTime = time();
		}
		$this->handleRequest($connection, $request, $worker);
	};

	...
}`
