### ISSUE TITLE
problems while running with deamon

### ISSUE THREAD

**Issue by gulinfang** [walkor/Workerman#205]
env:
centos7 + php7.1.4

1. There are two master processes .
2. Master process does not exit when stop.

**Comment by walkor** [comment]
Please use english, that can help all people to understand each other. Thanks. : -)
Or you can send your question to http://wenda.workerman.net which is for chinese.
Anyway, please describe the problem in detail or someone else can't help you

**Comment by walkor** [comment]
> 1. There are two master processes .

How do you judge there are two master processes?

> 2. Master process does not exit when stop.

How do you judge master process does not exit?

Can you describe the problem in  more detail like this？
1. Show the codes ```start.php```.
2.What operations have been done? Please paste screenshot.
3.How do you judge problem occurred? Please paste screenshot.

Another important point is that...
Have you modified the workerman source code?

**Comment by gulinfang** [comment]
This is my start.php file:
`<?php

use Workerman\Worker;

/**
 * run with command
 * php start.php start
 */

ini_set('display_errors', 'on');

// 检查扩展
if(!extension_loaded('pcntl'))
{
    exit("Please install pcntl extension. See http://doc3.workerman.net/install/install.html\n");
}

if(!extension_loaded('posix'))
{
    exit("Please install posix extension. See http://doc3.workerman.net/install/install.html\n");
}

// 标记是全局启动
define('GLOBAL_START', 1);

require_once dirname(__DIR__) . '/vendor/autoload.php';

// 加载所有Applications/*/start.php，以便启动所有服务
foreach(glob(dirname(__DIR__).'/Applications/Statistics/start*.php') as $start_file)
{
    require_once $start_file;
}
// 运行所有服务
Worker::runAll();
`
And i haven't changed any workerman code.

Now I can see the processes :
`  
4539 ?        Ss     0:00 WorkerMan: master process  start_file=/mnt/php/test/shell/start.php

  4540 ?        S      0:00  \_ WorkerMan: master process  start_file=/mnt/php/test/shell/start.php

  4541 ?        S      0:00      \_ WorkerMan: worker process  StatisticProvider text://0.0.0.0:55858

  4542 ?        S      0:00      \_ WorkerMan: worker process  StatisticWorker statistic://0.0.0.0:55656

  4543 ?        S      0:00      \_ WorkerMan: worker process  StatisticWeb http://0.0.0.0:55757

  4544 ?        S      0:00      \_ WorkerMan: worker process  StatisticFinder text://0.0.0.0:55858
`

The master process remains after I stoped :
`
4539 ?        Ss     0:00 WorkerMan: master process  start_file=/mnt/php/test/shell/start.php

  4540 ?        S      0:00  \_ WorkerMan: master process  start_file=/mnt/php/test/shell/start.php
`

**Comment by walkor** [comment]
Please try another php version.

**Comment by xpader** [comment]
Use `ps auxf | grep Workerman` in linux, or use `ps auxd | grep Workerman` in FreeBSD to show your process tree.
