### ISSUE TITLE
Problem in SSL and WSS connection on HTTPS Server

### ISSUE THREAD

**Issue by rkshgupta** [walkor/Workerman#207]
I'm trying to use this project on https server using wss/SSL connection but I'm getting an error in chrome:
WebSocket connection to 'wss://*.*.*.*:port/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

and if I use ws to connect then 
WebSocket connection to 'ws://*.*.*.*:port/'  failed: Connection closed before receiving a handshake response
```

// SSL context
$context = array(
    'ssl' => array(
        'local_cert' => '/etc/nginx/one.pem',
        'local_pk'   => '/etc/nginx/one.key',
    )
); 
```

What is one.pem and one.key?

Please help me with this solution.

**Comment by walkor** [comment]
Please use https://certbot.eff.org/ to create ssl pem file and key.
What is pem file look this.
https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file
