### ISSUE TITLE
WebSocket - cannot access HTTP headers

### ISSUE THREAD

**Issue by vponomarev** [walkor/Workerman#211]
Hello.

I need to access HTTP headers (cookies and X-Forwarded-For), but cannot do it with current implementation.

According to the code, we have an event onWebSocketConnect.
static::parseHttpHeader will be called if this event is enabled, but this event is checked in a way:

`if (isset($connection->onWebSocketConnect)) { ... }
`
so i have to set onWebSocketConnect handler directly into $connection, not to a worker.
As a workaround i found an approach:
```
$worker->onConnect($connection) {
 $connection->onWebSocketConnect = function ($connection, $buffer) { .... // here i have access to HTTP headers }

```
but this is not a good way.

-----------------------------------
My suggesting in Protocols/Websocket.php replace:
`if (isset($connection->onWebSocketConnect)) { ... }
`
with
`if (isset($connection->worker->onWebSocketConnect)) { ... }
`
this will allow to set an $worker->onWebSocketConnect handler without need of injecting this handler into any connection.
I made such patch on my deployment and it works fine.

p.s. the same issue with onWebSocketClose call.

**Comment by walkor** [comment]
Good idea. And I think we need compatible old usage, so the codes may look like this
```php
if (isset($connection->worker->onWebSocketConnect) 
|| isset($connection->onWebSocketConnect))
 { ... }
```

**Comment by vponomarev** [comment]
Yes, you're right.
Even more, to save maximum level of control $connection->onWebSocketConnect should have a priority over $connection->worker->onWebSocketConnect.
Something like this:
```
if (isset($connection->onWebSocketConnect) || isset($connection->worker->onWebSocketConnect)) {
$wsEvent = isset($connection->onWebSocketConnect)?connection->onWebSocketConnect:$connection->worker->onWebSocketConnect;
...
call_user_func($wsEvent,...);
```
}
