### ISSUE TITLE
How i can send data to connection without using callback?

### ISSUE THREAD

**Issue by kko123** [walkor/Workerman#214]
I used local host tcp port for transfer data from another php script.
how i can send array $to to current connection?
```php
require_once('vendor/autoload.php');
use Workerman\Worker;
$context = array(
    'ssl' => array(
        'local_cert' => '/home/admin/conf/web/xxx.pem',
        'local_pk' => '/home/admin/conf/web/xxx.key',
        'verify_peer' => false,
    )
);
$ws_worker = new Worker("websocket://xx.xx.xxxx:9999", $context);
$ws_worker->transport = 'ssl';
$ws_worker->onWorkerStart = function()
{
    $inner_tcp_worker = new Worker("tcp://127.0.0.1:9998");
    $inner_tcp_worker->onMessage = function($connection, $data) {
        $data = json_decode($data);
        $to['tel'] = $data->to;
        $to['msg'] = $data->message;
        echo json_encode($to);
    };
    $inner_tcp_worker->listen();
};
```

**Comment by walkor** [comment]
```php
require_once('vendor/autoload.php');
use Workerman\Worker;
$context = array(
    'ssl' => array(
        'local_cert' => '/home/admin/conf/web/xxx.pem',
        'local_pk' => '/home/admin/conf/web/xxx.key',
        'verify_peer' => false,
    )
);
$ws_worker = new Worker("websocket://xx.xx.xxxx:9999", $context);
$ws_worker->transport = 'ssl';
$ws_worker->onWorkerStart = function()
{
    $inner_tcp_worker = new Worker("tcp://127.0.0.1:9998");
    $inner_tcp_worker->onMessage = function($connection, $data) {
        $data = json_decode($data);
        $to['tel'] = $data->to;
        $to['msg'] = $data->message;
        echo json_encode($to);
        global $ws_worker;
        if ($ws_worker->connections) {
            $connection = current($ws_worker->connections);
            $connection->send(json_encode($to));
        }
    };
    $inner_tcp_worker->listen();
};
```

**Comment by kko123** [comment]
Thank you! It works!
How i can donnate to this project? Can't find any donation info.
And another question:
I added after require_once('vendor/autoload.php'):
$mysqli = new mysqli($host_db, $login_db, $password_db, $dbase);
if ($mysqli->connect_error) {
    die('Error (' . $mysqli->connect_errno . ') '
            . $mysqli->connect_error);
}
$mysqli->query("SET NAMES 'utf8';");
$mysqli->query("SET CHARACTER SET 'utf8';");
$mysqli->query("SET SESSION collation_connection = 'utf8_general_ci';");
and added some function with mysql queries.
script work nice in start mode but not working in daemon mode.
How i can fix it?

**Comment by walkor** [comment]
I just added donate link in readme.

<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UQGGS9UB35WWG"><img src="http://donate.workerman.net/img/donate.png"></a>
Thank you for your generosity.

**Comment by kko123** [comment]
Please accept my modest donation!
Thank you for your help and libraries.

**Comment by walkor** [comment]
Thank you so much.
