### ISSUE TITLE
Feature request: support of HTTP/WebSocket in single worker

### ISSUE THREAD

**Issue by vponomarev** [walkor/Workerman#216]
It will be fine to support both HTTP and WebSocket connections within single Worker() instance.
How it can be implemented:
1. Visitor sends HTTP request with upgrade header
2. Workerman see 'Upgrade' header and issues onUpgradeRequest event to request permission to switch protocol.
3. Protocol is switched from HTTP to Websocket if permission was granted (onUpgradeRequest returns `true`).

**Comment by walkor** [comment]
It's a good feature, and I'll think about it.
Thank you so much.

**Comment by jbkingsley** [comment]
I am thinking this feature too. This feature would  be very convenient in reusability and maintainablity when we developed a server that must support  http and websocket at the same time.

**Comment by gai00** [comment]
how about this flow?
connection -> http -> upgrade_to_ws -> websocket_request
connection -> http -> not_upgrade -> http_request

Difference is receive http request using upgrade or not.

**Comment by ishland** [comment]
You just have to make a protocol detector. And start a internal listening in this worker.
This can switch protocol without upgrade header.

**Comment by walkor** [comment]
#359
