### ISSUE TITLE
New command optional "stop -g"  and "reload -g" are not work.

### ISSUE THREAD

**Issue by farwish** [walkor/Workerman#227]
I fetch the master branch to test it.

1. There are two pictures with environment php7.1 on centos7 :

Option  "stop -g" will blocking in while(1) and can not work. 
![image](https://user-images.githubusercontent.com/6552412/31584137-0be8e7de-b16e-11e7-8afb-f5a4b3c05d69.png)

 `php websocket_server.php stop` works fine.
![image](https://user-images.githubusercontent.com/6552412/31584142-1c22316e-b16e-11e7-84a6-a18be8438356.png)

Option "reload -g" can not truly reload.
![image](https://user-images.githubusercontent.com/6552412/31584009-49bf89c6-b16b-11e7-98a9-e3b7db1a0a57.png)

`php websocket_server.php reload` also can not works fine.
![image](https://user-images.githubusercontent.com/6552412/31584104-3ce2e980-b16d-11e7-9848-3246b3fdb73b.png)

Maybe that patch should be fixed or excluded in the master at present.

**Comment by walkor** [comment]
Thanks for your issue. I will find the problem.

**Comment by walkor** [comment]
Fixed.
