### ISSUE TITLE
Programaticaly obtain stats

### ISSUE THREAD

**Issue by IngwiePhoenix** [walkor/workerman#23]
Is there a way to obtain the workerman statistics from within the code? Would be very useful for a monitoring component I am working on! :)

**Comment by walkor** [comment]
Which statistics?
[workerman-statistics](https://github.com/walkor/workerman-statistics) or the statistics of command ```php your_file.php status```

**Comment by IngwiePhoenix** [comment]
I would like to capture the statistics outputted by the „status“ command. I will look into that link you gave me too, never seen it before. :)

**Comment by IngwiePhoenix** [comment]
workerman-statistics does not have an english README … so I can’t quite understand what it does...

**Comment by walkor** [comment]
Yes capture the status outputted is the most convenient way.

**Comment by IngwiePhoenix** [comment]
And there is no way to do get the stats  from within a worker itself?

**Comment by walkor** [comment]
You can get the stats of current worker  from 
 Workerman\Connection\ConnectionInterface::$statistics 

https://github.com/walkor/workerman/blob/master/Workerman/Connection/ConnectionInterface.php#L19

**Comment by IngwiePhoenix** [comment]
And how to get it from all workers at once?

**Comment by walkor** [comment]
No such interface, but capture status output is the best way to get status from all workers.
