### ISSUE TITLE
About connection abnormal disconnect

### ISSUE THREAD

**Issue by wulie88** [walkor/Workerman#231]
网络异常断开（如：直接关闭网络）连接未销毁，未触发onClose，Gateway::getClientIdByUid() 也有。

还有就是如何有效的判断在线？

**Comment by walkor** [comment]
Please use english, that can help all people to understand each other.
And this is not workerman's issue but gatewayWorker's. 
Please move the issue to [here](https://github.com/walkor/gatewayworker).

Thanks.
