### ISSUE TITLE
PHP Error:  Call to undefined function Workerman\Lib\pcntl_signal()

### ISSUE THREAD

**Issue by ruelbermudez** [walkor/Workerman#234]
Hi, 
I am new to Workerman, just recently installed it but having this error:

> PHP Error:  Call to undefined function Workerman\Lib\pcntl_signal() in D:\phpStudy\WWW\Workerman\Lib\Timer.php on line 56

I can't seem to find solutions out there. Is there a work around here?

Thanks.

**Comment by walkor** [comment]
Here is for the project for windows.
https://github.com/walkor/Workerman-for-win

**Comment by ruelbermudez** [comment]
Thanks. Working now.
