### ISSUE TITLE
Binary protocol problem

### ISSUE THREAD

**Issue by Golodnyi** [walkor/Workerman#235]
I can not solve the problem with the binary protocol in WebSocket, chrome produces a bug in Game.ts: 61 WebSocket connection to 'ws: //127.0.0.1: 8000 /' failed: Could not decode a text frame as UTF-8., As I understand it this is due to the wrong frame that the server gives away, probably it gives out the text format, instead of the binary, in the documentation i did not find a way to configure under the binary protocol

**Comment by walkor** [comment]
```php
<?php
require_once __DIR__ . '/Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Protocols\Websocket;

$worker = new Worker('websocket://0.0.0.0:12345');
$worker->onConnect = function($connection){
    $connection->websocketType = Websocket::BINARY_TYPE_ARRAYBUFFER;
};
$worker->onMessage = function($connection, $data)
{
    $connection->send('hello');
};
Worker::runAll();
```

Here are the codes. Sorry for delay.
