### ISSUE TITLE
Unclean a closed connection by close() websocket's method (1006)

### ISSUE THREAD

**Issue by stigout** [walkor/Workerman#236]
Hi!
Sorry for my English :)
I have PHP (php 7.0) websocket server and JavaScript client.

When server has received a connection and anyone message from JS-client, WS-server is sending the close command to client.
`$ws->onMessage = function($connection, $data)`
`{`
` $connection->send('I am closing the connection\n');`
` $connection->close('Closing');`
`};
`
But JS-client has received a code "1006" and variable wasClean == false, also JS-client is not received a reason of closed (because connection has uncleanly closed).
`CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …`

How can I close the connection cleanly?

**Comment by walkor** [comment]
Sorry, I can't reproduce this problem.
Is there any special operation?

**Comment by stigout** [comment]
No. I haven't called `ws.close()` at JS-client.

But I have tried it.
I have removed `$connection->close('Closing');` in the Server-side and rebooted it.
Next I've tried to call `ws.close()` in the client-side (JavaScript), but I've received a code 1006 from `ws.onclose`.

Code:
`$(document).ready(function(){`
`  if ("WebSocket" in window) {`
`  var ws_url = 'ws://*MyIPisDEL*/websocket/';`
`  var ws = new WebSocket(ws_url);`
`  ws.onopen = function() {`
`  ws.send('Good!');`
`  };`
`  ws.onerror = function(e) {`
`  console.log(e);`
`  };`
`  ws.onmessage = function(e) {`
`  console.log(e.data);`
`  ws.close(1000, 'Test reason');`
`  };`
`  ws.onclose = function(e) {`
` //always return code is 1006 `
`  console.log(e);`
`   };`
`  } else {`
`   alert("No support a websocket");`
`  }`
` });`

**Comment by walkor** [comment]
I think you can send a message to js client tell the client to close the ws connection by it self.

**Comment by web-technologies** [comment]
have same problem on php 8.1
