### ISSUE TITLE
Worker类runAll方法疑问

### ISSUE THREAD

**Issue by xcorp1986** [walkor/Workerman#238]
使用如self::checkSapiEnv()方法，在实际过程中整合第三方框架，一般选择继承Worker类，修改parseCommand()方法，然后cli的执行命令类似
```SHELL
php wwwroot/index.php Worker/Main start
```
才能正确获取参数。
但发现框架中的Worker类指向是self，导致上述命令失效，请问self::checkSapiEnv()改成static::checkSapiEnv()是否更合理？

**Comment by walkor** [comment]
Done.

**Comment by xcorp1986** [comment]
nice，这样方便子类复写父类方法
