### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by AndrewSologor** [walkor/Workerman#241]
Sometimes it happens that `status` and `stop` commands returns
> not run

but `start -d` command gives me
> Warning: stream_socket_server(): unable to connect to tcp://0.0.0.0:41414 (Address already in use) in /.../library/vendor/workerman/workerman/Worker.php on line 1648
  Fatal error: Uncaught exception 'Exception' with message 'Address already in use' in...

and I can see that the server is running because it receives requests as usually, but I can't stop or restart it though terminal commands.
I have to kill process on 41414 port to gain the control back.

**Comment by walkor** [comment]
It looks like the PID file is missing.
You can use ```Worker::$pidFile = '/your/path/of/workerman.pid';``` before ```Worker::runAll();``` to set the pid file to a safe path.
The default pid path is the in workerman parallel position.

**Comment by AndrewSologor** [comment]
Ok, thank you! I'll try it next time if this repeated.
