### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#244]
In the following code
```php
// SSL context.
$context = array(
    'ssl' => array(
        'local_cert'  => '/your/path/of/server.pem',
        'local_pk'    => '/your/path/of/server.key',
        'verify_peer' => false,
    )
);
```

Why when `verify_peer` is `false` everything works and when `verify_peer` is `true` when have this error

> Warning: stream_socket_enable_crypto(): Could not get peer certificate in vendor/workerman/workerman/Connection/TcpConnection.php on line 394

I use not self-signed certificate , I have a trusted certificate

**Comment by walkor** [comment]
I am not familiar with ssl.
```verify_peer``` looks like an option that whether to verify the remote certificate.
If ```verify_peer=true``` then the remote client side must has a certificate.
Also ```cafile``` option must be setted in server side if ```verify_peer=true```.

Here are the [ssl options](http://php.net/manual/en/context.ssl.php) in php manual. Hope that will help.
