### ISSUE TITLE
Cannot install on Windows via Composer

### ISSUE THREAD

**Issue by jfcherng** [walkor/Workerman#249]
The changelog of `workerman-3.5.3-stable` says `Support windows.` hence I give it a try.

I install it via `Composer` with `require workerman/workerman` and it give following error messages.
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for workerman/workerman ^3.5.3 -> satisfiable by workerman/workerman[v3.5.3].
    - workerman/workerman v3.5.3 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
```
However, in `composer.json`, `"ext-pcntl": "*",` is never available on Windows.

**Comment by walkor** [comment]
Fixed. Please update workerman-3.5.4-stable.
