### ISSUE TITLE
How can I share a common variable between worker processes?

### ISSUE THREAD

**Issue by bleid3** [walkor/Workerman#254]
How can I share a common variable `$users` between worker processes (if set `$wsWorker->count > 1`)?
`$users = [];`
`$wsWorker = new Worker("websocket://0.0.0.0:1234" );`
`$wsWorker->count = 5;`
`$wsWorker->onClose = function ($connection) use (&$users) {`
     `print_r(array(count($users))); //different in diferent processes, I need an equal result`
`}`

**Comment by walkor** [comment]
Variables between different processes are separated, unable to share or be accessed across processes.

**Comment by bleid3** [comment]
Thank you!
Another question about passed variable from php script(web site) to $wsWorker 

I have the following configuration servers
`$users = [];`

        $channel_server = new Channel\Server('0.0.0.0', 1235);


        $innerTcpWorker = new Worker(MessengerServerHelper::LOCAL_SOCKET);
        $innerTcpWorker->name = 'Local server';
        $innerTcpWorker->onWorkerStart = function () {
            Channel\Client::connect('127.0.0.1', 1235);
        };
        $innerTcpWorker->onMessage = function ($connection, $data) use (&$users) {
            $event_name = 'event_inner_message';
            Channel\Client::publish($event_name, $data);
        };


        $wsWorker = new Worker("websocket://0.0.0.0:" . MessengerServerHelper::WEB_SOCKET_PORT);
        $wsWorker->name = 'Messenger WS-server';
        $wsWorker->count = 1;
        $wsWorker->onWorkerStart = function ($worker) use (&$users) {
            Channel\Client::connect('127.0.0.1', 1235);

            $event_name = 'event_inner_message';
            Channel\Client::on($event_name, function ($data) use ($worker, &$users) {
                $messageData = json_decode($data, true);
                $userId = $messageData['user']['id'] ?? $messageData['user'] ?? false;
                if ($userId && !is_array($userId)) {
                    $this->sendDataToUser($users, $userId, $data);
                }
            });
        };`

and in php script(he is in another place)  i do
`$instance = @stream_socket_client(self::LOCAL_SOCKET, $errno, $errstr, 30);
fwrite($connection, $event . "\n");`

Php script -> innerTcpWorker -> Channel -> wsWorker
Is it  correct way?
Can i do Php script -> wsWorker ?

**Comment by zrlhk** [comment]
you can use websocket client. like:  https://github.com/zrlhk/PHP-websocket-client

**Comment by walkor** [comment]
@bleid3 Yes, it is a correct way.
