### ISSUE TITLE
How to hide or update the Server information in Response Header ?

### ISSUE THREAD

**Issue by farwish** [walkor/Workerman#256]
I note that the Server info is fixed in websocket server.
```
$handshake_message .= "Server: workerman/".Worker::VERSION."\r\n";
```

Is there any good way to update or hide it ? it will be needed.

**Comment by walkor** [comment]
Unfortunately, no such interface is implemented.
I think you can write a class to inherit the ```Workerman\Protocols\Websocket``` class to implement it.
