### ISSUE TITLE
Debuging in production mode 

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#257]
How can I detect in production mode and heavy loads , Which line of code is taking long times? I have stop fails in ` php start.php stop` some times in heavy load and some strange behavior , hanging  for minutes after hours of good working

**Comment by farwish** [comment]
@sm2017 
1.Show status:  `php start.php status`.
2.In daemon mode, you also can log standard output in your business logic by setting `Worker::$stdoutFile = '/tmp/stdout.log'`.
3.Using `tcpdump` dump handshake process to see the network traffic is normal in linux, it likes the tool `wireshark`.
4.Enter  `strace -p processId` in command line to see system calls, like the business logic executed and signal processed etc.

**Comment by sm2017** [comment]
@farwish In heavy load how `strace` can be usable?

**Comment by farwish** [comment]
i think some can be used.
`strace -c -p Pid`  show sys call statistic.
`strace -o output.log -T -p Pid ` output log into file with time of each sys call.
`strace -o output.log -T -e select -p Pid` see specific sys call such as select.

do you find any way or idea to resolve trouble these day?  @sm2017

**Comment by sm2017** [comment]
@farwish Not completely
But I am waiting for replies in related issues

https://github.com/walkor/GatewayWorker/issues/36
https://github.com/walkor/GatewayWorker/issues/37

**Comment by sm2017** [comment]
@farwish . last version . and no strange message when stop fails

**Comment by farwish** [comment]
Make sure if there is a `xxxxxx.pid` file that saved the workerman master process id, if not exists, this problem can be fixed use `Worker::$pidFile` to save pid in a safe place. Run `ps aux | grep WorkerMan` to see current master process id is matched with in the pidFile , if pid not matched, maybe pid is used by other program, delete the pid file.  This is a way to force stop all workers `ps aux | grep WorkerMan | awk '{print $2}' | xargs kill -9`. @sm2017

**Comment by walkor** [comment]
Is the problem still in existence? How to judge the failure of the stop？

**Comment by sm2017** [comment]
@walkor  yes and I dont know a solution

**Comment by walkor** [comment]
How to judge the failure of the stop？

**Comment by sm2017** [comment]
>How to judge the failure of the stop？

When I run `php index.php stop` command it prints something like this (Not exactly as I type it not copy past , I have no output at the moment)

```
stopping ...
stop fails
```

> any screenshot ?

I will send once

**Comment by walkor** [comment]
The reasons for stop fail I can think of are the following.

1. Pressed Ctrl Z to cause the process to hang up. 
2. The user that runs the stop command is not the same as the startup user. 
3, The PID stored in the PID file is overdue (for example, the server restarts), and the process of pid is not a workerman process. The solution for this case is to delete the workerman's PID file and try again.

**Comment by sm2017** [comment]
@ walkor 1 & 2 is not occured , I'm sure , please dont close issue when the `stop fails` occurred again I eill check 3rd case

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this
