### ISSUE TITLE
workerman运行一段时间后会自动关闭，cron定时重启无效

### ISSUE THREAD

**Issue by aqnaruto** [walkor/Workerman#258]
我的workerman是单独运行的，但是机器上同时有nginx的php服务，
不知是否是干扰问题，每运行十几个小时候会自动关闭。
我在cron里加了定时重启，但是后台定时重启无效，每次我手动去重启才恢复正常

![image](https://user-images.githubusercontent.com/9067159/34904387-cfbe5240-f87f-11e7-837e-40357ec383a7.png)
以上是cron的log，难道这样加错了吗？还是这样根本无效

**Comment by farwish** [comment]
It seems a permission problem.

**Comment by aqnaruto** [comment]
@farwish thankyou, you mean when i  add ` php /web-msg-sender-master/stat.php restart`  to cron  need some permission  ?

**Comment by aqnaruto** [comment]
![image](https://user-images.githubusercontent.com/9067159/34904846-d5f5e516-f888-11e7-960e-3a8ca194fec4.png)

**Comment by walkor** [comment]
Please start workerman as daemon mode.
