### ISSUE TITLE
能收到心跳，但是Gateway::isOnline却返回false

### ISSUE THREAD

**Issue by liujian883** [walkor/Workerman#26]
workerman 3.2.1:

心跳是这么配置的。
$gateway->pingInterval = 4;                                                                           
 $gateway->pingNotResponseLimit = 2;                                                                   
$gateway->pingData = '';  
然后客户端每4s发送心跳数据给服务器。我们的服务器收到之后，会根据 
$key = $_SERVER['GATEWAY_CLIENT_ID'];来存储到memcache里面。而且是8s的过期时间。
此服务运行了2天左右（客户端保持连接2天不断线），出现了异常情况。
我们有两个客户端工控设备。这两个设备一直可以往服务器传输数据，服务器也可以往设备发送数据。
但是，Gateway::isOnline里面却返回false,也就是memcache里面没有gateway-clientid这个客户端。但是
数据却是正常传输的。而我们自己也保存了clientid这个key到memcache，因为我们是定时刷新的。只要客户端有心跳数据来就会刷新，所以，我们里面能看到这个连接，wireshark抓包显示服务器和客户端的连接确实存在。所以应该是gateway进程空间里面保持了这个连接。但是memcache里面却没有，所以business里面看不到这个连接。

**Comment by walkor** [comment]
GatewayWorker已经支持Redis存储，请使用Redis存储

另外GatewayWorker从workerman目录中独立出来了，放在https://github.com/walkor/GatewayWorker
