### ISSUE TITLE
Web services to get the data of bugs

### ISSUE THREAD

**Issue by sunphpacc** [walkor/Workerman#261]
Web request can be normal output for the first time, a second favor data missing, testing found out buffer data is missing,
Found in the web server code is as follows:
$connection - > close ($content);
![qq 20180118183706](https://user-images.githubusercontent.com/35444533/35093730-2c428548-fc7e-11e7-8978-ee629ec7b547.jpg)
![qq 20180118183738](https://user-images.githubusercontent.com/35444533/35093743-35fea120-fc7e-11e7-9d96-f713dd6de29d.jpg)

Found again after every web intercession, connection is not really closed.
So in this code added later
$this - > close
Results web server output is normal, but the server panel quote us close undefined error

**Comment by walkor** [comment]
Can you show all of your codes.

**Comment by walkor** [comment]
Please replace
```php
require_once($template_file);
```
 with
```php
require($template_file);
```
in ```Sunphp/Lib/Controls/TemplateControl.php``` line 40.

The second time loading php the same files via ```require_once``` will not work in workerman,  because workerman is the memory-resident framework.

**Comment by sunphpacc** [comment]
Thank you, replacement shows normal
