### ISSUE TITLE
这里是否有问题？

### ISSUE THREAD

**Issue by presleylee** [walkor/Workerman#262]
https://github.com/walkor/Workerman/blob/3e1d4a3c2bbb83795c12d28784cc9be326d2b22b/Events/Select.php#L268

这里是否有问题？是否应该是这句代码：$except = $this->_exceptFds;

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/commit/5a954448b05287888e1b1b8ea11c393376d83903
Fixed and thanks.
