### ISSUE TITLE
Cloudflare CDN

### ISSUE THREAD

**Issue by zuicis** [walkor/Workerman#264]
$connection -> getRemoteIp, stdoutFile  and  logFile shows wrong IP address if we using cloudflare cdn network with or without mod_cloudflare

cloudflare.com variables:
$_SERVER["HTTP_CF_IPCOUNTRY"]   - user IP address 
$_SERVER["HTTP_CF_CONNECTING_IP"] - user country 

`
Workerman version:3.5.4
PHP version:7.0.27-0+deb9u1

Press Ctrl+C to quit. Start success.
Array
(
    [REQUEST_METHOD] => GET
    [REQUEST_URI] => /
    [SERVER_PROTOCOL] => HTTP/1.1
    [HTTP_HOST] => fr***.hit***.com
    [SERVER_NAME] => fr***.hit***.com
    [HTTP_CONNECTION] => Upgrade
    [HTTP_UPGRADE] => websocket
    [HTTP_ACCEPT_ENCODING] => gzip
    [HTTP_CF_IPCOUNTRY] => LV
    [HTTP_X_FORWARDED_FOR] => 162.158.***.***
    [HTTP_CF_CONNECTING_IP] => 91.135.***.****    
    [HTTP_CF_RAY] => 3e217342dd5c*****
    [HTTP_X_FORWARDED_PROTO] => https
    [HTTP_CF_VISITOR] => {"scheme":"https"}
    [HTTP_PRAGMA] => no-cache
    [HTTP_CACHE_CONTROL] => no-cache
    [HTTP_ORIGIN] => https://fr***.hit***.com
    [HTTP_SEC_WEBSOCKET_VERSION] => 13
    [HTTP_USER_AGENT] => bla bla bla
    [HTTP_ACCEPT_LANGUAGE] => bla bla bla
    [HTTP_COOKIE] => __cfduid=dcaff0ca76dea98de39b3dcf6892c3d2a1512645120; _ga=GA1.2.353154846.1512645142; _gid=GA1.2.831071814.1516714187
    [HTTP_SEC_WEBSOCKET_KEY] => k0WpULbVttDku********
    [HTTP_SEC_WEBSOCKET_EXTENSIONS] => permessage-deflate; client_max_window_bits
    [QUERY_STRING] =>
)`

**Comment by walkor** [comment]
I find some links help that will help.
https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-
https://support.cloudflare.com/hc/en-us/sections/200805497-Restoring-Visitor-IPs
https://www.sunnyhoi.com/how-to-find-real-ip-address-website-behind-cloudflare/
