### ISSUE TITLE
中文用户欢迎到 wenda.workerman.net 讨论

### ISSUE THREAD

**Issue by walkor** [walkor/Workerman#266]
**为了方便所有人(包括外国友人)互相沟通理解，强烈建议使用英文在github发issue**。

中文同胞欢迎到**专设**的中文社区 http://wenda.workerman.net 探讨。
或者加入QQ群：786967683 交流，小伙伴们一直在这里等着你。

感谢大家支持。

**Comment by go-xmyang** [comment]
群已经满员
