### ISSUE TITLE
Problem with SSL

### ISSUE THREAD

**Issue by ckjet** [walkor/Workerman#267]
Hi Walkor. I'm trying code from readme file:

```
$context = array(
            'ssl' => array(
                'local_cert' => '/Users/alias/mamp-cert/fss.loc.crt',
                'local_pk' => '/Users/alias/mamp-cert/fss.loc.key',
                'verify_peer' => false,
            )
        );

        // Create a Websocket server with ssl context.
        $ws_worker = new Worker("websocket://0.0.0.0:2346", $context);

        // Enable SSL. WebSocket+SSL means that Secure WebSocket (wss://). 
        // The similar approaches for Https etc.
        $ws_worker->transport = 'ssl';

        $ws_worker->onMessage = function($connection, $data) {
            // Send hello $data
            $connection->send('hello ' . $data);
        };

        $ws_worker->onConnect = function($connection) {
            // Emitted when websocket handshake done
            $connection->onWebSocketConnect = function($connection) {
                echo "New connection\n";
            };
        };

        Worker::runAll();
```

And this for js-client:

```
ws = new WebSocket("wss://127.0.0.1:2346");
ws.onopen = function() {
    alert("connection success");
    ws.send('tom');
};
ws.onmessage = function(e) {
    alert("recv message from server：" + e.data);
};
```

But client not connect with server. How can I use websocket with SSL?

**Comment by walkor** [comment]
The certificate must be a valid certificate.
The certificate specifies which domain name is used to access it, so please confirm that 127.0.0.1 is legal for the certificate

**Comment by ckjet** [comment]
I'm trying on domain which have certificate, but still not connect.

My test page: https://firstsender.com/st.html

Google chrome show this error:
WebSocket connection to 'wss://firstsender.com:2346/' failed: Error in connection establishment: net::ERR_INSECURE_RESPONSE

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/35658395-0fcfd7d0-073c-11e8-9cfb-6711f6b50e31.png)
![image](https://user-images.githubusercontent.com/6073368/35658417-264164c0-073c-11e8-8e5f-26df72567cda.png)

I found that ```https://firstsender.com:2346/```'s certificate is not consistent with the ```https://firstsender.com/'s certificate```, and ```https://firstsender.com:2346/```'s certificate has expired

**Comment by ckjet** [comment]
Thank you Walkor! That's help me. I forget about end of my sertificate (which im using for sockets).

**Comment by walkor** [comment]
You are welcome.
