### ISSUE TITLE
Error installing pcntl extension on my Mac

### ISSUE THREAD

**Issue by Mydly** [walkor/Workerman#269]
I run "sudo make install"

yumingliangdeMacBook-Pro:pcntl yumingliang$ sudo make install
Password:
/bin/sh /Users/yumingliang/Downloads/php-5.6.33/ext/pcntl/libtool --mode=install cp ./pcntl.la /Users/yumingliang/Downloads/php-5.6.33/ext/pcntl/modules
cp ./.libs/pcntl.so /Users/yumingliang/Downloads/php-5.6.33/ext/pcntl/modules/pcntl.so
cp ./.libs/pcntl.lai /Users/yumingliang/Downloads/php-5.6.33/ext/pcntl/modules/pcntl.la
----------------------------------------------------------------------
Libraries have been installed in:
   /Users/yumingliang/Downloads/php-5.6.33/ext/pcntl/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `DYLD_LIBRARY_PATH' environment variable
     during execution

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
Installing shared extensions:     /usr/lib/php/extensions/no-debug-non-zts-20131226/
cp: /usr/lib/php/extensions/no-debug-non-zts-20131226/#INST@53442#: Operation not permitted
make: *** [install-modules] Error 1

**Comment by walkor** [comment]
It looks like the permissions of the operating system.
