### ISSUE TITLE
Websocket : Uninitialized string offset

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#270]
In the following line
https://github.com/walkor/Workerman/blob/master/Protocols/Websocket.php#L297

Sometime I have warning 
>Uninitialized string offset: 1

**Comment by farwish** [comment]
Maybe some hidden bug triggered in some situation, what the scene is?

**Comment by sm2017** [comment]
@walkor 😭

**Comment by walkor** [comment]
decode() should  be called after input() check.
decode() only be called when input() return >0.
https://github.com/walkor/Workerman/blob/master/Protocols/Websocket.php#L51
will make sure the buffer length will not be less than 2.
So I don't know why you have the waring.
Do you call decode() manually?

You can add some codes to show the call stack like this.
```php
    public static function decode($buffer, ConnectionInterface $connection)
    {
        $masks = $data = $decoded = null;
        // Show the call stack.
        if (strlen($buffer)<2) echo new \Exception('we need more buffer');
        $len = ord($buffer[1]) & 127;
        if ($len === 126) {
            $masks = substr($buffer, 4, 4);
            $data  = substr($buffer, 8);
       ....
```

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
If this problem persists and we can reopen this.
