### ISSUE TITLE
Asynced URL fetch

### ISSUE THREAD

**Issue by vbezruchkin** [walkor/Workerman#282]
Hello,

Thanks for your library - it's awesome :)
I have one question though. I need to parse a list of URLs (preferably using asynced mode) and insert results into my database. 

At the moment I implemented this using https://github.com/stil/curl-easy library, but I would prefer to use one library and it seems yours has all necessary features for this.

Could you please show an example how I can create a pool of URLs and run them to get results using asynced mode?

Just extra information. I created a new Timer worker that's run every 10 minutes, and it starts fine, but I would like to fetch all URLs content during each worker start.

Thanks

**Comment by walkor** [comment]
There is a project hoping to help you.
https://github.com/kiddyuchina/Beanbun

**Comment by vbezruchkin** [comment]
Thanks. I've achieved this using Guzzle :) Thanks for your library again!
