### ISSUE TITLE
Client id conflict

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#286]
According to https://github.com/walkor/GatewayWorker/issues/17

Client id calculated by  `$local_ip`, `$local_port` and  `$connection_id`  , I have a use case that assign client id to uid (In redis)  when a machine restarted ,  `$connection_id`  restarted too , and `clientId` to `uid` map conflicted may be the current clientId captured by another uid before

So can you please make 
https://github.com/walkor/Workerman/blob/master/Connection/TcpConnection.php#L179

as `public static` to let me set it random initial ?

**Comment by walkor** [comment]
> Client id calculated by ```$local_ip```, ```$local_port``` and ```$connection_id```.

 The ```$connection_id``` is created by [gateway::generateConnectionId](https://github.com/walkor/GatewayWorker/blob/2a7a3e0a819220e370b25fd23c8fb64443a42633/src/Gateway.php#L302) , so there's no need to change  anything for TcpConnection.php. 
You can modify behavior of ```gateway::generateConnectionId``` by extending gateway class.

**Comment by sm2017** [comment]
@walkor ok , thanks a lot
