### ISSUE TITLE
socket on multiple thread error

### ISSUE THREAD

**Issue by soha1410** [walkor/Workerman#287]
Hi, when I use this library for socketIO on one thread it works like a charm . but when increase number of thread there is the below error.
`WebSocket connection to 'wss://.....' failed: Error during WebSocket handshake: Unexpected response code: 403`
It try to reconnect until it success but on some client this never happen.
can anyone help me?

**Comment by walkor** [comment]
This library dos not support socketIO, but [phpsocket.io](https://github.com/walkor/phpsocket.io) supports socketIO. 
Unfortunately socketIO does not support multiple threads.

**Comment by soha1410** [comment]
thank you so much .
