### ISSUE TITLE
stream_socket_accept(): accept failed: Connection timed out

### ISSUE THREAD

**Issue by exbit** [walkor/Workerman#296]
what is the reason for this error?

Worker 0 starting...
Worker 1 starting...
Worker 2 starting...
Worker 3 starting...
Workerman[spark] start in DEBUG mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.5.5          PHP version:7.0.28-1
------------------------ WORKERS -------------------------------
user          worker        listen                        processes status
root          none          websocket://10.1.22.252:8000   4         [OK]
----------------------------------------------------------------
Press Ctrl+C to stop. Start success.

An uncaught Exception was encountered

Type:        ErrorException
Message:     stream_socket_accept(): accept failed: Connection timed out
Filename:    /root/Workerman/Worker.php
Line Number: 2171
Worker process terminated
New connection user: monitor from - id: 1 - ip: 10.10.10.2:7220
Worker 3 starting...

**Comment by walkor** [comment]
I'm not sure.
It looks like a network timeout.
How can I reproduce this?

**Comment by exbit** [comment]
Сan't tell how to reproduce the bug, I have it randomly appears. May be this error you need to code to handle that worker would not crash?

**Comment by walkor** [comment]
I guess thundering herd caused this error. Try to set ```$worker->reusePort = true;``` that may help.
See https://github.com/walkor/Workerman/issues/156. 

There is an operator @ to ignore error at 
https://github.com/walkor/Workerman/blob/fbfd9abe7a0415c3568bbbea7604a7bd0f460200/Worker.php#L2171. May be your codes has set set_error_handler() and threw the exception.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this.
