### ISSUE TITLE
Swoole support is invalid

### ISSUE THREAD

**Issue by woann** [walkor/Workerman#300]
My php has installed the swoole extension, but when I turn on the service, I print out Worker::$eventLoopClass instead of Workerman\Events\Swoole instead of \Workerman\Events\Event. This swool support is to be turned on manually? Or Have priority? How can I turn on swoole?

**Comment by walkor** [comment]
Yes, you should turn it on manually with codes like this.
```php
Worker::$eventLoopClass = '\Workerman\Events\Swoole';
```
#294
