### ISSUE TITLE
worker和connection中都维护了一个onmessage？

### ISSUE THREAD

**Issue by JackZForDream** [walkor/Workerman#31]
能不能举个具体的例子说明一下为何要这样？在两个回调中都可以做信息发送，有什么区别的地方？
（区别是只针对当前连接有效，是不是假设在 worker中的onmessage的参数 connection中读取
$connection->worker->connections 然后遍历 绑定onmessage 是无效的。但还是想不出具体的应用场景。动态改变？
）

**Comment by walkor** [comment]
最终起作用的永远是connection上的onMessage回调，
connection建立后worker的onMessage回调会赋值给connection，见源码
https://github.com/walkor/Workerman/blob/master/Worker.php acceptConnection方法实现部分

之所以有个worker->onMessage，主要是方便使用，例如下面代码
```php
use Workerman\Worker;
require_once './Workerman/Autoloader.php';
$worker = new Worker('websocket://0.0.0.0:8484');
// 当有客户端连接事件时
$worker->onConnect = function($connection)
{
    // 设置连接的onMessage回调
    $connection->onMessage = function($connection, $data)
    {
        var_dump($data);
        $connection->send('receive success');
    };
};
// 运行worker
Worker::runAll();
```
与
```php
use Workerman\Worker;
$worker = new Worker('websocket://0.0.0.0:8484');
// 直接设置所有连接的onMessage回调
$worker->onMessage = function($connection, $data)
{
    var_dump($data);
    $connection->send('receive success');
};
// 运行worker
Worker::runAll();
```
效果相同，但是第二种写法更简洁易懂。

每个连接都可以拥有自己的协议及onMessage/onClose/on{...}等属性，运行过程中可以根据需要重新赋值绑定，这样非常灵活，尤其在AysncTcpConnection中。

这里有一个典型的动态设置连接的on{...}回调的应用，https://github.com/walkor/shadowsocks-php，
主要的业务代码见 https://github.com/walkor/shadowsocks-php/blob/master/Applications/Shadowsocks/start.php

**Comment by JackZForDream** [comment]
是的，这样子是灵活了很多。非常感谢您的回答。
