### ISSUE TITLE
Warning: change gid or uid fail.

### ISSUE THREAD

**Issue by AndrewSologor** [walkor/Workerman#312]
Probably it is a question.

What do I try to do is create systemd service to run workerman server. The main purpose is to restart server when it drops (if process will be stopped/killed).

**/etc/systemd/system/workerman.service** config:
```
[Unit]
Description=workerman
After=syslog.target
After=network.target
After=mongodb.service
Requires=mongodb.service

[Service]
Type=forking
PIDFile=/run/workerman/workerman.pid
WorkingDirectory=/path/to/projectRoot
RuntimeDirectory=workerman

User=my-apache-user
Group=my-apache-group

ExecStart=/usr/bin/php5.6 www/index_socketio.php start -d
ExecStop=/usr/bin/php5.6 www/index_socketio.php stop
ExecReload=/usr/bin/php5.6 www/index_socketio.php restart -d
TimeoutSec=300
Restart=always

[Install]
WantedBy=multi-user.target
```
> Why did I set user to my-apache-user? Because I run the service through php's exec() function.

and in my start file **index_socketio.php** I set:
```php
Worker::$pidFile = '/run/workerman/workerman.pid';
```

So when I run `sudo systemctl start workerman.service ` I see next messages in the `workerman.log` file:
```
2018-04-09 21:37:19 pid:11179 Workerman[www/index_socketio.php] start in DAEMON mode
2018-04-09 21:37:19 pid:11184 Warning: change gid or uid fail.
```
`Worker.php` is unable to run `posix_setgid($gid)` and `posix_initgroups($user_info['name'], $gid)` functions because they requires root privileges (and process is being ran under `my-apache-user` user).

**Seems the server and systemd service are working fine.** But I'm not sure that I can leave it as is. I don't want to run the server with root privileges. Is there some pitfalls with wrong group id on the system process?

**Comment by walkor** [comment]
Maybe you setted ```$worker->user = '...';``` in your codes which only working when start workerman as root privileges. So just remove ```$worker->user = '...'; $worker->group = '...'; ``` in your codes.
Also you can ignore this warning because the user of the running process is already apache-user.

**Comment by AndrewSologor** [comment]
I've not changed any worker params except `Worker::$pidFile`.
When I start the server directly from the terminal (i.e. `php www/index_socketio.php start -d`) it detects that the process group is right and I don't get that warning.
I'll leave it as is. Thank you!

**Comment by kaluma78** [comment]
здравствуйте, сделал так как вы написали!
при проверки статуса пишет активно, но сам сервер не работает!
hello, I did as you wrote!
when checking the status, it writes actively, but the server itself does not work!

**Comment by kaluma78** [comment]
here is my code  : startServerCarwash.service

[Unit]
Description=StartServerCarwash

After=syslog.target
After=network.target
After=mongodb.service

[Service]
Type=forking

User=root

ExecStart=/usr/bin/php /home/admin/sites/fresh.test-handyhost.ru/ServerCarwash/server.php start -d


[Install]
WantedBy=multi-user.target

**Comment by kaluma78** [comment]
change user, no changes

**Comment by kaluma78** [comment]
sudo visudo -f /etc/sudoers.d/ServerCarwash

Cmnd_Alias STARTSERVERCARWASH_CMNDS = /bin/systemctl start startServerCarwash.service, /bin/systemctl stop startServerCarwash.service, /bin/systemctl restart startServerCarwash.service, /bin/systemctl status startServerCarwash.service
%nobody ALL=(ALL) NOPASSWD: STARTSERVERCARWASH_CMNDS
