### ISSUE TITLE
Child Process' STDOUT

### ISSUE THREAD

**Issue by IngwiePhoenix** [walkor/Workerman#32]
I am trying to debug an issue, but this issue occurs in a child process of Workerman. How can I get it's STDOUT to be shared with the parent in order to see it in the process, or directed into a file?

**Comment by walkor** [comment]
You can redirect STDOUT into a file like this.

```php
use Workerman\Worker;
require_once './Workerman/Autoloader.php';

Worker::$daemonize = true;

// All output will be redirected to /tmp/stdout.log
Worker::$stdoutFile = '/tmp/stdout.log';

$worker = new Worker('Text://0.0.0.0:8484');
$worker->on{...} = function(){...

// Run all workers
Worker::runAll();
```

More informations see https://github.com/walkor/workerman-manual/blob/master/english/src/worker-development/stdout_file.md

**Comment by IngwiePhoenix** [comment]
And how can I get this working in a non-deamonized mode? The Workerman process is managed via NodeJS. The entry point for Workerman: https://github.com/DragonsInn/BIRD3/blob/master/php-lib/request_handler.php

**Comment by walkor** [comment]
You can also redirect STDOUT into a file like this.
```php
global $STDOUT, $STDERR;
$stdfile = '/your/path/stdfile';
@fclose(STDOUT);
@fclose(STDERR);
$STDOUT = fopen($stdfile,"a");
$STDERR = fopen($stdfile,"a");
```

**Comment by IngwiePhoenix** [comment]
I am redirecting using php://stdout <php://stdout> now. I need to test this more but so far, no error was thrown! :)
