### ISSUE TITLE
Timer+websocket

### ISSUE THREAD

**Issue by energo5** [walkor/Workerman#320]
I have:
$ws_worker = new Worker("websocket://0.0.0.0:2346");
$ws_worker->onMessage = function($connection, $data)
{
    $connection->send('hello ' . $data);
};

How right i can use method $connection->send('text') in same php code instead "echo "Timer"":
$ws_worker->onWorkerStart = function($ws_worker)
{
    $time_interval = 5;
    $timer_id = Timer::add($time_interval,
        function()
        {
            echo "Timer";
        }
    );
};

**Comment by walkor** [comment]
Is this what you want?
```php
$ws_worker->onWorkerStart = function($ws_worker)
{
    $time_interval = 5;
    $timer_id = Timer::add($time_interval,
        function() use ($ws_worker)
        {
            foreach($ws_worker->connections as $connection) {
                $connection->send('text');
            }
        }
    );
};
```

**Comment by energo5** [comment]
Yes, thank you.

**Comment by walkor** [comment]
You are welcome.
