### ISSUE TITLE
Send image from server to client

### ISSUE THREAD

**Issue by energo5** [walkor/Workerman#321]
Hello, сan you tell right way to send image+text instead only text from server:
$ws_worker->onMessage = function($connection, $data) {
    $connection->send('hello');
};

to client:
ws.onmessage = function(e) {
    document.write("recv message from server: " + e.data);
};

**Comment by walkor** [comment]
You can send img tag like ```<img src='your_pic.jpg'>``` to client.
It will be downloaded automatically by HTTP when the browser renderings the img tag.

**Comment by energo5** [comment]
You mean transfer from the server to the client via the websocket only a link to the file, and on the client through JavaScript to show in the browser. Correctly?

**Comment by walkor** [comment]
yes
