### ISSUE TITLE
Combining several WebSocket servers to a cluster

### ISSUE THREAD

**Issue by plashenkov** [walkor/Workerman#325]
Hi!

Is it possible to combine several WebSocket servers to a cluster? Using RabbitMQ or another mechanism. How can this be done? Or should we use https://github.com/walkor/phpsocket.io for this?

Thank you!

**Comment by walkor** [comment]
You use channel to do that.
These links may help.
https://github.com/walkor/Workerman/issues/175
https://github.com/walkor/Workerman/issues/184
