### ISSUE TITLE
Timer problem

### ISSUE THREAD

**Issue by ishland** [walkor/Workerman#328]
I Just Added a timer. Then the memory usage is bigger and bigger. Why?
![screenshot_20180513-222837](https://user-images.githubusercontent.com/30385023/39968285-47904d88-56fd-11e8-87fe-732e942f707a.png)

**Comment by ishland** [comment]
Self fixed

**Comment by walkor** [comment]
What is the problem?

**Comment by ishland** [comment]
memory leaks

**Comment by walkor** [comment]
It is workerman's bug?
