### ISSUE TITLE
Undefined class constant 'CMD_ON_CONNECTION'

### ISSUE THREAD

**Issue by 327** [walkor/Workerman#330]
upgrade to last version,I have some exception:
Undefined class constant 'CMD_ON_CONNECTION' in /data/wwwroot/sd_watch_gateway/vendor/workerman/gateway-worker/src/BusinessWorker.php:377
Stack trace:
#0 [internal function]: GatewayWorker\BusinessWorker->onGatewayMessage(Object(Workerman\Connection\AsyncTcpConnection), Array)
#1 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Connection/TcpConnection.php(639): call_user_func(Array, Object(Workerman\Connection\AsyncTcpConnection), Array)
#2 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #68371, 2, Resource id #68371)
#3 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Events/Event.php(185): EventBase->loop()
#4 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(2130): Workerman\Events\Event->loop()
#5 /data/wwwroot/sd_watch_gateway/vendor/workerman/gateway-worker/src/BusinessWorker.php(190): Workerman\Worker->run()
#6 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(1323): GatewayWorker\BusinessWorker->run()
#7 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(1156): Workerman\Worker::forkOneWorkerForLinux(Object(GatewayWorker\BusinessWorker))
#8 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(1130): Workerman\Worker::forkWorkersForLinux()
#9 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(1455): Workerman\Worker::forkWorkers()
#10 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(1404): Workerman\Worker::monitorWorkersForLinux()
#11 /data/wwwroot/sd_watch_gateway/vendor/workerman/workerman/Worker.php(468): Workerman\Worker::monitorWorkers()
#12 /data/wwwroot/sd_watch_gateway/start.php(41): Workerman\Worker::runAll()

**Comment by taozywu** [comment]
@327  please look your GatewayWorker version.

**Comment by walkor** [comment]
This is not workerman's issue but gatewayworker's.
```Undefined class constant 'CMD_ON_CONNECTION' in /data/wwwroot/sd_watch_gateway/vendor/workerman/gateway-worker/src/BusinessWorker.php:377
```

There is no key words CMD_ON_CONNECTION in https://github.com/walkor/GatewayWorker/blob/master/src/BusinessWorker.php#L377 .
Please make sure you upgraded to the latest version.

**Comment by 327** [comment]
how to see gatewayworker version ? I user composer by  "workerman/gateway-worker": "^3.0"

**Comment by 327** [comment]
![image](https://user-images.githubusercontent.com/2648290/40297878-d5466fb0-5d13-11e8-9bab-104cfb19e766.png)
this is my version info

**Comment by walkor** [comment]
Gateway::VERSION in src/Gateway.php.

**Comment by 327** [comment]
/**
 *
 * Gateway，基于Worker 开发
 * 用于转发客户端的数据给Worker处理，以及转发Worker的数据给客户端
 *
 * @author walkor<walkor@workerman.net>
 *
 */
class Gateway extends Worker
{
    /**
     * 版本
     *
     * @var string
     */
    const VERSION = '3.0.8';

**Comment by walkor** [comment]
Can you show codes of /data/wwwroot/sd_watch_gateway/vendor/workerman/gateway-worker/src/BusinessWorker.php:377 。

**Comment by 327** [comment]
![image](https://user-images.githubusercontent.com/2648290/40302979-98f0e440-5d23-11e8-9eec-415cda79317d.png)

**Comment by walkor** [comment]
gateway-worker/src/BusinessWorker.php:377
As you see , ```Undefined class constant 'CMD_ON_CONNECTION' in ``` error message will not happen here.

**Comment by walkor** [comment]
You are welcome.
