### ISSUE TITLE
Invalid frame header?

### ISSUE THREAD

**Issue by hoangweb** [walkor/Workerman#331]
chrome report WebSocket connection to 'ws://192.168.205.13:8080/' failed: Invalid frame header?
please help me.

**Comment by taozywu** [comment]
@hoangweb  please look http://wenda.workerman.net/?/question/1335

**Comment by taozywu** [comment]
@hoangweb  can you show full code ?

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this.
