### ISSUE TITLE
Class 'Workerman\Workerman\Lib\Timer' not found

### ISSUE THREAD

**Issue by azekammi** [walkor/Workerman#332]
Class 'Workerman\Workerman\Lib\Timer' not found in /Applications/XAMPP/xamppfiles/htdocs/Workerman/Worker.php on line 530

**Comment by walkor** [comment]
Can you  show the codes of /Applications/XAMPP/xamppfiles/htdocs/Workerman/Worker.php on line 530?

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this.

**Comment by nop1984** [comment]
@walkor Got the same problem. I see that Timer.php is located in `namespace Workerman;` while `workerman/http-client/src/ConnectionPool.php` tries to get it in `use \Workerman\Lib\Timer;`

**Comment by joanhey** [comment]
@nop1984 Update your http-client

v0.1.7
https://github.com/walkor/http-client/blob/v0.1.7/src/ConnectionPool.php#L17

v1.0.8 and up
https://github.com/walkor/http-client/blob/v1.0.8/src/ConnectionPool.php#L17

**Comment by nop1984** [comment]
@joanhey thanks, dunno why composer took v 0.1.7 as default.

offtopic: about http-client, maybe you have idea why stream_socket_get_name() returns false? Because of that had to switch to guzzle. and workerman client and server (erpnext) both in same ubuntu VM inside WSL2
