### ISSUE TITLE
Is there a way to distinguish worker processes?

### ISSUE THREAD

**Issue by dajnz** [walkor/Workerman#333]
In case of multiple worker processes it would be great to have capability to distinguish different processes since connection ID is unique within each separate process for the same worker.

This would be helpful for multiple websocket connections handled by single worker instance listening specific port and having several processes. Actually in my case I see same connection IDs for different connections (handled by different processes of the same worker instance), and this makes connection ID unreliable.

And I can't use multiple worker instances each with one process because I need to listen one specific port.

**Comment by walkor** [comment]
Worker has a id property.
You can add prefix to connection->id to make it unique like this.
```php
$worker = new Worker('websocket://0.0.0.08080');
$worker->count = 8;
$worker->onConnect = function($connection) use ($worker){
    $connection->id = $worker->id.$connection->id;
};
...
```
