### ISSUE TITLE
Option for set ip cliente source from HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by INHack20** [walkor/Workerman#336]
t would be very nice if you could set the client ip using a HTTP_X_FORWARDED_FOR header, in order to visualize the real ip of the client when load balancing is implemented with nginx or with haproxy.

Example:

php Server.php connections
Workerman[/home/accwitty/public_html/mpandco_client/src/Node/App/Server.php] connections
--------------------------------------------------------------------- WORKERMAN CONNECTION STATUS --------------------------------------------------------------------------------
PID Worker CID Trans Protocol ipv4 ipv6 Recv-Q Send-Q Bytes-R Bytes-W Status Local Address Foreign Address
12527 PHPSocketIO 2 tcp Frame 1 0 0B 0B 0B 5.2KB ESTABLISHED 172.30.143.19:37364 172.30.143.18:2206
12527 PHPSocketIO 3063 ssl RFC6455 1 0 0B 0B 1.4KB 393B ESTABLISHED 172.30.143.19:2021 172.30.143.2:27590
12527 PHPSocketIO 4439 ssl RFC6455 1 0 0B 0B 1.2KB 234B ESTABLISHED 172.30.143.19:2021 172.30.143.2:24646

The IP 172.30.143.2 is a proxy server with haproxy, but the public ip of de client is another.

Spanish original:
sería muy bueno si se pudiera setear la ip del cliente mediante una cabecera HTTP_X_FORWARDED_FOR, para poder visualizar la ip real del cliente cuando se implementa balanceo de carga con nginx o con haproxy.

**Comment by walkor** [comment]
Workerman is a generic socket framework which not designed specifically for HTTP.
Workerman can support many protocols, and it will not make special implementation for any communication protocol.

**Comment by walkor** [comment]
Sorry, I mean workerman will not provide these features.

**Comment by INHack20** [comment]
Ok thanks.
