### ISSUE TITLE
All clients have the same identifier (1)

### ISSUE THREAD

**Issue by DeltaVetal26** [walkor/Workerman#342]
Hi! I have many devices (WebSocket Client) and WebSocket Server. I want to send commands to clients, knowing their identifier. 1. I connected to the WebSocket server from different clients (Browser / Phone / ESP8266-Wifi), but id everywhere = 1. I decided that the problem is related to the same IP address of the devices, but no. I downloaded the original sample WebSocket server:

`<?php
require_once __DIR__ . '/autoload.php';
use Workerman\Worker;

// Create a Websocket server
$ws_worker = new Worker("websocket://0.0.0.0:2342");

// 4 processes
$ws_worker->count = 4;

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
    echo "New Client: $connection->id\n";
 };

// Emitted when data received
$ws_worker->onMessage = function($connection, $data)
{
    // Send hello $data
    $connection->send('hello ' . $data);
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

// Run worker
Worker::runAll();`
That's what's in the console:
https://imgur.com/a/kukJzKU

How to fix it?

**Comment by taozywu** [comment]
@DeltaVetal26  

It's ok to run your code on my computer！
```
----------------------------------------------------------------
----------------------- WORKERMAN -----------------------------
Workerman version:3.5.11          PHP version:7.2.2
------------------------ WORKERS -------------------------------
user          worker        listen                     processes status
root          none          websocket://0.0.0.0:12345   4         [OK] 
----------------------------------------------------------------
Press Ctrl+C to stop. Start success.
New Client: 1
New Client: 2
```

That's my websocket code
```js
var ws = new WebSocket("ws://127.0.0.1:12345");
ws.onopen = function(e){console.log("onopen");};
ws.onmessage = function(e){console.log(e.data);};
```
Please show your js websocket code.

**Comment by walkor** [comment]
Connection id is not unique for every processes but for one process.
Connection id maybe the same for many processes.
Connection id is an id for one process not for global.
See https://github.com/walkor/Workerman/issues/333

**Comment by DeltaVetal26** [comment]
It worked!
-New Client: 01
New Client: 11
New Client: 31
Connection closed
New Client: 02
Connection closed
New Client: 12
Connection closed
New Client: 21
Connection closed
New Client: 13
Connection closed
New Client: 32
Connection closed
New Client: 03
Connection closed
Connection closed
New Client: 33
Connection closed
New Client: 34
Connection closed
New Client: 14
Connection closed_

@taozywu @walkor 
Many thanks!!! I love the Worker!

**Comment by walkor** [comment]
You are welcome.

**Comment by DeltaVetal26** [comment]
Sorry, it works fine when I have:
```php
$worker->count = 1;
```
I increased the number of connections and installed the channel:
```php
use Workerman\Worker;
require_once __DIR__ . '/autoload.php';

// Channel Server.
$channel_server = new Channel\Server('0.0.0.0', 2206);

$worker = new Worker('websocket://0.0.0.0:2342');
// 6 processes.
$worker->count=6;
$worker->onWorkerStart = function($worker)
{
    // Channel client connect to Channel Server.
    Channel\Client::connect('127.0.0.1', 2206);
    // Subscribe $worker->id event .
    Channel\Client::on($worker->id, function($data)use($worker){
        foreach ($worker->connections as $connection) {
           $connection->send($data);
        }
    });
};

$worker->onConnect = function($connection) use ($worker)
{
    echo "New connection from ip: " . $connection->getRemoteIp() ."\n"; // Сообщение в консоль
    //global $id;
    $id = $worker->id.$connection->id; // id write
    echo "Connect client: $id\n";
};
$worker->onMessage = function($connection, $data) {
   if (strpos($data, 'Browser:') !== false) {
    $wid = $data[9];//substr($data, 10);
    $evsid = substr($data, 10);
    $worker_id = $wid;
    $message = "EVS LED ON";
    Channel\Client::publish($worker_id, $message);
   }
};
Worker::runAll();
```

Example: I send a message:
```txt
"Browser: 32"
```
, then the algorithm truncates this message and writes the variables:
```php
 $worker_id = 3
 $evsid = 2
```
Then the message is sent to channel # 3:
```php
Channel\Client::publish($worker_id, $message);
```
When I send a message = it is sent to all members of the channel
# 2, which is not very good. How do I send a message to a client with ID 32? 3 - channel number, 2 - customer ID. 
The source code of the channel uses only the publication ($ worker_id, $ message);

**Comment by walkor** [comment]
```php
use Workerman\Worker;
require_once __DIR__ . '/autoload.php';

// Channel Server.
$channel_server = new Channel\Server('0.0.0.0', 2206);

$worker = new Worker('websocket://0.0.0.0:2342');
// == Add a evsidConnections to store evsid to connection. ==
$worker->evsidConnections = [];
// 6 processes.
$worker->count=6;
$worker->onWorkerStart = function($worker)
{
    // Channel client connect to Channel Server.
    Channel\Client::connect('127.0.0.1', 2206);
    // Subscribe $worker->id event .
    Channel\Client::on($worker->id, function($data)use($worker){
        $evsid = $data['evsid'];
        $content = $data['content'];
        if (isset($worker->evsidConnections[$evsid])) {
            $connection = $worker->evsidConnections[$evsid];
            $connection->send($content);
        }
    });
};

$worker->onConnect = function($connection) use ($worker)
{
    echo "New connection from ip: " . $connection->getRemoteIp() ."\n"; // Сообщение в консоль
    //global $id;
    $id = $worker->id.$connection->id; // id write
    // == Store  ==
    $connection->evsid = $id;
    $worker->evsidConnections[$id] = $connection;

    echo "Connect client: $id\n";
};

// == Do not forget unset $worker->evsidConnections[$connection->evsid] ==
$worker->onClose = function($connection)use($worker){
    if (isset($connection->evsid)) {
        unset($worker->evsidConnections[$connection->evsid]);
    }
};

$worker->onMessage = function($connection, $data) {
   if (strpos($data, 'Browser:') !== false) {
    $wid = $data[9];//substr($data, 10);
    $evsid = substr($data, 10);
    $worker_id = $wid;
    // == Pass evsid to ==
    $message = ["evsid"=>$evsid, "content"=>"EVS LED ON"];
    Channel\Client::publish($worker_id, $message);
   }
};
Worker::runAll();
```

**Comment by DeltaVetal26** [comment]
Unfortunately, this does not work(
Example: I'm writing the command
 ```txt
"Browser: 42"
```
, but on this device with ID 42 commands were not received. Did I do something wrong?

**Comment by walkor** [comment]
Fixed and please try again.

**Comment by DeltaVetal26** [comment]
@walkor Everything is working! Many thanks!!!
