### ISSUE TITLE
reactPHP Plugin dosen't work in new version of workerman

### ISSUE THREAD

**Issue by jbkingsley** [walkor/Workerman#343]
After update workerman to new version, reactphp plugin dumped in php7+
I checked the files changed and  found Workerman/Events/React/ has update.

Base.php implements LoopInterface, so I got the error : 
" Declaration of Workerman\Events\React\Base::addReadStream($stream, $listener) must be compatible with React\EventLoop\LoopInterface::addReadStream($stream, callable $listener)"

**Comment by walkor** [comment]
Please try to update react/event-loop to the latest version.
React/event-loop changed the React\EventLoop\LoopInterface since v0.5.0.
