### ISSUE TITLE
fwrite buffer is kinda small

### ISSUE THREAD

**Issue by tyurderi** [walkor/Workerman#344]
See here: https://github.com/walkor/Workerman/blob/master/Connection/TcpConnection.php#L688

For bigger downloads (like 100MB) this buffer size is too small. Can't it simply be increased or configurable?

**Comment by walkor** [comment]
```php
fwrite($this->_socket, $this->_sendBuffer, 8192);
```
8192 is not buffer size limit, but the length of data for fwrite.
The send buffer size limit by ```TcpConnection::$defaultMaxSendBufferSize``` which default value is 1024*1024 Bytes and can be change by codes ```TcpConnection::$defaultMaxSendBufferSize = 100*1024*1024;```

**Comment by tyurderi** [comment]
Yup - but by increasing `TcpConnection::$defaultMaxSendBufferSize` the speed of the transmission is way too slow. It feels like 0,1MB per second. When changing the length of data for fwrite the speed is increasing very good. For example I did this:

```php
fwrite($this->_socket, $this->_sendBuffer, 8192 * 1024);
```

**Comment by walkor** [comment]
Removed the length param for write.
But for ssl connection the length param must be setted due to https://bugs.php.net/bug.php?id=72333 .
