### ISSUE TITLE
make event.so with Include libevent OpenSSL support YES

### ISSUE THREAD

**Issue by jbkingsley** [walkor/Workerman#349]
when I checked Include libevent OpenSSL support NO, I got a make-failed. 
So I had to check Yes.

I wonder if I checked Yes,  wokerman would work well or not ？

**Comment by walkor** [comment]
Work well.

**Comment by jbkingsley** [comment]
OK...thanks
I'm gonna keep watching my program

**Comment by walkor** [comment]
You are welcome.
