### ISSUE TITLE
如何优雅的实现应用层路由

### ISSUE THREAD

**Issue by shellus** [walkor/Workerman#35]
例如我的上行包和下行包都有“route”字段，常见值：“push.error.auth.not_login”、“post.auth.login”
如何优雅的进行路由，workerman中是否已有接口？如果没有，应该如何实现才优雅？是否可以使用某个现有的composer route package来实现？

**Comment by walkor** [comment]
workerman自身没有路由。
路由属于业务框架部分，workerman自身不涉及任何业务逻辑，workerman只专注于socket通讯，不关注传输的是什么内容，workerman传输的数据可能是包含业务逻辑的数据包，也可能是无任何逻辑的视频流，或者是其它数据

如何实现路由可以根据自己业务情况而定，业务不同路由实现可能不同，这里没有统一的方案

**Comment by shellus** [comment]
那是否有典型的路由案例可以参考呢？

**Comment by walkor** [comment]
不好意思，我这里没有
