### ISSUE TITLE
Fork and process life

### ISSUE THREAD

**Issue by Shkarbatov** [walkor/Workerman#351]
Hi all, I have two question about daemon work.

I use supervisord for forking php processes and supervisord watching for this process work.
If some script will die he will restart it.

As I understand, Workerman can fork process like:

    $ws_worker->count = 4;

**1)** But if one of workers will die - it will not start again, so I still need use supervisord for this?
**2)** How you prefer to work with this? Make fork by PHP, as code above and use supervisord or use supervisord for fork process and watch by them.

**Comment by DTFreeman** [comment]
$ws_worker->count = 4;

 $ws_worker Master process will fork 4 child process, and master process will never die... if child process crash/exception/die, master will restart it!

**Comment by Shkarbatov** [comment]
> master process will never die

To optimistic :)

> @see Workerman\Worker::monitorWorkersForLinux()

Thanks!
