### ISSUE TITLE
Notice: Use of undefined constant OS_TYPE_LINUX

### ISSUE THREAD

**Issue by morix-gao** [walkor/Workerman#352]
Notice: Use of undefined constant OS_TYPE_LINUX - assumed 'OS_TYPE_LINUX' in 

Message：
Notice: Use of undefined constant OS_TYPE_LINUX - assumed 'OS_TYPE_LINUX' in /xxxx/vendor/workerman/workerman/Worker.php on line 2005
Use of undefined constant OS_TYPE_LINUX - assumed 'OS_TYPE_LINUX' in file /xxxx/vendor/workerman/workerman/Worker.php on line 955

Centos7 + PHP5.6

How to fix it ?

**Comment by walkor** [comment]
OS_TYPE_LINUX defined in file https://github.com/walkor/Workerman/blob/master/Lib/Constants.php.
Please check.

**Comment by morix-gao** [comment]
Thank U~
