### ISSUE TITLE
PHP Warning:  Error while sending STMT_CLOSE packet. PID=21790 in Unknown on line 0

### ISSUE THREAD

**Issue by olegius88** [walkor/Workerman#357]
Hi.

How correctly to destroy the worker process ? if possible, show the code

**Comment by taozywu** [comment]
@olegius88 
Can you show more informations that include the workerman version, the third-party framework, and the PHP version?

**Comment by walkor** [comment]
MySql server will close connection when the connection idle for `interactive_timeout` seconds which can be change in my.conf.
The error message will be displayed when the php process closing and then mysql extension will send close package to mysql server by the closed connection. 

You can close the mysql connection manually when the the task completed then the close package will not send again to mysql server.
Finally,  this is not a serious problem. You can just ignore it.

**Comment by olegius88** [comment]
workerman-3.5.14-stable
framework - WordPress 4.9.8
PHP 7.2.9

worpdress run in onWorkerStart event in single Worker

**Comment by taozywu** [comment]
@olegius88 

Please do as he(@walkor) says 

I guess when your scripts are done , but you do not close mysql 

Good luck at last!
