### ISSUE TITLE
using in docker container with my app

### ISSUE THREAD

**Issue by sanan-php** [walkor/Workerman#362]
Currently in my Dockerfile:
```bash
CMD ["/usr/sbin/php-fpm7.2", "-F", "./chatter/web/ws/index.php start -d"]
```
Unfortunately, this method launches a worker from a websocket, but when asked from a browser, this php file does not see the incoming data $ _REQUEST, $ _COOKIE, etc. (Obviously, because it's CLI). I need to start the worker with the websocket, inside the docker container with my application, so that it also accepts incoming data. For the second day I'm trying to solve it, but I can not do anything :(

Is it possible to solve this problem?

**Comment by sanan-php** [comment]
I also removed "./chatter/web/ws/index.php start -d". Because this needs to be done inside the container, not in the dockerfile :) in any case, this does not solve the problem

**Comment by walkor** [comment]
Workerman works only in `php cli`, but `CMD ["/usr/sbin/php-fpm7.2", "-F", "./chatter/web/ws/index.php start -d"]` seems use `php-fpm`.

**Comment by sanan-php** [comment]
I also removed "./chatter/web/ws/index.php start -d". Because this needs to be done inside the container, not in the dockerfile :) in any case, this does not solve the problem

**Comment by sanan-php** [comment]
thanks:)  issue solved! greetings from Moscow:)) 
the problem really was not only this, but also in my settings of the docker, as well as what should be specified when creating the websocket ip-address 0.0.0.0 with port from dockerfile's EXPOSE value (for ex 8080)
