### ISSUE TITLE
Problems with frames

### ISSUE THREAD

**Issue by abramovantonru** [walkor/Workerman#363]
Hello. I have problems with transport data from client to server by websocket workerman connection (BUT server messages to client by local tcp worker without errors).

Params:
Client OS = windows 10;
Server OS = centos 7 (it's local server in virtual machine); 
Browser = chromium based latest version (ws connection on other production service work good);

Server side code:

```
<?

require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;

// Create a Websocket server
$ws_worker = new Worker("websocket://0.0.0.0:8891");

// 4 processes
$ws_worker->count = 4;

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
	echo "New connection\n";
};

// Emitted when data received
$ws_worker->onMessage = function($connection, $data)
{
	// Send hello $data
	$connection->send('hello ' . $data);
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
	echo "Connection closed\n";
};

// Run worker
Worker::runAll();
```

Client side code:

```
var ws = new WebSocket ('ws://nskuslugi.loc:8891');

ws.onopen = function () {
	console.log('Open');
}

ws.onmessage = function (e) {
	console.log('Message:' + e.data);
}

ws.onclose = function () {
	console.log('Close');
}

ws.onerror = function(){
	console.log(e);
}

ws.send('Some data to send');
ws.send('And more data');
```

Browser error: "WebSocket connection to 'ws://nskuslugi.loc:8891/' failed: Could not decode a text frame as UTF-8."
Server error: "frame not masked so close the connection".

What am I doing wrong?
Coded in JSON request and response, but the error is the same.

P.S sorry for my English

![image](https://user-images.githubusercontent.com/20409030/45189442-b68b4900-b241-11e8-9718-2db3b7494d10.png)
![image](https://user-images.githubusercontent.com/20409030/45189458-c60a9200-b241-11e8-9498-afe7fb677e68.png)
![image](https://user-images.githubusercontent.com/20409030/45189475-d7ec3500-b241-11e8-9182-ec49b37fc92f.png)

**Comment by abramovantonru** [comment]
Dump: https://pastebin.com/qMTNwDBi

```
20 packets captured
20 packets received by filter
0 packets dropped by kernel
```

![image](https://user-images.githubusercontent.com/20409030/45205130-f4ac5b00-b289-11e8-8fbf-9cbc3744b1c2.png)
![image](https://user-images.githubusercontent.com/20409030/45205214-29201700-b28a-11e8-9fcb-a577a38e2fe5.png)
![image](https://user-images.githubusercontent.com/20409030/45205229-39d08d00-b28a-11e8-9489-77af0be63c77.png)

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/45212811-7327ed80-b2c8-11e8-997e-97a6b3e4293e.png)
Try to add codes `echo "input:",bin2hex($buffer),"\r\n";` to `Protocols/Websocket.php` like this. 
Restart workerman and run command `tcpdump -AXXns 4096 -iany port 8891` and retry then show the output.

**Comment by abramovantonru** [comment]
Server echo: https://pastebin.com/NC3a0MXn
Dump: https://pastebin.com/hddE1gRc

![image](https://user-images.githubusercontent.com/20409030/45213358-fe40bd80-b29f-11e8-810f-4651fb137947.png)

**Comment by walkor** [comment]
Please compress and upload all the codes.

**Comment by abramovantonru** [comment]
There may be a conflict between the server settings and the Workerman, because the other project (phpws) is working completely.
I will remind you that errors appear only when the client sends messages to the server. Separately from the server the messages come up correctly, but not in response to the client, but sent through the local socket.

[workerman.zip](https://github.com/walkor/Workerman/files/2363226/workerman.zip)

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/45274007-ec515b80-b4e7-11e8-9f2a-e346100e3648.png)
![image](https://user-images.githubusercontent.com/6073368/45274026-0428df80-b4e8-11e8-81e4-379218264cee.png)

It works fine for me.

**Comment by walkor** [comment]
Closing since it seems we can't help here.

**Comment by abramovantonru** [comment]
Thank you for your time. The problem can not be solved and you can not reproduce it. It's a pity, but it happens. I now use swoole, everything works fine without any changes to the platform and settings. There is a large community around Workerman and I like it, but such problems do not allow it to be used. Probably some problems with the place where the client understands how to sign a frame with a mask. Only this way I can explain the byte code instead of the normal input data on the server. Two different frameworks work, so the problem is only this. I apologize for not being able to understand and help improve the Workerman.

**Comment by walkor** [comment]
If `mbstring.func_overload = 2/3/7` in php.ini then the behavior of function strlen() will changed and the error happened. 
Php manual : http://www.php.net/manual/en/mbstring.overload.php

So make sure the `mbstring.func_overload = 0` in your php.ini every thing will work fine.

**Comment by abramovantonru** [comment]
Thanks you, but my CMS Framework required _mbstring.func_overload = 2_.
