### ISSUE TITLE
Some code snippets to be optimized for Worker.php 

### ISSUE THREAD

**Issue by blogdaren** [walkor/Workerman#365]
@walkor well,  i found that some code snippets which located in Worker.php seems to be redundant between line 1591 and line 1602, so i guess there is a better workaroud to remove the redundant code.
#### Now it looks like this:
https://github.com/walkor/Workerman/blob/32d510235cee94c7172a9b683b2b47d1ef38bc74/Worker.php#L1583-L1602
#### After removing the redundant code, it looks like this:
https://github.com/blogdaren/Workerman/blob/1d8d104dede52c02d58b255351976bcc3d2bf8d6/Worker.php#L1583-L1597

#### so is it right to be optimized for this?  or my pleasure to submit a PR if necessary.

**Comment by walkor** [comment]
I'm not sure. 
The codes format looks disordered.

**Comment by walkor** [comment]
Please format the codes and I will try check again.

**Comment by blogdaren** [comment]
@walkor 
1. well, i have found the reason why codes become so disordered on github, plz see:   http://www.blogdaren.com/post-2476.html
2. BTW, i fixed the code reformat added pull request #364， and i will pay more attention to it later.
3. After removing the redundant code  once again, it looks like this:
https://github.com/blogdaren/Workerman/blob/0c70d0f431cf676a5b86ef42da0fde4a0a780cba/Worker.php#L1583-L1597

**Comment by walkor** [comment]
That's ok， please send pr.
Thank you.

**Comment by blogdaren** [comment]
PR #367 submited

**Comment by walkor** [comment]
Merged and thanks.
