### ISSUE TITLE
How to display data to the browser when the server communicate with each other.

### ISSUE THREAD

**Issue by tuchido** [walkor/Workerman#371]
Hi Walkor,

I'm developing an application, which allows the servers to connect to each other via websocket.

My code is as follows:

Server A : 

```
        $ws_worker = new Worker("websocket://0.0.0.0:1110");
	$ws_worker->onWorkerStart = function($ws_worker)
	{
	    echo "Worker MCS starting...\n";
	};

	$ws_worker->onConnect = function($connection)
	{
		echo "new connection from ip " . $connection->getRemoteIp()." ".$connection->getRemotePort(). "\n";
	};

	$ws_worker->onMessage = function($connection, $data)
	{

	    $connection->onWebSocketConnect = function($connection)
	    {

		    $ws_connection = new AsyncTcpConnection("ws://0.0.0.0:1111");
		    $ws_connection->onConnect = function($connection){
		        $connection->send('data');
		    };
		    $ws_connection->onMessasge = function($connection, $data){
		        echo "recv: $data\n";
		    };
		    $ws_connection->onError = function($connection, $code, $msg){
		        echo "error: $msg\n";
		    };
		    $ws_connection->onClose = function($connection){
		        echo "connection closed\n";
		    };
		    $ws_connection->connect();
	    };
	};

	$ws_worker->onClose = function($connection)
	{
	    echo "Connection closed";
	};

	// Run worker
	Worker::runAll();
```
Server B : 

```
        $ws_worker = new Worker("websocket://0.0.0.0:1111");
	$ws_worker->onWorkerStart = function($ws_worker)
	{
	    echo "Worker starting...\n";
	};

	// Emitted when new connection come
	$ws_worker->onConnect = function($connection)
	{
	    // Emitted when websocket handshake done
	    $connection->onWebSocketConnect = function($connection)
	    {
	        echo "New connection\n";
	    };
	};

	// Emitted when data is received
	$ws_worker->onMessage = function($connection, $data)
	{
		echo $data;
	    // Send hello $data
	    $connection->send('hello ' . $data);
	};

	// Emitted when connection closed
	$ws_worker->onClose = function($connection)
	{
	    echo "Connection closed";
	};

	// Run worker
	Worker::runAll();
```

How do I display data to the browser for tracking type like progress bar with outgoing data and received data?

Please help me because I need to solve this problem.

Thanks.

**Comment by tuchido** [comment]
@walkor

**Comment by walkor** [comment]
Here is an example for javascript.
```javascript
ws = new WebSocket("ws://ip:1111");
ws.onopen = function() {
    ws.send('tom');
};
ws.onmessage = function(e) {
    // browser will recv data from workerman
    alert("recv:" + e.data);
};
```

**Comment by tuchido** [comment]
thanks walkor,

I tried this way, but that's not what I want to ask.

My idea is that the workers communicate with each other but how can it be displayed to the browser?

Or is there a way to save to the database and display it to the browser in real time?

**Comment by tuchido** [comment]
If you follow the javascript code above, the client can only connect to the server, and the server can not connect to the client.

I want to simulate the server and connect to each other.

There are 5 servers:
server A connects and sends data to server B, server B receives the data of server A and processes, then server B connects and sends data to server C and finally server C returns the connection for server A.

In a cycle like this, how can I display the data sent and the received data of all servers to the browser?

**Comment by walkor** [comment]
Sorry for my last answer.
You use channel to do multi workers communication.
These links may help.
https://github.com/walkor/Workerman/issues/175
https://github.com/walkor/Workerman/issues/184
https://github.com/walkor/Workerman/issues/317

**Comment by tuchido** [comment]
Hi Walkor,

Thanks for your help, I am very happy to be told this.

**Comment by walkor** [comment]
You are welcome.
