### ISSUE TITLE
建议 AsyncTcpConnection 增加一个 remoteHost 属性

### ISSUE THREAD

**Issue by xiaopiao5789** [walkor/Workerman#373]
AsyncTcpConnection 里面有一个 getRemoteHost 方法，获取的是在构建的时候传入的地址中 host。
这里会导致 Ws 协议设置 Host 的时候用的是地址的 host，并且不能自行通过 $this->wsHttpHeader['Host'] 进行设置。
希望这个地方改进一下。
实在无处可提交建议，才发到 GitHub，请见谅。

**Comment by walkor** [comment]
什么情况下需要地址的host与http header中的host不同呢？

**Comment by xiaopiao5789** [comment]
@walkor 公共服务使用 CDN 加速，如果是内部服务则没太大必要经过 CDN，如果服务端对 Host 进行绑定则需要这种情况。

**Comment by xiaopiao5789** [comment]
Duplicate of #374

**Comment by walkor** [comment]
Ws prptocol support host setting now.
```php
$ws_connection = new AsyncTcpConnection("ws://workerman.net:7272");
$ws_connection->headers = array('Host' =>'workerman.net');
$ws_connection->onMessage = function($con, $data){
    var_export($data);
};
$ws_connection->connect();
```
