### ISSUE TITLE
OnClose function when connection is broken

### ISSUE THREAD

**Issue by DeltaVetal26** [walkor/Workerman#377]
Hi,

Workerman has a WebSocket server.
If the client closes the connection, I see a message like "Connection Closed". But when a sudden shutdown occurs, for example, when a client has a network failure, I don’t see any messages.

Is it possible to track the sudden closure of a client using the onClose function?

**Comment by walkor** [comment]
Not all closure of a client can be track.
Some time client can not send `fin` package to the server for example the network closed unexpectedly.
IF server not receive a `fin` package it will think that the connection is not break so the `onClose` callback not will be fired.
You can send something to client to detect the broken, and this is why all the long connection applications maintain the heartbeat on the application layer.
