### ISSUE TITLE
路由规则问题

### ISSUE THREAD

**Issue by liujian883** [walkor/Workerman#38]
在我们的项目里面，存在这样一种情况，gateway/business模型中，business收到客户端的某一种命令，其实应该所有的business都执行某种操作。所以，我想在gateway解析出我们自定义的协议之后，根据协议的命令字来决定是随机路由还是全部路由。
目前自定义的路由也只能路由给一个business。
$gateway->router = function($worker_connections, $client_connection, $cmd, $buffer)
{
   //这里根据$buffer中我们自定义的命令来决定是随机转发还是全部转发
   if(特殊命令需要全部转发)
{
return $worker_connections;
} 
   return $worker_connections[array_rand($worker_connections)];
};

sendToWorker里面就需要做如下改动：
            // 调用路由函数，选择一个worker把请求转发给它
            $worker_connections = call_user_func($this->router, $this->_workerConnections, $connection, $cmd, $body);
         foreach ($worker_connections as $worker_connection)
        {
            if(false === $worker_connection->send($gateway_data))
            {
                $msg = "SendBufferToWorker fail. May be the send buffer are overflow";
                $this->log($msg);
                return false;
            }
       }

这样可行不？谢谢。

**Comment by liujian883** [comment]
使用is_array判断下$worker_connection再进行foreach。实验确定可以进行全部business的路由

**Comment by walkor** [comment]
可以
