### ISSUE TITLE
It maybe bugs for Text protocol

### ISSUE THREAD

**Issue by blogdaren** [walkor/Workerman#386]
https://github.com/walkor/Workerman/blob/b374bb86f9dae74bf373e924173a891eb6435c7a/Protocols/Text.php#L68

well, as we can see line 68 above,  the code snippet ` trim($buffer)` will trim both the left and right whitespace , however the `encode` method only add the right "\n" to the package, thus it will cause some words with space to be ouput unexpectedly,  i think `rtirm($buffer)`  maybe right here.

**Comment by walkor** [comment]
Fixed.
