### ISSUE TITLE
I run in -d mode but my terminal is blocked

### ISSUE THREAD

**Issue by sanan-tech** [walkor/Workerman#387]
https://imgur.com/O0m7j9L

Why is my terminal blocked and why I can't execute other commands in the terminal after launch?

**Comment by sanan-tech** [comment]
I run Ctrl+C, Ctrl+Z, exit command, but is not working:(

**Comment by walkor** [comment]
Please try to run command ‘ strace public/wss/index.php start -d’ and show the output.

**Comment by sanan-tech** [comment]
> Please try to run command ‘ strace public/wss/index.php start -d’ and show the output.
https://anotepad.com/notes/hjfjtp

**Comment by walkor** [comment]
Please show your command for starting workerman.
It seems like you are using docker and docker can not receive your ctrl c (SIGINT) signal.
