### ISSUE TITLE
TcpConnection中close的一个错误

### ISSUE THREAD

**Issue by agui2200** [walkor/Workerman#39]
TcpConnection 中close方法中$this->send 参数错误,导致错误的数据包解析失败,gateway无限epoll_wait假死

**Comment by walkor** [comment]
<pre>close方法中$this->send 参数错误</pre>

没看出参数哪里错了

**Comment by agui2200** [comment]
.....就$this->send,在close方法里面，send的时候，传的是你自己写的msg字符串，然后因为定义的方法，默认是要去封包的，封包的时候就会失败了，还有个问题，set_error_handler，这个东西，我觉得workerman自己应该定义一个

**Comment by walkor** [comment]
发个pullrequest吧，看不懂你在说什么。 定义方法？封包失败？因为定义的方法导致封包失败？

set_error_handler 框架自身用不到这个，没有必要定义。并且定义了可能会影响业务，因为业务很可能会定义自己的set_error_handler 。如果业务需要它可以完全自己定义。
