### ISSUE TITLE
Worker[xxx] process terminated with ERROR: E_COMPILE_ERROR "Cannot declare class xxx, because the name is already in use in xxxxxx line xx

### ISSUE THREAD

**Issue by blogdaren** [walkor/Workerman#391]
https://github.com/walkor/Workerman/blob/9893a3b26eb06f9d35a760e0dd049a5dacbfcb40/WebServer.php#L208

1、Now, make workerman work as a webserver, and let us assume that the web root is `/path/to/web` where i write a php script named `index.php`：
````
<?php
namespace User;

class User
{
    static public function getName()
    {
        return 'user-1' . time();
    }
}

echo \User\User::getName() . '<br />';
echo "user-2" . '<br />';
````
2、`curl http://x.x.x.x./index.php`, then php throw error as title described, and i find out it seems to be the problem of  `include` statement, which indeed can explain why error occurs, so i try to change `include $workerman_file`  to `include_once $workerman_file`, then it worked well as expected, but it cause some other problems, `ob_xxx` functions not work as expected.

**Comment by walkor** [comment]
include_once will not include and execute index.php again so no output there.
In workerman, classes should be defined as a single file and loaded with include_once/require_once.
The standard practice is like this.
index.php
```php
<?php
require_once /your/path/of/User.php
echo \User\User::getName() . '<br />';
echo "user-2" . '<br />';
```
This is also the practice of most frameworks.

**Comment by blogdaren** [comment]
okay, i got that , tks.

**Comment by walkor** [comment]
You can add a file monitor to check if any file changed and then reload automatically.
Here is some example.
https://github.com/walkor/workerman-filemonitor
https://github.com/walkor/workerman-filemonitor-inotify (inotify extension required)

**Comment by blogdaren** [comment]
en...., i got that【FileMonitor】 long ago,  **but as to http application**, i just don't understand why we need workerman to reload the code manually or with compoment like  `FileMonitor` every time when the code self changed,  if so, on one hand,  it will make us do such a  job frequently in development mode； on the other hand, i guess that the good news is the class code `require_once` will keep reside memory, right？  so do u mean is it necessary or right way to do like this ?

**Comment by walkor** [comment]
Yes, workerman is a resident memory program. PHP not allowed to redefine a class when it already in memory.
```php
<?php
namespace User;

class User
{
    static public function getName()
    {
        return 'user-1' . time();
    }
}

echo \User\User::getName() . '<br />';
echo "user-2" . '<br />';
```
The codes works fine in php-fpm/apache because everything will be destroyed(include class definition) after the request finished. When the next request comes php-fpm/apache will load the class to memory again and  there is problem because every thing destroyed before this request. Everything destroyed and rebuild again will lead to bad performance.
If you use other resident memory http application like java/c/c++/go etc it also need to some operation like reload after code change.

**Comment by blogdaren** [comment]
@walkor 
1、firstly, tks for your awesome replying, i feel that i m lack of certain understanding for the specifics `resident memory` for a long time, i always thought  **HTTP APPLICATION** code based on Workerman works like PHP-FPM,  **i just mean the HTTP APPLICATION**，currently it looks i have wrong understanding， in other words, all applications based on Workerman will run as `resident memory` ，so is it right to understand？
2、secondly, if step one what i said is right, i have a little of doubt for the WebServer：
https://github.com/walkor/Workerman/blob/9893a3b26eb06f9d35a760e0dd049a5dacbfcb40/WebServer.php#L208
here, the `include statement`，【yeah i can understand the class code】but assume the application code  `/path/to/index.php` looks like this:
`<html><body>demo</body></html>`,  in this case,  i wonder how `include` can make the index.php keep reside memory？ and i know that we call `include` every time will lead to PHP to reload the code from disk,  now it seems contradictory,  is it right to understand or how was that？

**Comment by blogdaren** [comment]
@walkor 
1、firstly, tks for your awesome replying, i feel that i m lack of certain understanding for the specifics `resident memory` for a long time, i always thought  **HTTP APPLICATION** code based on Workerman works like PHP-FPM,  **i just mean the HTTP APPLICATION**，currently it looks i have wrong understanding， in other words, all applications based on Workerman will run as `resident memory` ，so is it right to understand？
2、secondly,  i have a little of doubt for the WebServer：
https://github.com/walkor/Workerman/blob/9893a3b26eb06f9d35a760e0dd049a5dacbfcb40/WebServer.php#L208
here, the `include statement`，【yeah i can understand the class code】but assume the application code  `/path/to/index.php` looks like this:
`<html><body>demo</body></html>`,  in this case,  i wonder how `include` can make the index.php keep reside memory？ and i know that we call `include` every time will lead to PHP to reload the code from disk,  now it seems contradictory,  is it right to understand or how was that？

**Comment by blogdaren** [comment]
@walkor  okay, got that..., tks a lot.
