### ISSUE TITLE
Connect to remote server from PHP

### ISSUE THREAD

**Issue by FrozenCoyote** [walkor/Workerman#392]
$host = 'my_ws_server.ru';  // my server
 $port = my_port;
 $local = "http://my_ws_server.ru/ws/sender.php";  //my_script
 $data = 'hello world!';  //что шлем

 $head = "GET / HTTP/1.1"."\r\n".
 "Upgrade: WebSocket"."\r\n".
 "Connection: Upgrade"."\r\n".
 "Origin: $local"."\r\n".
 "Host: $host"."\r\n".
 "Content-Length: ".strlen($data)."\r\n"."\r\n";

 $sock = fsockopen($host, $port, $errno, $errstr, 2);

 fwrite($sock, $head ) or die('error:'.$errno.':'.$errstr);
 $headers = fread($sock, 2000);

 /* Here I drops data from $headers into file, for control, and what I have: 
HTTP/1.1 400 Bad Request
<b>400 Bad Request</b><br>Sec-WebSocket-Key not found.<br>This is a 
WebSocket service and can not be accessed via HTTP.<br>See <a 
href="http://wiki.workerman.net/Error1">http://wiki.workerman.net/Error1</a> 
for detail. 
*/
fclose($sock);

what i need to do to connect to my remote server? Thank you

**Comment by walkor** [comment]
I think this link will help.
https://github.com/Textalk/websocket-php
