### ISSUE TITLE
mac os  static::$_statisticsFile  is_readable

### ISSUE THREAD

**Issue by xiaobaig0407** [walkor/Workerman#393]
my question is the same when i use php testprocess.php  status 
it shows not run and didn't show the  chart 
and I debuged it  it shows that 
if (!is_readable(static::$_statisticsFile)) {
            return '';
        }
I found _statisticsFile is not  writeable ,
I touch the  new _statisticsFile  file   called  at the directroy 
/var/folders/jh/_pz07vrj0d788kpj39fymkg80000gn/T/_usr_local_var_www_workerman_test_testprocess.php.status

but it still not work  and I change the perssion into chmod 777 /var/folders/jh/  , it still  execute 
!is_readable(static::$_statisticsFile),
and the file /_usr_local_var_www_workerman_test_testprocess.php.status also disappear in a few minutes

**Comment by walkor** [comment]
`It shows not run` there are three reasons for this.

1. The service has not been started or already shut down. Run command `ps auxf` to see if process workerman exists.

2. Pid file missing. The pid file localtion is `dirname('workerman/Worker.php'). "/../xxx.pid` by default and can be changed by codes `Worker::$pidFile='/your/path/workerman.pid';`.

3. The process startup user and status user are not the same.

**Comment by xiaobaig0407** [comment]
and I change this sentense 
static::$_statisticsFile                      = sys_get_temp_dir() . "/$unique_prefix.status";
into 
   static::$_statisticsFile                      =   dirname(__FILE__) . "/test/$unique_prefix.status";
,otherwise it will stop at this 
 if (!is_readable(static::$_statisticsFile)) {
            return '';
        }

**Comment by xiaobaig0407** [comment]
sorry, i have a questioin , I can use strace to debug in liux ,but what can i do with mac?

**Comment by walkor** [comment]
Try dtruss with mac.
