### ISSUE TITLE
Example of handshake for WebSocket

### ISSUE THREAD

**Issue by werthd** [walkor/Workerman#394]
Hey, first of all i wanted to mention that i have looked through all the Documentation and the issues but couldn't find anything that would help me.
Im trying to get a connection to my Websocket Server which seems to fail at the handshake. I'd be happy to get a hint or an example what i am supposed to do inside:
```php
$ws_worker->onConnect = function($connection){}
```
The terminal logs:
```
worker[none:86611] exit with status 11
```
and the Chrome console logs:
```
WebSocket connection to 'wss://localhost:2346/' failed: Connection closed before receiving a handshake response
```
after i tried to connect by:
```
ws = new WebSocket('wss://localhost:2346');
```
I'd like to mention that i'm not trying to get fully into the topic because it just a fun project.
Sorry for any misspelled words and thank you for your time.

**Comment by werthd** [comment]
This is my current php file:
```php
<?php
use Workerman\Worker;
require_once './Autoloader.php';

$context = array(
    'ssl' => array(
        'local_cert'  => './cert/server.crt',
        'local_pk'    => './cert/server.key',
        'verify_peer' => false,
    )
);

// Create A Worker and Listens 2346 port, use Websocket protocol
$ws_worker = new Worker("websocket://0.0.0.0:2346", $context);

// 4 processes
$ws_worker->count = 4;

$ws_worker->transport = 'ssl';

// Emitted when new connection come
$ws_worker->onConnect = function($connection) {

    echo("Trigger onConnect\n");

    // When websocket connection established  onWebSocketConnect callback will be called then you can get the http header of websocket handshake by $_SERVER in it.
    $connection->onWebSocketConnect = function($connection){

        echo("Trigger onWebSocketConnect\n");

    };
};
$ws_worker->onMessage = function($connection, $data)
{
    echo "Message: ".$data."\n";
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

// Run worker
Worker::runAll();
```

and this is what i do on my chrome console:

```javascript
ws = new WebSocket('wss://localhost:2346');
WebSocket {
    binaryType: "blob"
    bufferedAmount: 0
    extensions: ""
    onclose: null
    onerror: null
    onmessage: null
    onopen: null
    protocol: ""
    readyState: 3
    url: "wss://localhost:2346/"
}
```
```
VM66:1 WebSocket connection to 'wss://localhost:2346/' failed: Connection closed before receiving a handshake response
```
My terminal logs:
```
Trigger onConnect
worker[none:91025] exit with status 11
```

The `onWebSocketConnect` isn't triggered. I don't know where i am supposed to get the header from to continue.

**Comment by walkor** [comment]
Run command `php -v` and show the output.
Sorry for the delay.

**Comment by werthd** [comment]
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies

**Comment by werthd** [comment]
I did compile my own version of php to be able to use pcntl.

**Comment by walkor** [comment]
`status 11` means coredump for php. I think this is php 7.3.0's bug. 
Please use more stable version for php, for example php7.2.13 or greater, php7.1.25 or greater or php7.0.33.

**Comment by kelvindc** [comment]
I have the same problem too, 
used to work fine in 7.2
status 11 after upgrade to 7.3

**Comment by werthd** [comment]
Thanks a lot. I installed php 7.1 and it works 👍.
One last question is there already an implementation of a handshake somewhere that i could use ?
