### ISSUE TITLE
Cluster multiserver/multichannel separate start/stop with global shared $data between servers

### ISSUE THREAD

**Issue by x-jim** [walkor/Workerman#395]
Hello there,

I want to do a cluster server separate by services, like, users, admin, shop, and then i want to start/stop one by one if i want. But i want to see the unified stats like php mainServer status

is possible to mantain on server in one port for example: mainServer.php port:2000 with a unique channel
userServer.php port 2001 and then in userServer  (with their channel), I can use a $users variable from mainServer?

I tried to unify the servers and start mainServer, but then i cannot start/stop by service server, if i stop the mainServer all servers going offline.

I tried one alternative to, emit data in shopServer.php to mainServer.php to recover the $users but not worked.

thank you very much!

**Comment by walkor** [comment]
> I want to do a cluster server separate by services, like, users, admin, shop, and then i want to start/stop one by one if i want. But i want to see the unified stats like php mainServer status

What's stats do you want?

**Comment by x-jim** [comment]
I want to separate code from mainServer.php

main.php
`<?php
require_once '../vendor/autoload.php';
use Workerman\Worker;
use PHPSocketIO\SocketIO;
use PHPSocketIO\ChannelAdapter;

$server         = new stdClass();
$server->users  = array();

# Canal de Shop
$shop_channel    = new Channel\Server('127.0.0.1', 8989);
$main_channel    = new Channel\Server('127.0.0.1', 8990);

// Conectamos el cluster
$io                 = new SocketIO(2000);
$io->worker->name   = 'main';
$io->worker->count  = 1;
$io->on('workerStart', function() use($io) {


    // Seleccionamos el canal
	ChannelAdapter::$ip    = '127.0.0.1'; // Server A
	ChannelAdapter::$port  = 8989;
	$io->adapter('\PHPSocketIO\ChannelAdapter');

    echo "Worker ID: ". $io->worker->id. PHP_EOL;
});

$io->on('connection', function($socket) use($io) {
    global $server;

    $socket->join($io->worker->name);

    echo "Conntected to main" . PHP_EOL;

    $socket->on('tester', function($socket) use($io, $server) {
        echo "Server called" . PHP_EOL;
        return 'WOWOOOOOOOOOOOO';
    });

});

// Shop service, here it works.
require 'shop.php';

Worker::runAll();`


Shop.php
`require_once '../vendor/autoload.php';
use Workerman\Worker;
use PHPSocketIO\SocketIO;
use PHPSocketIO\ChannelAdapter;
use PHPSocketIO\Event\Emitter;
use Workerman\Connection\AsyncTcpConnection;

// Conectamos al cluster
$io = new SocketIO(2001);

//$global_worker = new GlobalData\Server('0.0.0.0', 2207);

$io->worker->count          = 1;
$io->worker->name           = 'shop';
$service                    = $io->worker->name;

$io->on('workerStart', function($worker) use($io) {

    ChannelAdapter::$ip    = '127.0.0.1'; // Server A
    ChannelAdapter::$port  = 8989;
    $io->adapter('\PHPSocketIO\ChannelAdapter');

    echo "__________" .PHP_EOL;
});
`
I want to start/stop service shop standalone from main.php, meanwhile main,php, but i want to acces to $server Object from main.php, because there are the users, maybe im in a wrong way but i need to separate services from one unique cluster.

And then when I write php main.php status i want to see the connected services with their status on the console, is it possible?

Thank you!

**Comment by walkor** [comment]
`$io = new SocketIO(2000);` and `$io = new SocketIO(2001);` means two different processes let's mark them A and B. IF A change the variable $server B can not see the change that means variables are separated between processes. But you can store the variables to mysql/redis etc and every process can get them from it any time.
If you want to start/stop standalone services the you must separate them to two start files (remove `require 'shop.php';` from main.php).  Then you can run command `php main.php start -d` and `php shop.php start -d` to start service standalone.And can stop any one by command `php startfile.php stop`. Workerman does not support stop one service when the all services start in one startfile. Workerman does not support see all service status form one command when services start in different startfiles.

**Comment by x-jim** [comment]
Thank you for your answer, finally I just did one file main.php with a globalDataServer ($server  = new \GlobalData\Server('127.0.0.1', 9118);)

and then in other service called shop.php but included in main.php just to start it with one command and im using: 

workerStart in shop.php
`$io->on('workerStart', function() use($io, $server) {

            // Seleccionamos el canal
        	ChannelAdapter::$ip    = '127.0.0.1'; // Server A
        	ChannelAdapter::$port  = 8989;
        	$io->adapter('\PHPSocketIO\ChannelAdapter');

            global $global;
            $global = new \GlobalData\Client('127.0.0.1:9118');
            $global->add('test', 1);
            $global->add('boot', 1);
        });`

And when user is logged I need to do something like this:

`$server->users[$msg['id_user']] = array(
                            'id_user'       => $msg['id_user'],
                            'id_company'    => $msg['id_company'],
                            'sockets'       => array($socket->id),
                            'token'         => $msg['token'],
                            'id_locale_app' => $msg['id_locale_app'],
                            'id_locale_attribute' => $msg['id_locale_attribute'],
                        );

                        # Seteamos globalmente los usuarios del servidor
                        $global->add('users', $server->users);

                        # Creamos una sala de usuario, donde todas las comunicaciones de dicho usuario pasarán por aqui
                        $socket->join($msg['id_user']);`

Because one user can be connected in multiple devices and different ip's, with this I save all users and the sockets per user (1-N) 1 User - N sockets.

By the way I have some questions:

1- Is there a way to load balance a service?
2- Why $io->to($socket->id)->emit('stat', 'hello'); doesn't work for me? maybe I should do $io->in($socket->id])->emit('stat', 'hello'); like a room?
3- Is there a way to use the same channel in 2 different services? ex: shop.php and main.php connect to same channel;
4- It is planned to do in a future, the features what I want? like multiple service global stats in one file? 

Sorry for all the questions!
PS: walkor, you had a amazing sockets library, congrats :)

Thank you in advance.

**Comment by walkor** [comment]
1- Yes, lvs dns nginx haproxy etc. You can find them in google.
2-`$socket->id` can not be shared between process. Just use `$io->emit();`
3-Yes, phpsocket.io support different services use the same channel server.
4- Sorry, there is no plan at present.
Most of questions are relate to project [phpsocket.io](https://github.com/walkor/phpsocket.io). If you has more question about [phpsocket.io](https://github.com/walkor/phpsocket.io)  welcome to post issues to [here](https://github.com/walkor/phpsocket.io/issues).
