### ISSUE TITLE
Change source code documentation to English?

### ISSUE THREAD

**Issue by devypt** [walkor/Workerman#40]
Hello great team,

Is there are any plan to change the source code comments and documentation to English as this will make life easier for all, I can help on this if needed.

**Comment by IngwiePhoenix** [comment]
I doubt so, since the developer is asian (Chinese I think it was?) and will likely prefer to document in his foreign language. Understandable, imho.

**Comment by walkor** [comment]
@devypt 
Yes, we need your help.
If you can help us we will be very grateful !
: )

**Comment by sixFingers** [comment]
@devypt I'm in, too
