### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by zuicis** [walkor/Workerman#401]
HI
At start reserved memory are fine for every worker  but a few days later, the reserved memory exceeds a few hundred megabytes, and on only after `kill pid` or worker restart memory is released .

How can I manually release memory without erasing pid / restarting worker?

Normal view picture:
![normal](https://user-images.githubusercontent.com/3358507/52198756-94d3d380-286c-11e9-9ae4-a97a62c287bd.png)

Pictures where you can see problem:
![memory](https://user-images.githubusercontent.com/3358507/52198762-9ac9b480-286c-11e9-90b7-49c2679a1a73.png)

![memory3](https://user-images.githubusercontent.com/3358507/52202054-0401f580-2876-11e9-8c21-acca726c0d26.png)

![memory4_tcp](https://user-images.githubusercontent.com/3358507/52203619-64933180-287a-11e9-89f9-f32e1d2b7ae0.png)

For testing:
	    $worker -> onWorkerStart = function($worker){
		    Timer::add(0.1, function() use($worker){
		        foreach($worker->connections as $connection) {
		         	$connection -> send('x');
		        }
	        });

**Comment by walkor** [comment]
I think there's some memory leak in your business codes.
The simplest way is add a timer to check the memory and restart the current process like this.
```php
$worker -> onWorkerStart = function($worker){
    Timer::add(10, function() use ($worker){
        if (memory_get_usage(true) > 128*1024*1024 && count($worker->connections) == 0) {
            // Restart current process.
            Worker::stopAll();
        }
    });
};
```
The best solution is to find the code that causes the memory leak and fix it.

**Comment by zuicis** [comment]
Hi, at this moment i already automaticly restarting proceses with timer:

```php
$maxMemory = ArrayHelper::getValue(Yii::$app -> params, 'workerman.maxMemory','128');
if ($upInsert -> memory >= $maxMemory || ($upInsert -> connections == 0 && $upInsert -> memory >= 20)){
	posix_kill($upInsert -> pid, SIGQUIT);
	if ($upInsert -> memory >= $maxMemory * 2){
		posix_kill($upInsert -> pid, SIGUSR1);
	}
}
```

About memory leak, i testet also without my code and got that leak. Mby php7.2 have same problems, because i didn't see it for an older versions. For testing i create empty script:

```php
private function Work(){
	$name = "TEST";
	$consoleDir = Yii::getAlias('@console');
	FileHelper::createDirectory($consoleDir . '/runtime/pids');
    Worker::$stdoutFile = $consoleDir . "/runtime/logs/{$name}_stdout.log";
    Worker::$logFile = $consoleDir . "/runtime/logs/{$name}_workerman.log";
    Worker::$pidFile = $consoleDir . "/runtime/pids/{$name}.pid";
	Worker::$eventLoopClass = '\Workerman\Events\Event';

	$context = ['ssl' => []];
	$worker = new Worker("websocket://0.0.0.0:8910", $context);
	$worker -> name = $name;
    $worker -> count = 4;
    $worker -> user = 'www-data';
    $worker -> group = 'www-data';
    $worker -> reloadable = true;

    $worker -> onWorkerStart = function($worker){
	    Timer::add(0.01, function() use($worker){
	    	if (!empty($worker -> connections)){
		        foreach($worker->connections as $connection) {
		        	$connection -> send('x');
		        }
	    	}
        });
    };

	$worker -> onMessage = function($connection,$data) use ($worker){
		//after some time this answer fills memory and after client reconect memory not
 		echo "WE GOT ANSER!!! \n";
	};

	Worker::runAll();		
}
```

**Comment by xpader** [comment]
I think we better not run Yii in Workerman, because Yii is not designed to run persistently in the process, that may make memory leak.

**Comment by zuicis** [comment]
Im runing workerman from yii2-console (CLI) with disabled debuger and logger :
```php
if (php_sapi_name() == "cli" || basename(dirname(getcwd())) == "api" ){
	defined('YII_DEBUG') or define('YII_DEBUG', false);
}
```
```php
Yii::$app -> log -> targets['file'] -> enabled = false;
```
if I'm not mistaken, the problem occurred after the php version upgrade to 7.2

**Comment by walkor** [comment]
I can‘t tell where your business codes have memory leak. May be the Tablets class, you must find it by yourself.

**Comment by WalentinG** [comment]
@walkor hi, which profiler or service you will recommend to use on production with workman to find memory leaks?
