### ISSUE TITLE
Websocket send from server

### ISSUE THREAD

**Issue by TechOverflow** [walkor/Workerman#402]
Is it possible for the server to send a message to a connected client individually? Not as a response, just as a message.
In this case, how can the client be identified? By connection number? Ie. `$ws_worker->send(123, 'Hello client')`

**Comment by walkor** [comment]
Each client has a corresponding TcpConnection instance `$connection`. You can call $connection->send('..') send message to the corresponding connected client.  All connections stored in the array `$worker->connections` and you can choose which one to send.
