### ISSUE TITLE
How to use try-catch in onMessage 

### ISSUE THREAD

**Issue by shturnev** [walkor/Workerman#405]
How to use (and is it possible) try-catch in onMessage method, like:

```php
$ws_worker = new Worker("websocket://0.0.0.0:2346");
$ws_worker->onMessage = function($connection, $data) {
  try{
    //do something
   if(something wrong){  throw new \Exception("error msg", 1); }
    
  }catch(Exception $e){
    $connection->send(json_encode(['error' => $e->getMessage()]));
 }
}
```

At the moment, catch does not work. How to do it right? Thnx

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/53551977-600a2200-3b75-11e9-8b8c-6f562f4835cd.png)
![image](https://user-images.githubusercontent.com/6073368/53552029-6f896b00-3b75-11e9-9277-6afe159eb329.png)
It's works fine for me.

**Comment by shturnev** [comment]
> ![image](https://user-images.githubusercontent.com/6073368/53551977-600a2200-3b75-11e9-8b8c-6f562f4835cd.png)
> ![image](https://user-images.githubusercontent.com/6073368/53552029-6f896b00-3b75-11e9-9277-6afe159eb329.png)
> It's works fine for me.

Yes you are right! Apparently I did not understand something ..
Sorry for interrupting

**Comment by walkor** [comment]
You are welcome
