### ISSUE TITLE
Can a startup file open multiple ports?

### ISSUE THREAD

**Issue by lynncho** [walkor/Workerman#408]
Hello there,

Dear Mr. Walkor, your workerman project is exciting, can php actually do these things? ! ! very impressive.

However, regarding the workman listening port, I have a suggestion:

1)  I developed a "memory MVC framework" based on workerman, which avoids the consumption of traditional php web service process destruction. https://github.com/lynncho/shy

2) The framework provides command modes, such as "php console list", which is the execution entry for all commands. The framework can start the workerman through "php console http start -d", but since the workerman can only open one port for a startup file, the console command mode of my framework cannot open multiple ports.

I hope that the framework can perform multiple socket services at the same time, so it is recommended that Mr. Walkor change the generation rules of the process id file and allow one startup file to open multiple services.

Written in Shanghai

Lynn, sincerely, salute

**Comment by walkor** [comment]
Thank you for your post and good work for project https://github.com/lynncho/shy .

Workerman can listening multi port  in one start file like this.
```
<?php
use Workerman\Worker;
$ws_worker = new Worker('websocket://0.0.0.0:1234');
$ws_worker->onMessage = function(){};
$http_worker = new Worker('http://0.0.0.0:5678');
$http_worker->onMessage = function(){};
// ...
Worker::runAll();
```
I hope this is what you want.

**Comment by lynncho** [comment]
Thanks for your reply, I want to open the port independently, independent socket service.

**Comment by walkor** [comment]
Worker::$pidFile marked which service to deal with.
You can change Worker::$pidFile by command $argv like this.
```php
<?php
use Workerman\Worker;
$module = $argv[3];
Worker::$pidFile = "/tmp/$module.pid";
call_user_func($module);
function chat() {
    $worker = new Worker('websocket://0.0.0.0:1234');
    $worker->onMessage = function(){};
}
function api() {
    $worker = new Worker('http://0.0.0.0:5678');
    $worker->onMessage = function(){};
}
Worker::runAll();
```
Then start with command like ```php start.php start -d chat``` ```php start.php start -d api```.
Stop with command ```php start.php stop -d chat```  ```php start.php stop -d api```.

**Comment by walkor** [comment]
I believe this has been answered, so I'm closing this for now.
