### ISSUE TITLE
date_default_timezone_set('Asia/Shanghai');

### ISSUE THREAD

**Issue by morozovsk** [walkor/Workerman#411]
Remove it please.
By default PHP uses timezone of server.
All my php scripts use right timezone exept workerman.
If you use 'Asia/Shanghai' as timezone on your server then your php uses 'Asia/Shanghai'.
If you use 'UTC' as timezone on your server but you want to use in php 'Asia/Shanghai' then you need change timezone in your php.ini or in your php script but you don't need to change it for all users of your library.
I don't need setup every settings twice (per system and per php).

I couldn't change every php.ini files on on every server so now I have to use:
```php
if (!ini_get('date.timezone')) {
    ini_set('date.timezone', exec('date +"%Z"'));
}
```

But it's stupid.

**Comment by walkor** [comment]
You are right. 
The codes removed.
Thank you for your posts. 👍
