### ISSUE TITLE
http protocol header How do I set json header?怎么设置Json头

### ISSUE THREAD

**Issue by leihenshang** [walkor/Workerman#412]
http protocol header How do I set json header?怎么设置Json头

**Comment by walkor** [comment]
$worker = new Worker('http://0.0.0.0:1234');
$worker->onMessage = function($con, $data){
    \Workerman\Protocols\Http::header('Content-Type:application/json; charset=utf-8'); 
    $con->send('something');
};

**Comment by leihenshang** [comment]
thank you very much!我成功了，不过官网的文档不详细啊，建议出一个类似于项目实例的东西。

At 2019-04-15 17:44:56, "walkor" <notifications@github.com> wrote:


$worker = new Worker('http://0.0.0.0:1234');
$worker->onMessage = function($con, $data){
\Workerman\Protocols\Http::header('Content-Type:application/json; charset=utf-8');
$con->send('something');
};
