### ISSUE TITLE
Question about websocket server and async Redis

### ISSUE THREAD

**Issue by makbeth** [walkor/Workerman#413]
Hello! I've just started using websockets and asynс possibilities provided by Workerman. Can anybody tell me how to implemetn this case:
1. I start a websocket server and a Redis client
2. I create a subscription to a channel, e.g. User channel
3. User connects to the websocket server
4. On connection event I write some data to Redis (e.g. that this user is online) and call Redis publish method (pubsub) - here is the question: 
Will publish method be called automatically or I must call this method manually each time I add data to Redis?
5. On publish event I send all users connected to the websocket server the data I store in Redis. 
I think it will work for realtime notifications of online users on the website. 
Can anybody tell me is this approach correct? Can I use it in a case like private chat between two users? 
It will be great if anybody can show me an example how I can do my case in Workerman style. Like best practice for this case. Thank you! I really appreciate your help!

**Comment by wonderful60** [comment]
You can refer to the author's [Channel](https://github.com/walkor/Channel) implementation, which is similar to your requirements.Sorry, there are only Chinese instructions now.
