### ISSUE TITLE
DDOS protection dissconnect client

### ISSUE THREAD

**Issue by Xhonor** [walkor/Workerman#415]
Hello. Established not long ago, protection against DDOS attacks. But there was a problem with the worker.
The connection began to stupidly close after 5 minutes of inactivity. Are there any methods to fix this? JS keep alive timeout - did not help for some reason.

**Comment by walkor** [comment]
Try to  send  "heartbeat" message to workerman every specified time interval for example every 50 seconds.
If the connection still closed unexpected try to shorten the time interval by 25 seconds.

**Comment by Xhonor** [comment]
Hello. I tried this option:
```
$worker->onWorkerStart = function($worker)
{
    $time_interval = 10;
    $timer_id = Timer::add($time_interval,
        function() use ($worker)
        {
            foreach($worker->connections as $connection) {
                $connection->send(pack('H*', '890400000000'), true);
                //echo "Heartbeat...";
            }
        }
    );
```

All the same, websockets are closed.
Tried through js, works ... But periodically also closes the connection.
Why is that?

**Comment by walkor** [comment]
Try to connect workerman directly. Do not use DDOS protection.
