### ISSUE TITLE
processes count

### ISSUE THREAD

**Issue by rottenberry** [walkor/Workerman#417]
```php
// 4 processes
$ws_worker->count = 4;
```
What happens to my websocket server if I set the count to 1? And when should I use more than one process? Is there any rule for that?

**Comment by wonderful60** [comment]
It's mentioned here
https://github.com/walkor/workerman-manual/blob/master/english/src/worker-development/count.md

**Comment by rottenberry** [comment]
> It's mentioned here
> https://github.com/walkor/workerman-manual/blob/master/english/src/worker-development/count.md

Thanks, but unfortunately, it's still not completely clear for me: the manual only says that the code sets the amount of worker intances, but no information about when to use it and how many instances you should create depending on your goal. Would be glad to get further explanations.

**Comment by wonderful60** [comment]
http://doc.workerman.net/faq/processes-count.html sorry,only chinese information.

**Comment by rottenberry** [comment]
Thank you very much!
