### ISSUE TITLE
class \Protocols\Wss not exist in C:\OSPanel\domains\Traderman\vendor\workerman\workerman\Connection\AsyncTcpConnection.php:150

### ISSUE THREAD

**Issue by shmuel-livshits** [walkor/Workerman#419]
Hi. I am trying to get data true wss from wss://api.bitfinex.com/ws
By I'am getting error
0 C:\OSPanel\domains\Traderman\app\Console\Commands\bitfinexSocketRecord.php(48): Workerman\Connection\AsyncTcpConnection->__construct('wss://api.bitfi...')
#1 [internal function]: App\Console\Commands\bitfinexSocketRecord->App\Console\Commands\{closure}(Object(Workerman\Worker))
#2 C:\OSPanel\domains\Traderman\vendor\workerman\workerman\Worker.php(2342): call_user_func(Object(Closure), Object(Workerman\Worker))
#3 C:\OSPanel\domains\Traderman\vendor\workerman\workerman\Worker.php(1351): Workerman\Worker->run()
#4 C:\OSPanel\domains\Traderman\vendor\workerman\workerman\Worker.php(1294): Workerman\Worker::forkWorkersForWindows()
#5 C:\OSPanel\domains\Traderman\vendor\workerman\workerman\Worker.php(509): Workerman\Worker::forkWorkers()
#6 C:\OSPanel\domains\Traderman\app\Console\Commands\bitfinexSocketRecord.php(70): Workerman\Worker::runAll()

**Comment by walkor** [comment]
Try codes.
```
$con = new AsyncTcpConnection('ws://api.bitfinex.com/ws');
$con->transport = 'ssl';
```
