### ISSUE TITLE
problems with websocket

### ISSUE THREAD

**Issue by DJServer** [walkor/Workerman#421]
I followed a standard example of the code for realization of websocket. php and js. after start in the script PHP console. I try to be connected on the client. But I see an error of WebSocket connection to 'wss://127.0.0.1:8000/chat /' failed: Error in connection establishment: net:: ERR_CONNECTION_REFUSED.
How to solve this problem? With SSL everything is all right. I checked also without https. Same mistake.
Scanned external ports whether they have to be visible as php a script opened after start?

**Comment by walkor** [comment]
Did you start workerman?
Show the output for starting workerman.

**Comment by DJServer** [comment]
yes workerman start. [https://prnt.sc/npoomo](url)
in console i test ab -n1 -c1 -k http://127.0.0.1:8000/ and all work fine.
when i try connect from web page in js i get error failed: Error in connection establishment: net:: ERR_CONNECTION_REFUSED

**Comment by walkor** [comment]
If you want to connect it from web page you should use real domain or real ip but not `127.0.0.1` .
Change `wss://127.0.0.1:8000/chat` to `ws://real_ip_or_domain:8000/chat`.

If you want to use` wss` not `ws` there are some configs required for example.
```php
$context = array(
    // More see http://php.net/manual/zh/context.ssl.php
    'ssl' => array(
        'local_cert'                 => '/path/of/server.pem', 
        'local_pk'                   => '/path/of/server.key',
        'verify_peer'                => false,
        // 'allow_self_signed' => true, 
    )
);
$worker = new Worker('websocket://0.0.0.0:8000', $context);
// websocket+ssl means wss
$worker->transport = 'ssl';
$worker->onMessage = function($con, $msg) {
    $con->send('ok');
};
Worker::runAll();
```
Remember, if you want to use `wss`, you need to use domain instead of IP to connect server or you will get a failure. And the domain name must be the domain name held by the certificate file (local_cert , local_pk).

**Comment by DJServer** [comment]
Ok, when i use domain name (not 127.0.0.1) i had new error. net::ERR_CONNECTION_TIMED_OUT.
I correctly registered ssl path and use your code. and still get error connection timed out.
i use nginx as web server. whether it can as that to influence work of sockets?

**Comment by walkor** [comment]
Can you show the full error message?

**Comment by DJServer** [comment]
WebSocket connection to 'wss://mysite.com:8000/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT. this error i get in browser.
for check of sockets, I install node js and started client-server application. and there the same problem, is not connected. so a problem most likely in a web the server. as far as I understand

**Comment by DJServer** [comment]
Yes I found in what the reason. It is necessary to add settings to nginx which allow to replace the protocol
proxy_pass http://127.0.0.1:8000;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;

thanks for the help.
