### ISSUE TITLE
Workerman losing messages under load

### ISSUE THREAD

**Issue by VladimirMerk** [walkor/Workerman#422]
If the server has a low load average, then everything is fine, but on a highly loaded server (with an load average above 3 for example), the workerman starts to behave unstably.
Random messages sent by the client do not reach the server and vice versa, some messages sent by the server never reach the client, although the connection is preserved.

Is it possible to deliver messages guaranteed, or check whether it is received?

**Comment by walkor** [comment]
No program can guarantee fast and stable runs on high-load servers.

If you want to check whether message is received there are some works required.
For server side every message send to clients should be stored in DB and has a mark field which marked whether the message is received by client. When client received a message it should send an ack message to server to mark the message has received. So when you want to check if some message not received by client just check DB.

**Comment by VladimirMerk** [comment]
Understood thanks!
Is it possible that the work that takes place inside Workerman\Lib\Timer blocks the receipt of new messages by the server before it is completed?

**Comment by walkor** [comment]
Sorry, I don't understand what you mean.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this
