### ISSUE TITLE
How two receive whole message in onMessage function

### ISSUE THREAD

**Issue by andriimelnyk1** [walkor/Workerman#423]
I use library WorkerMan for sending data to clients via websockets. I have a code, which sends data to Worker via tcp protocol:

```
$instance = stream_socket_client('tcp://mysitedomain.com:5000');
$message_text = json_encode($message);
fwrite($instance,  $message_text. "\n");
```

My receiver code is:

```
$receiver_worker= new \Workerman\Worker('tcp://mysitedomain.com:5000');
$receiver_worker->transport = 'ssl';
$receiver_worker->onMessage = function($connection, $data) {

Worker::log($data);
$data_json = json_decode($data, TRUE);

//here I process the $data

}
```

My problem is when $message_text is too big, then I receive not one message, but two or more. The cause is described in fwrite function documentation:

> Writing to a network stream may end before the whole string is written. Return value of fwrite() may be checked:

And suggetion is:

```
function fwrite_stream($fp, $string) {
    for ($written = 0; $written < strlen($string); $written += $fwrite) {
        $fwrite = fwrite($fp, substr($string, $written));
        if ($fwrite === false) {
            return $written;
        }
    }
    return $written;
}
```

But I do not know, how it can help me. I can process received json only atomically and should be shure that whole json is received, but not some parts.

**Comment by walkor** [comment]
A communication protocol is needed to transfer data between client and server.
The communication protocol is used to tell the server how big the data packet is.
The server buffers the data according to the communication protocol until it receives the complete data packet and then starts processing.

Workerman supports this mechanism, and you can define your own communication protocol in workerman. You can also use communication protocols prepared by workerman, such as text protocol。

You can try these codes.
Server side.
```php
// use text protocol
$receiver_worker= new \Workerman\Worker('text://mysitedomain.com:5000');
``` 
Client side.
```php
function fwrite_stream($fp, $string) {
    // text protocol need char "\n" to mark an complete package.
    $string .= "\n";
    for ($written = 0; $written < strlen($string); $written += $fwrite) {
        $fwrite = fwrite($fp, substr($string, $written));
        if ($fwrite === false) {
            return $written;
        }
    }
    return $written;
}
```

The text protocol is defined here https://github.com/walkor/Workerman/blob/master/Protocols/Text.php.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this
