### ISSUE TITLE
workerman 进程存在,但是status失败，是什么情况？

### ISSUE THREAD

**Issue by joostshao** [walkor/Workerman#43]
1:
php /data/program/Crontab/workerman/start.php status
Workerman[/data/program/Crontab/workerman/start.php] not run
用户定义信号 2

2:
ps -aux | grep WorkerMan
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.7/FAQ
appweb   23675  0.0  0.0 193940  2184 ?        S    Sep21   0:00 WorkerMan: master process  start_file=/data/program/Crontab/workerman/start.php
appweb   23676  0.0  0.0 193940  1760 ?        S    Sep21   0:00 WorkerMan: worker process  crontab none               
appweb   23696  0.0  0.0  61192   776 pts/2    S+   09:58   0:00 grep WorkerMan

这个是不是有问题？　　进程存在，但status有问题。

**Comment by walkor** [comment]
应该是pid文件被删除了，导致找不到主进程，无法发送status信号，所以status看不到。
可以参考手册
http://doc3.workerman.net/worker-development/pid_file.html
把pid文件放到安全的地方

**Comment by joostshao** [comment]
多谢，我已经修改到当前目录下了，　tmp　目录下放着有时候不是很安全。
