### ISSUE TITLE
Server start normally but write in log pid:1538 Exception: Address already in use in /var/www/html/ws/Worker.php:2216 every second

### ISSUE THREAD

**Issue by FrozenCoyote** [walkor/Workerman#430]
Hello, 

after server start with php -q /var/www/html/ws/server.php start -d records below fall in log. How can fix this problem? Thanks!

2019-07-03 12:47:42 pid:1538 Exception: Address already in use in /var/www/html/ws/Worker.php:2216
Stack trace:
#0 /var/www/html/ws/server.php(40): Workerman\Worker->listen()
#1 [internal function]: {closure}(Object(Workerman\Worker))
#2 /var/www/html/ws/Worker.php(2342): call_user_func(Object(Closure), Object(Workerman\Worker))
#3 /var/www/html/ws/Worker.php(1488): Workerman\Worker->run()
#4 /var/www/html/ws/Worker.php(1318): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#5 /var/www/html/ws/Worker.php(1292): Workerman\Worker::forkWorkersForLinux()
#6 /var/www/html/ws/Worker.php(1622): Workerman\Worker::forkWorkers()
#7 /var/www/html/ws/Worker.php(1571): Workerman\Worker::monitorWorkersForLinux()
#8 /var/www/html/ws/Worker.php(511): Workerman\Worker::monitorWorkers()
#9 /var/www/html/ws/server.php(59): Workerman\Worker::runAll()
#10 {main}

**Comment by walkor** [comment]
Can you show your codes?

**Comment by FrozenCoyote** [comment]
What file? server.php?

**Comment by walkor** [comment]
yes

**Comment by FrozenCoyote** [comment]
<?php
require_once __DIR__ . '/Autoloader.php';
use Workerman\Worker;
use Workerman\Connection\TcpConnection;

$ws_worker = new Worker("websocket://0.0.0.0:9696"); //, $context
$ws_worker->count = 16;
$ws_worker->users = array();

    $ws_worker->onWorkerStart = function() use (&$users)
    {
        $inner_tcp_worker = new Worker("tcp://127.0.0.1:1234");
        $inner_tcp_worker->onMessage = function($connection, $data) use (&$users) 
        {
            $data = json_decode($data);
            $incoming_users = json_decode($data->user, true); 
        // Всем онлайн-пользователям           
            if(in_array("all", $incoming_users) == true)
            {
                foreach($users as $key => $user) 
                {
                    $webconnection = $users[$key];
                    $webconnection->send($data->message);
                }              
            }
        // Выборочным онлайн-пользователям           
            else
            {
                foreach($users as $key => $user) 
                {
                    if(in_array($key, $incoming_users) == true) 
                    {
                        $webconnection = $users[$key];
                        $webconnection->send($data->message);
                    }
                }  
            }
        };

        $inner_tcp_worker->listen();
    };

    $ws_worker->onConnect = function($connection) use (&$users)
    {
        
        $connection->onWebSocketConnect = function($connection) use (&$users)
        {
            $users[$_GET['user']] = $connection;
        };
    };

    $ws_worker->onClose = function($connection) use(&$users)
    {
        $user = array_search($connection, $users);
        unset($users[$user]);
    };

// Run worker
Worker::runAll();

**Comment by FrozenCoyote** [comment]
`<?php
require_once __DIR__ . '/Autoloader.php';
use Workerman\Worker;
use Workerman\Connection\TcpConnection;

$ws_worker = new Worker("websocket://0.0.0.0:9696"); //, $context
$ws_worker->count = 16;
$ws_worker->users = array();

    $ws_worker->onWorkerStart = function() use (&$users)
    {
        $inner_tcp_worker = new Worker("tcp://127.0.0.1:1234");
        $inner_tcp_worker->onMessage = function($connection, $data) use (&$users) 
        {
            $data = json_decode($data);
            $incoming_users = json_decode($data->user, true); 
        // Всем онлайн-пользователям           
            if(in_array("all", $incoming_users) == true)
            {
                foreach($users as $key => $user) 
                {
                    $webconnection = $users[$key];
                    $webconnection->send($data->message);
                }              
            }
        // Выборочным онлайн-пользователям           
            else
            {
                foreach($users as $key => $user) 
                {
                    if(in_array($key, $incoming_users) == true) 
                    {
                        $webconnection = $users[$key];
                        $webconnection->send($data->message);
                    }
                }  
            }
        };

        $inner_tcp_worker->listen();
    };

    $ws_worker->onConnect = function($connection) use (&$users)
    {
        
        $connection->onWebSocketConnect = function($connection) use (&$users)
        {
            $users[$_GET['user']] = $connection;
        };
    };

    $ws_worker->onClose = function($connection) use(&$users)
    {
        $user = array_search($connection, $users);
        unset($users[$user]);
    };

// Run worker
Worker::runAll();

`

**Comment by walkor** [comment]
```php
$ws_worker->count = 16;
```
change to 
```php
$ws_worker->count = 1;
```

**Comment by FrozenCoyote** [comment]
Thank you very much! what it means?

**Comment by walkor** [comment]
Number of processes.
