### ISSUE TITLE
Broke connection with err: recv data before handshake

### ISSUE THREAD

**Issue by avenger33** [walkor/Workerman#432]
Hi. Have the problem with PHP 7.2.16 and Workerman 3.5 on Windows 10.
Test it on 2 PC - both has Windows 10x64 + PHP 7.2 + Workerman 3.5.
First PC work well with websockets, but second broke connection with error 'recv data before handshake'.
Websocket server code is code from Basic usage example from Workerman git page.
When i try custom server code (not Workerman) - it's work.
On both PC install Apache web server.
I am tried to update php to 7.3.7 but it's does't help.
How can i fix that?

**Comment by walkor** [comment]
```php
$worker = new Worker('ws://0.0.0.0:xx');
```
This is the wrong way to start a websocket service, you will get an error `recv data before handshake`.

This is the right way .
```php
$worker = new Worker('websocket://0.0.0.0:xx');
```

Please check that.

**Comment by avenger33** [comment]
Thanks. it's work
