### ISSUE TITLE
error on posix_getpid()

### ISSUE THREAD

**Issue by moscorp** [walkor/Workerman#433]
Hi, please help to solve this error !

PHP Fatal error:  Uncaught Error: Call to undefined function Workerman\posix_get                                                      pid() in /vendor/workerman/workerman/Worker.php:2081

**Comment by walkor** [comment]
Please install posix extension for php.

**Comment by moscorp** [comment]
Thanks for reply, I can found posix were installed

php -m | grep posix
posix

my machine is synology linux based os, it there any conflict with this ?

**Comment by moscorp** [comment]
okay, it works now... then, please guide me to save the received data to mysql, thanks !
