### ISSUE TITLE
How can I scale "workerman" across multiple servers?

### ISSUE THREAD

**Issue by voodooism** [walkor/Workerman#436]
Friendly speaking, I haven’t used WebSockets before, but now I really need it. One big question that bothers me: _how can I scale "workerman" across multiple servers?_

The problem is my application has a distributed structure and each user request comes to one of four backend servers. How can I achieve regardless of the server to which the request came, the answer was sent to all  WebSocket clients

I will be grateful for any information will help me solve my problem.
**Thanks for attention!**

**Comment by walkor** [comment]
You  can try `workerman/channel`.

`workerman/channel` is a proxy, it can distribute message to all channel clients which subscribe some subject.

Install `workerman/channel`.

`composer require workerman/channel`

channel_server.php.  Run one server let's say the ip is $channel_server_ip.
```php
<?php
use Workerman\Worker;
require_once __DIR__ . '/vendor/autoload.php';

$channel_server = new Channel\Server('0.0.0.0', 2206);
Worker::runAll();
```

ws_server.php. You can run it multiple servers.
```php
<?php
use Workerman\Worker;
require_once __DIR__ . '/vendor/autoload.php';

$worker = new Worker('websocket://0.0.0.0:4236');
$worker->count=8;
$worker->name = 'pusher';
$worker->onWorkerStart = function($worker)
{
    // connect to channel_server
    $channel_server_ip = '192.168.x.x';
    Channel\Client::connect($channel_server_ip, 2206);

    $event_name = 'send_to_all';
    Channel\Client::on($event_name, function($event_data)use($worker){
        $message = $event_data['content'];
        foreach($worker->connections as $connection)
        {
            $connection->send($message);
        }
    });
};

Worker::runAll();
```

api_server.php. You can run it multiple servers.
```php
<?php
use Workerman\Worker;
require_once __DIR__ . '/vendor/autoload.php';

$http_worker = new Worker('http://0.0.0.0:4237');
$http_worker->name = 'publisher';
$http_worker->onWorkerStart = function()
{
    // connect to channel_server
    $channel_server_ip = '192.168.x.x';
    Channel\Client::connect($channel_server_ip, 2206);
};

$http_worker->onMessage = function($connection, $data)
{
    $connection->send('ok');
    if(empty($_GET['content'])) return;
    $event_name = 'send_to_all';
    $content = $_GET['content'];
    Channel\Client::publish($event_name, array(
       'content'  => $content
    ));
};

Worker::runAll();
```

Curl the address `http://api_server_ip:4237?content=blabla....` then all the websocket clients which connect to `ws_server_ip:4236` will get the data `blabla....`.

**Comment by walkor** [comment]
I believe this has been answered, so I'm closing this for now. 
Please come back with more details if this problem persists and we can reopen this

**Comment by voodooism** [comment]
**First of all, thank you for your answer!**

Perhaps I didn't understand what did you mean, but  I think it won't solve my problem.

As I can see from your answer you suggest running just only one main server (named channel_server) that will be route all requests to all other connections. Please,  correct me if I understand it wrong.

But In my case, I should provide horizontally scaling and fault tolerance. The main purpose is: if one of the backend servers will die this situation shouldn't be a problem. 
And as I can imagine, on each physical server, something like a "channel" should be running.

I attach a picture below which shows servers-structure scheme to make it easier to understand what I mean.

![scheme-server](https://user-images.githubusercontent.com/31572316/62408097-0d291080-b5d4-11e9-9b7a-46f1dacabfc9.jpg)

So, I want to establish a connection from front-end of my application by WebSocket to NGINX server's IP. And then I think NGINX will decide to what kind of server request will send. 
As a result, I would like to open a connection using only one IP address, and inside this should be distributed to different servers. In this case, if one of the servers will crash, it won't affect the performance of the application.

I hope I managed to explain what I mean :)

Is it possible to achieve this using your extension? 
I will be very pleased for any information that will help me solve my problem.

**Thanks for attention!**

**Comment by char101** [comment]
You already described the solution yourself, just use nginx to load balance the websocket requests [1].

[1] https://www.nginx.com/blog/websocket-nginx/
