### ISSUE TITLE
Am I a worker, or master?

### ISSUE THREAD

**Issue by IngwiePhoenix** [walkor/Workerman#44]
Currently, I have been using Workerman by checking the `$argv` array for the scenario of starting, or not.

Like here: https://github.com/DragonsInn/BIRD3/blob/master/app.php#L92-L101

But is there actually a better way to know this?

What I want to do is only launch the class on the master process, and not on the workers.

**Comment by walkor** [comment]
I think your approach is good enough.
I think for some time and no better way to come up with.
