### ISSUE TITLE
Nodejs

### ISSUE THREAD

**Issue by ronlinet** [walkor/Workerman#441]
I see that the https://github.com/walkor/Workerman#a-webserver is running on port 80 ( apache ? ). Does that means that we can run the Websocket service on an apache installation  without installing any NodeJS Socket.IO server ?

**Comment by walkor** [comment]
More precisely, we can run Websocket service on a `php cli` installation without installing any NodeJS Socket.IO server or apache/nginx?

**Comment by ronlinet** [comment]
Hi Walkor, 
Thank you for your quick feedback. 
What I am trying to ask if $web = new WebServer("http://0.0.0.0:80"); will not interfere with apache which will run at the same port. 
To put you more in the context I would like to hook the Workerman into an existing LAMP installation where the port 80 is already taken by the apache WEB server.

**Comment by walkor** [comment]
You can not use port 80 in workerman if the port 80 is already taken by apache. Just use another port which not in using.
