### ISSUE TITLE
Question about scalability 

### ISSUE THREAD

**Issue by lpadillae** [walkor/Workerman#444]
Can anyone help me with ideas what's the best approach to use workerman but making scalable? Something like a farm server. Not sure if this posible but let's read the following example:

Server 1 the main server
Server 2 secondary server 
Server 3 secondary server

Server 1 can handle db interactions and send message from server 2 to server 3 and the otherwise way around. 

Not sure if you understand my point but any idea about this topic is welcome. Thanks in advance.

**Comment by taozywu** [comment]
@lpadillae 
I think this link is useful for you http://doc.workerman.net/components/channel.html or https://github.com/walkor/channel
And you can follow rpc https://github.com/walkor/workerman-jsonrpc

Good luck!
