### ISSUE TITLE
How many processes are optimal and how does it work?

### ISSUE THREAD

**Issue by voodooism** [walkor/Workerman#445]
In all your examples, you specify the number of worker processes equal to four.

Could you explain what it affects and how it works? What is the optimal number of processes and what does it depend on?

I read the closed issues, but still not understand clearly how it works. Could you give some examples?

**Thanks for attention!**

**Comment by taozywu** [comment]
@voodooism 
I think you can read this link http://doc.workerman.net/faq/processes-count.html.
Good luck!

**Comment by voodooism** [comment]
I tried to read that, but Chinese is a big problem for me even with google translate. Can you be so kind to write some examples in English, please?

**Comment by taozywu** [comment]
@voodooism 
No, not unless I have that time.

**Comment by walkor** [comment]
The recommended number of processes is 1-3 times the number of CPUs.

My home language is not English so I can't describe how it works in English.
But you can refer to some articles on the principle of nginx. The principle of workerman is the same as that of nginx.

**Comment by char101** [comment]
The workers process requests serially so if your code idles a lot (e.g. accessing a relational database or making a remote web service call) you'll need to increase the number of workers (probably up to 4 * the number of cores) to fully utilize the CPU usage.

In node for example there is the event queue that will make the CPU busy, in workerman case it is the OS scheduler that is making the CPU busy thus more processes should be better unless the code itself is CPU intensive.
