### ISSUE TITLE
Write to log file while running daemon

### ISSUE THREAD

**Issue by vffkiva** [walkor/Workerman#446]
Hello Team,
First of all let me thank you for your product. Looks nice so far. 
However, let me ask you a question. No really an issue, but maybe luck of knowledge.

I have wrapped Workerman into Yii2 framework and I have enabled loging, so to write configured  Yii2 framework logs. Those log files are updated only when I'm stopping worker daemon. 

Question - is it possible to write into the log files (no necessarily Yii2 logs) data, when the worker daemon is running, so not having those files updated at worker daemon stop?

Thank you in advance,
Vladimir

**Comment by walkor** [comment]
> Question - is it possible to write into the log files (no necessarily Yii2 logs) data, when the worker daemon is running, so not having those files updated at worker daemon stop?

Yes.

> Those log files are updated only when I'm stopping worker daemon.

I'm not familiar with the Yii framework. I guess your yii program did not enter the codes for logging before workerman stops.

**Comment by vffkiva** [comment]
Thanx for the update. Just tried myself, simple writting through fwrite on event "onmessage". Yes, it is working. So it looks like I need to dig into my framework documentation.
