### ISSUE TITLE
Protect WSS and my Worker

### ISSUE THREAD

**Issue by Xhonor** [walkor/Workerman#450]
Hello. There was such a thought.
I have a worker, it works under the wss protocol.
In fact, anyone can connect to my web socket server and send data packets. (for example, here https://www.websocket.org/echo.html)
How to protect a worker from this? How to prohibit reception of worker packages from other sites?
Is it possible to track $ _SERVER REFERER?

**Comment by Xhonor** [comment]
Or am I wrong and no one can do this?

**Comment by ishland** [comment]
You can tunnel it through the webserver like Apache2 or Nginx.

**Comment by Xhonor** [comment]
> You can tunnel it through the webserver like Apache2 or Nginx.

How can i do that? :)
Can you give an example?)

**Comment by xpader** [comment]
Add a property to connection like `authorized`, default value is `false`.
When every connection was connected, they need send a command like 'login PASS_WORD', then verify it,  and marked `authorized` to `true`.
When every connection was connected, add a timer to set a login timeout, like when you connected, you must login in 5 seconds, else connection will be closed.
Every operation need verify `authorized` is true, if its not, close connection.

**Comment by walkor** [comment]
Thanks @xpader . 
Another way to protect your worker connect from other sites.
```
$worker->onWebSocketConnect = function($connection) {
    $from_site = $_SERVER['HTTP_ORIGIN'];
    echo "Connection from site $from_site\n";
     if ($from_site != 'http://example.com') {
         $connection->close();
     }
};
```

**Comment by raghuveer** [comment]
even though I am trying to use workerman now, I had implemented signature concept on user level based on shared secret, a HMAC integrity check.

**Comment by techno-express** [comment]
I think you should request this **framework** author to add some CI tests. Is anything working/passing as implemented?

**Comment by raghuveer** [comment]
I tried running basic examples and it worked, you are right, having CI tests will be more easier
