### ISSUE TITLE
Supervisord with Workerman

### ISSUE THREAD

**Issue by lpadillae** [walkor/Workerman#451]
I am able to run workerman using supervisord with the following configuration:
[program:name]
command=php -q /path/to/workerman start
user=developer
autostart=true
autorestart=true
stderr_logfile=/path/to/log
stdout_logfile=/path/to/log

But if i add "-d" to the command supervisor can not execute it and it is not displayed, but if i check the command line is running, also it says in the workerman log file that is already running.

Any idea how to fix this?

**Comment by taozywu** [comment]
@lpadillae 

https://wenda.workerman.net/question/2671

This link may can help you !

**Comment by xpader** [comment]
Why need supervisord for workerman??
Workerman has a main process to hold all the subprocess running.
The only reason for this is you need start workerman on machine bootup??
