### ISSUE TITLE
PHP 7 - Base.php not compatible with react LoopInterface

### ISSUE THREAD

**Issue by florianwagner81** [walkor/Workerman#453]
PHP 7 fails with Base.php not being compatible with React\EventLoop\LoopInterface. In many declarations the word "**_callable_**" is needed before the parameter.
Furthermore the following functions are missing:

1. public function removeStream($stream)
2. public function isTimerActive(TimerInterface $timer)
3. public function nextTick(callable $listener)
4. public function tick()

Additionally it is calling functions in the React StreamSelectLoop that are not present: 
return $this->_eventLoop->addSignal($signal, $listener);     (Line 235)
return $this->_eventLoop->removeSignal($signal, $listener);    (Line 244)

Finally the TimerInterface now lies in the namespace "React\EventLoop\Timer\TimerInterface" in the same file

**Comment by walkor** [comment]
Thank you for your post.
react/event-loop released new version which changed something.

Please try the version 0.5.3 for react/event-loop.
