### ISSUE TITLE
The following error occurred when the client connected

### ISSUE THREAD

**Issue by BecksWang** [walkor/Workerman#456]
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
 
How should I set up the server?

**Comment by walkor** [comment]
Show your client side codes please.

**Comment by cpgb85** [comment]
My client side is literally just this:

`var socket = new WebSocket('ws://localhost:2346');`

and it breaks the php library.

**Comment by walkor** [comment]
`var socket = new WebSocket('ws://localhost:2346', protocols);`.
Workerman not support the  second parameter `protocols`. Please check.

**Comment by BecksWang** [comment]
Thank you for your reply. I've settled it.
