### ISSUE TITLE
invliad _statisticsFile path

### ISSUE THREAD

**Issue by vb2005xu** [walkor/Workerman#46]
PHP Warning:  readfile(/var/folders/gp/gfm74_6x0pn2lc0xm6xzsj140000gn/T/workerman.status): failed to ope
n stream: No such file or directory in /Users/vb2005xu/workspace/workman-console/vendor/workerman/workerrman/Worker.php on line 563 

```
case 'status':
                // 尝试删除统计文件，避免脏数据
                if(is_file(self::$_statisticsFile))
                {
                    @unlink(self::$_statisticsFile);
                }
                // 向主进程发送 SIGUSR2 信号 ，然后主进程会向所有子进程发送 SIGUSR2 信号
                // 所有进程收到 SIGUSR2 信号后会向 $_statisticsFile 写入自己的状态
                posix_kill($master_pid, SIGUSR2);
                // 睡眠100毫秒，等待子进程将自己的状态写入$_statisticsFile指定的文件
                usleep(100000);
                // 展示状态
                readfile(self::$_statisticsFile);
                exit(0);
```

文件都不存在,直接读取合适吗?

**Comment by vb2005xu** [comment]
这个东西你们真的测试过吗?

**Comment by sukui** [comment]
posix_kill($master_pid, SIGUSR2);

**Comment by walkor** [comment]
这个文件是运行status命令后动态生成的。没生成的原因一般是debug模式运行时按了ctrl z强制挂起了主进程，导致主进程不响应任何命令。请不要挂起主进程

**Comment by vb2005xu** [comment]
mac 上始终报错,linux上没事

**Comment by walkor** [comment]
brew 安装的PHP5.30？mac 的这个版本信号控制函数有bug，不要用这个版本。换个版本就好了

**Comment by vb2005xu** [comment]
PHP 5.5.23 (cli) (built: Mar 23 2015 01:47:37)                                                          │---
Copyright (c) 1997-2015 The PHP Group                                                                   │Press Ctrl-C to quit. Start success.
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
