### ISSUE TITLE
Problems after autorun

### ISSUE THREAD

**Issue by M0nik** [walkor/Workerman#467]
Hello!
For autorun, I use the instruction [start with system](http://doc.workerman.net/faq/start-with-system.html)
And it works, the script starts automatically.
But when i try to stop, restart and status, errors are displayed, for example,

```
php start.php status -d
Workerman [start.php] status
Workerman [start.php] not run
```

```
php start.php restart -d
... Address already in use ... 
```
(first error [workerman start fail](http://doc.workerman.net/faq/workerman-start-fail.html))

I tried changing the directory of the _workerman.pid_ file and this does not help.

**Comment by walkor** [comment]
Show your `/etc/rc.local` please.

**Comment by M0nik** [comment]
```
#!/bin/bash

ulimit -HSn 102400
/usr/bin/env php /home/admin/web/socket.kassa.mobi/public_html/start.php start -d

exit 0
```

**Comment by walkor** [comment]
Make sure your login user is root which runs command `status`.

When the script starts automatically. Please try run command `/usr/bin/env php /home/admin/web/socket.kassa.mobi/public_html/start.php status` as root. If it still not work please run command `ps auxf` to check whether workerman start successfully.

At last check whether the workerman.pid created successfully.

**Comment by M0nik** [comment]
Yes, run with _sudo_ helped

`sudo php /home/admin/web/socket.kassa.mobi/public_html/start.php status -d`

Thank you!
