### ISSUE TITLE
AsyncTcpConnection wss onMessage doesn't work

### ISSUE THREAD

**Issue by akimovmaxim** [walkor/Workerman#473]
Hi! Thanks so much for a great library. Question about AsyncTcpConnection. Have wss server `$context         = [
			'ssl' => [
				'local_cert'  =>x ,
				'local_pk'    =>x ,
				'verify_peer' => false,
			],
		];
		$wsWorker = new Worker( 'websocket://0.0.0.0:' . $port, $context );
		$wsWorker->transport = 'ssl';` 
Js client works great with address 'wss:domain:port', but AsyncTcpConnection
`$worker->onWorkerStart = function ( $worker ) {

	$connection            = new AsyncTcpConnection( 'websocket://domain:port' );
	$connection->transport = 'ssl';

	$connection->onConnect = function ( $connection ) {
		echo "onConnect\n";
                $connection->send('test');
	};

	$connection->onMessage = function ( $connection, $data ) {
		echo "onMessage\n";
	};

	$connection->onClose = function ( $connection ) {
		echo "onClose\n";
	};

	$connection->onError = function ( $connection, $code, $msg ) {
		echo "onError\n";
	};

	$connection->connect();

};`
doesn't working properly, means call only onConnect & onClose, also  $connection->send return null & doesn't send any data. The connection exists, because it closes after a timeout specified on the server. What are the possible reasons? Thanks.

**Comment by walkor** [comment]
Try codes.
$connection  = new AsyncTcpConnection( 'ws://domain:port' );

**Comment by akimovmaxim** [comment]
That helped. Thanks. It turns out 'websocket' is different with 'ws', sorry, I thought it was alias. Also have small question about closing connection on the server side, js client say : wasClean: false, code: 1006, reason: "", but if close on client side have : wasClean: true, code: 10000. It is not very important for me, but maybe talking about some kind of error on the server?

**Comment by walkor** [comment]
If you want a clean close when closing connection on the server side try the codes `$connection->close("\x88\x02\x27\x10", true);`.

**Comment by akimovmaxim** [comment]
There are changes, but doesn't clean close : code: 10000, reason: "", wasClean: false. Also if close from js have same code (with wasClean:true), but doesn't find this code in https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent, say normal is 1000.

**Comment by akimovmaxim** [comment]
Yes, the code has become 1000, but wasClean : false. Also if close on js side still have code: 10000.

**Comment by walkor** [comment]
You should upgrade workerman

**Comment by akimovmaxim** [comment]
already tried composer update, but say nothing to install or update

**Comment by joanhey** [comment]
Try the `dev-master` in composer.

`"workerman/workerman": "dev-master"`

**Comment by akimovmaxim** [comment]
Update, on server side everything remains as it was, only client side close now look completely right (wasClean & 1000)

**Comment by walkor** [comment]
The codes below works for me. You can try that.
```php
use Workerman\Worker;

function cleanClose($connection) {
    $connection->onWebSocketClose = function($connection){
        $connection->close();
    };
    $connection->send("\x88\x02\x03\xe8", true);
}

$worker = new Worker('websocket://0.0.0.0:1120');
$worker->onMessage = function($connection, $data)
{
    cleanClose($connection);
};
Worker::runAll();
```

**Comment by akimovmaxim** [comment]
Yes, it's works, thanks. You will add this code to default close?

**Comment by walkor** [comment]
I'm not going to add them right now. I want to consider the compatibility between different communications protocols.
Maybe  add them in the future version 4.0.

**Comment by akimovmaxim** [comment]
Understand, thanks for answers
