### ISSUE TITLE
[Question] Any reason to maintain php 5.3 ?

### ISSUE THREAD

**Issue by joanhey** [walkor/Workerman#475]
PHP 5.3 is unsupported from 14 Aug 2014.
https://www.php.net/supported-versions.php
https://www.php.net/eol.php

We can clean the code using new versions.
v5.4
* callable type hint
* traits to separate the code and don't repeat it.
* ....

v5.6
* variadic  `...$var`
* ...

v7.0
 * `($this->callable)();` instead of `call_user_func()` that is very slow
* Null coalescing operator `$var ?? 'default'`
* ...

And if we want to create tests, we need to use new versions or later change the tests again.

Also it's possible to have two branchs.

**Comment by walkor** [comment]
Many users still use php5.3. Mandatory upgrades are not wise. In addition, upgrading to 5.4 will not bring any obvious benefits to developers. Developers can still choose to use PHP 5.4 or higher to develop workerman programs.
