### ISSUE TITLE
[Question]  Listen multiple sockets

### ISSUE THREAD

**Issue by mastir** [walkor/Workerman#479]
I need to run 3 sockets in one worker thread. So i have 3 sockets with different protocols: 
1) income port (tcp) used to connect devices with custom protocol.
2) status socket (unix) used by monitoring service threads
3) command socket used by admin to send data to devices (unix)

I can run 3 workers, but i need to run them in single thread to have simple communication between sockets. When device change its state i can send message to all status clients, and when admin send commands via command socket them simply redirected to some connected device on main socket. 

here is the suggested pseudo code:

	$this->workers[$name] = $worker = new Worker( 'tcp://0.0.0.0:60291' );
	$worker->protocol = DeviceProtocol::class;
	$worker->name = 'main';
	$app = $this->createApplication('income);
	//here we set onConnect, onMessage, onError, onClose handlers.
	$app->attach($worker);

	$status_server = new TcpConnection('unix:///run/device_status.sock');
	$status_server->protocol = MonitorProtocol::class;
	$status_app = $this->createApplication('status');
	//here we set onConnect, onMessage, onError, onClose handlers.
	$status_app->attach($status_server);
	$status_app->connect($app);

	$command_server = new TcpConnection('unix:///home/admin/device_admin.sock');
	$command_server->protocol = Jsonp::class;
	$command_app = $this->createApplication('command');
	//here we set onConnect, onMessage, onError, onClose handlers.
	$command_app->attach($conn);
	$command_app->connect($app);

	$worker->onWorkerStart = function() use ($status_server, $command_server){
		$status_server->listen();
		$command_server->listen();
	}

But i`ve found that all connection classes are client side only, is there any way to create listening sockets using Workerman framework or should i use other libs like reactphp for this?

**Comment by walkor** [comment]
Yes, you can do that like this.
```php
$worker = new Worker( 'tcp://0.0.0.0:60291' );
$worker->onWorkerStart = function() {
    global $status_server, $command_server;
    $status_server = new Worker('unix:///run/device_status.sock');
    $status_server->onMessage = function (){....};
    $status_server->listen();

    $command_server = new Worker('unix:///home/admin/device_admin.sock');
    $command_server->onMessage = function (){....};
    $command_server->listen();
};
$worker->onMessage = function(){....};
```

**Comment by mastir** [comment]
Nice, thank you!

**Comment by abhinavgmfs** [comment]
Hi Walkor,

How can we implement this in gateway worker solution.

Can you send me the example.

Thank you
