### ISSUE TITLE
求助：storeClientAddress fail

### ISSUE THREAD

**Issue by dalarge** [walkor/Workerman#48]
大概500人在线，时间久了就报如下错误，重启后正常
2015-12-11 14:53:42 createGlobalClientId fail GatewayWorker\Lib\StoreDriver\Redis :
2015-12-11 14:53:42 storeClientAddress fail.

redis用的内网地址，cpu占用20%左右，大神帮分析下原因出在哪？

**Comment by walkor** [comment]
redis扩展单例长连接不太稳定，改成短连接就好了。方法是每次instance的时候重新new 个 Redis实例。
或者升级下GatewayWorker，目前GatewayWorker2.0已经去掉了redis的依赖，也不会有这个问题。

GatewayWorker2.0 与GatewayWorker1.0区别见手册
http://workerman.net/gatewaydoc/appendices/upgrade.html

**Comment by dalarge** [comment]
谢谢，我升级试试
