### ISSUE TITLE
单机连接数超过6000的时候断开socket链接client_id依然存在

### ISSUE THREAD

**Issue by dalarge** [walkor/Workerman#49]
soory，又来麻烦你了，已经升级到2.0
单机连接数超过6000的时断开socket链接，有一定几率client_id依然存在
一个终端对应两个或多个client_id，向这两个client_id发广播，该终端都能收到

实际应用中的表象
我从一个房间A进入另一个房间B，在房间B还能收到A房间的信息

**Comment by walkor** [comment]
因为你的终端发起了两个连接导致的
