### ISSUE TITLE
microservices

### ISSUE THREAD

**Issue by morozovsk** [walkor/Workerman#492]
I use workerman for microservices.
For example:

index.php:
```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';
use Workerman\Worker;

/*if (ini_get('pinba.enabled')) {
    pinba_schema_set('workerman');
    pinba_script_name_set("workerman/index.php");
}*/

$services = [
    "http://0.0.0.0:9011" => 'ms1',
    "http://0.0.0.0:9012" => 'ms2',
    "http://0.0.0.0:9013" => 'ms3',
    "http://0.0.0.0:9014" => 'ms4',
];

foreach ($services as $socket_name => $service_name) {
    $Worker = new Worker($socket_name);
    $Worker->name = $service_name;
    $Worker->count = 4;
    $Worker->onWorkerStart = function () use ($Worker, $service_name) {
        /*if (ini_get('pinba.enabled')) {
            pinba_script_name_set("workerman/$service_name.php");
        }*/
        $Worker->onMessage = include "$service_name.php";
        /*$Worker->onClose = function($connection) use ($service_name) {
            if (ini_get('pinba.enabled')) {
                pinba_flush("workerman/$service_name.php", PINBA_FLUSH_RESET_DATA);
            }
        };*/
    };
}

Worker::runAll();
```

ms1.php
```php
<?php

$redis = new Redis();

$redis->pconnect('127.0.0.1');

return function($connection, $data) use ($redis)
{
    $r = 'hello world';

    $connection->close($r);
};

```

nginx.conf:
```nginx
location ~ ^/ms1$ {
    proxy_pass http://127.0.0.1:9011;
}
location ~ ^/ms2$ {
    proxy_pass http://127.0.0.1:9012;
}
```
It works little slower then swoole but it's much more useful:
* When I need to update my code I just use "php index.php reload" (or I need to use reload graceful?)
* When I have an error in one microservice workerman restarts it while another microservices work fine.

But I have couple problems.
* If I need to add one new microservice I need to do "restart" (and workerman will restart all microservices).
* If I need to reload one new microservice I need to do "reload" (and workerman will reload all microservices).

How to reload one microservice?
How to start one new microservice without restart?
How to use Worker("unix:http:ms1.sock") instead of Worker("http://0.0.0.0:9011") for http proxy in nginx like this:

```nginx
location ~ ^/ms1$ {
    proxy_pass unix:/var/www/workerman/ms1.sock;
}
```

PS: Thanks a lot for your library.

**Comment by walkor** [comment]
These are very good questions.
I wrote an example that I hope will help you.
index.php
```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';
use Workerman\Worker;

$services = include "config.php";

// Create new service
function create_worker($service_name, $info)
{
    $Worker = new Worker($info['listen']);
    $Worker->count = $info['count'];
    $Worker->user = $info['user'];
    $Worker->name = $service_name;
    $Worker->onWorkerStart = function () use ($Worker, $service_name) {
        $Worker->onMessage = include "$service_name.php";
    };
    return $Worker;
}

foreach ($services as $service_name => $info) {
    create_worker($service_name, $info);
}

// onMasterReload will called in master scope when run `php index.php reload` command.
Worker::$onMasterReload = function () {
    $all_workers = [];
    foreach (Worker::getAllWorkers() as $worker) {
        $all_workers[$worker->name] = $worker;
    }
    $services = include "config.php";
    // Start new worker.
    foreach ($services as $service_name => $info) {
        if (!isset($all_workers[$service_name])) {
            $worker = create_worker($service_name, $info);
            if (!$worker->reusePort) {
                $worker->listen();
            }
        }
    }
    // Change old worker config. Here is worker->count.
    foreach ($all_workers as $service_name => $worker) {
        if (isset($services[$service_name])) {
            $worker->count = $services[$worker->name]['count'];
        }
    }
};

// Parse command "php index.php reload {$service_name}"
if ($argv[1] == 'reload' && isset($argv[2])) {
    $reload_service_name = $argv[2];
    echo "reload $reload_service_name\n";
   // Send signal SIGUSR1 to the worker processes.
    exec("php index.php status | grep ' $reload_service_name' | awk '{print $1}' | xargs kill -SIGUSR1");
    exit("reload complete\n");
}

Worker::runAll();
```

config.php
```php
<?php
return [
    "ms1" => [
        // As you see, you can use unix socket like this.
        'listen' => 'unix:///var/www/workerman/ms1.sock',
        'count'  => 1,
        'user'   => 'www-data', 
    ],
    "ms2" => [
        'listen' => 'http://0.0.0.0:9012',
        'count'  => 2,
        'user'   => 'www-data',
    ],
    "ms3" => [
        'listen' => 'http://0.0.0.0:9013',
        'count'  => 3,
        'user'   => 'www-data',
    ],
    "ms4" => [
        'listen' => 'http://0.0.0.0:9014',
        'count'  => 4,
        'user'   => 'www-data',
    ]
];
```

> How to reload one microservice?

Use command `php index.php reload $service_name` for example `php index.php reload ms1`.

> How to start one new microservice without restart?

Add new service config in `$config.php` then run command `php index.php reload`

> How to use Worker("unix:http:ms1.sock") instead of Worker("http://0.0.0.0:9011") for http proxy in nginx like this:

The codes like this.
```php
new Worker('unix:///your/path');
```

**Comment by morozovsk** [comment]
Thanks a lot.

The reloading of one service works perfectly and creating of new service too.
But I have two problems with unix socket:
1. after start workerman creates socket file /var/www/workerman/ms1.sock and after reload/restart it already exists and I have error:
>stream_socket_server(): unable to connect to unix:///var/www/workerman/vpnservers.sock (Unknown error) in file /var/www/workerman/vendor/workerman/workerman/Worker.php on line 2224 

in line:
> $this->_mainSocket = \stream_socket_server($local_socket, $errno, $errmsg, $flags, $this->_context);

It works only if I delete file /var/www/workerman/vpnservers.sock

2. 'new Worker('unix:///your/path');' uses tcp transport and doesn't understand http protocol so nginx with option 'proxy_pass http://unix:/var/www/workerman/vpnservers.sock;' couldn't get anything from workerman.

I think it is not easy to add support restart/reload and http protocol for unix sockets so I will use ports instead of unix sockets.

**Comment by walkor** [comment]
1、To fix `unable to connect to unix..` we have modify function `create_worker` like this.
```
function create_worker($service_name, $info)
{
    $Worker = new Worker($info['listen']);
    $Worker->count = $info['count'];
    $Worker->user = $info['user'];
    $Worker->name = $service_name;
    $Worker->onWorkerStart = function () use ($Worker, $service_name) {
        $Worker->onMessage = include "$service_name.php";
    };
   // === Here ===
    if ($Worker->transport == 'unix') {
        $Worker->reusePort = false;
    }
    return $Worker;
}
```

2、If you want to support http protocol with unix socket you can try to set the protocol like this.
```php
$worker = new Worker('unix:///your/path');
// == Here ==
$worker->protocol = '\Workerman\Protocols\Http';
```

**Comment by morozovsk** [comment]
Thanks a lot.

**Comment by indigoram89** [comment]
@walkor thank you so much. how to stop one of child processes completely in this example?
