### ISSUE TITLE
Add server-sent events protocol [enhancement]

### ISSUE THREAD

**Issue by joanhey** [walkor/Workerman#494]
It's a really basic protocol.
SSE is useful when we only need to send data to the client.
Examples: 
In workerman: vm-stats, workerman-stats, ...

That makes them an excellent choice when there's no need to send data from the client to the server in message form. For example, `EventSource` is a useful approach for handling things like social media status updates, news feeds, or delivering data into a client-side storage mechanism like IndexedDB or web storage.

The **main advantage over websockets is that reconnect automatically** and an small and easy unified js api.

Info:
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events

Really easy to use in the client without js libs:
https://developer.mozilla.org/en-US/docs/Web/API/EventSource

We only need to send the correct header at connect, and send data with `data:` and `event:`.

**Comment by walkor** [comment]
Workerman supports server-sent events now. Workerman >= 4.0.0 required.

sse.php
```
<?php
require_once __DIR__ . '/../Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Protocols\Http\Response;
use Workerman\Protocols\Http\ServerSentEvents;
use Workerman\Connection\TcpConnection;
use \Workerman\Lib\Timer;

$worker = new Worker('http://0.0.0.0:1111');
$worker->name = 'sse';
$worker->onMessage = function($connection, $request)
{
    if ($request->header('accept') === 'text/event-stream') {
        $connection->send(new Response(200, ['Content-Type' => 'text/event-stream']));
        $timer_id = Timer::add(1, function () use ($connection, &$timer_id){
            if ($connection->getStatus() !== TcpConnection::STATUS_ESTABLISHED) {
                Timer::del($timer_id);
                return;
            }
            $connection->send(new ServerSentEvents(['event' => 'message', 'data' => 'hello', 'id'=>1]));
        });
        return;
    }
    $connection->send('ok');
};

Worker::runAll();
```

Server starting.
`php sse.php start`

javascript
```js
var source = new EventSource('http://127.0.0.1:1111');
source.onmessage = function (event) {
  console.log(event.data);
};
```

**Comment by joanhey** [comment]
Extra info to use SSE:

https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/
