### ISSUE TITLE
Trying to run background process and nothing happens

### ISSUE THREAD

**Issue by enefeka** [walkor/Workerman#498]
I´m having a little trouble trying to run a background task when using sockets. Since it give no errors at all, I´m a little lost as how to proceed. Here is my code (the relevant part at least):

```
$socket->on('post_location', function ($data)use($socket){
    $path = DOCROOT;
    exec("cd $path && cd .. && sudo php oil refine testsocket> /dev/null &");
    $socket->broadcast->emit('post_location', array(
        'username'=> $socket->username,
        'message'=> $data
    )); 
});
```
I've also tried this:

```
$socket->on('post_location', function ($data)use($socket){
        Worker::test_socket();
        $socket->broadcast->emit('post_location', array(
            'username'=> $socket->username,
            'message'=> $data
        )); 
    });
```
And in the Worker class of workerman the background task. Note that everything else works, but for some reason I cannot seem to run the task, it just does nothing. If I call it anywhere else, it works. The task at this moment is just a log:

```
class Testsocket 
{
    public static function run ()
    {
        \Log::info('Testing');
    }
}
```
Would appreciate any pointers. Thanks!

**Comment by walkor** [comment]
This is not workerman's issue. Please move it to https://github.com/walkor/phpsocket.io.
