### ISSUE TITLE
How i can integrate custom php script to workerman socket

### ISSUE THREAD

**Issue by iqoptionizator** [walkor/Workerman#499]
Hi all.
Can yo help me with integration workerman socket and my own php.

I need to send some data from my php script to client, who also connected to socket over workerman.
At this time I just send some data into workerman namespace (after worker connect).

How I can connect to opened sockets from outside of workerman main script?

**Comment by walkor** [comment]
```php
<?php
use Workerman\Worker;
require_once './Workerman/Autoloader.php';
global $worker;
$worker = new Worker('websocket://0.0.0.0:1234');
// Must be 1
$ws_worker->count = 1;
$ws_worker->onWorkerStart = function($worker)
{
    // listen http port
    $http_worker = new Worker('http://0.0.0.0:5678');
    $http_worker->onMessage = function($http_connection, $data)
    {
        $msg = !empty($_GET['msg']) ? $_GET['msg'] : 'nothing';
        broadcast($msg);
        $http_connection->send('ok');
    };
    $http_worker->listen();
};

$ws_worker->onMessage = function($connection, $data)use($worker)
{
   // ...
};

function broadcast($message)
{
    global $worker;
    foreach($worker->connections as $connection)
    {
        $connection->send($message);
    }
}
Worker::runAll();
```
Here is an example. Your outside of workerman main script can use http protocol to access the workerman service  and can do something broadcast message to all clients for example. The ws_worker and http_worker is in the same process and can access interfaces or variables with each other.
