### ISSUE TITLE
Bad SEO

### ISSUE THREAD

**Issue by morozovsk** [walkor/Workerman#500]
I can't find your library in github by query "php websocket" or "websocket" in "php".
https://github.com/search?l=PHP&p=1&q=websocket&type=Repositories
![screen461](https://user-images.githubusercontent.com/1822063/69189811-bcf4a080-0b27-11ea-986c-bd4776e33fec.png)

https://github.com/search?q=php+websocket&type=Repositories
![screen462](https://user-images.githubusercontent.com/1822063/69189873-e4e40400-0b27-11ea-89f4-2a18aba9cd04.png)

Even my old library is on second position but your library is even not in top 10. (I checked in google chrome incognito).

I think the problem is in very long description.

https://github.com/search?q=workerman+websocket&type=Repositories
![screen463](https://user-images.githubusercontent.com/1822063/69190032-3ee4c980-0b28-11ea-90ad-1e05e7aad5f8.png)

And may be github is indexing only "An asynchronous event driven PHP framework for easily building fast, scalable network applications. Supports HTTP, We".

If you like to have more traffic from search queries in github try to short your description. 
For example:
**An asynchronous event driven PHP framework. Supports HTTP, Websocket, SSL and other custom protocols. Supports** libevent, HHVM, ReactPHP. http://www.workerman.net

I think only first 120 symbols will be indexed. So use it for important keywords.
And you need to use tags for your others repositories, for example, walkor/workerman-todpole . Now walkor/workerman-todpole is on third position by query "php websocket"  despite your project has much more likes then mine.

**Comment by walkor** [comment]
Thank you for your post. This is really a problem. Now I've shortened the description and will check the effect  in a few days.
