### ISSUE TITLE
exit_status:11 

### ISSUE THREAD

**Issue by go-xmyang** [walkor/Workerman#501]
# 作者你好，我遇到了exit 11的错误，论坛和github上没找到满意的答复，分析coredump文件也只是看到了信号。
- 环境:   
docker容器，源镜像：php:7.3-cli-alpine3.10
- 状态：
![image](https://user-images.githubusercontent.com/29217985/69205523-23f47280-0b85-11ea-993f-6bb211108ce9.png)
- 版本:
![image](https://user-images.githubusercontent.com/29217985/69205548-31a9f800-0b85-11ea-8ae1-4839258aaa76.png)
- 扩展：
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
dom
event
fileinfo
filter
ftp
gd
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache

**Comment by go-xmyang** [comment]
![image](https://user-images.githubusercontent.com/29217985/69206289-35d71500-0b87-11ea-9800-13cfde0dfe4d.png)

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/issues/452

In php.ini set pcre.jit=0.
It seems jit in PHP 7.3.11 is not stable enough.

**Comment by darshitkkhatri** [comment]
When i remove libevent then is working fine. why so?
