### ISSUE TITLE
discard calling Worker property $_localSocket which may cause unexpected problem

### ISSUE THREAD

**Issue by blogdaren** [walkor/Workerman#509]
### issue from 
https://wenda.workerman.net/question/4921
### issue reproduce 
write code like this:
```
$worker = new Worker("MyUdp://0.0.0.0:9999");
$worker->transport = 'udp';
```
then it will cause unexpected problem:
1、on one hand, the worker console seems looks well, but in fact you will see nothing  if run command ```lsof -ni:9999```; 
2、on the other hand, the property ```$worker->transport``` also not work well.
### issue reason:
i found it is caused by Worker property ```$_localSocket``` which called not properly，because ```$_localSocket```  will always keep the same value when we change one property related，
this is not what we want.  
### suggestion:
well,  ```$_localSocket``` intended to reduce the numbe of parsing socket address, but in fact, it just has such a small effect on the performance improvement, so i think it is better to discard calling this property.

**Comment by walkor** [comment]
merged
