### ISSUE TITLE
(Possible) performance issue

### ISSUE THREAD

**Issue by vdmitrydev** [walkor/Workerman#512]
Hi!

I have a remote server: Ubuntu 18.04.3, PHP 7.4.1, Workerman 3.5.23.

There is a php script:
```
<?php
echo $_REQUEST['number'] * 10;
```
It is run via HTTP request by PHP-FPM. Response time is about 50 ms.
<img width="888" alt="fpm" src="https://user-images.githubusercontent.com/7867682/72743235-50942d00-3bbc-11ea-93af-f39fd72d637e.png">

I launched websocket worker:
```
<?php
use Workerman\Worker;
require_once __DIR__ . '/vendor/autoload.php';

// Websocket server
$worker = new Worker('websocket://0.0.0.0:2346');

$worker->onMessage = function ($conn, $data) {
    $conn->send($data*10);
};

Worker::runAll();
```
JS code:
```
var s = new WebSocket('ws://<server_ip>:2346');
s.send(15);
```
Server sends `150` back in the same ~50 ms:
<img width="443" alt="ws" src="https://user-images.githubusercontent.com/7867682/72743962-b8974300-3bbd-11ea-912d-80ebce38ce57.png">

I thought that communication through websockets should be faster than through HTTP request-response (less traffic, less preparations etc).

Am i doing something wrong? Maybe something is misconfigured? Any help is appreciated.

P.S. Installation of `event` extension did not affect anything. Still ~50 ms.

**Comment by walkor** [comment]
I think Network Latency is the key which consumes most of the time. You can do a localhost test then you will see the TTFB is much smaller.
The advantage of websocket is persistent connection and full duplex transmission. For example when the websocket connection established server can send data to clients anytime and do not need client send request message to server first. But HTTP server can only send data to the clients after the clients send requests first, during this period  may happen dns lookup、tcp three-way handshake which results http more slower.

**Comment by vdmitrydev** [comment]
You are right, local websocket works much faster. I was confused by Google Chrome explanation, thought TTFB is a time between server receives request and first sent byte. Seems like it is time between client sends request and first byte which includes network latency.

Tanks for your answer and great library. Good luck!
