### ISSUE TITLE
Composer - Undefined index: file

### ISSUE THREAD

**Issue by stanislavkukucka** [walkor/Workerman#514]
Composer fails at generating autoload
ErrorException  : Undefined index: file
**\vendor\workerman\workerman\Worker.php:2175**

Backtrace file is missing when running composer commands, otherwise it works fine from app.

Added if check manually so it works, but I need to repeat this every time a new version is released.
**if (isset($backtrace[0]['file'])) {
	$this->_autoloadRootPath = \dirname($backtrace[0]['file']);
	Autoloader::setRootPath($this->_autoloadRootPath);            
}**

**Composer v1.6.3
Php 7.2.24
OS Win 10**

**Comment by walkor** [comment]
var_dump($backtrace); and show the results please.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this
