### ISSUE TITLE
POF workerman + mysql + increasing core numbers

### ISSUE THREAD

**Issue by lenninpadilla** [walkor/Workerman#515]
Hey guys right now i have a doubt about this code:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;

// Create a Websocket server
$ws_worker = new Worker("websocket://0.0.0.0:2346");

// 12 processes
$ws_worker->count = 12;

$ws_worker->onWorkerStart = function() {
    global $db;
    $db = new \Workerman\MySQL\Connection('localhost', '3306', 'root', '', 'db');
    $all_tables = $db->query('show tables');
    //print_r(json_encode($all_tables));
    echo "test" . PHP_EOL;
};

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
    echo "New connection\n";
 };

// Emitted when data received
$ws_worker->onMessage = function($connection, $data) {
    global $mysql;
    $mysql->query('show databases' /*trim($data)*/, function ($command, $mysql) use ($connection) {
        if ($command->hasError()) {
            $error = $command->getError();
        } else {
            $results = $command->resultRows;
            $fields  = $command->resultFields;
            $connection->send(json_encode($results));
        }
    });
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

// Run worker
Worker::runAll();
```

Inside onWorkerStart I am making a query, also printing something but it seems like this is being called the number you use for cores. Maybe you will say making queries in that method (onWorkerStart ) is not right, what could be the right place to pre load some data before anyone get connected to the socket?

**Comment by walkor** [comment]
onWorkerStart is right place to pre load some data before anyone get connected to the socket.

**Comment by lenninpadilla** [comment]
Let's use the following example: my core numbers is 4, so this is making 4 calls to the db when onWorkerStart is called, so that's what i am trying to avoid... But i am not sure how to handle it... but it is just happening when that method is called.

**Comment by walkor** [comment]
When ws_worker->count = 4 it is normal for the database to be called 4 times, because each process needs to be initialized.

**Comment by lenninpadilla** [comment]
My concern is if each process will send 4 times in others request to the socket, basically i have a logic internally sometimes make some calls to the db... in onMessage method

**Comment by walkor** [comment]
Don't worry about it. Each process works independently and does not affect each other.

**Comment by teks1967** [comment]
Good evening! you can show a simple example to make a request in a function 

$ws_worker->onMessage = function($connection, $data){
mysqli_query($db, "INSERT INTO hist (date, us_ip) VALUES

where are examples of request code

Thank you in advance!!!
