### ISSUE TITLE
Best way to change a header with timer [question]

### ISSUE THREAD

**Issue by joanhey** [walkor/Workerman#516]
In the thechempower benchmark, now I decoupled the [Server](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/workerman/server.php) and [App](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/workerman/app.php).

It's a good example to port apps and frameworks. 

We are sending a Date header in each request
`Http::header('Date: '.gmdate('D, d M Y H:i:s').' GMT');`

A lot of servers and frameworks, create it only every second, as the resolution timer is 1 s for the date header.
We are executing, in each request, the `gmdate` function and join the result string. That's more than 1 million times per second, in the plaintext and json benchmark.

Why not use a timer for that?
`Http::header($date_header);`
and use a `Add::timer()` to change the variable every second.

Which way will be better to do it ?

Thank you.

**Comment by walkor** [comment]
Yes, I agree with you. It is unreasonable to calculate `gmdate` for each request.
We can create every second like this.
```
use Workerman\Lib\Timer;
class App {
    public static $dateHeader = null;
}
$http_worker->onWorkerStart = function () {
    Timer::add(1, function(){
        App::$dateHeader = 'Date: '.gmdate('D, d M Y H:i:s').' GMT';
    });
    init();
};

$http_worker->onMessage = static function ($connection) {
    Http::header(App::$dateHeader);
    $connection->send(router());
};
```

**Comment by joanhey** [comment]
In that example, it's creating a timer for every worker.

Is it possible to have 1 timer for all workers ?

**Comment by walkor** [comment]
Processes are independent and cannot use the same timer directly.
