### ISSUE TITLE
4.0 benchmark  performance reduce

### ISSUE THREAD

**Issue by hovo728** [walkor/Workerman#523]
I am glad to see the release of version 4.0, and I am also glad to finally have a more convenient way to use the session.

I just did a stress test for http mode. The same hardware 3.5.29 has 33xxx QPS. But 4.0 only has 18XXX.

My command is as follows

ab -k -r -c100 -n300000 http://192.168.0.181:8080

Is there anything I should pay attention to?

**Comment by walkor** [comment]
Can you show me the codes?

**Comment by hovo728** [comment]
Thank you for your reply

My code is as follows：

require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;

$http_worker = new Worker("http://0.0.0.0:8080");

// 4 processes
$http_worker->count = 8;

// Emitted when data received
$http_worker->onMessage = function($connection, $data)
{
    // $_GET, $_POST, $_COOKIE, $_SESSION, $_SERVER, $_FILES are available
    var_dump($_GET, $_POST, $_COOKIE, $_SESSION, $_SERVER, $_FILES);
    // send data to client
    $connection->send("hello world \n");
};

Worker::runAll();

**Comment by walkor** [comment]
Do not var_dump data to terminal which will reduce the performance.
$_SESSION is not defined for workerman 4.x. If you `var_dump($_SESSION)` `Undefined variable: _SESSION` will appear and maybe log it to disk which will  reduce the performance.

I did a stress test use the following codes for 4.0.
```php
require_once DIR . '/vendor/autoload.php';
use Workerman\Worker;

$http_worker = new Worker("http://0.0.0.0:8080");

$http_worker->count = 2;

// Emitted when data received
$http_worker->onMessage = function($connection, $data)
{
    $connection->send("hello world \n");
};

Worker::runAll();
```
The results 121678.04 [#/sec] .

**Comment by hovo728** [comment]
You got it ..Is my fault!

After  marked  var_dump 
I did  test again

workerman 3.5.29  results  43510
workerman 4.0.00  results  42492

My result is relatively low. It should be that my hardware is virtualized on the old hardware.
I also test another Item (base on C/C++)  In the same environmen ... result 39477

the measured results make me extremely happy
because it was my mistake that caused workerman benchmark reduce 

Thank you very much for promoting this project and quick response!

**Comment by walkor** [comment]
I'm glad you like it. 😊
