### ISSUE TITLE
Default argument start for Workerman

### ISSUE THREAD

**Issue by kooijohan** [walkor/Workerman#528]
Hello,

Im trying to run Workerman in a Laravel Artisan Command (https://laravel.com/docs/5.8/artisan).

On Windows everything works fine if I run:
`php artisan mqtt:listen`

But if I run the same command I get this error:
```
Unknown command: mqtt:listen
Usage: php yourfile <command> [mode]
```

This is because the value of `$argv[1]` = `mqtt:listen` in this case. In the `Worker.php` the function `parseCommand()`  is using $argv[1] to match it with an available command (which should be start for my use case). 

Can I somehow specify "start" as default argument?

**Comment by walkor** [comment]
Change `$argv[1]` to the `available command` in the right place.

**Comment by kooijohan** [comment]
@walkor that feels a bit dirty, but ok thanks!

**Comment by aFluxx** [comment]
> @walkor that feels a bit dirty, but ok thanks!

Hi Kooijohan, could you maybe explain how you solved this? I'm running into the same issue on a Laravel install.

Windows works fine (local), but on the server the command doesn't work.

**Comment by aFluxx** [comment]
> @walkor that feels a bit dirty, but ok thanks!

Hi Kooijohan, could you maybe explain how you solved this? I'm running into the same issue on a Laravel install.

Windows works fine (local), but on the server the command doesn't work.

**Comment by shellshock1953** [comment]
Same here, running Laravel inside Docker container:
```Dockerfile
FROM php:8-fpm-alpine
```
Dockerfile itself can be found [here](https://github.com/aschmelyun/docker-compose-laravel/blob/main/dockerfiles/php.dockerfile)
On local machive everything works (windows workstation), inside Docker fails/
