### ISSUE TITLE
Websocket tcpConnection : how get real remoteIp with Cloudflare

### ISSUE THREAD

**Issue by light-source** [walkor/Workerman#531]
Hello Walkor.
I hope that you are doing well. Thank you so much for the great library.
I have question regarding using Cloudflare as CDN service. 
It's working as proxy, and all request now is going through them servers, so I can't get real ip of customers. 
But the service is always creating addition http header - 'CF-Connecting-IP' so I can get real ip in my site (manual in request headers or with using apache mod 'remoteip' https://support.cloudflare.com/hc/en-us/articles/360029696071-Restoring-original-visitor-IPs-Option-2-Installing-mod-remoteip-with-Apache). 
I was tried to get real ip for websocket tcpConnection, but I had troubles with it. Can you please suggest me way, how I can get access to the request headers or maybe another way to get real customer ip?
Thank you in advance.

**Comment by walkor** [comment]
Hi light-source.
You can get the `CF-Connecting-IP` value from websocket handshake header like this. When you get the value add a property(for example `realIp`) to `$connection` to store it then you can use it anywhere by code `$connection->realIp`;
```php
$worker = new Worker('websocket://0.0.0.0:8080');
$worker->onWebSocketConnect = function ($connection) {
     var_dump($_SERVER);
     $connection->realIp = $_SERVER['HTTP_CF_CONNECTING_IP'];
};
$worker->onMessage = function ($connection, $data) {
    echo $connection->realIp;
};
```

**Comment by light-source** [comment]
That's it, thank you very much!

**Comment by walkor** [comment]
You are welcome.
