### ISSUE TITLE
 Class 'think\facade\Validate' not found

### ISSUE THREAD

**Issue by xue-y** [walkor/Workerman#533]
thinkphp5.1 中用到 GatewayWorker, 下载文件
[ http://www.workerman.net/download/GatewayWorker-for-win.zip](url)
官方测试文件，
点击运行start_for_win.bat  ，提示
PHP Fatal error:  Class 'think\facade\Validate' not found in F:\phpStud\PHPTutorial\WWW\CasPHP\vendor\topthink\think-captcha\src\helper.php on line 13

Fatal error: Class 'think\facade\Validate' not found in F:\phpStud\PHPTutorial\WWW\CasPHP\vendor\topthink\think-captcha\src\helper.php on line 13

**Comment by walkor** [comment]
Close due to https://github.com/walkor/Workerman/issues/266 .
