### ISSUE TITLE
pid:2166 worker[none:2237] exit with status 134

### ISSUE THREAD

**Issue by webpro100** [walkor/Workerman#534]
FreeBSD 12.1-RELEASE-p2 GENERIC  amd64
php 7.4.5

last version of worker

**Comment by walkor** [comment]
Please run command `php -v` and `php -m` and show the output.
`exit with status 134` means process get a signal `SIGABRT` which maybe a bug for your php version or some extensions's bug.

**Comment by webpro100** [comment]
`$ php -v
PHP 7.4.5 (cli) (built: Apr 23 2020 01:30:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
$
`

`$ php -m
[PHP Modules]
bz2
Core
ctype
curl
date
dom
ev
exif
fileinfo
filter
gd
gmagick
hash
iconv
json
libxml
mbstring
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

$
$
`

**Comment by walkor** [comment]
Remove `ev` extension and try again.

**Comment by webpro100** [comment]
`Stack trace:
#0 /usr/local/www/apache24/data/libs/workerman/Worker.php(2336): Workerman\Events\Ev->add(Resource id #726, 1, Array)
#1 /usr/local/www/apache24/data/libs/workerman/Worker.php(2374): Workerman\Worker->resumeAccept()
#2 /usr/local/www/apache24/data/libs/workerman/Worker.php(1541): Workerman\Worker->run()
#3 /usr/local/www/apache24/data/libs/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#4 /usr/local/www/apache24/data/libs/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#5 /usr/local/www/apache24/data/libs/workerman/Worker.php(1675): Workerman\Worker::forkWorkers()
#6 /usr/local/www/apache24/data/libs/workerman/Worker.php(1624): Workerman\Worker::monitorWorkersForLinux()
#7 /usr/local/www/apache24/data/libs/workerman/Worker.php(548): Workerman\Worker::monitorWorkers()
#8 /usr/local/www/apache24/data/ws-server.php(130): Workerman\Wor in /usr/local/www/apache24/data/libs/workerman/Events/Ev.php on line 83"
2020-05-10 08:16:55 pid:2266 worker[none:2973] exit with status 65280
2020-05-10 08:16:55 pid:2974 Worker[2974] process terminated with ERROR: E_ERROR "Uncaught Error: Class 'Ev' not found in /usr/local/www/apache24/data/libs/workerman/Events/Ev.php:83`

**Comment by walkor** [comment]
show your codes please

**Comment by webpro100** [comment]
i have another installation on freebsd 11 with php71, and this codes work fine there.

https://we.tl/t-tlKHojtlmo

**Comment by walkor** [comment]
Try to remove `Worker::$eventLoopClass = '\Workerman\Events\Ev';` from ws-server.php.

**Comment by webpro100** [comment]
Thank you very match), seems to be all ok.
