### ISSUE TITLE
Unix socket bind error

### ISSUE THREAD

**Issue by Incisakura** [walkor/Workerman#537]
**Environment**
PHP: 7.4.3
Workerman: v4.0.5

**Issue**
https://github.com/walkor/Workerman/blob/2094b5de07e5881cc9aae070496f7808922f2ef2/Worker.php#L2223-L2233
When using workerman by unix socket, php would throw a fatal error.
```
stream_socket_server(): unable to connect to unix://tmp/test.sock (Unknown error) in file */vendor/workerman/workerman/Worker.php on line 2233
PHP Fatal error:  Uncaught Exception in */vendor/workerman/workerman/Worker.php:2235
```
This issue could be reproduced by these codes.
```php
<?php
$errno = 0;
$msg = '';
stream_socket_server('unix://tmp/test.sock', $errno, $msg, \STREAM_SERVER_BIND | \STREAM_SERVER_LISTEN);
```

**Additional**
According to [PHP document](https://www.php.net/manual/en/stream.constants.php#constant.stream-server-listen), "Tells a stream created with stream_socket_server() and bound using the STREAM_SERVER_BIND flag to start listening on the socket." which should mean we **shouldn't use both** STREAM_SERVER_LISTEN and STREAM_SERVER_BIND.

**Comment by walkor** [comment]
`unix://tmp/test.sock` is not correct. Try `unix:///tmp/test.sock`.

**Comment by Incisakura** [comment]
Oh, sorry for noob mistake...
