### ISSUE TITLE
Workerman on bref AWS

### ISSUE THREAD

**Issue by Nidiots** [walkor/Workerman#538]
Hi , i am trying to setup workerman on AWS using bref(serverless) framework , but getting this error ,

can not save pid to /var/task/vendor/workerman/workerman/../_var_task_artisan.pid

Do we have any way ? or how i can change the pid directory location.

**Comment by walkor** [comment]
Change pid location by codes  `Worker::$pidFile ='...';`. For example.
```php
use Workerman\Worker;
Worker::$pidFile = '/your/path/of/workerman.pid';

$worker = new Worker(...);
```
