### ISSUE TITLE
Syncing between workers

### ISSUE THREAD

**Issue by gotzmann** [walkor/Workerman#539]
Are there any sync primitives for communication and resource sharing between workers in Workerman? Something like mutexes or channels?

For example, if I'll start 16 workers with it's own timers and would like to prevent any data races and mutual blocking when accessing for single shared resource within functions started by timers.

**Comment by walkor** [comment]
There is no proprietary resource sharing or synchronization primitive for workerman. 
Resource sharing or data synchronization follows most theories and uses in PHP. For example, shared memory, redis, file lock, semaphore etc.

**Comment by gotzmann** [comment]
Thanks!
