### ISSUE TITLE
Restart on file change

### ISSUE THREAD

**Issue by IngwiePhoenix** [walkor/Workerman#54]
I'm currently restarting workerman over and over and over each time a file changes.

It'd be handy to have a way to restart it faster. Any idea?

My idea with watching files comes from the things the JavaScript community does; where they watch files for their last modified date, and if it was modified, the entire service is restarted. Usually used for development and disabled in production, of course.

**Comment by walkor** [comment]
There are two monitoring services available which can monitor files change and then send reload signal to master process of workerman. 

https://github.com/walkor/workerman-filemonitor/blob/master/Applications/FileMonitor/start.php
This is a file monitoring service for workerman.

https://github.com/walkor/workerman-filemonitor-inotify/blob/master/Applications/FileMonitor/start.php
This is a file monitoring service too which need inotify extension.

Choose one of them for installation.

**Comment by IngwiePhoenix** [comment]
Ill go with the first one. Awesome, you totally got this covered! :)

Though...may I request english docs? At least an english example on how to utilize it? The only chinese I know is blind, so she can't help me ;)

**Comment by walkor** [comment]
It is very easy.
Require the start.php in your script and change [$monitor_dir](https://github.com/walkor/workerman-filemonitor/blob/master/Applications/FileMonitor/start.php#L6) to the catalogue of your project.

**Comment by IngwiePhoenix** [comment]
Okay, cool! Thanks for that. :)

**Comment by walkor** [comment]
You are welcome.
