### ISSUE TITLE
Workerman + Cloudflare doesn't work

### ISSUE THREAD

**Issue by webeffected** [walkor/Workerman#541]
I'm really sorry, if this question is stupid, but we learn through asking questions, so forgive me please )))

Websocket server is working great on dev environment on my local machine and it doesn't matter if I specify IP address or local domain to start _**new Worker()**_.

But things are getting interesting, when I'm trying to do the same thing on my actual website, which is proxied through Cloudflare. There are not a lot of articles about Cloudflare + websockets, what to say about cloudflare + workerman...

So when I try to start actual production websocket it only works if I specify a real server IP address at any port. 

And I can connect only to ws://ip:8443 not wss, despite of the fact, that I have working Let's Encrypt certificate.

When I try to start a server using my domain name, it gives me this error:

> stream_socket_server(): unable to connect to tcp://domain.com:8443 (Cannot assign requested address) in file /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php on line 2233
> 
> PHP Fatal error:  Uncaught Exception: Cannot assign requested address in /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php:2235
> 
> Stack trace:
> `#0` /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php(1524): Workerman\Worker->listen()
> 
> `#1` /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
> 
> `#2` /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
>  
>  `#3` /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
> 
> `#4` /var/www/user/data/www/domain/releases/20200624232530/func/websocket/server-ws.php(93): Workerman\Worker::runAll()
> 
> `#5` {main} thrown in /var/www/user/data/www/domain/releases/20200624232530/vendor/workerman/workerman/Worker.php on line 2235

To sum up everything:
- I'm using basic websocket configuration from your README.md;
- websocket is only working if I use my server IP address and only on WS protocol, not WSS;
- it throws error above if I try to create server using domain name and 8443 port;
- SSL/TLS encryption mode is Full (strict) (Let's Encrypt on server side);
- I've read these articles:
https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets
https://www.cloudflare.com/website-optimization/web-sockets/
Which basically say that I am able to use websockets on cloudflare without any special preparation. Well, thanks a lot, but I can't...

I've also read this article about ports - https://support.cloudflare.com/hc/en-us/articles/200169156-Identifying-network-ports-compatible-with-Cloudflare-s-proxy

And websockets are enabled in Network tab in my cloudflare settings.

So, are there any suggestions, what am I missing here?

**Comment by walkor** [comment]
```
stream_socket_server(): unable to connect to tcp://domain.com:8443 (Cannot assign requested address)
```
That means that the IP address(`domain.com's ip`) to be bound by the server does not belong to the local machine.
Please do not use domain but `0.0.0.0` instead. 
```php
$worker = new Worker('websocket://0.0.0.0:8443');
```
I'm sorry, I not familiar with Cloudflare, so I can't tell you how to proxy WSS with Cloudflare.

**Comment by webeffected** [comment]
Thanks a lot for your reply!

But in that case 

`$worker = new Worker('websocket://0.0.0.0:8443');`

I'm only able to connect to **ws://0.0.0.0:8443**, which exposes my actual IP address to all users, because javascript is used to connect on client side and all Cloudflare benefits, including a lot of security issues, are melting (because any bad guy can get real ip address).

What I'm trying to achieve is to connect users through **wss://domain:8443**.

And there is another problem, not connected with Cloudflare. I have working SSL certificate, so why am I only able to connect to WS, not WSS? Do I need to do something on server side to enable WSS?

**Comment by taozywu** [comment]
@webeffected 
this code maybe help you!
```
<?php
require_once __DIR__ . '/Workerman/Autoloader.php';
use Workerman\Worker;

// 证书最好是申请的证书
$context = array(
    'ssl' => array(
        'local_cert'  => '/etc/nginx/conf.d/ssl/server.pem', // 也可以是crt文件
        'local_pk'    => '/etc/nginx/conf.d/ssl/server.key',
        'verify_peer' => false,
    )
);
// 这里设置的是websocket协议，也可以http协议或者其它协议
$worker = new Worker('http://0.0.0.0:443', $context);
// 设置transport开启ssl
$worker->transport = 'ssl';
$worker->onMessage = function($con, $msg) {
    $con->send('ok');
};

Worker::runAll();
```

and this link(http://doc.workerman.net/faq/ssl-support.html) will help you !
good luck!

**Comment by webeffected** [comment]
**Thanks, taozywu!** I'll try it.

As another workaround I can add this page rule in Cloudflare:

`*domain:8443/* > SSL: Off`

But this is disabling Cloudflare SSL to 8443 port, which is not good, I suppose.
However after this setting, connection to wss://domain:8443 was successfully opened.

I'll try taozywu solution.

**Comment by walkor** [comment]
```php
$worker = new Worker('websocket://0.0.0.0:8443');
```
It doesn't mean you can only connect with IP, you can connect with domain name.

**Comment by webeffected** [comment]
So, finally we got it working.

I'll answer my own questions in case someone may also find it helpful.

First of all you need to start server not on 0.0.0.0 ip, but on your actual server ip address.

If everything is fine, you should be able to connect to **wss://site.com:8443**. 

You can take any opened port, but Cloudflare allows for secured connections only:
    443
    2053
    2083
    2087
    2096
    8443

There is no need to turn off SSL in Cloudflare page rules in order to get websocket working (however it will work). In case of Workerman, as **taozywu** [mentioned](https://github.com/walkor/Workerman/issues/541#issuecomment-649419950) above, we just need to pass SSL certificates.

In my case path to certificates was: **/var/www/httpd-cert/user/**

There I found files:
site.com_le1.crtca
site.com_le1.key

Issued by Let's Encrypt. So I pasted them to $context variable:

```
...
'local_cert'  => '/var/www/httpd-cert/user/site.com_le1.crtca',
'local_pk'    => '/var/www/httpd-cert/user/site.com_le1.key',
...
```

But, still ws server wasn't working, telling me this error:

`Error: stream_socket_enable_crypto(): SSL_R_NO_SHARED_CIPHER: no suitable shared cipher could be used.  This could be because the server is missing an SSL certificate (local_cert context option).`

The reason is simple - workerman server doesn't have access to /var/www/httpd-cert/user/ folder.

Solution is to create links to certificates from place where it can be reached.

Again, in my case:

```
sudo ln /var/www/httpd-cert/user/site.com_le1.crtca /var/www/user/data/www/site/current/func/websocket/ssl/cert.pem
sudo ln /var/www/httpd-cert/user/site.com_le1.key /var/www/www-real/data/www/site/current/func/websocket/ssl/cert.key
```

But be careful, these links can't be reachable from web. You can block access to them through .htaccess or nginx, for example.

Then we had this error:

`SSL handshake error: stream_socket_enable_crypto(): Unable to set local cert chain file 'ssl/cert.pem'; Check that your cafile/capath settings include details of your certificate and its issuer`

Which was fixed by changing the certificate files permissions - they were created by root user, therefore user under ws server could not use them. Granting permissions to current user, running workerman, solved the problem.

After this, websocket server started to work, as it was expected.

**Please, give me feedback if something, what I've just explained is wrong. I'm still learning ))**

P.s. Approximately once in a minute every client disconnects from ws server. We have auto reconnect function, so it is not a big deal, but is that a normal behaviour?

**Comment by walkor** [comment]
> First of all you need to start server not on 0.0.0.0 ip, but on your actual server ip address.

It is common to way to bind `0.0.0.0` which means binds to all network interfaces on the current computer include `127.0.0.1` and your actual server ip address.

> P.s. Approximately once in a minute every client disconnects from ws server. We have auto reconnect function, so it is not a big deal, but is that a normal behaviour?

Please add heartbeat to your application  that means your client need to send some data(any data for example `ping`) to the server at regular intervals. This prevents the connection from being closed by Cloudflare due to inactivity for a long time. When your server get ping data, just ignore it.
