### ISSUE TITLE
[linux] reload comand does not pick up source file change because they are forks

### ISSUE THREAD

**Issue by char101** [walkor/Workerman#542]
Hi,

If I modify `server.php` and then run `php server.php reload` in linux, the workers are still running the old code because they are forked process and thus their memory is a copy of the parent process. How then can we reload source code change in linux without having to restart the master process every time?

**Comment by walkor** [comment]
For example.

start.php
```php
$worker = new Worker('websocket://0.0.0.0:6666');
$worker->onWorkerStart = function($worker){
    // You can also use spl_autoload to require MyClass file.
    require __DIR__ . '/MyClass.php';
    $my_class = new MyClass();
    $worker->onConnect = [$my_class, 'onConnect'];
    $worker->onMessage = [$my_class, 'onMessage'];
    $worker->onClose = [$my_class, 'onClose'];
};
Worker::runAll();
```
MyClass.php
```php
class MyClass 
{
    public function onConnect($connection)
    {

    }

    public function onMessage($connection, $data)
    {

    }

    public function onClose($connection)
    {
      
    }
}
```

**Comment by char101** [comment]
Thank you, it works.

I'll try to explain what happens here for other people that might face the same problem. We put the application code in a class in a separate file. But we don't load the class in `server.php`. That way, when the process is forked, the application class does not exist yet in the PHP cache. Then we `require` the application class in `onWorkerStart` thus causing it to load the updated application class every time a worker is restarted.

**Comment by char101** [comment]
A caveat of this is that since the application code is `require`d inside a function, any `global` variables inside it need to be declared `global`.

```app.php```
```php
global $var;
$var = 'some global value';

function onMessage($connection, $request)
{

}
```

**Comment by shunhua** [comment]
![HR~}~0YP4@W31_{7B}ZHJ32](https://github.com/walkor/workerman/assets/11988030/06b78c52-be6c-48d4-8ffb-0aec68f4af11)
引入文件报错 咋回事?

**Comment by shunhua** [comment]
> ![HR~}~0YP4@W31_{7B}ZHJ32](https://user-images.githubusercontent.com/11988030/282637521-06b78c52-be6c-48d4-8ffb-0aec68f4af11.jpg) 引入文件报错 咋回事?

myclass里操作不了数据库？
