### ISSUE TITLE
Redis session serializer config

### ISSUE THREAD

**Issue by char101** [walkor/Workerman#544]
Hi,

Would it be possible to add an option to set the serialization method for the redis session handler?

Php-redis supports php, igbinary, and msgpack serializer with msgpack being the fastest and php the slowest.

**Comment by char101** [comment]
Hmm actually the serializer does not matter because the `Session` class uses `serialize`.

**Comment by walkor** [comment]
```php
$t = microtime(true);

$i = $j = 1000000;

$data = [
    'uid'  => 123,
    'name' => 'tom',
    'sex'  => 0,
    'avatar' => 'http://www.example.com/avatar.png'
];

/*for($k=0; $k<$i; $k++) {
  $pack = msgpack_pack($data);
  msgpack_unpack($pack);
}*/

for($k=0; $k<$i; $k++) {
  $pack = serialize($data);
  unserialize($pack);
}

echo $j/(microtime(true) - $t) , "\n";
```

msgpack result 1293388.
serialize result 1423799.

That means serialize's performance is slightly better than msgpack's  in some cases.

And I don't think it makes much difference to use serializer or msgpack, because IO is the bottleneck here.

**Comment by char101** [comment]
Thanks for the benchmark. This is the result on my computer (arch linux 64 bit)

```
msgpack pack 8431802
php serialize 8699071

PHP 7.4.7 (cli) (built: Jul  6 2020 18:37:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies
```

So indeed msgpack seems to be on par with php serialize for small map.

If you decide to keep using php `serialize` then at least the redis serializer need to be set to `Redis::SERIALIZER_NONE`, because othewise the session data will be serialize twice, first by the `Session` class and then by the `redis` extension.

Benchmark code

```php
<?php

const N = 10000000;

$data = [
    'uid'    => 123,
    'name'   => 'tom',
    'sex'    => 0,
    'avatar' => 'http://www.example.com/avatar.png',
];

function benchmark($title, $f)
{
    $t1 = microtime(true);
    $f();
    $t2 = microtime(true);
    echo $title.' '.round(N / ($t2 - $t1))."\n";
}

$msgpack = new MessagePack(false);

benchmark('msgpack pack', function () {
    global $data, $msgpack;
    for ($i = 0; $i < N; ++$i) {
        $msgpack->pack($data);
    }
});

benchmark('php serialize', function () {
    global $data;
    for ($i = 0; $i < N; ++$i) {
        serialize($data);
    }
});
```

**Comment by walkor** [comment]
The default value of `Redis::OPT_SERIALIZER` is `Redis::SERIALIZER_NONE` so you do not need to set again.

**Comment by char101** [comment]
Thanks, my mistake.
