### ISSUE TITLE
Do long sleep() in one worker blocks all others?

### ISSUE THREAD

**Issue by gotzmann** [walkor/Workerman#545]
It seems that when sleep() called within one worker (busy), all others (free) cant respond to incoming requests.
When I replace sleep() with just one big computational loop - all works fine.
Am I right and why is it so?

**Comment by walkor** [comment]
> It seems that when sleep() called within one worker (busy), all others (free) cant respond to incoming requests.

Blocked processes do not affect other processes. If a process is blocked, all requests to that process will be blocked.

**Comment by gotzmann** [comment]
> Blocked processes do not affect other processes.

So if there Worker() with count of workers == 2 and one of it workers blocked with sleep(), second one should work fine? It seems that when one worker blocked with sleep(), second do not respond.

**Comment by char101** [comment]
It does not block the other worker but workerman will still queue requests to the sleeping worker, so some requests will stall.

**Comment by char101** [comment]
We can force the worker to stop accepting connections by wrapping the sleep with

```php
<?php
$connection->worker->unlisten();
sleep(10);
$connection->worker->listen();
```

This way new connections will only be handled by the other workers.

**Comment by walkor** [comment]
Blocking processes can not accept new connections so you do not need to call unlisten. But the blocking processes already hold some connections, if there are some requests coming which belong to these connections they will all send to the blocking process and will waiting. 

>  It seems that when one worker blocked with sleep(), second do not respond.

If you test with browser, remember there will be an additional favicon.ico request which may have affected your test.

Here is an example to show  that if one process blocked it has not affected to others.
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;

$worker = new Worker('http://0.0.0.0:8686');
$worker->count = 2;

$worker->onWorkerStart = function($worker){
    // Call sleep only on process which id is 0.
    if ($worker->id == 0) {
        while (1) {
            echo "I'm sleeping\n";
            sleep(10);
        }
    }
};

$worker->onMessage = function($con, $request) {
    $con->send("I'm ok");
};

Worker::runAll();
```

**Comment by char101** [comment]
What about calling `sleep` in he `onMessage handler?

I tried calling `sleep` on the request handler (`onMessage`) on a specific route (url). When accessing other route by opening several new browser tabs, 60-70% are stuck on a loading state.

**Comment by char101** [comment]
> But the blocking processes already hold some connections, if there are some requests coming which belong to these connections they will all send to the blocking process and will waiting.

Is this caused by keep alive connection. I never considered it before but do keep alive connections works across browser tabs?

**Comment by walkor** [comment]
> Is this caused by keep alive connection. 

Yes.

> do keep alive connections works across browser tabs?

I don't know.

> I also used nginx in front of workerman. Nginx might hold a keep alive connection to workerman.

I think keep-alive is also used between nginx and workerman.

**Comment by char101** [comment]
Thanks, I removed these lines from nginx configuration

```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

and can verify that new connections are indeed not being blocked.
