### ISSUE TITLE
`is_file` result might be cached when cleaning temporary upload file

### ISSUE THREAD

**Issue by char101** [walkor/Workerman#546]
Hi,

The call to `is_file` in [Request.php](https://github.com/walkor/Workerman/blob/master/Protocols/Http/Request.php#L611) might be cached by PHP so if the temporary file has been moved, the call to `unlink` will results in a warning.

So before calling `is_file` it might be necessary to call `clearstatcache` with the file path.

**Comment by walkor** [comment]
Fixed and thanks for your post.

**Comment by char101** [comment]
Thanks. By the way, in `clearstatcache` we can specify the the path that we want to clear. Wouldn't it be better to only clear the state cache for the upload path?

```
\clearstatcache(true, $item['tmp_name']);
```

**Comment by walkor** [comment]
> Wouldn't it be better to only clear the stat cache for the upload path?

It looks like should call `\clearstatcache(true, $item['tmp_name']);` many times. So I think call `clearstatecache();` is better.

**Comment by char101** [comment]
Oh right it is in a loop. Thanks.
