### ISSUE TITLE
 Fatal error: Class Workerman\Events\React\Base contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (React\EventLoop\LoopInterface::removeStream, React\EventLoop\LoopInterface::isTimerActive, React\EventLoop\LoopInterface::nextTick, ...) in /var/www/u0544126/data/www/porno-chatik.tk/vendor/workerman/workerman/Events/React/Base.php on line 24 Error: Class Workerman\Events\React\Base contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (React\EventLoop\LoopInterface::removeStream, React\EventLoop\LoopInterface::isTimerActive, React\EventLoop\LoopInterface::nextTick, ...) worker[none:150006] exit with status 65280

### ISSUE THREAD

**Issue by cr1gger** [walkor/Workerman#553]
`
Fatal error: Class Workerman\Events\React\Base contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (React\EventLoop\LoopInterface::removeStream, React\EventLoop\LoopInterface::isTimerActive, React\EventLoop\LoopInterface::nextTick, ...) in /var/www/u0544126/data/www/porno-chatik.tk/vendor/workerman/workerman/Events/React/Base.php on line 24
Error: Class Workerman\Events\React\Base contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (React\EventLoop\LoopInterface::removeStream, React\EventLoop\LoopInterface::isTimerActive, React\EventLoop\LoopInterface::nextTick, ...)
worker[none:150006] exit with status 65280
`
Use code of documentation.
I tried to write these methods myself in the Base.php file:
`public function nextTick(callable $listener)
    {
    }
    public function isTimerActive(TimerInterface $timer)
    {
    }
    public function tick()
    {
    }`

But then he swears at the addSignal method.
Says that it does not exist, namely this method: return $ this -> _ eventLoop-> addSignal ($ signal, $ listener);

I think there is a problem in LoopInterface itself
This function:
`public function addSignal($signal, $listener)
    {
        return $this->_eventLoop->addSignal($signal, $listener);
    }`

What is the problem ?

**Comment by walkor** [comment]
Try to remove react/event-loop by command composer remove react/event-loop`
