### ISSUE TITLE
Doesn't work after certificate update

### ISSUE THREAD

**Issue by webeffected** [walkor/Workerman#559]
Hello again!

After [last time we met](https://github.com/walkor/Workerman/issues/541) everything was working fine until the day my certificate had to update automatically through Let's Encrypt. I have wildcard certificate, which means I have to make changes to dns records every update. So I forgot to do so and my website went down for a few days until I noticed that.

After I changed everything, including path to new certificate in my websocket server.php, website started to function normally, but now I can't connect to websocket.

Everytime a client tries to connect, workerman throws this error:

```
SSL handshake error: stream_socket_enable_crypto(): Unable to set local cert chain file 'ssl/cert.pem'; 
Check that your cafile/capath settings include details of your certificate and its issuer
```

I double checked certificate - it includes the last one (I've removed old).

We are using rocketeer to deploy to our server and one of it's tasks include this command:

```
$this->run("sudo ln /var/www/httpd-cert/user/site.com_le2.crtca /var/www/user/data/www/site/current/func/websocket/ssl/cert.pem");
$this->run("sudo ln /var/www/httpd-cert/user/site.com_le2.key /var/www/user/data/www/site/current/func/websocket/ssl/cert.key");
```

We use it to make a link to cert in a place, which is accessible for workerman. It was working fine with old certificate.

The only thing I've changed in this command was old filenames to new:
site.com_le1.crtca >>> site.com_le2.crtca
site.com_le1.key >>> site.com_le2.key

Website is working through Cloudflare and sometimes it throws this error:

![изображение](https://user-images.githubusercontent.com/15102895/92094894-a204cb80-eddd-11ea-8b46-eb3629ba8cf8.png)

Sometimes it happened with old certificate and never influenced websocket connection, at least I've never noticed. After I press F5 everything is working again. I have Full (strict) SSL option enabled on Cloudflare, which encrypts end-to-end, but requires a trusted CA or Cloudflare Origin CA certificate on the server.

Any suggestions?

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/92096646-b78fea80-ee09-11ea-800e-8f335ff5215d.png)

It is certificate files permissions issue?

**Comment by webeffected** [comment]
Yes, thank you! I also just tried it and fixed the problem, came back to write an answer and you've already answered too ))

**Comment by walkor** [comment]
ok.
