### ISSUE TITLE
PHP-7.0.4 运行workerman报错。libevent 无法使用

### ISSUE THREAD

**Issue by jackyxie** [walkor/Workerman#56]
![pic](https://cloud.githubusercontent.com/assets/3347704/13628406/c8eb9f7c-e60c-11e5-8e40-1b88c4c41c83.jpg)

**Comment by walkor** [comment]
已经修复，重新更新再试下

**Comment by jackyxie** [comment]
我是使用这种方式安装的哦：
composer require workerman/workerman

**Comment by jackyxie** [comment]
最新的release可以用吗？

**Comment by walkor** [comment]
在master主分支上，测试没问题才放到release.

**Comment by jackyxie** [comment]
好的，我用master的试试
