### ISSUE TITLE
 How do I integrate another service?

### ISSUE THREAD

**Issue by vladus06** [walkor/Workerman#562]
Hi
does not work $ws_worker->onConnect 
my function dump_event only work
how can I combine both services $ws_worker = new Worker and $manager = new AGI_AsteriskManager();?
AGI_AsteriskManager() - I use to receive data from Asterisk.
ty

```
require_once 'vendor/autoload.php';
include('/var/lib/asterisk/agi-bin/phpagi.php');

use Workerman\Worker;

$users = [];
$ws_worker = new Worker("websocket://0.0.0.0:8010");
$ws_worker->onWorkerStart = function() use (&$users)
        {
                $manager = new AGI_AsteriskManager();
                $manager->connect();
                $manager->add_event_handler('*', 'dump_events');
                $manager->wait_response();
                $manager->disconnect();
        };

function dump_events($ecode,$data) 
	{
          var_dump($data);
	};

$ws_worker->onConnect = function($connection) use (&$users)
{
        $connection->onWebSocketConnect = function($connection) use (&$users)
        {
	     $users[$_GET['user']] = $connection;
        };
};

$ws_worker->onClose = function($connection) use(&$users)
	{
	    $user = array_search($connection, $users);
	    unset($users[$user]);
	};

Worker::runAll();

```
script run result

Workerman[./server_test.php] start in DEBUG mode
------------------------------------------- WORKERMAN --------------------------------------------
Workerman version:3.5.19          PHP version:7.3.21
-------------------------------------------- WORKERS ---------------------------------------------
proto   user            worker          listen                      processes    status
tcp     root            none            websocket://0.0.0.0:8010    1             [OK]
--------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
object(stdClass)#12 (5) {
  ["Event"]=>
  string(11) "FullyBooted"
  ["Privilege"]=>
  string(10) "system,all"
  ["Uptime"]=>
  string(7) "1619067"
  ["LastReload"]=>
  string(6) "275143"
  ["Status"]=>
  string(12) "Fully Booted"
}

Workerman[./server_test.php] connections
--------------------------------------------------------------------- WORKERMAN CONNECTION STATUS --------------------------------------------------------------------------------
PID      Worker          CID       Trans   Protocol        ipv4   ipv6   Recv-Q       Send-Q       Bytes-R      Bytes-W       Status         Local Address          Foreign Address

* no connections

**Comment by walkor** [comment]
Because of AgI_Asteriskmanager blocking the process and the process unable to handle connection events.
Move AgI_Asteriskmanager to another process($manager) and when the process receive data from Asterisk then curl post it to the ws_worker with http protocol. Here is an example.
```php
$users = [];
$manager = new Worker();
$manager->onWorkerStart = function() use (&$users)
        {
                $manager = new AGI_AsteriskManager();
                $manager->connect();
                $manager->add_event_handler('*', 'dump_events');
                $manager->wait_response();
                $manager->disconnect();
        };
function dump_events($ecode,$data) 
{
    $ch = curl_init ();
    $post_data = ['ecode' => $ecode, 'data' => $data];
    curl_setopt ( $ch, CURLOPT_URL, 'http://127.0.0.1:8011');
    curl_setopt ( $ch, CURLOPT_POST, 1 );
    curl_setopt ( $ch, CURLOPT_HEADER, 0 );
    curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, 1 );
    curl_setopt ( $ch, CURLOPT_POSTFIELDS, $post_data );
    curl_setopt ($ch, CURLOPT_HTTPHEADER, array("Expect:"));
    $return = curl_exec ( $ch );
    curl_close ( $ch );
};
$ws_worker = new Worker("websocket://0.0.0.0:8010");
$ws_worker->onWorkerStart = function() use (&$users)
 {
        // Here an HTTP listener is enabled in the current process to receive data from $manager process.
        $http = new Worker('http://0.0.0.0:8011');
        $http->onMessage = function ($connection, $request) {
               $connection->send('ok');
               // Here get AGI_AsteriskManager ecode and data
               var_dump($request->post('ecode'), $request->post('data'));
        };
        $http->listen();
 };

$ws_worker->onConnect = function($connection) use (&$users)
{
        $connection->onWebSocketConnect = function($connection) use (&$users)
        {
	     $users[$_GET['user']] = $connection;
        };
};

$ws_worker->onClose = function($connection) use(&$users)
	{
	    $user = array_search($connection, $users);
	    unset($users[$user]);
	};

Worker::runAll();
```
