### ISSUE TITLE
Redis 

### ISSUE THREAD

**Issue by codeezy** [walkor/Workerman#564]
Hi, i try to build rate limit with _phpredis_ 

i need to know if i can declare a Redis class with **onWorkerStart** and use redis method list **onMessage**
It's work but tell me this initialization is сorrect or is it IO blocking? This is only needed to verify the key at redis storage, (not pubsub)

```
use Workerman\Worker;

require_once __DIR__ . '/vendor/autoload.php';

$http_worker = new Worker('http://0.0.0.0:2345');
$http_worker->count = 4;

$http_worker->onWorkerStart = function($http_worker) {
    global $redis;
    $redis = new \Redis();
    $redis->connect('127.0.0.1', 6379);
};

$http_worker->onMessage = function($connection, $request) {
    global $redis;

    // i need to use this Lists

    // $redis->lIndex()
    // $redis->lPush()
    // $redis->ltrim()
    // $redis->lLen()
    // $redis->expire()
    // $redis->exec()

    $connection->send("Hello World");
};

Worker::runAll();
```

**Comment by walkor** [comment]
This initialization is сorrect.
phpredis is IO blocking library but you but don't worry, redis is fast enough.

**Comment by codeezy** [comment]
Thanks!
Is it acceptable to add a Mysql connection to **onWorkerStart** and how will performance suffer while using `Redis` and  `workerman/mysql` connections? 

```
$http_worker->onWorkerStart = function($http_worker) {
    global $redis;
    global $mysql;

    $redis = new \Redis();
    $redis->connect('127.0.0.1', 6379);

    $mysql = new Workerman\MySQL\Connection($mysql_host, $mysql_port, $user, $password, $db_bname);
};
```

**Comment by walkor** [comment]
It is recommended to add MySQL connection in **onWorkerStart**.

I can't tell you how much influence the performance of redis and mysql. This is related to many factors, and the specific impact needs to be tested by yourself.

If redis and MySQL are used, it is recommended that the number of processes be set to 2-4 times of the CPU.

**Comment by codeezy** [comment]
Thank you!

**Comment by lenninpadilla** [comment]
Hello, guys. I am trying to use the same project (phpredis) but i am doing the same making redis connection in onWorkerStart like this:

`try {
        global $redis;

        $redis = new Redis();
        $redis->pconnect('IP', 6379);
        //$redis->setOption(Redis::OPT_READ_TIMEOUT, -1);
        $redis->subscribe(['publisher1'], function($redis, $chan, $msg) {
            echo "get $msg FROM $chan\n";
        });
    } catch (Exception $e) {
        echo "Error message: " . $e->getMessage();
    }`

But i am planning to use pub/sub, I am receiving messages from redis using pub/sub but new incoming connections to the websocket aren't able to finish the handshake. Also i tried the other package that walkor offers for redis and it works as expected like this:

`$worker->onWorkerStart = function() {
    global $redis;
    $redis = new Client('redis://IP:6379');
    $redis->subscribe(['publisher1'], function ($channel, $message) {
        echo "$channel, $message" . PHP_EOL;
    });
};`

Any help related to this topic is welcome, thanks in advance.

**Comment by lenninpadilla** [comment]
Also I can't use that package because of this:
https://github.com/walkor/redis/issues/3

And not sure if i can use rawCommand

**Comment by walkor** [comment]
I think you can use `workerman/redis` to subscribe and other command use phpredis.

**Comment by rentstack** [comment]
> I think you can use `workerman/redis` to subscribe and other command use phpredis.

Can you give an example the correct code of concurrent use phpredis +  workerman/redis to pub/sub?

**Comment by walkor** [comment]
```php
$worker->onWorkerStart = function() {
    global $redis;
    $redis = new Redis();
    $redis->pconnect('IP', 6379);

    $redis_ subscribe= new Client('redis://IP:6379');
    $redis_subscribe->subscribe(['publisher1'], function ($channel, $message) {
        echo "$channel, $message" . PHP_EOL;
    });
};
```

**Comment by rentstack** [comment]
Thanks! can I add the same way to onWorkerStart  `react/mysql` or it will be a heavy load on the workernam?
