### ISSUE TITLE
How to compatible with amphp coroutine

### ISSUE THREAD

**Issue by xpader** [walkor/Workerman#569]
Amphp use \Amp\Loop::run(callback) to start event loop, and all coroutine running in the callbacks, but Loop::run() will block the process.

For example I want to use Amp's Coroutine in Workerman's onMessage, message 1 run Loop::delay(), message two will block until delay finished.

How can I let workerman use Amp's event loop, may be they can compatible?

**Comment by xpader** [comment]
... I found some way to do that, that is replace workerman event loop with this project: https://github.com/CismonX/Workerman-Amp..
It seems compatible with latest Workerman.

**Comment by walkor** [comment]
👍

**Comment by PNixx** [comment]
Not working with 4.0 version and amp repository was archived...

**Comment by xpader** [comment]
@PNixx It is compatible with Workerman 4, the problem is composer.json config is deprcated. Just copy file to use is OK.

**Comment by xpader** [comment]
I have use this to create a coroutine framework: https://github.com/wind-framework/wind-framework
