### ISSUE TITLE
如何实现多个worker之间的资源共享？比如文件描述符和socket连接或者文件?

### ISSUE THREAD

**Issue by joostshao** [walkor/Workerman#57]
如何实现多个worker之间的资源共享？比如文件描述符和socket连接或者文件?

**Comment by walkor** [comment]
在主进程中创建的资源子进程默认继承共享。另外通过unix socket配合socket_sendmsg也能实现进程间resource描述符传递共享。
但是有些资源共享会有问题，比如数据库连接，mysql服务端返回数据理论上其它共享的进程上也有能读到，导致mysql连接异常。
尽量不要资源共享，最好是每个worker进程自己创建独享。

**Comment by joostshao** [comment]
多谢，资源隔离，自己管理
