### ISSUE TITLE
Does this look more concise ？

### ISSUE THREAD

**Issue by twomiao** [walkor/Workerman#570]
**The signalHandler method in the Worker class, the original code:**
  if($signal === \SIGQUIT) {
  &nbsp; &nbsp;static::$_gracefulStop = true;
  } else {
   &nbsp; &nbsp;static::$_gracefulStop = false;
  }

**More concise code:**
static::$_gracefulStop = ($signal === \SIGQUIT);
This code looks more concise and beautiful! ! !

**Comment by walkor** [comment]
Yes, you are right.
