### ISSUE TITLE
Does this look better?

### ISSUE THREAD

**Issue by twomiao** [walkor/Workerman#571]
**The Worker file is in line 2005, the original code for unit conversion:**
&nbsp;$bytes_format = function ($bytes) {
&nbsp;&nbsp;if ($bytes > 1024 * 1024 * 1024 * 1024) {
&nbsp;&nbsp;&nbsp;&nbsp;return round($bytes / (1024 * 1024 * 1024 * 1024), 1) . "TB";
&nbsp;&nbsp;}
&nbsp;&nbsp;if ($bytes > 1024 * 1024 * 1024) {
&nbsp;&nbsp;&nbsp;&nbsp;return round($bytes / (1024 * 1024 * 1024), 1) . "GB";
&nbsp;&nbsp;}
&nbsp;&nbsp;if ($bytes > 1024 * 1024) {
&nbsp;&nbsp;&nbsp;&nbsp;return round($bytes / (1024 * 1024), 1) . "MB";
&nbsp;&nbsp;}
&nbsp;&nbsp;if ($bytes > 1024) {
&nbsp;&nbsp;&nbsp;&nbsp;return round($bytes / (1024), 1) . "KB";
&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;return $bytes . "B";
        };

**More appropriate code:**
$bytes_format = function ($bytes) {
&nbsp;&nbsp;$dataUnits = ['B', 'KB', 'MB', 'GB', 'TB', 'PB'];
&nbsp;&nbsp;$index = 0;
&nbsp;&nbsp;while (($bytes = $bytes / 1024) > 1024) {
&nbsp;&nbsp;&nbsp;if ($index === 0) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$index = 1;
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;++$index;
&nbsp;&nbsp;}
&nbsp;return round($bytes, 1) . "{$dataUnits[$index]}";
};

**Comment by walkor** [comment]
I think each has its own advantages. Your code looks compact but not easy to understand.

**Comment by twomiao** [comment]
If you add more data units, **your code needs to copy one line and keep accumulating the number of lines of code.**
I have added more data units here, **just the array ['B','KB','MB','GB','TB','PB','EB', and more];**

**Comment by walkor** [comment]
TB is enough for the size of data transmitted by a single connection.
