### ISSUE TITLE
ReusePort is still true even using unix socket transport

### ISSUE THREAD

**Issue by bohanyang** [walkor/Workerman#572]
Related to #502

https://github.com/walkor/Workerman/blob/49708bb40e16cccb91aa1ffa841e64a34677a264/Worker.php#L2216
This condition will always return true since `$this->transport` is tcp by default.
Passing e.g. `unix:///tmp.sock` to the constructor won't change `$this->transport`.

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/blob/49708bb40e16cccb91aa1ffa841e64a34677a264/Worker.php#L2325

`$this->protocol` changed to `unix` here when use `unix:///tmp.sock` as constructor.

**Comment by bohanyang** [comment]
But this line of code is in the `parseSocketAddress` method, which is not being called before **_the logic_** of setting ReusePort in the constructor.

When the `Worker` is instanciated, even if the constructor argument `socket_name` is `unix:///tmp.sock`, it'll not be parsed by `parseSocketAddress` so `$this->transport` will be the default value `tcp`, thus ReusePort is set to true.

In the `listen` method, even if `parseSocketAddress` method is called and `$this->transport` is set to `unix`, since **_the logic_**  exists in the constructor, ReusePort stays true.

It's easy to produce this issue:
```php
<?php
use Workerman\Worker;

require __DIR__ . '/vendor/autoload.php';

$worker = new Worker('unix:///var/run/dcs/php/workerman2.sock');
var_dump($worker->reusePort); // bool(true)
```
Run first time: OK
```php
$worker = new Worker('unix:///var/run/dcs/php/workerman2.sock');
Worker::runAll();
```
```sh
php 2.php start
```
Ctrl-C to stop the worker, you'll see the unix socket file is left on the disk.
When run the second time,
```
Fatal error: Uncaught Exception in /var/www/workerman/vendor/workerman/workerman/Worker.php:2250
Stack trace:
#0 /var/www/workerman/vendor/workerman/workerman/Worker.php(1531): Workerman\Worker->listen()
#1 /var/www/workerman/vendor/workerman/workerman/Worker.php(1378): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#2 /var/www/workerman/vendor/workerman/workerman/Worker.php(1352): Workerman\Worker::forkWorkersForLinux()
#3 /var/www/workerman/vendor/workerman/workerman/Worker.php(1685): Workerman\Worker::forkWorkers()
#4 /var/www/workerman/vendor/workerman/workerman/Worker.php(1634): Workerman\Worker::monitorWorkersForLinux()
#5 /var/www/workerman/vendor/workerman/workerman/Worker.php(544): Workerman\Worker::monitorWorkers()
#6 /var/www/workerman/2.php(7): Workerman\Worker::runAll()
#7 {main}
  thrown in /var/www/workerman/vendor/workerman/workerman/Worker.php on line 2250
worker[none:1480] exit with status 65280
stream_socket_server(): unable to connect to unix:///var/run/dcs/php/workerman2.sock (Unknown error) in file /var/www/workerman/vendor/workerman/workerman/Worker.php on line 2248
```

If ReusePort is off, the unix socket file will be deleted after worker stops.

**Comment by walkor** [comment]
Fixed. Thank you so much. 👍
