### ISSUE TITLE
Trouble with MySQL

### ISSUE THREAD

**Issue by Bogdan1111111** [walkor/Workerman#575]
My worker work with MySQL. On debbug mode all work right, but in daemon mode sql-queries not work.
How fix this problem and do working code?

**Comment by walkor** [comment]
Do not initialize the MySQL connection directly in the startup file. Put the MySQL connection initialization in onWorkerStart.

Wrong way.
```
$db = new Db(....);
$worker = new Worker(...);
```

The right way
```php
$worker = new Worker(...);
$worker->onWorkerStart = function(){
    $db = new Db(....);
};
```

**Comment by Bogdan1111111** [comment]
Ok, how i can get variable $db in onConnect and other methods?

**Comment by walkor** [comment]
There are many ways to do that. For example.
```php
$worker = new Worker(...);
$worker->onWorkerStart = function(){
    global $db;
    $db = new Db(....);
};

$worker->onConnect = function(){
    global $db;
    $db->select(...);
};
```

**Comment by Bogdan1111111** [comment]
thx for support, all are worked
