### ISSUE TITLE
Trouble with MySQL 2

### ISSUE THREAD

**Issue by Bogdan1111111** [walkor/Workerman#576]
My worker work with MySQL. On debbug mode all work right, but in daemon mode sql-queries not work.
How fix this problem and do working code? Sorry i know that is double issue, but i running old version of code in debud mode.
I'm rewrite my code as you ask but it stop working and in gebug mode. ws client connecting with server

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/issues/575
It looks like a duplicate issue.
If you still have questions, please continue to post your questions in the above link. Do not repeatedly create similar duplicate issues.
In addition, we can't confirm what problem you are talking about through your description above. If you want help, you need to provide a more detailed description, including the goal you want to achieve, the results of the current performance (screenshots), specific code (including server and client), screenshot of startup interface, and screenshot of error reporting (if any).
