### ISSUE TITLE
PHP 8 and daemon mode

### ISSUE THREAD

**Issue by rogit** [walkor/Workerman#577]
PHP 8.0.0 RC2
When trying to start in daemon mode:

Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, null given in /var/www/Workerman/Worker.php:1253
Stack trace:
#0 /var/www/Workerman/Worker.php(1253): fclose()
#1 /var/www/Workerman/Worker.php(1537): Workerman\Worker::resetStd()
#2 /var/www/Workerman/Worker.php(1381): Workerman\Worker::forkOneWorkerForLinux()
#3 /var/www/Workerman/Worker.php(1355): Workerman\Worker::forkWorkersForLinux()
#4 /var/www/Workerman/Worker.php(542): Workerman\Worker::forkWorkers()
#5 /var/www/wm.php(52): Workerman\Worker::runAll()
#6 {main}
  thrown in /var/www/Workerman/Worker.php on line 1253

In non-daemon mode it is ok.

**Comment by walkor** [comment]
Fixed and thank you for your post.

**Comment by henggedaren** [comment]
php 8.0.16
thinkphp 6.0
gateway 3.0.22
php think worker:gateway -d 时仍然报这个错误。

请问该怎么解决。

**Comment by walkor** [comment]
升级workerman
