### ISSUE TITLE
php7 Timer定时器使用异常worker[none:28567] exit with status 139

### ISSUE THREAD

**Issue by jackyxie** [walkor/Workerman#58]
这种情况如何排查问题？
![timer](https://cloud.githubusercontent.com/assets/3347704/13634517/fc809562-e630-11e5-9910-1b3e1b55884d.jpg)

**Comment by walkor** [comment]
139是进程收到SIGSEGV信号推出了，应该是Libevnet扩展coredump了。
PHP7的Libevent扩展还没stable，等等再用吧。
或者用ev扩展试下（注意php7版本的ev也没stable）

**Comment by jackyxie** [comment]
那目前就暂时用不了libevent咯？

**Comment by walkor** [comment]
PHP7 目前还暂时用不了libevent。小于PHP7的版本可以用

**Comment by jackyxie** [comment]
哦，好的。忘了是 reusePort才需要php7

**Comment by joostshao** [comment]
https://github.com/gophp7/gophp7-ext/wiki/extensions-catalog
为什么不能呢?

**Comment by joelhy** [comment]
PHP7用户可以用[Event](https://pecl.php.net/package/event)扩展，不过需要 PHP 5.4+。
[libevent](https://pecl.php.net/package/libevent)扩展，最后更新时间为2013年5月22号，不可能有考虑PHP 7兼容性，不推荐在 PHP 7上使用。
或者使用[ev](https://pecl.php.net/package/ev)扩展，新版本也有考虑 PHP 7兼容性。

@walkor  建议`Workerman\Events`里增加对 [Event](http://docs.php.net/event) 扩展的支持，并文档中优先推荐使用这个扩展。

**Comment by joelhy** [comment]
@walkor  如果启用 Event 扩展支持，示例程序代码Applications/*/Event.php：[workerman-chat](https://github.com/walkor/workerman-chat/blob/master/Applications/Chat/Event.php)，[workerman-todpole](https://github.com/walkor/workerman-todpole/blob/master/Applications/Todpole/Event.php)的 Event 类名需要更改成其他名称，或者加上 namespace 以防命名冲突。

**Comment by walkor** [comment]
感谢 @joelhy 的建议
workerman已经支持了[ev](https://pecl.php.net/package/ev)扩展。
[Event](http://docs.php.net/event) 扩展也会支持，具体时间还没定。

GatewayWorker框架已经支持自定义Event.php的类名，可以避免冲突，但是默认类名仍然是Event，如果要支持Event扩展，还是要兼容下。

**Comment by lpadilla-nowoptics** [comment]
Is this a valid issue yet? I am facing same similar issue with php 8.2 and workerman 4.1, apache version is: 2.4.52
