### ISSUE TITLE
Set Header for Http Response

### ISSUE THREAD

**Issue by yuskamal** [walkor/Workerman#581]
Dud,
Actualy I want to send file to Client :

              $filedl = file_get_contents($filenya);
              $file_size = filesize($filenya);
              Http::header("Content-type: text/plain");
              Http::header("Accept-Ranges: bytes");
              Http::header("Content-Disposition: attachment; filename=" .$reqnya["namafile"] . ".txt");
              $connection->send($filedl);

But A got the Error ...
Error: Call to undefined method Workerman\Protocols\Http::header() 

Thx

**Comment by walkor** [comment]
Here is an example.
```php
use Workerman\Worker;
use Workerman\Protocols\Http\Response;
require_once __DIR__ . '/vendor/autoload.php';

$worker = new Worker('http://0.0.0.0:8080');

$worker->onMessage = function($connection, $request)
{
    $file = '/your/path/of/file';
    $response = (new Response())->withFile($file)->withHeaders([
        'Accept-Ranges'         => 'bytes',
       'Content-Disposition'  =>'attachment; filename=somename.txt'
    ]);
    $connection->send($response);
};

Worker::runAll();
```

**Comment by yuskamal** [comment]
OK, done many thanks
