### ISSUE TITLE
PHPSESSID/Cookies in the Workerman

### ISSUE THREAD

**Issue by sites21** [walkor/Workerman#586]
How can I get cookies (for example: PHPSESSID) for defination and authorization my user in my web site on the server? I use websocket connection, not a HTTP. Thank you.

**Comment by walkor** [comment]
For example.
```php
$worker = new Worker('websocket://0.0.0.0:1234');
$worker->onWebSocketConnect = function ($connection) {
    $connection->cookies = $_COOKIE;
};
$worker->onMessage = function($connection, $data) {
    var_dump($connection->cookies);
};
```

**Comment by sites21** [comment]
Empty response like []
In my web browser I can clearly get cookies via
`var_dump($_COOKIES);`

But on the server i can get only empty list of cookies.

**Comment by walkor** [comment]
Are you sure you added a cookie to the websocket domain name?

**Comment by xpader** [comment]
Use $_COOKIE in websocket server has no problem?? $_COOKIE is super global variable, and there's no context in workerman asynchronous, the data cross every other connections.

**Comment by walkor** [comment]
Workerman will assign $_COOKIE a value in  the onWebsocketConnect callback.

**Comment by sites21** [comment]
Thank you, guys. But the problem was in proxy. I didn't do that.
Similar issue: https://github.com/walkor/Workerman/issues/384

**Comment by sites21** [comment]
Why $_SESSION empty to?

**Comment by walkor** [comment]
Workerman's websocket service does not support $_SESSION.

**Comment by teks1967** [comment]
hi

$_COOKIE['user']=12345 or $_GET['user']=12345

$ws_worker->onConnect = function($connection) use (&$users){
 $connection->onWebSocketConnect = function($connection) use (&$users){

$users[$_COOKIE['user']]= $connection;
OR
$users[$_GET['user']]= $connection;

installed and I get an empty request, what should I do?
I'll be very thankful!

**Comment by teks1967** [comment]
Notice: Undefined index: userk in 

Help!!!

**Comment by teks1967** [comment]
> Workerman's websocket service does not support $_SESSION.

i also tried sessions
Notice 

although test.php sees $_COOKIE['user']=12345

Help! plis
