### ISSUE TITLE
SSL and DAEMON mode doesn't work

### ISSUE THREAD

**Issue by sites21** [walkor/Workerman#590]
I use:
- Nginx (proxy)
- PHP 7.2
- SSL

I'm glad when I start Workerman as usual mode, because everything work. But when I try to add "-d" to launch Daemon method, I get an error:
**Error during WebSocket handshake: Unexpected response code: 502**

And connection finished.

Nginx error log give me this errors:
`upstream prematurely closed connection while reading response header from upstream, client: **.***.***.***, server: site.ru, request: "GET /ws HTTP/1.1", upstream: "http://***.**.**.*:3000/", host: "site.ru"`

**Comment by walkor** [comment]
Do you use MySQL or redis or other storage?

**Comment by sites21** [comment]
MariaDB

**Comment by sites21** [comment]
Connection finished in the browser, not in websocket

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/issues/575
I think this link will help you.

**Comment by sites21** [comment]
Wow. It works, thank you
