### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state. ERROR

### ISSUE THREAD

**Issue by sites21** [walkor/Workerman#592]
I'm faced with new error a few hours later. If I open my website, then connection will open. But If I switch tabs in my browser after 5 minutes, I'll get this error **WebSocket is already in CLOSING or CLOSED state** in my webbrowser's console and lose connection 
I'm surfed the Internet and found a solution, that I should set PingTimeOut option on a client side. But how can I do this...
Also I seen Timer in the Workerman, but I'm doubt about relating this to my issue, because no information.

Similar Issue https://github.com/socketio/socket.io/issues/3259

**Comment by walkor** [comment]
Some gateway, routing nodes, such as firewalls will close the TCP connection that does not communicate for a long time(for example, 60 seconds), which leads to application communication failure. So we need to add a heartbeat to the application layer to keep the connection from being disconnected. In JS, `setInterval()` can be used to send some data to the server regularly through the connection, such as the following. 
```js
ws = new WebSocket('ws://example.com');
ws.onopen = function () {
    var t = setInterval(function(){
        if (ws.readyState != 1) {
            clearInterval(t);
            return;
        }
        ws.send('{type:"ping"}');
}, 55000);};
```
When the server receives heartbeat data, it can ignore it and do nothing. Heartbeat interval less than 60 seconds is better, such as 55 seconds.

**Comment by sites21** [comment]
May be It will help. But If I open my website(websocket) in the same browser with two similar tabs and start clicking, then I'll get this error too. I changed interval for a 5 seconds and it didn't affect. **WebSocket is already in CLOSING or CLOSED state**

**Comment by walkor** [comment]
**WebSocket is already in CLOSING or CLOSED state** means that the connection has been disconnected and data cannot be sent through this connection. In addition to the lack of heartbeat and being disconnected by the network node, it is also possible that the client or server called the close method, and there may be a bug in the business code.

**Comment by sites21** [comment]
The problem is not with connection already. The problem with multiple tabs. When 1 user open 15 tabs, then connection will lose. I found a answer on stackoverflow about this issue. Link https://stackoverflow.com/questions/59176767/socket-io-with-multiple-tabs-not-working-and-when-refreshing-the-page

I check connection variable and found out, that workerId has notunique id. And it possible affected on this error.

**Comment by walkor** [comment]
Is the problem solved?

**Comment by sites21** [comment]
Yes, the problem was with my code

**Comment by EbiFeke** [comment]
please my webterm shows disconnected...terminado and goes on to show websocket closed, how do i fix this?

**Comment by sites21** [comment]
> please my webterm shows disconnected...terminado and goes on to show websocket closed, how do i fix this?

1. Get sample from repository
2. Don't use SESSION
3. Check SQL queries
4. Check logs errors

**Comment by Ambyzhale** [comment]
how may you help me who has just started a software engineering course and i still don't know how to write a "c" or "js" script

**Comment by Engedasew-Haile** [comment]
unable access git hub resources,. its said disconnected or closed 
[WebSocket is already in CLOSING or CLOSED state.]       
[WebSocket is already in CLOSING or CLOSED state.]

**Comment by Danny-coursera** [comment]
how do i get back to where i stopped when the web socket closes automatically?
