### ISSUE TITLE
PM2 for managing Workerman?

### ISSUE THREAD

**Issue by Hadryan** [walkor/Workerman#597]
Hi there,

Is it possible to use [PM2 ](https://pm2.keymetrics.io/)for managing Workerman on server restart (for example)

**Comment by walkor** [comment]
It looks ok, but I haven't used it.

**Comment by Hadryan** [comment]
Then would you please be so kind and let me know _weithout other programs_, how you manage Workerman automatically restart after server restart?

**Comment by walkor** [comment]
Edit `/etc/rc.local` like this.

```
ulimit -HSn 102400
/usr/bin/env php /your/path/start.php start -d

exit 0
