### ISSUE TITLE
Bug: overwrite header value

### ISSUE THREAD

**Issue by alexpts** [walkor/Workerman#600]
https://tools.ietf.org/html/rfc2616#page-32

> Multiple message-header fields with the same field-name MAY be
>    present in a message if and only if the entire field-value for that
>    header field is defined as a comma-separated list [i.e., #(values)].
>    It MUST be possible to combine the multiple header fields into one
>    "field-name: field-value" pair, without changing the semantics of the
>    message, by appending each subsequent field-value to the first, each
>    separated by a comma. The order in which header fields with the same
>    field-name are received is therefore significant to the
>    interpretation of the combined field value, and thus a proxy MUST NOT
>    change the order of these field values when a message is forwarded.

```php
foreach ($head_data as $content) {
    if (false !== \strpos($content, ':')) {
        list($key, $value) = \explode(':', $content, 2);
        $this->_data['headers'][\strtolower($key)] = \ltrim($value);
    } else {
        $this->_data['headers'][\strtolower($content)] = '';
    }
}
```

**Comment by xpader** [comment]
Very good for this.
