### ISSUE TITLE
Can workerman support Unix Domain Socket protocol?

### ISSUE THREAD

**Issue by xpader** [walkor/Workerman#602]
Unix domain socket is a good way to implements local process communication instead of Channel, or be a backend of nginx.

**Comment by xpader** [comment]
Oh, I see Workerman is already supported Unix Domain, And there's a question is does unix domain need a wrap protocol? like unix://frame://.., or unix://text:// ?

**Comment by walkor** [comment]
Use wrap protocol like this for unix domain socket.
```php
$worker = new Worker('unix:///tmp/my_file');
$worker->protocol = 'Workerman\\Protocols\\Http';
$worker->onMessage = .....
```
