### ISSUE TITLE
Timer per request

### ISSUE THREAD

**Issue by yuskamal** [walkor/Workerman#603]
Is it problematic if each http request has its own timer ?
Like this ?

$http_worker->onMessage = function ($connection, $request)
.
.
.
$connection->timerid = Timer::add(1, function () use($connection,$http_worker,$key,$post1)
                {
                   $interval = time() - $http_worker->arrclient[$key]["timeout"];
                   if ($http_worker->arrclient[$key]["status"] == 3) {
                       Timer::del($connection->timerid);
                       $http_worker->arrclient[$key]["status"] = 1;
                       echo "Get Response From Converter\n";
                       $connection->send(json_encode($post1));
.
.
.

**Comment by walkor** [comment]
Creating timers constantly and not deleting it can cause memory leaks.
From the code point of view, `$connection->timerid` will be covered, resulting in timer can not be deleted correctly.
Each request for a timer will make it difficult for you to delete them correctly. It is recommended to use a global timer to handle these timer tasks.
