### ISSUE TITLE
Xdebug support

### ISSUE THREAD

**Issue by ww9** [walkor/Workerman#606]
Hi! I'm evaluating Workerman for a mid-size HTTP web server project for short requests (CRUD application).

I read all documentation on the Chinese docs translated to english. It works quite well and it's easy to understand.

One question I have is, can we use Xdebug to debug workers? I read #361  but I'm not sure.

I tried using XDebug on Windows 10 with Workerman and it works but only outside worker code:

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;
$http_worker = new Worker('http://0.0.0.0:2345');
$http_worker->count = 1; // breakpoint here works
$http_worker->onMessage = function ($connection, $request) {
    $connection->send("Hello World"); // breakpoint here doesn't work
};
Worker::runAll();
```

Is it supposed to work?
Is there some architecture change I can make to have Xdebug work inside worker code?
Some kind of HTTP redirection?

Thank you for Workerman! It looks amazing, elegant and simple!

**Comment by walkor** [comment]
Hi ww9.
According to my opinion, Workerman not support Xdebug.
If anyone succeeds, please share it.

**Comment by ww9** [comment]
Thank you. I'm still going to use Workerman.
I willl focus on unit tests in my project so I need to debug less.

Thank you for creating and sharing Workerman.

I hope to donate if the project is successful.

**Comment by harish2704** [comment]
@walkor : Hi, Thank you for creating this project. 

I tried using Xdebug with Workerman and it worked as expected without any issue. 
Ie, I put a break-point in the beginning of `onMessage` function and every new request was hitting that break point in the Vscode IDE. 

May I know why you said that Workerman may not support Xdebug?

**Comment by walkor** [comment]
@harish2704 Thank you for your post.
I see there are some posts here about workerman/webman and xdebug, although they are in Chinese, they might be helpful to everyone.
https://www.workerman.net/a/1653
https://www.workerman.net/a/1376
https://www.workerman.net/a/1484
https://www.workerman.net/a/1404
