### ISSUE TITLE
Documentation page http://wiki.workerman.net/ is not working

### ISSUE THREAD

**Issue by FelipoAntonoff** [walkor/Workerman#608]
Hello, the documentation page http://wiki.workerman.net/ is not working, go to the Welcome to nginx page.

Would you have any other documentation page in English or any language other than Chinese?

Edit: I found this Documents in Chinese: http://doc.workerman.net/

**Comment by walkor** [comment]
Hi FelipoAntonoff.
https://github.com/walkor/workerman-manual/blob/master/english/src/SUMMARY.md
Here is documentation page in English.
