### ISSUE TITLE
libevent installation parameters

### ISSUE THREAD

**Issue by ww9** [walkor/Workerman#610]
On Ubuntu 20.04 and PHP 8.0.3 I'm installing libevent with:

sudo apt install libevent-dev
sudo pecl install event

During installation some questions are asked:

```
Enable internal debugging in Event [no] : no
Enable sockets support in Event [yes] : yes
libevent installation prefix [/usr] : /usr
Include libevent's pthreads library and enable thread safety support in Event [no] : yes
Include libevent protocol-specific functionality support including HTTP, DNS, and RPC [yes] : yes
Include libevent OpenSSL support [yes] : yes
PHP Namespace for all Event classes [no] : yes
openssl installation prefix [no] : no
```

What should I chose there? Specially this: "pthreads library and enable thread safety support in Event".

**Comment by walkor** [comment]
Include libevent OpenSSL support [yes] : no&nbsp;others just press enter.

**Comment by ww9** [comment]
Thanks! This is how I got libevent working on Ubuntu 20.04 so others can see:

- sudo apt install php8.0-dev gcc make libevent-dev
- sudo update-alternatives --set phpize /usr/bin/phpize8.0
- sudo update-alternatives --set php-config /usr/bin/php-config8.0
- sudo pecl install event
   - answer: Include libevent OpenSSL support [yes] : no
- echo 'extension=event.so' | sudo tee /etc/php/8.0/mods-available/event.ini
- sudo phpenmod -v 8.0 event
- sudo mv /etc/php/8.0/cli/conf.d/20-event.ini /etc/php/8.0/cli/conf.d/30-event.ini
- php -i | grep event

The last command should print: 
```
/etc/php/8.0/cli/conf.d/30-event.ini,
event
libevent2 headers version => 2.1.11-stable
```

Note that I had to change the order of loading the extension with the command above `sudo mv /etc/php/8...` otherwise it would give me this error: "undefined symbol: socket_ce"

**Comment by 2ik** [comment]
PHP 8.1.0beta3
I had a warning:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'event.so' (tried: /usr/lib/php/20201009/event.so (/usr/lib/php/20201009/event.so: undefined symbol: socket_ce), /usr/lib/php/20201009/event.so.so (/usr/lib/php/20201009/event.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Solution, thanks @ww9 :
`sudo mv /etc/php/8.1/cli/conf.d/20-event.ini /etc/php/8.1/cli/conf.d/30-event.ini`

**All steps:**

- sudo apt install php8.1-dev libevent-dev
- pecl install event 
- - OpenSSL support: no
- sudo echo 'extension=event.so' | sudo tee /etc/php/8.1/mods-available/event.ini
- sudo phpenmod -v 8.1 event
- sudo mv /etc/php/8.1/cli/conf.d/20-event.ini /etc/php/8.1/cli/conf.d/30-event.ini
- php --ri event
