### ISSUE TITLE
Console commands don't work

### ISSUE THREAD

**Issue by Mota-atoM** [walkor/Workerman#611]
Hello everyone, the start, status commands do not work, in general, all the commands do not work.  The server can be started without the start command.  I am using php 8. Sorry for the stupid question.

**Comment by walkor** [comment]
Please show me your code.
Please show the screenshot after executing the relevant command.

**Comment by Mota-atoM** [comment]
My server file has Worker :: runAll () at the end, maybe this is the problem?

**Comment by ww9** [comment]
It works for me @Mota-atoM on Windows and Linux.

Please show your `start.php` code and a screenshot of the result when you run it.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
