### ISSUE TITLE
how workerman is faster than swoole itself ?

### ISSUE THREAD

**Issue by kocoten1992** [walkor/Workerman#616]
Hello, I saw benchmark on https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=plaintext

workerman: 25%
swoole: 15%

I dont believe it so I wrote a script (below) to test it myself:

```php
<?php

use Workerman\Worker;

require_once __DIR__ . '/vendor/autoload.php';

// #### http worker ####
$http_worker = new Worker('http://0.0.0.0:2345');

// 4 processes
$http_worker->count = 4;

// Emitted when data received
$http_worker->onMessage = function ($connection, $request) {
    //$request->get();
    //$request->post();
    //$request->header();
    //$request->cookie();
    //$request->session();
    //$request->uri();
    //$request->path();
    //$request->method();

    // Send data to client
    $connection->send("Hello World");
};

// Run all workers
Worker::runAll();
```

```php
<?php
use Swoole\Http\Server;
use Swoole\Http\Request;
use Swoole\Http\Response;

$server = new Swoole\HTTP\Server("127.0.0.1", 9501);
$server->set(['worker_num' => 4]);

$server->on("start", function (Server $server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$server->on("request", function (Request $request, Response $response) {
    $response->end("Hello World\n");
});

$server->start();
```

### Result
```bash
Running 5s test @ http://127.0.0.1:9501
  4 threads and 4 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    83.34us  274.08us  11.56ms   99.18%
    Req/Sec    14.84k     4.04k   18.97k    58.33%
  301141 requests in 5.10s, 47.39MB read
Requests/sec:  59050.57
Transfer/sec:      9.29MB

Running 5s test @ http://127.0.0.1:2345
  4 threads and 4 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    80.86us  378.40us   9.77ms   97.93%
    Req/Sec    25.65k     2.17k   28.28k    71.50%
  510596 requests in 5.01s, 64.28MB read
Requests/sec: 102014.51
Transfer/sec:     12.84MB
```

It is true - but how :smiley: ?
You are using swoole under the hood - so how is this possible ?

**Comment by mondagPHP** [comment]
it is true.
workerman is better to traditional phper!🤣🤣🤣🤣🤣

**Comment by walkor** [comment]
> You are using swoole under the hood - so how is this possible ?

Although workerman supports swoole as the underlying driver, but the above benchmark workerman did not use swoole.

I don't know why workerman performs better than swoole. It may be that swoole's internal implementation is more complex, which affects its performance.

**Comment by fakharak** [comment]
You are testing Swoole only for http requests/ response, without using co-routines to multiplex other I/O like Database, Redis, System Process/ Commands.

Plus, after frameworks achieves performance of a certain level, we seek a better trade-off between Performance and Featrues offered by a platform. Swoole certainily has all modern features required to program IoT, Real-time Network Communication, In-memory / Memory-first Architecture, Games and other Micro-services based on Communicating Sequential Process (CSP) model of Concurrent Programming.

**Comment by mastir** [comment]
So in general both can do microservice managment.
Swoole hides under hood many common threading managments and performance is a price.
Workerman is more straightforward but requires more development in PHP.

As for me Workerman is better solution, it has less features, but you gain absolute control of your apps. If you aren`t sure about your skills in process managment, memory, sockets, locks and other staff - Swoole can handle most of it with user-friendly methods. 

And you can use both, just be sure to use same event loop
