### ISSUE TITLE
Event Loop

### ISSUE THREAD

**Issue by Bogdan1111111** [walkor/Workerman#617]
How to add function in event loop?
I want that function called every iteration

**Comment by walkor** [comment]
> I want that function called every iteration

Sorry, I don't know what that means.

If you want to run a function all the time, you can use Timer.
But that leads to CPU consumption.

```php
use Workerman\Worker;
use Workerman\Timer;
$worker = new Worker();
$worker->onWorkerStart = function(){
    // call your function every 1 ms.
    Timer::add(0.001, function(){
        you're codes.
    });
};
Worker::runAll();
```

**Comment by Bogdan1111111** [comment]
Hello i mean that woeker is a loop(if I understand correctly)
is it possible to make it so that the function is called at each run of the loop(not by timer)?

**Comment by walkor** [comment]
Sorry, workerman not support that.
