### ISSUE TITLE
Workerman\Protocols\Http\Response withFile fail

### ISSUE THREAD

**Issue by RockCaoPHP** [walkor/Workerman#619]
![image](https://user-images.githubusercontent.com/12095506/116716670-9cae5e00-aa0a-11eb-9884-d623b7b76377.png)

Workerman\Protocols\Http\Response  $file need public
because in Workerman\Protocols\Http class call this var

![image](https://user-images.githubusercontent.com/12095506/116717299-5279ac80-aa0b-11eb-856a-a328f5521c03.png)

**Comment by walkor** [comment]
Thank you for your post. 👍
