### ISSUE TITLE
workerman有限制每次发送socket消息体的大小么？

### ISSUE THREAD

**Issue by dalarge** [walkor/Workerman#62]
flash客户端发现如果消息体超大，一个大消息体就会分多次接收，造成json格式错误

**Comment by sukui** [comment]
http://doc3.workerman.net/worker-development/max-package-size.html

**Comment by walkor** [comment]
tcp多次接收是正常现象，@dalarge 需要按照[手册协议部分](http://doc3.workerman.net/protocols/why-protocols.html)定义个协议去接收，就不会出现json格式错误现象。
