### ISSUE TITLE
Non-object

### ISSUE THREAD

**Issue by squid46** [walkor/Workerman#623]
Hello. Could you please tell me why sometimes a notice appears
**Trying to get property 'user' of non-object**
And the client doesn't get the message.
Thank you.
P.S. PHP 7.4.18. Client code wss://example.com:9443/?user=1

**Comment by walkor** [comment]
This means that your codes are not rigorous please check.

**Comment by squid46** [comment]
He doesn't always give it away. Out of 20 messages 1-2.
