### ISSUE TITLE
different user promts optimization

### ISSUE THREAD

**Issue by RLOFLS** [walkor/Workerman#624]
Unber Linux,User A runs eg:` php bin/start start` => ok
Switch to user B and enter the command `php bin/start status`, and it will dispaly:
```
Workerman[bin/start] status 
Workerman[bin/start] not run
```
In Fact, the program is running, but user B sends a signal and user A cannot receieve it,user B needs to use `sudo` to respond normally.
When `sudo` is not use, Suggest to optimize the output
For example:
```
Workerman[bin/start] is running
Workerman[bin/start] but does not have permission, You need to use the `sudo` command
```

**Comment by xpader** [comment]
Different user can not visit the same process, and you should not use different user to do that.

**Comment by walkor** [comment]
Linux has strict access control. You can't use different users to access the same process.
