### ISSUE TITLE
ws vs wss ==>> output buffer ??????

### ISSUE THREAD

**Issue by jintor** [walkor/Workerman#627]
Hi,

When I did a first test on ws, all was outputting as soon as it was pushed by the server
$wss_worker = new Workerman\Worker("websocket://domain.com:2346");

but as soon I added my .pem .cert and this
$wss_worker = new Workerman\Worker("websocket://domain.com:2346",$socketx_connex);
$wss_worker->transport = 'ssl';

** why with SSL the client browser WAIT before the whole php script finishes to output ???

is there a way to change the output buffer like in NGINX ?

example echo 'hello'; sleep(2); echo 'done';

ws: ===>> i see hello - wait - and 'done
wss: ==>> I wait and I see hello done all at once

how to fix this ?

**Comment by walkor** [comment]
It works fine for me.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6073368/121002677-2b0ec000-c7bf-11eb-809a-b2637c25b324.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/6073368/121002748-4083ea00-c7bf-11eb-95c8-7bb881fa4101.png">

Here is the codes:
```php
<?php
require 'vendor/autoload.php';
use Workerman\Worker;

$context = array(
    'ssl' => array(
        'local_cert'                 => '/etc/nginx/ssl/xxx.pem', 
        'local_pk'                   => '/etc/nginx/ssl/xxx.key',
        'verify_peer'                => false,
    )
);
$worker = new Worker('websocket://0.0.0.0:4431', $context);
$worker->transport = 'ssl';
$worker->onMessage = function($con, $msg) {
     echo 'hello'; sleep(2); echo 'done';
    $con->send('ok');
};

Worker::runAll();
```

Javascript.
```js
ws = new WebSocket('wss://d.popoim.cn:4431');
ws.open = function(){
    ws.send(1);
}
```

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
Please come back with more details if this problem persists and we can reopen this
