### ISSUE TITLE
Save ::_statisticsFile at tmp folder is bad idea

### ISSUE THREAD

**Issue by webrobot1** [walkor/Workerman#629]
It is not good idea to save data at tmp folder via php. because only proccess what create or edit  file at tmp folder can read it. when you try to get status Workerman can't unlink at firstly (see Worker.php line 932)  , but add new information at the end 

And file will be very large (when i found this problem it was 40Gb)

of course , you can edit your server  setting with PrivateTmp=false but this problem is very actualy [https://stackoverflow.com/questions/30444914/php-has-its-own-tmp-in-tmp-systemd-private-nabcde-tmp-when-accessed-through-ng](url)

**Comment by walkor** [comment]
> And file will be very large (when i found this problem it was 40Gb)

If the temporary file exists, we will delete it. See https://github.com/walkor/Workerman/blob/4d1e8da040cb6036cc1c0b1431e03a8a2a78eec6/Worker.php#L935

So it's not going to be append to the file indefinitely.

**Comment by webrobot1** [comment]
It is not deleated if it is not local server. Read about PrivateTmp server's setting - only process wjat create file can deleti it. Another process won't see the file

**Comment by webrobot1** [comment]
When you try get status - it is another process. And for this process tmp folder is empty

**Comment by walkor** [comment]
&gt; it is not local server.
What ‘s that mean?


&gt;&nbsp;When you try get status - it is another process. And for this process tmp folder is empty.


All the processes&nbsp;use the same user. So the all the processes can see the file.

**Comment by webrobot1** [comment]
If you have PHP-FPM no matter what user create file at tmp folder at server. Only process (pid) what create this file can see it at tmp folder (it rule only for tmp folder) and delete it and edit. 

Only if you edit server setting (PrivateTmp =false) you can all php process can see all files at tmp folder. In my sittuation i edit apache2.service file at the server. Without it, when i start server , and after that try to check status from another console _statisticsFile will not deleted, but always add new information . When i found this problem it was over 40gb

**Comment by walkor** [comment]
> If you have PHP-FPM no matter what user create file at tmp folder at server.
> In my sittuation i edit apache2.service file at the server. 

Workerman is a command line based application, not PHP-FPM or Apache but php-cli.

**Comment by webrobot1** [comment]
No matter, if at your servet PrivateTmp = true (in my situation it is, i think it is mostly)  _statisticsFile will be more and more.  And if you dont check it at tmp folder you dont know about it. Workerman will be work fine, but wont delete when you check status

**Comment by walkor** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/6073368/121035136-2c9cb000-c7e0-11eb-9642-f8d4d58c3938.png">

This is the result of my test. What you said didn't happen. Can you give me an example to reproduce the problem you said ? Include screenshots.

And I didn't find any PrivateTmp settings for PHP cli. Can you tell me where to set the PrivateTmp configuration of PHP cli ？

**Comment by webrobot1** [comment]
I have: Ubuntu, Apache , Php 7.2.

PrivateTmp  at file /lib/systemd/system/apache2.service
![изображение](https://user-images.githubusercontent.com/20768848/121037118-dfa4e380-c7b7-11eb-839f-c054b38f5abc.png)


And my tmp folder look like this

![изображение](https://user-images.githubusercontent.com/20768848/121037347-0d8a2800-c7b8-11eb-857d-d647c4251c40.png)

Workerman is running, file from static varrible ::_statisticsFile is created well....lets try to get status of Workerman....

**Comment by webrobot1** [comment]
I need try to get status of workerman from the php.

1 create simple script like index.php with code what execute my wokrerman application with command status:

<?php

echo shell_exec("php /srv/www/html/index.php eyJhcHAiOiJnYW1lIiwibW9kZWwiOiJTZXJ2ZXIiLCJhY3Rpb24iOiJzeW5jaCJ9 status");

**Comment by webrobot1** [comment]
2. look the result 

![изображение](https://user-images.githubusercontent.com/20768848/121039445-c1d87e00-c7b9-11eb-890b-b7cc123d368b.png)
- it seems not ok

**Comment by webrobot1** [comment]
3. File at tmp folder have more size
![изображение](https://user-images.githubusercontent.com/20768848/121039597-e5032d80-c7b9-11eb-9754-9a2f18449080.png)

**Comment by webrobot1** [comment]
4. Look of content of ::_statisticsFile
![изображение](https://user-images.githubusercontent.com/20768848/121039675-f815fd80-c7b9-11eb-8488-e002289f355e.png)

**Comment by walkor** [comment]
> create simple script like index.php with code what execute my wokrerman application with command status.

Workerman is a command line based application, not PHP-FPM or Apache but php-cli.
Do not use it under PHP-FPM or Apache.

**Comment by webrobot1** [comment]
5. try to debug, edit Worker.php:

go to line 932 and change 

` if (\is_file(static::$_statisticsFile)) {
                        @\unlink(static::$_statisticsFile);
                    }`

to 

`//if (\is_file(static::$_statisticsFile)) {
						
						static::safeEcho(get_current_user()."\n"); // check the user
						static::safeEcho(print_r(scandir(sys_get_temp_dir()), true)."\n"); // look at the folder assigned from line 601
						
                        //@\unlink(static::$_statisticsFile);
                   // }`

**Comment by webrobot1** [comment]
6. See the tmp folder again

**Comment by webrobot1** [comment]
> 
> 
> > create simple script like index.php with code what execute my wokrerman application with command status.
> 
> Workerman is a command line based application, not PHP-FPM or Apache but php-cli.
> Do not use it under PHP-FPM or Apache.

php can open comnand  console via exex, system, shell_exec comand  (CLI) see https://www.php.net/manual/en/function.exec.php

**Comment by webrobot1** [comment]
and is is realy CLI mode (you already have check it at line 555 ).

i use shell_exec  for change PID and try to get status. I get it. Look like al ok - but this process cant see the tmp folder. and file ::_statisticsFile will be more and more

**Comment by webrobot1** [comment]
well i need edit /lib/systemd/system/apache2.service, set PrivateTmp = false

**Comment by webrobot1** [comment]
as i say it work fine with PrivateTmp = false or PrivateTmp = true , but if it PrivateTmp = true another process from php, what open console and execute comand  (open at CLI mode) "status" will be return because it (another process) cant read ::_statisticsFile 

![изображение](https://user-images.githubusercontent.com/20768848/121043382-3bbe3680-c7bd-11eb-9d2b-0999d454a79c.png)


> 
> 
>     1. look the result
> 
> 
> ![изображение](https://user-images.githubusercontent.com/20768848/121039445-c1d87e00-c7b9-11eb-890b-b7cc123d368b.png)
> 
>     * it seems not ok

**Comment by webrobot1** [comment]
7. Change at /lib/systemd/system/apache2.service file (set PrivateTmp = false) and run again php script (what open console and run status command at cli mode), and we see what all work bacause not all process what start php can see all files at "tmp"  folder

![изображение](https://user-images.githubusercontent.com/20768848/121043673-82ac2c00-c7bd-11eb-959f-4cca45e1b835.png)

**Comment by webrobot1** [comment]
I think it actualy problem , bacause many people want integrate Workerman to they application and get functionality for:

status, run and stop workerman. How can they do what ? only if the y open console from php , use exec, system and so on command for it.

is they can get status ?
 - no (i think PrivateTmp  for apache and may be Nginx default = true  for ubuntu)

**Comment by webrobot1** [comment]
or Workerman will not server tmp folder (bacause it have a problem if PrivateTmp = true)

**Comment by walkor** [comment]
Do you have any good ideas?

**Comment by webrobot1** [comment]
> 
> 
> Do you have any good ideas?

it is typical problem when use tmp folder (with any applications)

![изображение](https://user-images.githubusercontent.com/20768848/121048323-5db8b880-c7bf-11eb-84e9-3351604f33de.png)

maybe use Workerman's folder for ::_statisticsFile. i think is is good idea

**Comment by webrobot1** [comment]
you already use Workerman folder for log and .pid file. i think if all Workarman's files was at one place - it is good. without problem

![изображение](https://user-images.githubusercontent.com/20768848/121049060-0a933580-c7c0-11eb-88d5-cec522b450e7.png)

**Comment by walkor** [comment]
Please pull form master and try again.
