### ISSUE TITLE
 SSL and Alice Domain

### ISSUE THREAD

**Issue by Sa1ch** [walkor/Workerman#630]
Hello! I have one worker and a many alias domain.
I get a mistake if the worker is connected from another domain: sslv3 alert certificate unknown

my settings:
```
'ssl' => [
        'local_cert'  => 'ssl.site.ru.pem',
        'local_pk'    => 'ssl.site.ru.key',
        'verify_peer' => false,
        'verify_peer_name' => false
    ]
```
Is it possible to somehow disable the certificate check?

**Comment by walkor** [comment]
Sorry. Workerman not support multi domain.
