### ISSUE TITLE
WebSocket connection to 'ws://0.0.0.0:8001/' failed: 

### ISSUE THREAD

**Issue by Artem2710** [walkor/Workerman#631]
How I can resolve this error? WebSocket connection to 'ws://0.0.0.0:8001/' failed

**Comment by walkor** [comment]
Please change `0.0.0.0` to real ip or domain.

**Comment by Artem2710** [comment]
I have this problem with all ip or domains

**Comment by Artem2710** [comment]
Please tell me if I should make any settings for my web server (I have nginx)?

**Comment by walkor** [comment]
Set iptables of your server and let port 8001 can be visited.

**Comment by Artem2710** [comment]
May you help me? At the moment when I connect to the server, the default page is triggered. What am I doing wrong?
![image](https://user-images.githubusercontent.com/38757512/121848689-0f417780-ccf3-11eb-8b19-22466222a035.png)

**Comment by walkor** [comment]
That means it works.There are no errors.

**Comment by Artem2710** [comment]
But why isn't my html code displayed?

**Comment by walkor** [comment]
I don’t know where your html codes put. And I don’t know how to visit your codes. If you don’t know how to visit your html codes just google “nginx html page serve”.

**Comment by Artem2710** [comment]
![image](https://user-images.githubusercontent.com/38757512/121855460-0903c900-ccfc-11eb-9828-554704703172.png)
Why is this block of code firing?

**Comment by walkor** [comment]
It is wrong way to visit 8001 port by http. 8001 is an websocket port and can be visit by codes like&nbsp;
ws = new WebSocket(‘ws://ip:8001’);

**Comment by Artem2710** [comment]
Thanks, now everything works correctly!

**Comment by Artem2710** [comment]
How can I connect to an already running socket server using your library?

**Comment by Artem2710** [comment]
Or in other words, how can I create a php client using your library?

**Comment by walkor** [comment]
https://github.com/walkor/Workerman#asynctcpconnection-tcpwstextframe-etc
