### ISSUE TITLE
Should Workerman\Events\React\Base implements EventInterface?

### ISSUE THREAD

**Issue by yedemon** [walkor/Workerman#632]
Hi. respectful walkor.
    Recently, i'm developing some project, and need to use ReactPHP's evloop implement. But I found Workerman\Events\React\Base implements React\EventLoop\LoopInterface while not Workerman\Events\EventInterface, and dosn't have clearAllTimer method. It's right? 

    Please give me some help.

**Comment by walkor** [comment]
It doesn't matter.
