### ISSUE TITLE
About enabling https & wss

### ISSUE THREAD

**Issue by raghuveer** [walkor/Workerman#639]
I am interested to know if you do suggest generating and providing the path to certificate & private key manually to workerman wherein workerman runs on any port above 1024 (as it runs based on non-root user).

Alternatively, we might have nginx running as reverse proxy on port 80 for http and port 443 for https, that proxies workerman serving as http server on any chosen port

Let'sencrypt issued ssl certificates are used and certbot from letsencrypt is chosen to auto-renew ssl certificates. I chose latter option (nginx as reverse proxy with a websocket service implementation that I did based on ratchet in the past).

keeping devops & CI/CD, letsencrypt ssl certificate renewal and scalability considerations in mind, I would like to know your view about which option to choose, to serve more connections @walkor  

thank you

**Comment by walkor** [comment]
In the actual project, I use nginx as the SSL proxy method most of the time.&nbsp;So I will chose latter option too (nginx as reverse proxy).

**Comment by raghuveer** [comment]
Thanks for your confirmation @walkor :)

**Comment by walkor** [comment]
You’re welcome.
