### ISSUE TITLE
CI test cases for Workerman helps

### ISSUE THREAD

**Issue by raghuveer** [walkor/Workerman#640]
Dear @walkor 

do we have CI tests available for Workerman library?

it will be helpful for easier adoption & when testing updates know

just some thoughts

thank you

With Best Regards
Raghuveer

**Comment by walkor** [comment]
Hi @raghuveer 
Thank your for your post.
There is no CI test at present.
I know CI testing is important, but I don't have the energy to implement it right now.

**Comment by raghuveer** [comment]
Thanks for sharing the practical situation, I respect that.
