### ISSUE TITLE
Why comment reusePort

### ISSUE THREAD

**Issue by Yurunsoft** [walkor/Workerman#641]
in https://github.com/walkor/Workerman/commit/af6025976fba817eeb4d5fbf8d0c1059a5819da3#diff-3a250715fea88c39eb37f7ecc0118e633eaf0a599ff7fc7adf5d374fa8604fbfR2216

**Comment by walkor** [comment]
When reuseport is turned on, it is not easy to find repeated listening port errors. When dealing with the feedback from developers, you will find that many people listen to the port repeatedly, resulting in abnormal business. Therefore, reuseport is turned off by default. You can turn it on through ·$worker - > reuseport = true·.

**Comment by Yurunsoft** [comment]
OK
