### ISSUE TITLE
mTLS in workerman, it is possible?

### ISSUE THREAD

**Issue by RicardoSette** [walkor/Workerman#643]
is it possible with workerman to enable client certificate validation to authentication?

on this site [examples](https://smallstep.com/hello-mtls#configuration-examples) it is explained how to configure servers (ex: GO/NGINX/Node/etc), since it is possible to configure in GO and Node I wondered about the possibility of configuring in Workerman, but I found nothing about mTLS.

In Workeman how can I validate the client's certificate? at what point would i run/configure this?

**Comment by walkor** [comment]
https://github.com/walkor/Workerman#enable-ssl
Here is an example for workerman to set ssl/tls.
