### ISSUE TITLE
the client loses the ability to connect a few hours after starting the workerman

### ISSUE THREAD

**Issue by Pushken** [walkor/Workerman#644]
I am starting proccess as daemon. Everything is fine at first, I can connect through the browser.
After a few hours, this opportunity disappears. JS throws connection error.
Command status, gives the result that the workerman is running and everything is fine.
After restart all is fine too, but this is not a good solution.

What do I need to provide you so that you can suggest how to solve my problem?

Thanks in advance

**Comment by walkor** [comment]
Do you use any db for example Mysql?

**Comment by Pushken** [comment]
Yes, mysql.

I have problem with connection to db, when at first when i start as daemon, before this problem. But then i put creating connection into workerman callback,

**Comment by walkor** [comment]
MySQL will close the inactive connection for a long time. Set a timer to access the database regularly and keep the database connection active like


Timer::Add(55, function(){
&nbsp; &nbsp; Db::query(‘select 1’);
}

**Comment by walkor** [comment]
$worker-&gt;onWorkerStart = function() {
&nbsp;Timer::Add(55, function(){
&nbsp; &nbsp; Db::query(‘select 1’);
&nbsp;}
};

**Comment by Pushken** [comment]
thx, i will try

**Comment by Pushken** [comment]
The night has passed and everything works with a timer.
Thank you so much!
