### ISSUE TITLE
php start.php status shows that the process is not running when it is running as a daemon

### ISSUE THREAD

**Issue by perezlenin** [walkor/Workerman#646]
Mi ingles no es muy bueno, usare el traductor
_My English is not very good, I will use the translator_

hice una actualización de la version 3.5 a 4.0.19
cuando inicio en modo demonio con php start.php start -d todo bien
_I did an update from version 3.5 to 4.0.19
when i start in daemon mode with php start.php start -d everything fine_
![worker_startdemon](https://user-images.githubusercontent.com/21348398/126713893-6a86d349-6180-4924-b8c9-2ea12603fc29.png)

pero cuando consulto el status (php start.php status) me dice que no esta corriendo el proceso (Workerman[start.php] not run)
_but when I check the status (php start.php status) it tells me that the process is not running (Workerman [start.php] not run)_
![worker_status](https://user-images.githubusercontent.com/21348398/126713975-ffe5b2c5-e8e9-4f36-8f26-29e8c4b04e0a.png)

Muestro mi archivo start.php
```php
<?php
date_default_timezone_set("America/New_York");
ini_set('display_errors', 'on');
if(strpos(strtolower(PHP_OS), 'win') === 0)
{
    exit("start.php not support windows, please use start_for_win.bat\n");
}
// 检查扩展
if(!extension_loaded('pcntl'))
{
    exit("Please install pcntl extension. See http://doc3.workerman.net/appendices/install-extension.html\n");
}
if(!extension_loaded('posix'))
{
    exit("Please install posix extension. See http://doc3.workerman.net/appendices/install-extension.html\n");
}
// 标记是全局启动
define('GLOBAL_START', 1);
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;
// Create a Websocket server
$ws_worker = new Worker('websocket://0.0.0.0:2346');
// 4 processes
$ws_worker->count = 4;
// Emitted when new connection come
$ws_worker->onConnect = function ($connection) {
    echo "New connection\n";
};
// Emitted when data received
$ws_worker->onMessage = function ($connection, $data) {
    // Send hello $data
    $connection->send('Hello ' . $data);
};
// Emitted when connection closed
$ws_worker->onClose = function ($connection) {
    echo "Connection closed\n";
};
// Run worker
Worker::runAll();
```

**Comment by walkor** [comment]
https://github.com/walkor/Workerman/blob/master/Worker.php#L2560
It seems checkMasterIsAlive return false.
Please log and check why checkMasterIsAlive return false.

**Comment by perezlenin** [comment]
Hice una depuración del archivo Worker.php de la function checkMasterIsAlive
_I did a debug of the Worker.php file of the checkMasterIsAlive function_
`protected static function checkMasterIsAlive($master_pid)
    {
        if (empty($master_pid)) {
            return false;
        }
        $master_is_alive = $master_pid && \posix_kill($master_pid, 0) && \posix_getpid() !== $master_pid;
        if (!$master_is_alive) {
            return false;
        }
        $cmdline = "/proc/{$master_pid}/cmdline";
        if (!is_readable($cmdline) || empty(static::$processTitle)) {
            return true;
        }
        $content = file_get_contents($cmdline);
        if (empty($content)) {
            return true;
        }
        echo $master_pid."\n";
        var_dump(static::$processTitle); // return WorkerMan
        var_dump($content);// return phpstart.phpstart-d
        return stripos($content, static::$processTitle) !== false;// not found $static::processtitle in $content
    }`

Retorna false porque no encuentra en el contenido del archivo  cmdline la palabra "Workerman"
_Returns false because the word "Workerman" is not found in the content of the cmdline file_

**Comment by walkor** [comment]
php 5.4 not support cli_set_process_title so the check returned false.
Please try change.
```php
return stripos($content, static::$processTitle) !== false;
```
```php
return stripos($content, static::$processTitle) !== false || stripos('php', static::$processTitle) !== false;
```

**Comment by perezlenin** [comment]
Funciona, gracias
_It works thank you_
