### ISSUE TITLE
Session lifetime with with RedisSessionHandler

### ISSUE THREAD

**Issue by char101** [walkor/Workerman#647]
Hi,

PHP internal session handler has an `updateTimestamp` method which will be called to update the session timestamp when there is an incoming request (not just when there is a modification to the session data). How do workerman refresh the redis key expiration time when there is new request that do not modify the session data?

**Comment by walkor** [comment]
Close by https://github.com/walkor/Workerman/pull/686

**Comment by char101** [comment]
I think that is only half of what is required, the redis key expiration should also be refreshed on every request.

As can be seen here https://github.com/php/php-src/blob/50f31829b1/ext/session/session.c#L2657 , `session_register_shutdown` (which calls session write function which calls updateTimestamp if the session data is not modified) is registered as a shutdown function and thus is called after every request.

Otherwise if the session data is not modified, it will expire after 24 minutes (the default value of `session.gc_maxlifetime`).

**Comment by walkor** [comment]
I think not every user want to refresh the key every request.
It is also optional in the PHP kernel. 
I think the user has the right to choose whether to call it automatically.
Users can choose to call it manually according to some situations, or implement a custom session handler like php-fpm which the code for workerman like this.

**MySessionHandler.php**
```php
use Workerman\Protocols\Http\Session\RedisSessionHandler;
class MySessionHandler extends RedisSessionHandler {
    public function read($session_id)
    {
        if ($ret = $this->_redis->get($session_id)) {
             $this->updateTimestamp($session_id);
        }
        return $ret;
    }
} 
```

````php
use Workerman\Protocols\Http\Session;
Session::handlerClass('MySessionHandler');
$worker = new Worker('http://0.0.0.0:8080');
....
````

**Comment by char101** [comment]
That is not how session in the fastcgi sapi works though, the session is always written on every request:

> When PHP shuts down (or when session_write_close() is called), PHP will internally encode the $_SESSION superglobal and pass this along with the session ID to the write callback. After the write callback has finished, PHP will internally invoke the close callback handler.

https://www.php.net/manual/en/session.customhandler.php

If `session.lazy_write` is `On`, which is the default value, `updateTimestamp` will be called instead of `write` if the session data does not change.

**Comment by char101** [comment]
I understand that this is a breaking change, so I am not asking for it to be changed. Users can simply update time redis expiration themselves. I write it here so that there are some explanation that the session expiration updating is different with normal php session.

**Comment by walkor** [comment]
Thank you for sharing. Let's know more about the mechanism of PHP session. 👍
