### ISSUE TITLE
protocol for Android

### ISSUE THREAD

**Issue by wsyzj92** [walkor/Workerman#651]
I am an Android developer. I had a problem. When I use socket with Workerman (server). 
How do I know about the params of header length and body length? 
I tried to ask my colleague. But he didn't know. I was so angry with what. 
This problem bothered me for 2 days.

![1628845306(1)](https://user-images.githubusercontent.com/54034989/129333421-e5c10321-958c-4dab-80a0-782867c8a35b.jpg)

**Comment by walkor** [comment]
Moved to https://wenda.workerman.net/question/6677
