### ISSUE TITLE
I can't start websocket server without daemon (-d) mode.

### ISSUE THREAD

**Issue by kotcich** [walkor/Workerman#656]
### worker[kotcich:2024998] exit with status 65280
**Worker[2025001] process terminated with ERROR: E_ERROR "Class Workerman\Events\React\Base contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (React\EventLoop\LoopInterface::removeStream, React\EventLoop\LoopInterface::isTimerActive, React\EventLoop\LoopInterface::nextTick, ...) in /var/www/www-root/data/www/api.isinda.ru/vendor/workerman/workerman/Events/React/Base.php on line 24"**

**Comment by kotcich** [comment]
And becouse of that (i think), callbacks $worker->onWorkerStart/$worker->onWorkerStart doesn't work when i type in console php ws.php stop

**Comment by kotcich** [comment]
`<?php

use Workerman\Worker;

require_once __DIR__ . '/vendor/autoload.php';

// Create a Websocket server
$worker = new Worker('websocket://0.0.0.0:8089');
$worker->name = 'kotcich';
$worker->count = 4;

// Emitted when socket start
$worker->onWorkerStart = function($worker)
{
    echo "Worker starting...\n";
};

// Emitted when socket stop
$worker->onWorkerStop = function($worker)
{
    echo "Worker closed... nigga\n";
};

// Emitted when new connection come
$worker->onConnect = function ($connection) {
    echo "New connection\n";
};

// Emitted when data received
$worker->onMessage = function ($connection, $data) {
    // Send hello $data
    $connection->send('Hello ' . $data);
};

// Emitted when connection closed
$worker->onClose = function ($connection) {
    echo "Connection closed\n";
};

// Run worker
Worker::runAll();`

**Comment by walkor** [comment]
Try run command ‘composer remove&nbsp;react/event-loop’

**Comment by kotcich** [comment]
> Try run command ‘composer remove&nbsp;react/event-loop’

 Not enough arguments (missing: "packages").  
                                               

remove [--dev] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--no-update-with-dependencies] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] <packages>...

**Comment by walkor** [comment]
Please paste the screenshot

**Comment by kotcich** [comment]
> Please paste the screenshot
![image](https://user-images.githubusercontent.com/55199603/132682980-c7dc3a28-3b74-4e35-a430-ce2c8cb89bb1.png)
I did the comman and it's worked, but issue not cure.

**Comment by walkor** [comment]
You should remove the package react/event-loop

**Comment by kotcich** [comment]
> react/event-loop

![image](https://user-images.githubusercontent.com/55199603/132684472-be032958-c0fe-4838-b5be-40be61bb8911.png)
I did composer remove react/event-loop. After that i see this messages and nothing changed.

**Comment by kotcich** [comment]
Sorry for my dump brain/ I deleted this dir manually and it's worked. You can closed issue
