### ISSUE TITLE
How should i set up url in new Workerman for remote SSL server?

### ISSUE THREAD

**Issue by kotcich** [walkor/Workerman#657]
I mean this:
`// SSL context.
$context = array(
    'ssl' => array(
        'local_cert'  => __DIR__ . '../../httpd-cert/www-root/*.domain.ru.crt',
        'local_pk'    => __DIR__ . '../../httpd-cert/www-root/*.domain.ru.key',
        'verify_peer' => false,
    )
);

// Create a Websocket server
$worker = new Worker('websocket://0.0.0.0:8089', $context);`

Instead of websocket://0.0.0.0:8089, what have to be? ip of remote server or domain as websocket://domain.ru:8089?

**Comment by kotcich** [comment]
![image](https://user-images.githubusercontent.com/55199603/132685838-6233d760-1695-463e-90f3-122e26e8d366.png)
I understood that i should use domain name in url from client socket side, but i get this errors in console on workerman server on each time, user trying connect. It means that user find the server, but connection not establish.

**Comment by walkor** [comment]
Make sure local_cert and local_pk is right and the file exist

**Comment by kotcich** [comment]
Sorry for 2 time, i dump. I fixed it problem. I mistake on route to ssl.key. When i foud out and changed the route, all worked.

**Comment by walkor** [comment]
That’s ok
