### ISSUE TITLE
Workerman的session问题

### ISSUE THREAD

**Issue by hetao29** [walkor/Workerman#66]
- 1.没有启用session的时候，调用了 sessionWriteClose，想开启的时候无法开启
 - 2.无法识别session_save_path的redis，memcache类型

**Comment by hetao29** [comment]
Workerman-master/Protocols/Http.php的229行
self::sessionWriteClose();
应该注释掉，因为没有用

**Comment by walkor** [comment]
1、229 行self::sessionWriteClose();是用来保存session的，去掉后就保存不了session了
2、目前暂时不支持session_save_path的redis，memcache类型。

http协议的应用不是workerman的目标，让PHPer摆脱PHP只能用于Web开发的束缚才是workerman的主要目标。目前不会花费太多时间去完善http协议及webserver。

如果想开发http协议的应用，nginx配合fpm是非常好的选择，各种mvc框架已经非常成熟了，开发、调试、部署、运维、维护都非常简单。

**Comment by hetao29** [comment]
我的意思因为代码没有session_start,所以session_close也应该没有必要

我也明白，workerman对http协议支持肯定有限，毕竟http协议细节很多，而且超级复杂。

明白你的设计定位。

何涛 Hetal

Tel: 13488810858

北京市海淀区，100080




在 2016年3月28日 上午11:14，walkor <notifications@github.com>写道：

**Comment by walkor** [comment]
sessionWriteClose 里面有判断是否调用了sessionStart，没有的话就直接返回了
