### ISSUE TITLE
How can I timeout a socket?

### ISSUE THREAD

**Issue by sasanchez1991** [walkor/Workerman#660]
How can I timeout a socket and close it if it stops sending something to the server after a set time

**Comment by walkor** [comment]
```php
<?php
require_once __DIR__ . '/Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Lib\Timer;

// Time out
define('HEARTBEAT_TIME', 55);

$worker = new Worker('websocket://0.0.0.0:1234');

$worker->onMessage = function($connection, $msg) {
    $connection->lastMessageTime = time();
    // Other codes....
};

$worker->onWorkerStart = function($worker) {
    Timer::add(1, function()use($worker){
        $time_now = time();
        foreach($worker->connections as $connection) {
            if (empty($connection->lastMessageTime)) {
                $connection->lastMessageTime = $time_now;
                continue;
            }
            if ($time_now - $connection->lastMessageTime > HEARTBEAT_TIME) {
                $connection->close();
            }
        }
    });
};

Worker::runAll();
```

**Comment by walkor** [comment]
```php
<?php
require_once __DIR__ . '/Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Lib\Timer;

// Time out
define('HEARTBEAT_TIME', 55);

$worker = new Worker('websocket://0.0.0.0:1234');

$worker->onMessage = function($connection, $msg) {
    $connection->lastMessageTime = time();
    // Other codes....
};

$worker->onWorkerStart = function($worker) {
    Timer::add(1, function()use($worker){
        $time_now = time();
        foreach($worker->connections as $connection) {
            if (empty($connection->lastMessageTime)) {
                $connection->lastMessageTime = $time_now;
                continue;
            }
            if ($time_now - $connection->lastMessageTime > HEARTBEAT_TIME) {
                $connection->close();
            }
        }
    });
};

Worker::runAll();
```

**Comment by sasanchez1991** [comment]
Thank you very much for your help, but nevertheless the client is closing in the established time, transmit or not, how can I do to fix it, the idea is that if the client is transmitting, do not remove it from the server, I only remove it if after a time that I have not transmitted anything to the attached server my code:

<?php
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;
use Workerman\Lib\Timer;

// Time out
define('HEARTBEAT_TIME', 10);

$worker = new Worker('tcp://190.0.17.60:10000');

//inicializa timer
$worker->onMessage = function($connection, $msg) {
    $connection->lastMessageTime = time();
    
};

// recibe data enviada
$worker->onMessage = function ($connection, $data) {
    // Send data to client
    echo $data;
    $connection->send("Hello  \n");
    
};

// funcion timer , si el cliente no trasmite lo saca del servidor
$worker->onWorkerStart = function($worker) {
    Timer::add(1, function()use($worker){
        $time_now = time();
        foreach($worker->connections as $connection) {
            if (empty($connection->lastMessageTime)) {
                $connection->lastMessageTime = $time_now;
                continue;
            }
            if ($time_now - $connection->lastMessageTime > HEARTBEAT_TIME) {
                $connection->close();
            }
        }
    });
};

Worker::runAll();

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/132850230-dd31e258-0249-4392-a7ef-4c66e6d40dfe.png)
There are two onmessage conflicts. Please delete the below and keep the above test again

**Comment by sasanchez1991** [comment]
So it worked perfect, however, I cannot take the data that it sends me and process it, in which way can I take the data sent by the client, and do a process and then respond to something

**Comment by sasanchez1991** [comment]
I think I have made it, I really appreciate your help

**Comment by walkor** [comment]
You are welcome

**Comment by KiNGKiMO** [comment]
I know this is old but I have a client software that sends "ping" requests which doesn't get catched at onMessage, is there a solution to keep such connection alive while using this method of timeout, or is there another method for timeout that works?
