### ISSUE TITLE
How can I know how many clients are connected?

### ISSUE THREAD

**Issue by sasanchez1991** [walkor/Workerman#661]
How can I know how many clients are connected at the moment?

**Comment by xpader** [comment]
`$worker->connections` is an array include all connected connections.

**Comment by sasanchez1991** [comment]
How can I print the number of those connections in the console?

**Comment by xpader** [comment]
You can use `php start.php status` to see the connection statuses.

**Comment by sasanchez1991** [comment]
I can't find start.php

**Comment by sasanchez1991** [comment]
I try to use the command in my file called server.php and it doesn't let me display status,

**Comment by walkor** [comment]
https://github.com/walkor/Workerman#available-commands
