### ISSUE TITLE
Can i send data to connection from socket with multiple proccesses if i know id of worker?

### ISSUE THREAD

**Issue by kotcich** [walkor/Workerman#668]
`$worker[1]->connections[17]->send(json_encode(['data' => $GLOBALS['login'][$user_id], 'message' => 'browsers']));`
I mean each new connection got his unique id within 1 proccess and it's possible to see 2 connection with same id but from different proccesses. I know and connection id and worker id (this i set to the client side and sending each time).
But i get error "Error: Cannot use object of type Workerman\Worker as array in /var/www/www-root/data/www/api.isinda.ru/backend/socket/auth.php:59"

**Comment by xpader** [comment]
Where did you get `$worker`??

**Comment by xpader** [comment]
You can use `GatewayWorker` or `Channel` component to communicate with each processes.
