### ISSUE TITLE
About Http keep-alive support

### ISSUE THREAD

**Issue by hetao29** [walkor/Workerman#67]
- 没有识别Keey-Alive头，如果client不close连接的话，workerman不会自己关闭连接，导致连接一直挂起

可以参考 https://github.com/hetao29/slightphp/commit/11b156ab5c29b9e6f273b7a7e84a534c6ce60368#commitcomment-16832265 这里需要手动close才行，感觉比较不方便

**Comment by linkec** [comment]
`<?php
use Workerman\Worker;
use Workerman\Lib\Timer;
require_once __DIR__ . '/Workerman/Autoloader.php';
$http_worker = new Worker("http://0.0.0.0:2345");
$http_worker->count = 4;
$http_worker->keepAlive = 10;
$http_worker->onWorkerStart = function($worker)
{
    Timer::add(1,function()use($worker)
    {
        foreach($worker->connections as $connection){
            if($connection->expTime<time()){
                $connection->close();
            }
        }
    });
};
$http_worker->onConnect = function($connection)
{
    $connection->expTime = time()+$connection->worker->keepAlive;
};
$http_worker->onMessage = function($connection,$data){
    $connection->expTime = time()+$connection->worker->keepAlive;
    
    //业务开始
    $connection->send('aaa');
    //业务结束
    
    if($connection->worker->keepAlive==0){
        $connection->close();
    }
};
Worker::runAll();`
可以这么实现

**Comment by linkec** [comment]
```
<?php
use Workerman\Worker;
use Workerman\Lib\Timer;
require_once __DIR__ . '/Workerman/Autoloader.php';
$http_worker = new Worker("http://0.0.0.0:2345");
$http_worker->count = 4;
$http_worker->keepAlive = 10;
$http_worker->onWorkerStart = function($worker)
{
    Timer::add(1,function()use($worker)
    {
        foreach($worker->connections as $connection){
            if($connection->expTime<time()){
                $connection->close();
            }
        }
    });
};
$http_worker->onConnect = function($connection)
{
    $connection->expTime = time()+$connection->worker->keepAlive;
};
$http_worker->onMessage = function($connection,$data){
    $connection->expTime = time()+$connection->worker->keepAlive;
    
    //业务开始
    $connection->send('aaa');
    //业务结束
    
    if($connection->worker->keepAlive==0){
        $connection->close();
    }
};
Worker::runAll();
```
可以这么实现
