### ISSUE TITLE
How many proccess recommended set, if my machine has 2 proccesor CPU?

### ISSUE THREAD

**Issue by kotcich** [walkor/Workerman#670]
I mean how many websocket proccesses.

**Comment by walkor** [comment]
It is recommended to set the number of processes to 1-4 times the number of CPUs.
I suggest that the number of processes is 2 for your situation.

**Comment by kotcich** [comment]
> It is recommended to set the number of processes to 1-4 times the number of CPUs. I suggest that the number of processes is 2 for your situation.

Thank you.
