### ISSUE TITLE
Websocket protocol code optimization

### ISSUE THREAD

**Issue by twomiao** [walkor/Workerman#674]
// Bad websocket handshake request.
        $connection->send("HTTP/1.1 200 WebSocket\r\nServer: workerman/".Worker::VERSION."\r\n\r\n<div style=\"text-align:center\"><h1>WebSocket</h1><hr>workerman/".Worker::VERSION."</div>",
            true);
        $connection->close();

> This is more reasonable
`$connection->close("HTTP/1.1 200 WebSocket\r\nServer: workerman/" . Worker::VERSION . "\r\n\r\n<div style=\"text-align:center\"><h1>WebSocket</h1><hr>workerman/" . Worker::VERSION . "</div>" );`

**Comment by walkor** [comment]
Thanks.
