### ISSUE TITLE
"Pending" status instead of "101"

### ISSUE THREAD

**Issue by litosh-web** [walkor/Workerman#677]
- 1 core
- 1 GB RAM
- Ubuntu 20
- Nginx

When I raising processes to 3 or 4, then I'll giving  status "Pending" from my websocket. If processes only one, then all good. Why?

**Comment by walkor** [comment]
Multi process does not reduce CPU busy, on the contrary, it may consume more CPU than a single process.
Multi process is generally used to make full use of multiple CPUs of the server.
If your server has only one CPU, using a single process is a good choice.
