### ISSUE TITLE
STARTTLS

### ISSUE THREAD

**Issue by areebmajeed** [walkor/Workerman#684]
I am trying to implement an SMTP server and trying to initialize a TLS handshake.

My worker is defined as such.

```
$context = array(
    'ssl' => array(
        'local_cert' => '../ssl/fullchain.pem',
        'local_pk' => '../ssl/privkey.pem',
        'verify_peer' => false,
        'allow_self_signed' => true,
    )
);

$tcp_worker = new Worker('tcp://0.0.0.0:2528', $context);
```

And, when the user requests to upgrade to a TLS connection by sending the STARTTLS connection. The following code is executed.

```
        $socket = $connection->getSocket();

        $crypto_method = STREAM_CRYPTO_METHOD_TLS_SERVER;

        if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_SERVER')) {
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_SERVER;
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_SERVER;
        }

        stream_set_blocking($socket, true);
        $result = stream_socket_enable_crypto($socket, true, $crypto_method);
        stream_set_blocking($socket, false);

        if ($result === false) {
            SMTPClient::sendTLSFailure($connection);
        }
```

Unfortunately, the result is always FALSE and the following error is printed on the screen.

PHP Warning:  stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number in /root/SMTPd/src/Session.php on line 123

There's not an issue with the SSL certificates as I temporarily switched from a TCP server to the HTTP server (with SSL enabled). It worked fine without any issues.

**Comment by areebmajeed** [comment]
Never mind, it seems to work. My bad!

**Comment by HeroSony** [comment]
How did you fix the issue?
