### ISSUE TITLE
The TcpConnection class obtains the client IP and port, making it easier

### ISSUE THREAD

**Issue by twomiao** [walkor/Workerman#685]
> Can be obtained like this

` /**
     * Get remote IP.
     *
     * @return string
     */
    public function getRemoteAddress()
    {
        $remoteAddress = parse_url($this->remoteAddress, PHP_URL_HOST);
        return ($remoteAddress === false) ? '' : $remoteAddress;
    }`

**Comment by walkor** [comment]
Workerman already has `getRemoteAddress` methods.
```php
    /**
     * Get remote address.
     *
     * @return string
     */
    public function getRemoteAddress()
    {
        return $this->_remoteAddress;
    }
```
 It is simple enough that there is no need to change it.

**Comment by twomiao** [comment]
/**
     * Get remote IP.
     *
     * @return string
     */
    public function getRemoteIp()
    {
        $remote_ip = parse_url($this->_remoteAddress, PHP_URL_HOST);
        return ($remote_ip === false) ? '' : $remote_ip;
    }

> Is this method

**Comment by twomiao** [comment]
> Workerman already has `getRemoteAddress` methods.
> 
> ```
>     /**
>      * Get remote address.
>      *
>      * @return string
>      */
>     public function getRemoteAddress()
>     {
>         return $this->_remoteAddress;
>     }
> ```
> 
> It is simple enough that there is no need to change it.

    /**
     * Get remote IP.
     *
     * @return string
     */
    public function getRemoteIp()
    {
        $remote_ip = parse_url($this->_remoteAddress, PHP_URL_HOST);
        return ($remote_ip === false) ? '' : $remote_ip;
    }

> getRemoteIp() and getRemotePort() methods

**Comment by walkor** [comment]
The current implementation is simple enough . I don't think it's necessary to change it unless it has a bug.
