### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Lukaum** [walkor/Workerman#687]
Im using workerman websocket in wamp server (apache, mysql, php). So i maked some configuration, to enable my mobile can access the server with ipv4 address. 

The problem is: When i access from my computer (the server), workerman listen the connection (all ok), but when i enter with mobile, workerman cant listen this.

Its can be a problem with some workerman configuration? How can i resolve?

**Comment by walkor** [comment]
I'm not sure why.
If your network environment supports IPv6, try to let workman listen IPv4 and IPv6 at the same time which codes may like this.
```
$worker = new Worker('websocket://[::]:8080');
```
Incidentally, workman should be started using the command line, similar to 'php start.php start' or 'php start.php start - d' as daemon.

**Comment by Lukaum** [comment]
@walkor I tried, but unsuccessful.  Only changed the port, because i didnt uderstanding the [::] in your answer. 

How i start the workerman (in cmd):
```
> cd path_folder
> php websocket.php
```

My worker now:
`$ws_worker = new Worker('websocket://***.***.***.***:8080');`

The mask `***.***.***.***` refers to the ipv4, i tried to access with mobile (multiple tests with browsers) and keep having the same problem, workeman cant listen connections that comes from outside devices, only connections in the sever (my computer, that running the script).

Javascript:
`var conn = new WebSocket('ws://192.168.1.144:8080');`

**Comment by xpader** [comment]
Looks like your port `8080` was blocked by firewall.
You should test can you access other port from your device.
You can visit your service from local machine because firewall not block localhost.

**Comment by Lukaum** [comment]
@xpader For other devices (mobiles that i tested),i access my pages without a problem (css, html and js working ok).
Apache running on port 80.
