### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Gonzo2O28** [walkor/Workerman#688]
Hey i am new to Workerman. And new to ininite loops as well.
I am successfully opening and connecting to the websocket due nginx and /ws location on my test machine.

But as soon as i start an infinite while-loop inside "$ws_worker->onMessage" it does not respond to new messages coming from javascript anymore. 
This infinite while-loop is needed to check for new messages in a chat application. 

I read the wiki, used Google and have no idea where to start. 
Ideas? Suggestions?

Thank you very much.

**Comment by walkor** [comment]
You can use Timer to replace with while-loop.

**Comment by Gonzo2O28** [comment]
Okay, do you have an example of it?
i thought i could send a json message to the "onMessageEvent" and then response with an infinite loop.
This works but the connection does not response to anything else than anymore which is ...bad ;).

**Comment by walkor** [comment]
```php
use Workerman\Worker;
use Workerman\Timer;
$worker = new Worker('websocket://0.0.0.0:1234');
$worker->onMessage = function($con, $data) {
      if (empty($con->timer)) {
         $time_interval = 1; // one second
         Timer::add($time_interval, function() use ($con){
                 $con->send('hi');
         });
      }
};
$worker->onClose = function($con){
    if (empty($con->timer)) {
        Timer::del($con->timer);
    }
};
Worker::runAll();
```

**Comment by walkor** [comment]
I believe this has been answered, so I'm closing this for now. 
Please come back with more details if this problem persists and we can reopen this
