### ISSUE TITLE
how to run on sub domin

### ISSUE THREAD

**Issue by amirfaramarzi** [walkor/Workerman#689]
hi @walkor 

How can a worker be run on a subdomain ??(linux)

Without using nginx and apache

**Comment by walkor** [comment]
Generally, workerman doesn't need to do anything.
As long as the IP pointed to by the subdomain name is correct.

**Comment by walkor** [comment]
I think the easiest solution is to add an nginx proxy.

**Comment by amirfaramarzi** [comment]
Does not use nginx proxy affect workerman performance?

**Comment by walkor** [comment]
Nginx has very good performance, and the performance impact can be ignored in most cases.

**Comment by amirfaramarzi** [comment]
Thank you @walkor
