### ISSUE TITLE
建议把所以require_once去掉改用namespace

### ISSUE THREAD

**Issue by gouchaoer** [walkor/Workerman#69]
require_once的性能很差，而且我相信需要用require的地方都可以用namespacr来代替

**Comment by gouchaoer** [comment]
等等。。。worker常驻内存的话这点时间不用考虑。。。好吧，不用改了

**Comment by walkor** [comment]
require_once性能很差是个错误的理论。
即使用了namespace，代码加载也是通过require\include\require_once\include_once加载的，没有多少区别。

另外workerman代码只会在启动时加载，以后就长驻内存了，不会重复运行require_once，没有任何性能影响。
