### ISSUE TITLE
socket_get_option on a Unix socket

### ISSUE THREAD

**Issue by toonvd** [walkor/Workerman#692]
Hi

Thank you for the awesome library.

Is the unix socket exposed somewhere? I get the stream socket when grabbing it from the connection: `req->connection->getSocket()`.
I want to get the `SO_PEERCRED` option to check what user connected to the UDS.

**Comment by walkor** [comment]
It has been added to the master and is expected to be released with version 4.0.26 in a few days

**Comment by toonvd** [comment]
Thanks, closing already!
