### ISSUE TITLE
Sending strings are buffered within the function???

### ISSUE THREAD

**Issue by kenw232** [walkor/workerman#699]
I have a strange problem with Workerman.  When its running under wss://  the sends within the functions are buffered.  Does anyone know why this is happening?  It happens on all versions of PHP we have.

```
Workerman version: 4.0.25          PHP version: 8.0.13
proto    user           worker          listen                                                    processes    status           
ssl       root           none             websocket://mydomain.com:25003    4                  [OK]
```

The server does this when a message is received:
```
    $wsWorker->onMessage = function ($connection, $data) 
    {
        $connection->send('Sending Data 1 (this should happen five seconds BEFORE 2...)');
        usleep(5000000);
        $connection->send('Sending Data 2...');
        ...
```
        
But the problem is Sending Data 1 and Sending Data 2 happen at the SAME time, not 5 seconds part.  The server does wait 5 seconds, but the client (web page) does not receive the message 5 seconds part.  Why?  And this only happened when we switched from ws: to wss: for SSL to make Chome work.
Same problem was posted here: https://issueexplorer.com/issue/walkor/Workerman/324

**Comment by walkor** [comment]
Do not use sleep/usleep in workerman which will block the process and workerman cannot get operation control and cannot perform send operation. The internal implementation of WS and WSS is a little different, but the most fundamental reason is that the process is blocked by the sleep function and the workerman cannot perform any operation.

Please replace usleep with a timer code may like this.
```php
 $connection->send('Sending Data 1 (this should happen five seconds BEFORE 2...)');
 usleep(5000000);
Workerman\Timer::add(5, function()use($connection){
    $connection->send('Sending Data 2...');
}, null ,false);
```
