### ISSUE TITLE
主进程如何同子进程共享数据

### ISSUE THREAD

**Issue by jackyxie** [walkor/Workerman#70]
使用过程中，发现onWorkerStart里面无法使用主进程中定义的常量。也无法直接在onWorkerStart里面引入文件定义的变量。有什么特定的引入方法吗？

**Comment by walkor** [comment]
贴代码

**Comment by hetao29** [comment]
这和workerman没有关系吧，直接global引有就行了

**Comment by jackyxie** [comment]
require_once 'conf/config.php';

	$worker = new Worker();
	
	//创建子进程的数目($markets是config里面的数组)
	$worker->count = count($markets);
	$worker->onWorkerStart = function ($worker) {
		Timer::add(0.5, 'taskGenerator', array('worker' => $worker, 'markets' => $markets));
	};

onWorkerStart里面的 $markets提示未定义

**Comment by jackyxie** [comment]
config.php
<?php
	$markets = array(
			'okc',
			'huob',
			'bitv',
	);

**Comment by walkor** [comment]
```php
require_once 'conf/config.php';
$worker = new Worker();
//创建子进程的数目($markets是config里面的数组)
$worker->count = count($markets);
$worker->onWorkerStart = function ($worker) {
    global $markets;
    Timer::add(0.5, 'taskGenerator', array('worker' => $worker, 'markets' => $markets));
};
```
如jackyxie所说，加个global就行了。
见php手册：http://php.net/manual/zh/language.variables.scope.php

**Comment by jackyxie** [comment]
嗯，使用global是可以。我还有另外一个问题：比如我有一个数组，数组里面的每一个元素我想用一个进程处理，workman要怎么实现啊？

**Comment by MINORITYmaN** [comment]
hi, or use global variables:
```
require_once 'conf/config.php';
$worker = new Worker();
//创建子进程的数目($markets是config里面的数组)
$worker->count = count($markets);
$worker->onWorkerStart = function ($worker) {
    Timer::add(0.5, 'taskGenerator', array('worker' => $worker, 'markets' => $GLOBALS['markets']));
};
```
kind regards, stefano
