### ISSUE TITLE
Get Headers in the onConnect callback

### ISSUE THREAD

**Issue by toonvd** [walkor/workerman#702]
Hi

For authentication purposes, I would like to be able to see headers in the `onConnect` callback as opposed to the `onMessage` callback since connection is already established by then. Is there any possibility to pass request info along or make it fetchable from the connection?

**Comment by walkor** [comment]
`onConnect` means the establishment of a TCP connection. At this time, there is no data transmission, so the header cannot be obtained. If you use the websocket protocol, you can set the `onWebsocketConnect` callback, where you can get the http header. However, for the HTTP protocol, the header must be obtained in `onMessage`.

**Comment by toonvd** [comment]
Clear, thank you!
