### ISSUE TITLE
use lowercase in response

### ISSUE THREAD

**Issue by ging-dev** [walkor/workerman#705]
hi @walkor, i have build a Symfony [library](https://github.com/gingteam/workerman-runtime/blob/535f4d00caae5e0d350345e8968f8aec9830a65c/src/Runner.php#L80) and use Workerman, the problem is Workerman uses uppercase in response header, this causes duplication of some headers. So I suggest using lowercase characters in response headers.

![image](https://user-images.githubusercontent.com/42226341/147627564-4ef4d75a-7813-4a9a-a687-c86a4a0c36cd.png)

**Comment by walkor** [comment]
It is recommended that you uses uppercase hearder for your project. Initial capitalization is a standard and common practice and If workerman changes that for your project, it may cause problems in other projects that have already used workerman.

**Comment by ging-dev** [comment]
> It is recommended that you uses uppercase hearder for your project. Initial capitalization is a standard and common practice and If workerman changes that for your project, it may cause problems in other projects that have already used workerman.

I think nowadays most websites have response headers in lowercase. Some conditional statements like [this](https://github.com/walkor/workerman/blob/1fcdb58ab59769cecc343f0d1740712b4b4bd7d9/Protocols/Http/Response.php#L421) often miss lowercase cases.

![image](https://user-images.githubusercontent.com/42226341/147629051-36fa3e94-b030-46ec-ad17-ed7eccfcb4ef.png)

**Comment by walkor** [comment]
Sorry, we can't make this change because it may affect projects that already use workerman.

**Comment by xpader** [comment]
> > It is recommended that you uses uppercase hearder for your project. Initial capitalization is a standard and common practice and If workerman changes that for your project, it may cause problems in other projects that have already used workerman.
> 
> I think nowadays most websites have response headers in lowercase. Some conditional statements like [this](https://github.com/walkor/workerman/blob/1fcdb58ab59769cecc343f0d1740712b4b4bd7d9/Protocols/Http/Response.php#L421) often miss lowercase cases.
> 
> ![image](https://user-images.githubusercontent.com/42226341/147629051-36fa3e94-b030-46ec-ad17-ed7eccfcb4ef.png)

The response headers display as lowercase in browser because of protocol http/2.0, not becuase of the they code as lowercase.
Some header start with ":" because of header compress in http 2.0 protocol, when protocol downgrade to 1.1 or 1.0, the headers will display as first word uppercase.
I suggest still use uppercase of first word for header name, eg: 'Content-Type'.

**Comment by xpader** [comment]
You can try to proxy workerman by pass nginx, and set nginx protocol as http/2.0 (need ssl), all header will display as lowercase in browser.

**Comment by xpader** [comment]
@walkor I think workerman should consider to implement http/2.0 protocol.

**Comment by ging-dev** [comment]
> 

My problem is not uppercase or lowercase, workerman skips the lowercase check, resulting in having 'Content-Type' and 'content-type' on response headers.

**Comment by walkor** [comment]
@ging-dev If you want to change `Content-Type` header please use uppercase of first word in workerman.

@xpader `http/2.0 protocol` looks very complicated I'm not sure if I want to implement it in PHP. Maybe someone can achieve it. There may be other simpler ways, such as nginx proxy etc. I'm not sure.
