### ISSUE TITLE
Changing unix domain socket permissions

### ISSUE THREAD

**Issue by toonvd** [walkor/workerman#707]
Hi

I know we can change the socket group by setting the global group variable before running the workers.
However, I did not find an ideal place / method to change the socket permissions. I want my group to be able to read and write on my socket but no execute.

At the moment I (ab)use `onWorkerStart`:

```php
$api->onWorkerStart = function() {
    chmod('/tmp/socket.sock', '1660');
};
```

But this means the permission is set everytime a worker starts. Is there perhaps a possibility to either add a global var to set socket permissions or add an afterSocketCreate event here: https://github.com/walkor/workerman/blob/master/Worker.php#L2238?

**Comment by walkor** [comment]
I suggest putting the permission settings in `onWorkerStart`.

> But this means the permission is set everytime a worker starts.

The worker has an ID number. By judging the ID number, only one process can set permissions. The codes is similar to this.

```php
$api->onWorkerStart = function($worker) {
    if ($worker->id == 0) {
        chmod('/tmp/socket.sock', '1660');
    }
};
```

**Comment by toonvd** [comment]
Does the trick, thanks!
