### ISSUE TITLE
Repeat the loop by some workers

### ISSUE THREAD

**Issue by amirfaramarzi** [walkor/workerman#710]
hi @walkor 

I have a database entry program that uses 8 workers

In the program, a for loop is used, which is responsible for entering information (a line is added with each loop rotation).

Sometimes the system randomly repeats each loop two or more times (instead of the loop being executed only once, it is also executed by other workers, for example, the second loop is executed three times)

This happens in some cases and most of the time the program works properly

My question is, is there a problem with my program ??

And how can this problem be solved?

**Comment by walkor** [comment]
Sorry. From the information you provided, I can't determine whether there is a problem with your program and can't give any comments.

**Comment by amirfaramarzi** [comment]
In general, when we use several workers

Are the loops run separately by each worker?

**Comment by walkor** [comment]
Yes

**Comment by amirfaramarzi** [comment]
Thanks @walkor
