### ISSUE TITLE
onWorkerStop的疑问

### ISSUE THREAD

**Issue by jackyxie** [walkor/Workerman#72]
我在定时器指定的方法里面设置了运行次数的检查，达到次数的时候，执行Worker::stopAll()。但是发现这样使用，无法启用新的进程来处理。

我主要用来在服务器跑后台数据。(下面我写的大概结构)

$worker->count = n;
$worker->onWorkerStart() = function ($worker) {
    Timer::add(0.5, 'taskGenerator', array());
}

taskGenerator(){
    static $runtimes = 0;
    $runtims++;

    //do some logic

    if ($runtimes > MAX_RUNTIMES) {
        Worker:stopAll();
    }
}

**Comment by walkor** [comment]
```$runtims++;```
单词拼写错了

**Comment by jackyxie** [comment]
代码里面是正确的，这里打错了

**Comment by walkor** [comment]
你可以试下 http://doc3.workerman.net/worker-development/stop-all.html 文档中的示例，看下是否正常。
如果正常，请检查下自己的业务逻辑，打印下日志，看下是否执行到了Worker:stopAll();

你贴的代码有语法错误，最好自己试下代码正确性在贴上来，这样大家都节省时间。
