### ISSUE TITLE
CLI args, getopt support

### ISSUE THREAD

**Issue by josephscott** [walkor/workerman#743]
I was looking for ways to pass command line arguments with workerman.  My initial tests with using getopt() didn't work, so I thought I'd ask if there is an established "workerman" approach to passing in command line args.

**Comment by walkor** [comment]
workerman uses `$argv` to pass command line parameters. 
https://github.com/walkor/workerman/blob/6c73788d4abfb6ac072462f7e9168ccbac4cd0c6/Worker.php#L880

**Comment by josephscott** [comment]
Ok, thank you.
