### ISSUE TITLE
timer bug The timer cannot be used

### ISSUE THREAD

**Issue by 1923998238** [walkor/workerman#753]
The timer is invalid when it is less than or equal to 1 second.
定时器的时间设置小于等于1秒时 定时器内函数在执行一次后会无延迟重复执行

```
<?php

require __DIR__ . './vendor/autoload.php';

use Workerman\Connection\AsyncTcpConnection;
$worker = new \Workerman\Worker();
$worker->onWorkerStart = function($worker){
    \Workerman\Timer::add(1, function (){
        echo 'H';
    });
};
\Workerman\Worker::runAll();
```
![image](https://user-images.githubusercontent.com/64238420/164982574-a0396227-7f0a-4dbd-81bb-68ea444fc87c.png)

**Comment by walkor** [comment]
感谢反馈，已经修复。
5.x的bug，不影响4.x版本。5.x目前还未发布，不要用于生产环境。
