### ISSUE TITLE
TypeError: Argument 1 passed to {closure}() must be an instance of TcpConnection, instance of Workerman\Connection\TcpConnection given

### ISSUE THREAD

**Issue by zgh419566** [walkor/workerman#754]
反馈一个问题，我使用workkerman做TCP服务器，同一服务器开启16个监听进程，经常会发现部分服务进程自动重启。
Workerman version:4.0.30 PHP version:7.3.22

反馈一个部分服务进程自动重启的问题，怀疑是Workerman有bug，可以帮解答一下吗？
从信息来看，我怀疑客户端在给服务器端发送信息的过程后，服务器还没有来得及回复，然后客户端就已经断开，导致服务器端发送数据异常。

报错信息如下 ：
Warning: (null)(): supplied resource is not a valid stream resource in Unknown on line 0

2022-04-13 09:26:28 pid:112045 TypeError: Argument 1 passed to {closure}() must be an instance of TcpConnection, instance of Workerman\Connection\TcpConnection given, called in /www/app/vendor/workerman/workerman/Connection/TcpConnection.php on line 370 and defined in /www/app/start_tcp_dzxsz.php:339
Stack trace:
#0 /www/app/vendor/workerman/workerman/Connection/TcpConnection.php(370): {closure}(Object(Workerman\Connection\TcpConnection), 2, 'client closed')/www/app/start_tcp_dzxsz.php(842): Workerman\Connection\TcpConnection->send('AWiTkJncYJJ/Cy/...')
#2 /www/app/vendor/workerman/workerman/Connection/TcpConnection.php(659): {closure}(Object(Workerman\Connection\TcpConnection), 'AWiTkJncYJJ/Cy/...') **
#3 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #9043, 2, Resource id #9043)
#4 /www/app/vendor/workerman/workerman/Events/Event.php(193): EventBase->loop()
#5 /www/app/vendor/workerman/workerman/Worker.php(2431): Workerman\Events\Event->loop()
#6 /www/app/vendor/workerman/workerman/Worker.php(1555): Workerman\Worker->run()
#7 /www/app/vendor/workerman/workerman/Worker.php(1397): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#8 /www/app/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkWorkersForLinux()
#9 /www/app/vendor/workerman/workerman/Worker.php(1692): Workerman\Worker::forkWorkers()
#10 /www/app/vendor/workerman/workerman/Worker.php(1641): Workerman\Worker::monitorWorkersForLinux()
#11 /www/app/vendor/workerman/workerman/Worker.php(551): Workerman\Worker::monitorWorkers()
#12 /www/app/start_tcp_dzxsz.php(931): Workerman\Worker::runAll()
#13 {main}
2022-04-13 09:26:29 pid:1923 worker[dzxsz_server:112045] exit with status 64000

**Comment by walkor** [comment]
头部加一个
use Workerman\Connection\TcpConnection;
