### ISSUE TITLE
Is this bug when I use Tcpconnection->send()  with OnError?

### ISSUE THREAD

**Issue by zgh419566** [walkor/workerman#757]
Is this bug when I use Tcpconnection->send()  with OnError?
I use workman as tcp server to serve for thousand of device, 
A program exit occurs by accident with log blow:
`2022-04-26 22:41:08 pid:193269 TypeError: Argument 1 passed to {closure}() must be an instance of TcpConnection, instance of Workerman\Connection\TcpConnection given, called in /www/app/vendor/workerman/workerman/Connection/TcpConnection.php on line 370 and defined in /www/app/ynyddzxsz/start_tcp.php:340
2022-04-26 22:41:08 pid:193257 worker[dzxsz_server:193269] exit with status 64000`
**it got better when I commented out the code with worker->onError**

**Comment by walkor** [comment]
[reduplicated](https://github.com/walkor/workerman/issues/754)
