### ISSUE TITLE
Add a pipe server

### ISSUE THREAD

**Issue by stunningpixels** [walkor/Workerman#76]
Really cool functionality would be the ability to have a server that can react to BASH stdin, so onMessage gets called every time a process writes to the pipe. I've tried to implement this myself but i'm really stuck!

**Comment by walkor** [comment]
stdin.php
```php
<?php
require_once /your/path/Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Connection\TcpConnection;

$worker = new Worker();
$worker->onWorkerStart = function($worker)
{
    $con = new \Workerman\Connection\TcpConnection(STDIN);
    $con->onMessage = function($con, $msg){
        echo "recv form stdin: $msg";
    };
};
Worker::runAll();
```

Run with command ```php stdin.php start``` and type some words you will see the result.
It looks strange bug works.

**Comment by stunningpixels** [comment]
That works pretty well, what about having multiple open pipes? How can you write to the STDIN if it's demonised

**Comment by walkor** [comment]
Who write pipes?

**Comment by stunningpixels** [comment]
For example if I were to run
`exec("./script")`
And get the output STDOUT of the script to call `$con->onMessage`

**Comment by walkor** [comment]
Here is an example for STDOUT of htop pipe to $con->onMessage. May be will help.
```php
<?php
require_once  '/your/path/Workerman/Autoloader.php';
use Workerman\Worker;
use Workerman\Connection\TcpConnection;

$worker = new Worker();
$worker->onWorkerStart = function($worker) {
    $con = new TcpConnection(popen('htop', 'r'));
    $con->onMessage = function($con, $data) {
        echo "recv from pipe: $data";
    };
};
Worker::runAll();
```
