### ISSUE TITLE
关于$request->file()方法的疑惑

### ISSUE THREAD

**Issue by topyao** [walkor/workerman#767]
```php
 dump($request->file());
```

如上代码，请求如下

![image](https://user-images.githubusercontent.com/64066545/172050458-b8d7ae17-cc5e-4de5-b517-2e892b60eb8f.png)

解析到的数据

^ array:1 [
  "file" => array:5 [
    "name" => array:6 [
      0 => "20211207_20145862_avatar.png.jpg"
      "name" => "20211207_20145862_avatar.png.jpg"
      "tmp_name" => "/tmp/workerman.upload.jU7xLm"
      "size" => 795559
      "error" => 0
      "type" => "image/jpeg"
    ]
    "tmp_name" => "/tmp/workerman.upload.dkhsfo"
    "size" => 795559
    "error" => 0
    "type" => "image/jpeg"
  ]
]

这个有些疑惑，第一个文件的name出现在了name里面下标为0。并且用$request->file('name');拿不到name的值

对比fpm模式下：

```php
^ array:1 [
  "file" => array:6 [
    "name" => array:1 [
      "name" => "20211207_20145862_avatar.png.jpg"
    ]
    "full_path" => array:1 [
      "name" => "20211207_20145862_avatar.png.jpg"
    ]
    "type" => array:1 [
      "name" => "image/jpeg"
    ]
    "tmp_name" => array:1 [
      "name" => "/tmp/phpZ6ERzP"
    ]
    "error" => array:1 [
      "name" => 0
    ]
    "size" => array:1 [
      "name" => 795559
    ]
  ]
]
```

结构更清晰

**Comment by walkor** [comment]
因为上传了一个文件，和一个文件数组，文件和文件数组的key冲突了。fpm看起来是把冲突的文件数组部分的上传给丢弃了，只保留了一个文件，严格来讲是数据丢失了。webman保留了2个文件，但是因为你使用了name为数组的key，整个文件数组看起来比较奇怪。

如果你只上传一个文件直接用 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/6073368/172055091-970de710-4667-4ace-aed8-9fd526c4564c.png">
即可。
获取上传文件时使用 `$requeset->file('file')`;

上传多个文件用 
file[]
file[]
这样的表单
