### ISSUE TITLE
Worker class code optimization

### ISSUE THREAD

**Issue by twomiao** [walkor/workerman#774]
### test code:
`
$worker = new Worker("http://0.0.0.0:7222");
$worker->count = 4  ;
$worker->onWorkerStart = function ()
{
};

\Workerman\Worker::runAll();
`
### operation result:
------------------------------------------ WORKERS ------------------------------------------
proto   user            worker          listen                 processes    status
tcp     meows           none            http://0.0.0.0:7222    4             [OK]
---------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.
array(0) {
}
array(0) {
}
array(0) {
}
array(0) {
}
Workerman[start.php] reloading
array(4) {
  [1753]=>
  int(1753)
  [1754]=>
  int(1754)
  [1755]=>
  int(1755)
  [1756]=>
  int(1756)
}
array(3) {
  [1754]=>
  int(1754)
  [1755]=>
  int(1755)
  [1756]=>
  int(1756)
}
array(2) {
  [1755]=>
  int(1755)
  [1756]=>
  int(1756)
}
array(1) {
  [1756]=>
  int(1756)
}

### Code optimization:
>> elseif (0 === $pid) {
      \srand();
      \mt_srand();
      if ($worker->reusePort) {
          $worker->listen();
      }
     static::$_pidsToRestart = static::$_pidMap  = []; // reload old data memory release
      .......
}

**Comment by xpader** [comment]
What is that???
