### ISSUE TITLE
WS协议onMessage回调函数问题？

### ISSUE THREAD

**Issue by leconsc** [walkor/Workerman#78]
为什么WebSocket Client（WS协议）连接后，针对onMessage回调，必须事前在onConnect里先呼叫：
$connection->send('message')， 否则onMessage不回有任何消息回应。以下是我的代码。

$ws_worker = new Worker("websocket://0.0.0.0:2347");
// 启动4个进程对外提供服务
$ws_worker->count = 4;

$ws_worker->uidConnections = array();

// 当收到客户端发来的数据后返回hello $data给客户端
$ws_worker->onConnect = function($connection)
{
    process($connection);
};

function process($connection)
{
    $wsConnection = new AsyncTcpConnection('ws://127.0.0.1:2346');
    
    $wsConnection->onConnect = function($conn){
         $conn->send('hello'); //如果没有这一句，下面的onMessage不回收到任何回复。
    };
    $wsConnection->onMessage = function($conn, $data) {
         echo 'receive:'.$data;
    };
    // 连接上发生错误时，一般是连接远程websocket服务器失败错误
    $wsConnection->onError = function($conn, $code, $msg){
        echo "error: $msg\n";
    };
    // 当连接远程websocket服务器的连接断开时
    $wsConnection->onClose = function($conn){
        echo "connection closed\n";
    };
    // 设置好以上各种回调后，执行连接操作
    $wsConnection->connect();
}
// 运行worker
Worker::runAll();
以下是另外一个websocket代码：
===========================================================

// 创建一个Worker监听2346端口，使用websocket协议通讯
$ws_worker = new Worker("websocket://0.0.0.0:2346");

// 启动4个进程对外提供服务
$ws_worker->count = 3;

// 当收到客户端发来的数据后返回hello $data给客户端
$ws_worker->onConnect = function ($connection) {
    echo "connection successful\n";
    process($connection);
};

function process($connection)
{
    $time_interval = 3;
    Timer::add($time_interval, function () use ($connection) {
        static $i = 1;
        $connection->send('dds-'. $i . "\n");
        $i++;
    });
}

// 运行worker
Worker::runAll();

**Comment by walkor** [comment]
这个问题是已知的，把workerman作为websocket客户端，客户端这一侧必须发送数据，才能触发websocket握手，才能建立起链接。
@leconsc 可以先这么用着，这个问题后面优化

**Comment by leconsc** [comment]
谢谢。

**Comment by walkor** [comment]
Workerman主分支已经优化解决

**Comment by leconsc** [comment]
好的。

**Comment by jbkingsley** [comment]
这个问题刚好碰到，真是太巧了，感谢

**Comment by walkor** [comment]
不客气
