### ISSUE TITLE
Daemon mod trouble

### ISSUE THREAD

**Issue by vchernysh** [walkor/workerman#787]
Hi. I want to run worker like a daemon, but I get only debug.

I use yii2 advanced template.
My action is next:
`php yii websockets/listen start`

I've tried run:
1. `php yii websockets/listen start&` -> get debug and worker runs (closing terminal provide close socket server)
2. `php yii websockets/listen start -d` -> get an error: `Error: Unknown alias: -d. Aliases available: -h (--help)`

`-h` get me next:

```
Usage: php yourfile <command> [mode]
Commands: 
start           Start worker in DEBUG mode.
                Use mode -d to start in DAEMON mode.
stop            Stop worker.
                Use mode -g to stop gracefully.
restart         Restart workers.
                Use mode -d to start in DAEMON mode.
                Use mode -g to stop gracefully.
reload          Reload codes.
                Use mode -g to reload gracefully.
status          Get worker status.
                Use mode -d to show live status.
connections     Get worker connections.
```
Why daemon mode does not work?
And why I haven't alias `-d` like in your README.md?

**Comment by walkor** [comment]
It seems that Yii cannot recognize the `-d` option, so Yii reports an error.
The simplest solution is to use nohup.
`nohup php yii websockets/listen start`

**Comment by vchernysh** [comment]
Fix it via `screen`. Thanks.
