### ISSUE TITLE
4.0.41版本 和 webman framework 结合使用时候无法正确识别数组参数

### ISSUE THREAD

**Issue by onetobig** [walkor/workerman#788]
php版本：PHP 8.0.17 

可以正确识别的环境：
workman 版本：4.0.39
webman 版本：1.3.20

![微信截图_20220729143653](https://user-images.githubusercontent.com/21326984/181698667-b6384616-4a63-448d-ba4c-9bd61324ddd0.png)

识别错误的环境：
workman 版本：4.0.41
webman 版本：1.3.20

![微信截图_20220729143749](https://user-images.githubusercontent.com/21326984/181698956-79fc7144-9452-4aad-9845-ea4077b04bde.png)

**Comment by walkor** [comment]
感谢反馈，已经修复，请更新到 workerman 4.0.42
