### ISSUE TITLE
目前是不是仅支持ws协议， 其安全协议wss什么时候支持呢？

### ISSUE THREAD

**Issue by leconsc** [walkor/Workerman#79]

**Comment by walkor** [comment]
wss只需要用nginx在ws前做一层ssl代理即可

**Comment by leconsc** [comment]
主要是client端是不需要nginx的，是直接希望通过wss来打开websocket连接的。因为我是在命令行下运行的。

**Comment by walkor** [comment]
不是在client端运行nginx，在服务端，除了连接时用wss客户端不用任何操作。
nginx开个端口代理ssl，wss经过这个nginx代理后数据就是ws的数据了，nginx把这个数据转发给workerman。

**Comment by leconsc** [comment]
我的意思是现在我已经有一个wss的websocket的service, 我需要通过AsyncTcpConnection作为客户端连接上去。但是现在Client仅支持ws协议，不支持wss协议。

**Comment by walkor** [comment]
哦，抱歉。我理解错了，以为你要workerman作为wss服务端。
workerman作为wss客户端，代码类似如下，就是加一句`$con->transport = 'ssl';`
```php
$con = new AsycnTcpConnection('ws://x.x.x.x:xx');
$con->transport = 'ssl';
$con->onXXX(.....
```
见手册 http://doc3.workerman.net/worker-development/async-tcp-connection-transport.html

要求workerman版本>=3.3.3

**Comment by leconsc** [comment]
好的。謝謝

**Comment by walkor** [comment]
不客气

**Comment by tjliu912** [comment]
workerman作为wss客户端，代码类似如下，就是加一句$con->transport = 'ssl';

$con = new AsycnTcpConnection('ws://x.x.x.x:xx');
$con->transport = 'ssl';
$con->onXXX(.....


ws://x.x.x.x:xx . 后面的部分是 port 一定是设定443吗？

// 这里设置的是websocket协议
$worker = new Worker('websocket://0.0.0.0:2022', $SSL_setting);
我这边设定port 为 2022 ，客户端连结时，不用设定成2022吗？

参考文档：http://doc3.workerman.net/faqas-wss-client.html
