### ISSUE TITLE
关于daemon启动的问题

### ISSUE THREAD

**Issue by tab-engineer** [walkor/workerman#795]
php bin/workerman.php start -d

启动后

php bin/workerman.php stop

报以下错误

PHP Fatal error:  Uncaught TypeError: (null)(): supplied resource is not a valid stream resource in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0

环境：
PHP 8.1.7 (cli) (built: Jun 10 2022 12:03:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies

**Comment by walkor** [comment]
可能是swoole影响的，暂时屏蔽试下

**Comment by tab-engineer** [comment]
屏蔽了，不报错了👍
