### ISSUE TITLE
send data in onConnect in tcp/ip

### ISSUE THREAD

**Issue by shahramomidvar** [walkor/workerman#797]
Hello, I need to check whether the user has permission when he opens the connection ( Tcp /ip ) , so I need data to be sent to check, how can I use it? Thank you for helping me

**Comment by walkor** [comment]
$worker->onMessage = function($connection, $data) {
    if (empty($connection->uid)) {
        if ($uid = your_check_ permission($data)) {
            $connection->uid = $uid;
            return;
        }
        $connection->close('no permission');
        return;
    }
     
    // has permission and get uid
    $uid = $connection->uid;
    // ......
};

**Comment by shahramomidvar** [comment]
Thanks
