### ISSUE TITLE
pcntl_signal ignored? How to handle SIGINT behavior?

### ISSUE THREAD

**Issue by cayolblake** [walkor/workerman#798]
Hi @walkor 

I am trying to intercept SIGINT to handle the behavior of CTRL+C, and execute a series of routines before terminating.

Doing the following just works in any normal script I have.

```
<?php
pcntl_async_signals(true);
pcntl_signal(SIGINT,function(){echo "received SIGINT";});
pcntl_signal(SIGSEGV,function(){echo "received SIGSEGV";});
```

Unfortunately its not working if using Workerman.

I also tried using

```
\Workerman\Worker::$onMasterStop = function () use ($p1, $p2) {
    // do op 1
    // do op 2
    // do op 3
};
```

But also unfortunately there're some sort of  rase condition that doesn't allow all routines to execute properly before terminating and only the first routine gets executed.

How you think this is could be achieved?

**Comment by walkor** [comment]
`\Workerman\Worker::$onMasterStop` works in the master process. May bie you should use $worker->onWorkerStop which works in the children processes.

**Comment by cayolblake** [comment]
That worked perfectly.

Thanks! 🤗
