### ISSUE TITLE
运行抛错

### ISSUE THREAD

**Issue by kaizhuQin** [walkor/workerman#8]
执行`./ workerman start`
出现下面的错误：
```
PHP Fatal error:  Call to undefined function posix_getpwuid() in /var/www/html/workerman-master/workerman/bin/workermand on line 92

Fatal error: Call to undefined function posix_getpwuid() in /var/www/html/workerman-master/workerman/bin/workermand on line 92
```

**Comment by moscorp** [comment]
Hi, 
php -m | grep posix
posix

The following error still happen, please help to solve!
PHP Fatal error:  Uncaught Error: Call to undefined function Workerman\posix_getpid() in wm/vendor/workerman/workerman/Worker.php:2081

**Comment by xpader** [comment]
不会是在 windows 上吧？

**Comment by moscorp** [comment]
不是，在synology Linux based 系統上裝的。
php -m | grep posix
posix
顕示有安裝posix的
