### ISSUE TITLE
我的workerman服务在运行时(start), 然后reload或restart都会出现异常情况，无法正常启动

### ISSUE THREAD

**Issue by leconsc** [walkor/Workerman#80]
我的环境是MacOS系统，PHP是5.5.37
我启动方法是： php app/workers/dssproxy.php start
显示结果如下：
Workerman[app/workers/dssproxy.php] start in DEBUG mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.3.4          PHP version:5.5.37
------------------------ WORKERS -------------------------------
user          worker        listen                    processes status
chenbin       none          websocket://0.0.0.0:2347   4         [OK] 
----------------------------------------------------------------
Press Ctrl-C to quit. Start success

现在通过ps -ef | grep "dssproxy.php" | grep -v "grep", 结果如下：
  501 14662  4058   0 10:17上午 ttys002    0:00.05 php app/workers/dssproxy.php start
  501 14663 14662   0 10:17上午 ttys002    0:00.16 php app/workers/dssproxy.php start
  501 14664 14662   0 10:17上午 ttys002    0:00.16 php app/workers/dssproxy.php start
  501 14665 14662   0 10:17上午 ttys002    0:00.16 php app/workers/dssproxy.php start
  501 14666 14662   0 10:17上午 ttys002    0:00.16 php app/workers/dssproxy.php start

现在我使用： php app/workers/dssproxy.php reload(在另一终端), 结果如下：
Workerman[app/workers/dssproxy.php] reload 
Workerman[app/workers/dssproxy.php] reload

现查看另一终端，结果如下：（start时的终端）
Workerman[app/workers/dssproxy.php] start in DEBUG mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.3.4          PHP version:5.5.37
------------------------ WORKERS -------------------------------
user          worker        listen                    processes status
chenbin       none          websocket://0.0.0.0:2347   4         [OK] 
----------------------------------------------------------------
Press Ctrl-C to quit. Start success.
Segmentation fault: 11

这个时候出现11的错误，并且回到命令行状态
现在再通过ps -ef | grep "dssproxy.php" | grep -v "grep", 结果如下：
  501 14663     1   0 10:17上午 ttys002    0:00.24 php app/workers/dssproxy.php start
  501 14664     1   0 10:17上午 ttys002    0:00.24 php app/workers/dssproxy.php start
  501 14665     1   0 10:17上午 ttys002    0:00.24 php app/workers/dssproxy.php start
  501 14666     1   0 10:17上午 ttys002    0:00.24 php app/workers/dssproxy.php start
从上看应该是master部分被kill掉了，而且现在无法start或restart, 因为port仍占用着，用下列命令：
php app/workers/dssproxy.php restart
报错： stream_socket_server(): unable to connect to tcp://0.0.0.0:2347 (Address already in use) 

请问这是什么原因？reload要怎么操作？应该注意些什么？

**Comment by walkor** [comment]
Segmentation fault: 11
说明某个扩展有bug，你看下是不是用了什么特殊的扩展，可以把不要的扩展都卸载掉。

**Comment by leconsc** [comment]
我运行其它程序，没有什么问题啊，只是在reload时，才出错。而且我的代码中也没有用其它扩展

**Comment by walkor** [comment]
你看看你的livevent扩展版本是不是太低了。

**Comment by leconsc** [comment]
我现在本地libevent是最新的2.0.22，php模块有:
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mcrypt
memcache
memcached
mhash
mysql
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib
但是仍旧有以上错误。

**Comment by walkor** [comment]
可以把libevent扩展卸载掉看看是不是libevent扩展问题，另外libevent扩展官方最新版本是0.1.0。
http://pecl.php.net/package/libevent

**Comment by leconsc** [comment]
1. 我刚才发现最初我没有安装php55-libevent
2. 刚才编译安装了libevent 0.1.0, 仍旧一样的错误，可能还是其它什么bug
还有没有其它什么可能造成这个错误？

**Comment by walkor** [comment]
那可能是php的bug，换个php版本试下吧
