### ISSUE TITLE
Sending a big message

### ISSUE THREAD

**Issue by Schtil** [walkor/workerman#806]
Greetings

I'm trying to implement sending messages by examples and ran into a problem

The messages I send to tcp://127.0.0.1:1234 are quite long, about 100k characters each
And it doesn't work very well.

With code
```
 $inner_tcp_worker = new Worker("tcp://127.0.0.1:1234");
 $inner_tcp_worker->onMessage = function($connection, $data) use (&$users) {
 var_dump($data);
 $data = json_decode($data,1);
 ....
```
I realized that I receive fragmentary messages, not entirely

What I tried to do:

1) Increased READ_BUFFER_SIZE constant to 1024*1024
2) When sending, increased the write buffer `stream_set_write_buffer($instance, 1024*1024*1024);`
3) And like this `fwrite($instance, json_encode($message), 1024*1024*1024);`
4) Edited php.ini and increased various limits

But it doesn't help

Where am I wrong?)

**Comment by walkor** [comment]
TCP is flow based and has no data boundary.
The program needs to buffer all data and confirm whether the data is received.
Generally, the length information needs to be placed in the message header, such as the `content-length` of the http protocol.

**Comment by Schtil** [comment]
Do you mean that the handler inside the Workerman should buffer the data?
```
 $inner_tcp_worker->onMessage = function($connection, $data) use (&$users) {
 ...
 }
 ```

**Comment by Schtil** [comment]
As a result, I used not TCP but WS connection for transmission
Thanks
