### ISSUE TITLE
Epoll异步非阻塞

### ISSUE THREAD

**Issue by xiabin** [walkor/Workerman#81]
Epoll到底是异步非阻塞 还是同步阻塞了?
从进程的角度来看 会一直被select所阻塞，但是从这个应用的角度来看，比如socket是非阻塞的 这样好像有觉得是是非阻塞的

或者说这个异步阻塞说定义是从epoll的实现原来上来说的。

不是很明白的是 网上对epoll有两种说法 不知道你怎么看

**Comment by walkor** [comment]
Epoll和同步/异步没直接关系，阻塞还是非阻塞看实际调用参数。

**Comment by xiabin** [comment]
但是epoll在调用的时候不会阻塞整个程序吗

**Comment by xiabin** [comment]
从理论上是会的 并不是真正的异步的回调只是从应用上来说某种意义上是异步回调或者异步非阻塞吧
