### ISSUE TITLE
sapi_windows_set_ctrl_handler 无法使用

### ISSUE THREAD

**Issue by crazywhalecc** [walkor/workerman#817]
## 问题
sapi_windows_set_ctrl_handler 无法使用

## 复现
直接使用 PHP 官方提供的样例代码，可以正常运行并提示和关闭：

```php
function ctrl_handler(int $event)
{
    switch ($event) {
        case PHP_WINDOWS_EVENT_CTRL_C:
            echo "You have pressed CTRL+C\n";
            exit(0);
            break;
        case PHP_WINDOWS_EVENT_CTRL_BREAK:
            echo "You have pressed CTRL+BREAK\n";
            break;
    }
}

sapi_windows_set_ctrl_handler('ctrl_handler');
while(true);
```

将其放到 Workerman 环境中运行，放到 `Worker::runAll()` 前可以正常启动 Workerman，但此时按 Ctrl+C 没有任何反应，只能通过任务管理器结束进程。（放到 `onWorkerStart` 下 set 也是一样的效果）

## 环境
- 操作系统：Windows 11
- PHP 版本：PHP 8.1.8 (cli) (built: Jul  5 2022 23:04:29) (ZTS Visual C++ 2019 x64)

**Comment by walkor** [comment]
大概原因是workerman一直阻塞在stream_select 调用，php检测不到 Ctrl+C 。按Ctrl+C后发个请求，让php才stream_select返回，能检测到

**Comment by crazywhalecc** [comment]
> 大概原因是workerman一直阻塞在stream_select 调用，php检测不到 Ctrl+C 。按Ctrl+C后发个请求，让php才stream_select返回，能检测到

怎么做到按CtrlC发请求呢，我想做的就是按下CtrlC做一些事情。这种情况下是不是只能加一个 Timer 了？

**Comment by walkor** [comment]
不了解sapi_windows_set_ctrl_handler的机制，加一个定时器应该能解决

**Comment by crazywhalecc** [comment]
目前我找到一种解决方案：

首先将 STDIN 加入 EventLoop，在启动后
```php
Worker::$globalEvent->add(STDIN, 1, function($x) {
    fgets($x);
});
sapi_windows_set_ctrl_handler('ctrl_handler');
```

**Comment by walkor** [comment]
好方法
