### ISSUE TITLE
有没有办法在Timer回调内函数终止当前定时器？

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [walkor/Workerman#82]
在当前定时器回调函数内，可能因为某个原因或条件，需要终止当前定时器，有没有办法？

**Comment by walkor** [comment]
用引用的方式将$timer_id传递就去即可
{{{
$timer_id = Timer::add(10, function()use(&$timer_id){
    Timer::del($timer_id);
});
}}}

**Comment by smallworld-network-wupeng** [comment]
我也想过这种方式，不过看起来很怪，不知道可不可行，所以没有测试。谢谢！
