### ISSUE TITLE
PHP-Side limitations exists?, permanent optimizations might needed on high-load environments?

### ISSUE THREAD

**Issue by DLLDev** [walkor/workerman#822]
Im fastinated by the Workerman benchmarks, im wondering how to achieve them, respectively how they was setup?

As we know for example, Apache Worker/MPM same as PHP-FPM in NGINX have always some sorts of Limits regarding how much requests it can handle.

I never really used PHP as "direct" Web Server daemon that much.

As Workerman uses PHP (CLI), are there any limitations or tweaks necessary other then "solid" Hardware to reach the probably maximum possible requests/performance?

**Comment by walkor** [comment]
If you only use the http protocol, the PHP Cli side does not need to do any configuration.
If you use the websocket protocol, you need to install the event extension for PHP Cli so that the workerman can hold more connections(10000 connections or more).

**Comment by DLLDev** [comment]
Thank you walkor,
I was thinking the same but wasn´t sure, this make me think about why to even using webservers for PHP code those days, they just give many people out there headaches all the time, especially on high load envs, where you have to endless tweak settings... Adding more CPU or RAM is a way easier and works longer then anything else...

I will slowly port as much of my code code as possible to workerman :-)
