### ISSUE TITLE
Http1.1 use by default persistent connections

### ISSUE THREAD

**Issue by joanhey** [walkor/workerman#834]
Hi, reopening the discussion about #829.

After reading more, list in documentation, I was more convinced to remove the header `Connection: keep-alive`.
Http1.1 don't need it. Only need to use the header `Connection: close` to close a connection.
Before, I checked Nginx is returning this header, but it's a legacy bug.

The browser send this header, for legacy reason.
They don't know if the server is Http1.0 or Http1.1.
Actually they don't send it -> https://httpbin.org/get

But I remember that I have in my pc the Techempower benchmark repo.
Where there are almost all servers, and they need a keep-alive connection to have good results.
The benchmark use http1.1.

The fastest and more modern servers, do NOT use `Connection: keep-alive`.

Here is a fast list.

### Without `Connection: keep-alive`
- Rust
-  Java
-  Go
-  Kestrel (Microsoft server for ASP.net)
- Nginx Unit (the new app server)

### With `Connection: keep-alive` 
- Nginx
- H2o

### With `Connection: keep-alive`  and Keep-alive header
- Nodejs

But with Nodejs, you can define it like you want.
And perhaps it's a bad configuration of the implementator.

## Documentation
https://www.oreilly.com/library/view/http-the-definitive/1565925092/ch04s05.html
https://www.haproxy.com/blog/http-keep-alive-pipelining-multiplexing-and-connection-pooling/

https://www.rfc-editor.org/rfc/rfc7230#section-6.3
https://www.rfc-editor.org/rfc/rfc2616#section-8.1.2
https://blog.devgenius.io/persistent-connections-in-http-1-1-45c3bc1c7c87
https://www.stackpath.com/edge-academy/what-is-keep-alive/
https://stackoverflow.com/questions/7927566/is-an-http-1-1-request-implicitly-keep-alive-by-default
https://en.ryte.com/wiki/Keep-Alive
https://stackoverflow.com/questions/10723812/if-a-http-1-0-client-requests-connection-keep-alive-will-it-understand-chunked

Nginx:
https://github.com/openresty/headers-more-nginx-module/issues/22
https://stackoverflow.com/questions/20919207/remove-connection-keep-alive-response-header-in-nginx-204-response-with-http
https://stackoverflow.com/questions/11817662/nginx-and-raw-headers

**Comment by walkor** [comment]
Yes, you are right. We should remove it.

**Comment by walkor** [comment]
In order to be more compatible with http 1.0, I decided to keep it temporarily.
