### ISSUE TITLE
建议v6将worker拆分为Worker和Server两部分

### ISSUE THREAD

**Issue by tianyiw2013** [walkor/workerman#849]
现在一个Worker只能监听一个Server(协议或端口)，现在不太方便，无法实现同一个进程同时监听两个端口或不同的协议。

我觉得可以把Worker里的Server部分独立出来，让Worker只负责进程的启动和重载等相关逻辑。

然后增加Server，new Server('http://0.0.0.0:8080')

这是reactphp创建server，使用起来比较方便，可以参考一下。
```php
$http = new React\Http\HttpServer(function () {
    return React\Http\Message\Response::plaintext("Hello World!");
});

$socket = new React\Socket\SocketServer('127.0.0.1:8080');
$http->listen($socket);

$socket = new React\Socket\SocketServer('127.0.0.1:9090');
$http->listen($socket);
```

或者也可以让Worker传入多个协议，如new Worker(['http://0.0.0.0:8080'], ['http://0.0.0.0:9090']);

这样可以让workerman更强大，例如我想在单个Worker里同时开启80和443，我觉得没太有必要把两个协议分成多个worker。

另外，我觉得也应该把Worker里fork进程的部分也独立出来，例如封装到class Man{}，让Man去负责系统的运行。

`Man`>`Worker`>`Server`>`Connection`

现在Worker负责的工作太多了，而且Worker是主进程、同时也是fork进程。。。

而且有了Man，可以在实现两个UnixMan和WinMan，把Windows部分也完善一下，windows可以通过tcp协议创建一个服务，实现master和fork进程间通信，实现进程管理如进程重载等，尽量和Unix平台对齐。
另外：我这几天实验了一下，win环境下多worker实现思路，也参考了webman的实现，其实可以不用去新建worker文件，创建进程时，指定--worker_index=$index，然后根据传入的worker_index去启动单个worker即可（所有的worker都会实例化一遍，但是最终只运行worker_index这个Worker）。

**Comment by tianyiw2013** [comment]
我最近在学习Workerman，想基于Workerman开发一套平台，但是有些地方就像我上面说的，只能二次开发workerman，没法通过现有的的代码实现，因此我实验性的参考workerman写了个简单的框架，实验证明win环境下多worker是可行的，只是win环境下没法复用端口实现负载均衡。

我实验性的这个框架，实际上就是把Worker分离成Man、Worker、Server三部分，还是比较喜欢Workerman的，希望Workerman新版本可以考虑一下这个建议。

Workerman轻量化，简单，坚持这一点。然后再把Worker分离成三部分实现，感觉就很完美，事件驱动可以直接采用Revolt，没必要自己维护了，我觉得Man（多进程管理）是Workerman未来发展的好方向！！（现在事件驱动框架太多了，如ReactPHP、Amphp，开发者在Workerman里引入Reactphp或其他框架进行开发，这样也更方便，各取所长）

下图是我在Win环境下研究成果，执着于win环境下多进程，是在win环境开发阶段就避免挖坑，毕竟是多进程嘛。
![image](https://user-images.githubusercontent.com/4644588/201824466-0ca41612-a9fb-4e95-9667-e1f6a101a3fc.png)

**Comment by walkor** [comment]
非常非常感谢你的建议。

> 现在一个Worker只能监听一个Server(协议或端口)，现在不太方便，无法实现同一个进程同时监听两个端口或不同的协议。

`new Worker(['http://0.0.0.0:8080'], ['http://0.0.0.0:9090']); `这种形式之前考虑过，但是这样会使得workerman内部实现以及用户使用变得复杂，所有的操作都需要考虑多协议多监听的情况，不如每个worker一个监听这种简单方便。

worker可以在onWorkerStart时给当前进程添加监听端口和协议，实现多端口多协议监听处理，并且还可以给不同的设置不同的业务处理函数，甚至可以做到只给特定的进程增加特定的端口和协议监听，参见手册 https://www.workerman.net/doc/workerman/worker/listen.html


> 我觉得可以把Worker里的Server部分独立出来，让Worker只负责进程的启动和重载等相关逻辑。然后增加Server，new Server('http://0.0.0.0:8080/')

感觉这和现在的 new Worker() 和 new Worker('http://0.0.0.0:8080'); 没有区别。增加server概念除了增加学习成本，好像没有其它太大益处。

> 另外，我觉得也应该把Worker里fork进程的部分也独立出来，例如封装到class Man{}，让Man去负责系统的运行。
Man>Worker>Server>Connection 现在Worker负责的工作太多了，而且Worker是主进程、同时也是fork进程。。。

如果需要用户理解Man Worker Server Connection 这些感念，这样感觉用户学习成本提高了不少，用户层面只需要有Worker 和 Connection就够用了。

> 我这几天实验了一下，win环境下多worker实现思路，也参考了webman的实现，其实可以不用去新建worker文件，创建进程时，指定--worker_index=$index

workerman在windows下运行机制确实有很大优化空间，例如多进程实现，与linux统一的启动文件等

> 事件驱动可以直接采用Revolt，没必要自己维护了

Revolt目前要求php>=8.1，要求有点高。另外Revolt由于涉及协程创建调度销毁，性能相比workerman自带的事件驱动有一定损失。后期看情况，有可能会直接使用Revolt。


最后
Workerman后续版本在接口上应该都会与现在的尽量保持一致，这样能够让其它依赖workerman的项目零成本升级。
除非有重大的缺陷，否则Workerman不会更变目前的接口。当然在保持对外接口不变的情况下，对于workerman内部实现不是很合理的地方，该优化还是要优化。

**Comment by tianyiw2013** [comment]
感谢回复，表示理解
