### ISSUE TITLE
注意提示：Include libevent OpenSSL support [yes] : 时输入no回车，其它直接敲回车就行

### ISSUE THREAD

**Issue by winer632** [walkor/Workerman#86]
如果选了yes会有什么影响？

**Comment by taozywu** [comment]
个人理解：
首先你问的问题跟workerman本身没多大关系，这是libevent跟ssl的问题。

你阔以看下https://github.com/libevent/libevent 这个链接并找到如下类似处理

> OpenSSL support

To build Libevent with OpenSSL support you will need to have OpenSSL binaries available when building, these can be found here: http://www.openssl.org/related/binaries.html

---
最后祝你好运！

**Comment by walkor** [comment]
像 @taozywu 说的，对workerman没影响，如果选择yes，需要安装下OpenSSL库，有些用户不会安装。为了简化安装步骤，选择no

**Comment by winer632** [comment]
明白了，多谢
