### ISSUE TITLE
HTTP connection: send PSR-7 Response object

### ISSUE THREAD

**Issue by vanodevium** [walkor/workerman#868]
Is there any way to write a PSR-7 Response object into the connection?
Something like this:

```
    public function onMessage($connection, $request)
    {
        $response = new \Laminas\Diactoros\Response\JsonResponse($request->post('data'), 200);
        $connection->send($response);
    }
```

(`$response` is standard PSR-7 ResponseInterface, which can be retrieved from any other way, like guzzle request)

---
I understand that there are not enough methods in the protocol, but there may already be ready-made wrappers or some way to do this.

It would be nice to be able to convert PSR-7 Response to Workerman Response object like `Response::fromPSR7($response)`

**Comment by vanodevium** [comment]
\Workerman\Protocols\Http\Response

```
    /**
     * @param \Psr\Http\Message\ResponseInterface $response
     * @return static
     */
    public static function fromPSR7($response) {
        return new static($response->getStatusCode(), $response->getHeaders(), $response->getBody());
    }
```

**Comment by walkor** [comment]
https://github.com/walkor/workerman/issues/51#issuecomment-684685099
Hope this link will help you.
