### ISSUE TITLE
4.1版本的Websocket.php中用到了php7才支持的特性

### ISSUE THREAD

**Issue by landso** [walkor/workerman#874]
4.1版本的定位是”PHP 5.4 or Higher“，但是在Websocket.php和Ws.php中用到了php7才支持的特性：

Websocket.php：

 - 合并运算符：”??“
 - Throwable
 - inflate_init()
 - inflate_add()

Ws.php:

- random_bytes()

虽然现在php7很普及，但毕竟是4.1版本，是否考虑修改以兼容php5.4

**Comment by walkor** [comment]
php5.4用workerman4.0就好了
workerman4.1要求php最低为7.0

**Comment by landso** [comment]
好的 看到readme已经更新了
