### ISSUE TITLE
关于\Webman\File->move()的疑惑

### ISSUE THREAD

**Issue by haozhi6** [walkor/workerman#876]
![image](https://user-images.githubusercontent.com/45025597/216233233-d01b773a-504d-4897-9118-9834f70e4759.png)
restore_error_handler()的用处是用于还原之前的错误处理程序,但是当前方中仅有一个set_error_handler()

我的疑问是不加restore_error_handler()是不是也没有什么影响,或者是它的真正用途是什么?

**Comment by walkor** [comment]
虽然有三个restore_error_handler，但是只会执行一次。

set_error_handler类似向堆栈压入一个错误处理函数，每次执行move方法都调用 set_error_handler 都会压入这样一个函数，
如果不调用restore_error_handler()弹出函数，压入的函数得不到释放，内存会占用越来越多。

**Comment by walkor** [comment]
下次webman的issue请发到webman项目里吧，这里是workerman项目。

**Comment by haozhi6** [comment]
> 下次webman的issue请发到webman项目里吧，这里是workerman项目。

好的 感谢老大回复,我是看这个代码在workerman\webman-framework中才来的workerman

**Comment by haozhi6** [comment]
是不是可以这么理解 因为是常驻内存所以才需要调用restore_error_handler,  php-fpm下就没什么影响

**Comment by walkor** [comment]
php-fpm 也需要restore_error_handler，否则框架入口设置的set_error_handler永远得不到执行。
90%的框架都会在入口处设置自己的error handler
