### ISSUE TITLE
Sub process will be reloaded after a certain amount of time with Swoole extension

### ISSUE THREAD

**Issue by Hanmo123** [walkor/workerman#878]
This problem is reproducible on **PHP with Swoole extension**

I noticed this problem when i am using webman, and created a sub-process in `config/process.php` like this(the code below is a minimal demo, where the problem reappears):
![MQC}7~KD4T@XWUK(ED7S(OU](https://user-images.githubusercontent.com/32361024/218306409-815c0f90-394f-44a6-a86d-9e3be62fc717.png)

`app/process/abc.php`:
![A(QYIC7B 1X0E4MC$MQJ UB](https://user-images.githubusercontent.com/32361024/218306444-a0296790-7e60-4154-a05e-9bbd18d08d04.png)

`composer.json`:
![_WE}WMRH8TO~VA7C((1) B](https://user-images.githubusercontent.com/32361024/218306463-6cd53970-cab6-4547-9eda-85e95f117d5c.png)

After two minutes, it logged like this:
![G@B`1{BK@APBP(`3IL(E$G9](https://user-images.githubusercontent.com/32361024/218306481-ac2cc221-9d31-4fb3-8525-dcd5f8cbe575.png)

Obviously, the sub-process was reloaded without exception.
I then tried to print the call_trace:
![%}W U69E{ZTQMS7749KGO42](https://user-images.githubusercontent.com/32361024/218306613-8bf80135-f3ad-45ea-8bfb-50b46e1f180c.png)

The `Worker::monitorWorkers` does not seem to work properly.

---

I installed swoole by using pecl. Here is my PHP version and Swoole info.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/32361024/218306778-6b002733-b5a2-4e11-a433-9bca24b139a1.png">

By the way, when i use the `swoole-cli`, it will works fine

**Comment by walkor** [comment]
Run `php start.php status` and find the abc process pid.
Run `strace -ttp pid` and wait for the process exit and the output may show why process exited.

**Comment by walkor** [comment]
Run `php start.php status` and find the abc process pid.
Run `strace -ttp pid` and wait for the process exit and the output may show why process exited.

**Comment by Hanmo123** [comment]
In the new container(the old container missed --cap-add=SYS_PTRACE) i found that even through i didn't install swoole extension, it also reloaded.

Here is the output of `strace` command
https://pastebin.com/raw/9wBFKMTj

**Comment by walkor** [comment]
Run command `trace -f php start.php start` and wait abc process exit then show the output.

**Comment by Hanmo123** [comment]
> trace -f php start.php start
you mean `trace -f php start.php start`?

For simplicity's sake, I closed the monitor process:

 ```
<unfinished ...>
[pid 13309] <... clock_nanosleep resumed>NULL) = 0
[pid 13309] clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=100, tv_nsec=0},  <unfinished ...>
[pid 13308] <... pselect6 resumed>)     = 0 (Timeout)
[pid 13308] pselect6(6, [5], [], [], {tv_sec=100, tv_nsec=0}, NULL^C <unfinished ...>
[pid 13307] <... wait4 resumed>0x7fffe8e73ab4, WSTOPPED, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
strace: Process 13307 detached
strace: Process 13308 detached
strace: Process 13309 detached
Workerman[start.php] stopping ...
```

the full log: https://pastebin.com/raw/SNjzUng9

**Comment by walkor** [comment]
The last strace result shows that the abc process did not exit. You should wait for the abc process to exit, and then paste the output.

Use command `strace -ftt php start.php start`.

**Comment by walkor** [comment]
How to determine whether the abc process exits? similar to the following output

```
21:32:52.043207 --- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=12964, si_uid=0} ---
21:32:52.044320 rt_sigreturn({mask=[]}) = -1 EINTR (Interrupted system call)
21:32:52.044497 rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
21:32:52.044769 getpid()                = 12963
21:32:52.044943 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
21:32:52.045184 close(3)                = 0
21:32:52.045304 close(2)                = 0
21:32:52.045368 close(1)                = 0
21:32:52.045434 close(0)                = 0
21:32:52.045627 munmap(0x7f11be800000, 2097152) = 0
21:32:52.045905 munmap(0x7f11becfa000, 41448) = 0
21:32:52.053762 exit_group(0)           = ?

```

**Comment by Hanmo123** [comment]
maybe i can build a docker image for you so that you can debug more sufficiently

**Comment by walkor** [comment]
That OK


------------------ Original ------------------
From: Hanmo ***@***.***&gt;
Date: Sun,Feb 12,2023 10:47 PM
To: walkor/workerman ***@***.***&gt;
Cc: walkor ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [walkor/workerman] Sub process will be reloaded after a certainamount of time with Swoole extension (Issue #878)





 
maybe i can build a docker image for you so that you can debug more sufficiently

**Comment by Hanmo123** [comment]
[Dockerfile.tar.gz](https://github.com/walkor/workerman/files/10720218/Dockerfile.tar.gz)

This is the docker file and modified files.
If the monitor process-related code is commented out, then the problem will not recur, which is why yesterday you said you could not see the exit.

**Comment by Hanmo123** [comment]
As I explored further, I found that the memory_limit in Monitor.php returned 0 on line 97
![image](https://user-images.githubusercontent.com/32361024/218413313-4c905a30-e872-47f4-90d1-3d90a209ecef.png)

<img width="91" alt="image" src="https://user-images.githubusercontent.com/32361024/218413428-94e7899c-7688-40a2-8e9f-0d2d737fe99e.png">

and process was finally killed by Monitor.php in L199.

**Comment by walkor** [comment]
> As I explored further, I found that the memory_limit in Monitor.php returned 0 on line 97 ![image](https://user-images.githubusercontent.com/32361024/218413313-4c905a30-e872-47f4-90d1-3d90a209ecef.png)
> 
> <img alt="image" width="91" src="https://user-images.githubusercontent.com/32361024/218413428-94e7899c-7688-40a2-8e9f-0d2d737fe99e.png">
> 
> and process was finally killed by Monitor.php in L199.

The monior process will monitor the memory usage of all business processes. If it exceeds 80% of the `memory_limit` in php.ini, it will automatically and safely restart the business process. There is a bug in the earlier version, which does not take into account that the `memory_limit` is `-1`. 

Please set `memory_limit=128M`(or other value  but not -1 or 0) OR update https://github.com/walkor/webman/blob/master/process/Monitor.php .

**Comment by Hanmo123** [comment]
The line is esixt in my monitor.php, i am using the latest version.

**Comment by walkor** [comment]
https://github.com/walkor/webman/blob/2acbb5d167388d8e8939db40dd71d3e9af5d4589/process/Monitor.php#L97-L100

Please check if codes are the same.

**Comment by Hanmo123** [comment]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/32361024/218422436-4e580164-8840-4167-a098-207234cb68c5.png">

Exact match, perfect fit.

**Comment by walkor** [comment]
This fixed and will release a few days.

Thank you very much for your report.
