### ISSUE TITLE
HTTP protocol

### ISSUE THREAD

**Issue by bublikOff** [walkor/workerman#897]
Function input in Http.php uses strpos to search headers and its case sensitive to headers first letter capitalization.
I suppose that using stripos instead strpos might be a better idea

RFC is not regalements http header capitalization. Header names are not case sensitive.

From [RFC 2616 - "Hypertext Transfer Protocol

`Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.`

**Comment by walkor** [comment]
thanks
