### ISSUE TITLE
压测逻辑应该这样写

### ISSUE THREAD

**Issue by xiaohuilam** [walkor/Workerman#92]
```php
<?php
....
$http_worker->count = 4;
$http_worker->onMessage = function($connection, $data) use($http_worker)
{

    $http_worker->_GLOBAL['test'] ++;
    echo $http_worker->_GLOBAL['test'];
    echo "\n";

    $uuid = mt_rand(10000, 99999);
    echo $uuid . ' begin' . "\n";
    usleep(10000);      // 模拟真实逻辑的处理耗时, 10ms
    echo $uuid . ' done' . "\n";
    $connection->send("hello world \n");
};
```

然后再次压测，可以发现性能下降严重，处理能力完全由`$http_worker->count` 决定，所以请容许我猜想Workerman没有真正意义上实现异步。

**Comment by walkor** [comment]
代码里面加sleep这种不能说性能下降了，这种属于QPS下降了，你通过观察系统负载其实是降低了。

任何语言像这样让进程完全睡眠都会导致QPS下降，这个不是框架决定的，完全是开发者的代码决定。

workerman的异步是通过非阻塞IO配合多进程来完成的，并不是开发者随意写代码都可以异步。
另外异步并不一定能提高服务器性能，一般来说只是一种编程手法，可以减少用户请求等待时间。

**Comment by yesme2000** [comment]
usleep(10000);  这种耗时的业务，应该交由后台程序去处理

**Comment by hetao29** [comment]
呃，我到不觉得是这样的，这样测试并发响应是没有问题的，onMessage里面的没有实现异步




2016-09-07 11:04 GMT+08:00 yesme2000 <notifications@github.com>:

**Comment by xiaohuilam** [comment]
> yesme2000 commented 10 minutes ago
> usleep(10000); 这种耗时的业务，应该交由后台程序去处理

10ms是模拟业务执行时间，像一般复杂度的业务，包含一两个for循环，执行耗时基本都在 10ms 级别

**Comment by walkor** [comment]
这里贴个workerman异步的例子，[ss-php代理](https://github.com/walkor/shadowsocks-php/blob/master/Applications/Shadowsocks/server.php)，很多用户用它来翻墙。

代理原理：比如用户想看一个youtube网页，代理服务端最简单的做法是在onMessage里把网页内容全部下载(curl/file_get_contents...)下来，然后整体发给客户端。如果这个下载过程只有100毫秒，感觉还可以接受。但是youtube视频流呢？不可能在onMessage里把视频下载完再发给用户，但是如果你只用curl或者file_get_conents等获取youtube视频数据就要同步等待(这个阻塞等待任何php框架都控制不了，workerman自然控制不了)，果所有进程都阻塞在这里，代理的吞吐量就会很差。

所以异步正确的做法应该是类似ss-php例子一样，利用IO非阻塞，异步建立socket链接，异步接受消息，异步转发消息，这样代理整个吞吐量就提高了，看youtube视频也就不会卡了。

所以还是我上面说的，代码是否异步执行不是全部由框架决定，很大程度上由开发者编码手法决定的，不是随便个代码扔上去就能异步滴。

**Comment by gouchaoer** [comment]
直接在异步回调逻辑里阻塞睡眠肯定不行，你睡眠10ms去模拟业务比如去查个sql啥的可以，但是查sql本身是同步的，也必导致qps下降的很厉害，就算nodejs你这么测也是一样的。

异步就意味着你不能阻塞，你需要把你10ms的同步业务改成回调方式。
