### ISSUE TITLE
No way to get Server IP and Port directly

### ISSUE THREAD

**Issue by joanhey** [walkor/workerman#921]
Hi, Walkor

I want to add `$_SERVER['SERVER_ADDR']` to Adapterman, but I can't find a direct way to get it.

I can create it in the `Http.php`,  from `Worker->socketName`.
But perhaps it will be better to be in the `Worker.php`, as it's useful in many apps. 

@walkor  What do you think is the best way or alternative ?

**Comment by walkor** [comment]
Create it in Http.php like this.


public function decode($buffer, $connection)
{
&nbsp; &nbsp; $_SERVER[‘SERVER_ADDR’] = $connection-&gt;getRemoteIp();


}


------------------ Original ------------------
From: Joan Miquel ***@***.***&gt;
Date: Wed,Jun 28,2023 6:25 PM
To: walkor/workerman ***@***.***&gt;
Cc: walkor ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [walkor/workerman] No way to get Server IP and Port directly (Issue #921)





 
Hi, Walkor
 
I want to add $_SERVER['SERVER_ADDR'] to Adapterman, but I can't find a direct way to get it.
 
I can create it in the Http.php,  from Worker-&gt;socketName.
 But perhaps it will be better to be in the Worker.php, as it's useful in many apps.
 
@walkor  What do you think is the best way or alternative ?

**Comment by joanhey** [comment]
Hmmm;
RemoteIP() is the ip of the client, not the Server IP.
