### ISSUE TITLE
Parse data when using PUT verb.

### ISSUE THREAD

**Issue by uribes78** [walkor/workerman#926]
I'm using workerman 'cause I think is great, but I'm developing an app and the want to use PUT method, but the ```Request``` instance has not a method to retrived data. Is there a method I can use? or there must be develop from scratch?

I have been trying to parse it using php://input but have not success. Any suggestion? Thanks anyway

**Comment by walkor** [comment]
Try $request->rawBody();

**Comment by uribes78** [comment]
Thanks for the advice, checking the method to parse POST request (```parsePost```) , I can see that it is the same as PUT, so I'm just validating method and using the ```$req->post()``` to retrivied data. Thanks again
