### ISSUE TITLE
EV events on destroy error

### ISSUE THREAD

**Issue by webrobot1** [walkor/workerman#940]
workerman version  4 has error  at code

```
   public function destroy()
    {
        foreach ($this->_allEvents as $event) {
            $event->stop();
        }
    }
```

it cant be work bacause structure of  $this->_allEvents it is 2 levels's array like at code 

`$this->_allEvents[$fd_key][$flag] = $event;`

**Comment by webrobot1** [comment]
maybe it need stoop $this->_eventSignal   or what ?

**Comment by walkor** [comment]
Fixed and thank you for your post.
