### ISSUE TITLE
Events uv cant handle stop signall

### ISSUE THREAD

**Issue by webrobot1** [walkor/workerman#942]
Hello again

Uv is Libuv library. it cant handle SIGQUIT  what is gracefull stop - https://docs.libuv.org/en/v1.x/signal.html

**Comment by webrobot1** [comment]
![image](https://github.com/walkor/workerman/assets/20768848/057646cd-fcea-488e-b1f3-fe87daef9641)

**Comment by webrobot1** [comment]
And as i see it cant handle SIGINT (2)  too

**Comment by webrobot1** [comment]
may be it is possible set as a constant at Worker.php which signal number master will send to child process ? Фе this reason i can extend Worker

**Comment by webrobot1** [comment]
workerman version 4.*

**Comment by walkor** [comment]
Sorry, I couldn’t find the issue you mentioned in https://docs.libuv.org/en/v1.x/signal.html.

**Comment by webrobot1** [comment]
> Sorry, I couldn’t find the issue you mentioned

graccefull stop signal oа workerman is SIGQUIT   but it not accapted by Libuv (UV)  and a lot of another signals

**Comment by webrobot1** [comment]
when worker forks events (like UV)  check the signals in workerman

**Comment by walkor** [comment]
I think if UV cannot handle certain signals, you should make compatibility changes in `Events/Uv.php` instead of modifying the `Worker.php` file.

**Comment by webrobot1** [comment]
> I think if UV cannot handle certain signals, you should make compatibility changes in `Events/Uv.php` instead of modifying the `Worker.php` file.

it is imposible baceuse worker process is running on event loop only this loop can wakeup process on signall

And if master process will sent signal what `Events/Uv.php` cant handle - it cant be handle

**Comment by webrobot1** [comment]
If `Events/Uv.php`  cant handle some of basic signals (number before 10+-)  maybe another events library can

**Comment by walkor** [comment]
If UV cannot receive signals such as SIGINT or SIQUIT, I believe this is a bug in UV, and Workerman will not be compatible with it.

**Comment by webrobot1** [comment]
ok, thank for feedback
