### ISSUE TITLE
`/src/Protocols/Http.php` `Content-Length` 疑问

### ISSUE THREAD

**Issue by tianyiw2013** [walkor/workerman#969]
https://github.com/walkor/workerman/blob/1c24fe43f58a8026f675551d5e1dcc9f3e48b76e/src/Protocols/Http.php#L134C1-L134C1

```php
        if ($pos = stripos($header, "\r\nContent-Length: ")) {
            $length += (int)substr($header, $pos + 18, 10);
            $hasContentLength = true;
        } 
```

`$length += (int)substr($header, $pos + 18, 10);` 
第三个参数为什么是固定数字10呢？是有特别的原因吗？
我觉得应该改成
```php
$length += substr($header, $pos + 18, strpos($header, "\r\n", $pos + 18) - $pos - 18);
```

**Comment by tourze** [comment]
感觉你写的更加合理点。

**Comment by twomiao** [comment]
1. 你这代码看似完整性，但功能来说他那个没问题的，你失去了可读性。
2. 如何解决这问题，添加一行英文注释说明下10的含义就行了。

**Comment by tianyiw2013** [comment]
> 1. 你这代码看似完整性，但功能来说他那个没问题的，你失去了可读性。
> 2. 如何解决这问题，添加一行英文注释说明下10的含义就行了。

源代码是`$length += (int)substr($header, $pos + 18, 10);`截取了10个字符长度，应该不正确，不一定是10个字符长度呢，然后强制转换为int，如果不强制转换的话，有可能截取到的结果是`999\nxxx`

**Comment by twomiao** [comment]
> > 1. 你这代码看似完整性，但功能来说他那个没问题的，你失去了可读性。
> > 2. 如何解决这问题，添加一行英文注释说明下10的含义就行了。
> 
> 源代码是`$length += (int)substr($header, $pos + 18, 10);`截取了10个字符长度，应该不正确，不一定是10个字符长度呢，然后强制转换为int，如果不强制转换的话，有可能截取到的结果是`999\nxxx`

int 32 位最大才多少，他这个极限是999999999字节，你见过这么大的网页文本(9G)？
截取到字符串的情况，强制转换int类型他不是已经处理这情况了？(int) substr(xxx);

**Comment by twomiao** [comment]
> > 1. 你这代码看似完整性，但功能来说他那个没问题的，你失去了可读性。
> > 2. 如何解决这问题，添加一行英文注释说明下10的含义就行了。
> 
> 源代码是`$length += (int)substr($header, $pos + 18, 10);`截取了10个字符长度，应该不正确，不一定是10个字符长度呢，然后强制转换为int，如果不强制转换的话，有可能截取到的结果是`999\nxxx`

那你复现问题，然后在提交pr。你这样写作者应该不会采取的。

**Comment by tianyiw2013** [comment]
https://3v4l.org/bqlb9

提取部分代码：
```php
<?php

$header = '
Content-Length: 999
Test: 2';
$pos = stripos($header, "\r\nContent-Length: ");
$value = substr($header, $pos + 18, 10);
$length = (int)$value;
var_dump($value, $length, $length === 999);
```

输出结果：
```
string(10) "99
Test: 2"
int(99)
bool(false)
```

**Comment by twomiao** [comment]
> 标准http报文测试没有问题

```
<?php

$header = "HTTP/1.1 200 OK \r\nAccess-Control-Allow-Methods: POST, GET \r\nAccess-Control-Allow-Origin: https://www.baidu.com"." \r\nContent-Length: 105 \r\nContent-Type: application/json; charset=utf-8\r\n\r\n";
$pos = strpos($header, "\r\nContent-Length: ");

$value = substr($header, $pos + 18, 10);

$length = (int)$value;

var_dump($value, $length, $length === 105); 
```

**Comment by xpader** [comment]
有些看似不合理的代码，实则很巧妙，当然你的出发点也是没错的，更加严谨。
