### ISSUE TITLE
Event loop

### ISSUE THREAD

**Issue by sm2017** [walkor/Workerman#99]
How can I replace workerman's event loop with https://github.com/reactphp/event-loop

**Comment by walkor** [comment]
Need a lot of changes and replacement are not recommend.

**Comment by socketman2016** [comment]
Why you have your own event loop? I think it is a mistake
Workerman is a powerful tool but there is a little plugin and extension for it 

Can you tell me how can I add a extension to workerman that based on reactphp event loop? for example these extensions
https://github.com/reactphp/filesystem
https://github.com/reactphp/http-client

**Comment by walkor** [comment]
I didn't know the existence of reactphp when I wrote workerman. 

Add a wrapper for reactphp-event-loop is a simple way to fit workerman.
Here is workerman's event-loop interface.
https://github.com/walkor/Workerman/blob/master/Events/EventInterface.php

**Comment by walkor** [comment]
Workerman support [reactphp-loop](https://github.com/reactphp/event-loop) now.
Examples.
https://github.com/walkor/Workerman#async-mysql-of-reactphp
