### ISSUE TITLE
Question: docker and debug/daemon mode

### ISSUE THREAD

**Issue by vanodevium** [walkor/workerman#992]
The nature of how docker works requires a single long-running process.
In fact, I can't run `php server.php start -d` because container will stop immediately.

Question: 
does the **debug** mode affects the performance of the **workerman**?
If it affects, is there any method of starting **workerman** not in **debug** mode, but as a long-running process?

Thanx!

**Comment by joanhey** [comment]
I use it in the techempower bencmark in debug mode
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/workerman/workerman.dockerfile#L25

And it's really fast
https://www.techempower.com/benchmarks/#section=test&runid=502e3495-dda5-4232-a89a-7c08755fcf0e&hw=ph&test=fortune

**Comment by walkor** [comment]
> does the debug mode affects the performance of the workerman?

debug mode does not affects the performance of the workerman.
