### ISSUE TITLE
Using this as Radius Server

### ISSUE THREAD

**Issue by rjjrbatarao** [walkor/workerman#999]
Thank you for this wonderful library, im currently using this as a pure php radius server :), still were fixing some minor issues check this link [radius](https://github.com/jyggen/radius/issues/2)
![image](https://github.com/walkor/workerman/assets/50077340/02389502-a86a-462d-9226-16e87fa8d1dd)
![image](https://github.com/walkor/workerman/assets/50077340/f2ac54f6-1ca4-47e4-934c-23120adf5836)

**Comment by walkor** [comment]
I'm glad you like it.

**Comment by rjjrbatarao** [comment]
I'll update here if the code ready for everyone i've already implemented accounting as well as the change of authorization, timers for the daily, weekly and monthly is still on going :) all concepts from freeradius are being implemented, its amazing what workerman  can do :)

**Comment by rjjrbatarao** [comment]
Below is my benchmark using golang radius 
![golang_radius_c10000_p100](https://github.com/walkor/workerman/assets/50077340/a03a41ee-5416-49de-8ed5-3b1b77efc814)
This is my benchmark for workerman radius
![php_radius_c10000_p100](https://github.com/walkor/workerman/assets/50077340/44c4ce75-ddc9-4ed3-951e-fc253fd73931)
ALthough its workerman radius is consistent at 7000 packet/s still not as fast as the golang radius which tops at 16000 packet/s is this the limitation of workerman or maybe it has to parse the packet which consumes speed I dont know how can I improve this to match golang speeds

**Comment by rjjrbatarao** [comment]
7000 packet/s is already impressive given that freeRadius could get lower benchmark than this as low as 200 packet/s if using sql. I'll keep on poking some settings or add database queries and rerun my benchmark again to see some difference

**Comment by walkor** [comment]
Workerman only supports one process on Windows servers, which cannot fully utilize its performance. If you want better performance, you need to use a Linux system. If your business does not involve external IO operations such as a database, the number of processes can be set equal to the number of CPU cores. Otherwise, the number of processes should be set to around four times the number of CPU cores.

**Comment by walkor** [comment]
Also, printing data to the terminal is a time-consuming operation, it is best to delete the relevant code 
```
var_dump("New authentication Connection\n");
var_dump("authentication Connection closed\n");
```

**Comment by rjjrbatarao** [comment]
@walkor I see thank you that sorts it out, im using it on my windows nonetheless it still good, I'll definetely deploy it on a linux machine
